### PR TITLE
Bump PLplot to 5.9.9

### PR DESCRIPTION
**Pull request by dsendkowski**

### CODE REVIEW

**Comment by alarcher** [comment]
The build of 5.8.0 failed with GCC 7.1 because of:
error: unrecognized command line option '-fno-force-mem'; did you mean '-fno-force-addr'

The option seems to have been removed since GCC 4.3.
Are you able to check if this is still an issue with the new version of PLplot?

**Comment by dsendkowski** [comment]
If setting `CC=/usr/bin/gcc-7` in Makefile is a correct way to build with GCC-7, then there is no such error in 5.9.9 version. However, I noticed some other things (during GCC-7 build) which need attention. I'll try to correct them and complete this PR.

**Comment by alarcher** [comment]
Thank you, that would help me a lot. There are only 70 components left to fix for GCC 7 so it would be nice to be able to setup a shadow build as soon as they are all fixed.
You can also use the variable GCC_VERSION to switch:
https://github.com/OpenIndiana/oi-userland/blob/oi/hipster/make-rules/shared-macros.mk#L509

**Comment by dsendkowski** [comment]
Fortunately, there is nothing that could prevent the component from building with GCC-7. I've just added some minor fixes (implicit declarations etc.) to the source code.

**Comment by alarcher** [comment]
@dsendkowski Great! Thank you!

**Comment by alarcher** [comment]
The test target does not run because gmake check is not the right way to execute the test suite.

**Comment by dsendkowski** [comment]
Ok, tests weren't built due to a missing CMake option.

**Comment by alarcher** [comment]
How do you execute them? I am not able to run the test suite :S
According to https://sourceforge.net/p/plplot/wiki/Testing_PLplot/ they are not run with gmake check, so our default test target is incorrect.

**Comment by dsendkowski** [comment]
I run `gmake test`:
```
dsend@oi-dev:/projects/oi-userland/components/image/plplot$ gmake test
(cd /projects/oi-userland/components/image/plplot/build/amd64 ; \
        /usr/bin/env  \
        ctest \
         check)
Test project /projects/oi-userland/components/image/plplot/build/amd64
      Start  1: examples_c
 1/10 Test  #1: examples_c .......................   Passed   13.77 sec
      Start  2: examples_cxx
 2/10 Test  #2: examples_cxx .....................   Passed   13.50 sec
      Start  3: examples_f77
 3/10 Test  #3: examples_f77 .....................   Passed    3.22 sec
      Start  4: examples_f95
 4/10 Test  #4: examples_f95 .....................   Passed    3.67 sec
      Start  5: examples_tcl
 5/10 Test  #5: examples_tcl .....................   Passed   18.20 sec
      Start  6: examples_svg
 6/10 Test  #6: examples_svg .....................   Passed   67.93 sec
      Start  7: examples_pscairo
 7/10 Test  #7: examples_pscairo .................   Passed   19.12 sec
      Start  8: examples_pngcairo
 8/10 Test  #8: examples_pngcairo ................   Passed   23.54 sec
      Start  9: examples_xfig
 9/10 Test  #9: examples_xfig ....................   Passed   13.22 sec
      Start 10: examples_compare
10/10 Test #10: examples_compare .................   Passed   43.28 sec

100% tests passed, 0 tests failed out of 10
```

**Comment by alarcher** [comment]
OK. I was missing dependencies sorry...

**Review by alarcher — APPROVED** [review]

**Pull request merged**
