### PR TITLE
library/perl-5/tk-perl build for all perl versions 5.22, 5.24 and 5.34

### PR DESCRIPTION
**Pull request by fritzkink**

### CODE REVIEW

**Comment by AndWac** [comment]
When I run "gmake sample-manifest" the resulting sample-manifest file is a lot bigger than yours. Can you check it, please?

**Comment by fritzkink** [comment]
Oh, sorry my fault. I forgot to rerun 'make sample-manifest' (I started 
with perl-524 initially). Should I commit the new sample-manifest ( 2289 
lines now sha256: 
6b0e92edbc31c8589ed242208c29a24fc45d4f800080863b31e375c5b67cbcc9 
manifests/sample-manifest.p5m)?

Am 09.01.2022 um 00:31 schrieb Andreas Wacknitz:

**Comment by AndWac** [comment]
Yes, please. And don't forget to squash the commits ;-)

**Comment by fritzkink** [comment]
Done. Hopefully github is still happy ;-).

Am 09.01.2022 um 15:45 schrieb Andreas Wacknitz:

**Review by AndWac — APPROVED** [review]

**Pull request merged**
