### PR TITLE
bump erlang to 19.3

### PR DESCRIPTION
**Pull request by grueni**
Requirement for couchdb-21

### CODE REVIEW

**Comment by AndWac** [comment]
Did you check whether ejabberd still works with it?

**Comment by grueni** [comment]
Not yet. ejabberd is version 2.10.3 from 2010/03/12.
Maybe its is time to update ejabberd to the newest version.
I will check this in the afternoon.

**Comment by pyhalov** [comment]
Can you reformat manifests according to https://wiki.openindiana.org/oi/oi-userland+-+best+practices ? We don't generally use solaris-userland manifests format, as it makes harder to compare component's manifest and sample-manifest.

**Comment by pyhalov** [comment]
Compilation fails here with
```
In file included from /usr/include/wx-2.8/wx/filesys.h:27:0,
                 from /usr/include/wx-2.8/wx/xrc/xmlres.h:23,
                 from gen/wxe_macros.h:42,
                 from gen/wxe_funcs.cpp:28:
/usr/include/wx-2.8/wx/filename.h: In static member function ‘static wxChar wxFileName::GetPathSeparator(wxPathFormat)’:
/usr/include/wx-2.8/wx/filename.h:393:43: error: ambiguous overload for ‘operator[]’ (operand types are ‘wxString’ and ‘unsigned int’)
         { return GetPathSeparators(format)[0u]; }
                                           ^
/usr/include/wx-2.8/wx/filename.h:393:43: note: candidates are:
/usr/include/wx-2.8/wx/filename.h:393:43: note: operator[](const wxChar* {aka const wchar_t*}, long int) <built-in>
In file included from /usr/include/wx-2.8/wx/memory.h:16:0,
                 from /usr/include/wx-2.8/wx/object.h:20,
                 from /usr/include/wx-2.8/wx/wx.h:16,
                 from gen/wxe_funcs.cpp:23:
/usr/include/wx-2.8/wx/string.h:822:13: note: wxChar& wxString::operator[](int)
     wxChar& operator[](int n)
             ^
/usr/include/wx-2.8/wx/string.h:824:13: note: wxChar& wxString::operator[](wxStringBase::size_type)
     wxChar& operator[](size_type n)
             ^
gmake[4]: *** [Makefile:157: i386-pc-solaris2.11/wxe_funcs.o] Error 1
```

**Comment by grueni** [comment]
I forgot to make a PR for wxWidgets 3.0.2. Will deliver it in some minutes but I have to reformat it before (it is still in Oracle design).

**Comment by pyhalov** [comment]
Another option is to add "CONFIGURE_OPTIONS.64 += --with-wx-config=/usr/bin/$(MACH64)/wx-config"

**Pull request merged**
