### PR TITLE
add fetching sources from mercurial repos (hg)

### PR DESCRIPTION
**Pull request by cgrzemba**
This adds fetching OSS from mercurial repos.
I need this for OSS from Mozilla projects.
This change is taken from solaris-userland

### CODE REVIEW

**Review by pyhalov — APPROVED** [review]

**Comment by pyhalov** [comment]
I think that having such rules is good, but using them for specific component is a bit troublesome, as file hash is changing every time it's fetched.

**Comment by pyhalov** [comment]
@cgrzemba Please, separate private branches, WIP branches and branches for PR. Now NetAddr-IP appeared in this PR.

**Review by pyhalov — CHANGES_REQUESTED** [review]
Remove this commit...

**Comment by cgrzemba** [comment]
sorry, is removed.

**Review by pyhalov — APPROVED** [review]

**Comment by alarcher** [comment]
@pyhalov @xen0l Should we merge?

**Comment by pyhalov** [comment]
I'd say yes, but I wanted to get one more review.

**Review by xen0l — APPROVED** [review]

**Pull request merged**
