### PR TITLE
WIP: transmission 2.92

### PR DESCRIPTION
**Pull request by xen0l**

### CODE REVIEW

**Comment by xen0l** [comment]
Any ideas what to do with GUI-related bits? I would like to split packages in transmission-gtk and transmission-cli and transmission-daemon, so we have a better granulatiry over this.

**Comment by pyhalov** [comment]
Truss it and find out what's wrong ;)

**Comment by xen0l** [comment]
I don't use GUI, so hopefully, we are able to find someone who could have a look at it. Otherwise, I have no idea how to deliver this update. I am interested in CLi/daemon client, so maybe package splitting?

**Comment by pyhalov** [comment]
Well, I can look at it when I have more free time

**Comment by pyhalov** [comment]
GUI seems more sane after https://github.com/OpenIndiana/oi-userland/pull/2600

**Comment by pyhalov** [comment]
For now 2 irritating things are:
- colored +/- buttons (don't know if it's bad);
- file browser in gtk3 apps looks poor. 
But overall I think it's possible to merge it.
One small necessary fix is to move it to appropriate category (components/network or components/desktop).

**Comment by pyhalov** [comment]
While downloading, transmission can get error
'Error: Operation not applicable (/home/alp/...)'

**Comment by pyhalov** [comment]
Merged https://github.com/OpenIndiana/oi-userland/pull/3316 insted

**Pull request closed without merging**
