### PR TITLE
Add xkeyboard-config 2.20

### PR DESCRIPTION
**Pull request by alarcher**

### CODE REVIEW

**Comment by pyhalov** [comment]
Wait. Originally most of the files lived in x11/keyboard/data-xkb ... Also there were 
<pre>
link path=usr/X11/lib/X11/xkb target=../../../share/X11/xkb
link path=usr/X11/share/X11/xkb target=../../../share/X11/xkb
</pre> . 
Do we still need them?

**Comment by alarcher** [comment]
I see it was not migrated yet.
I added the symlinks.
Should I keep the name or rename?

**Comment by pyhalov** [comment]
I don't have preferences here.

**Comment by alarcher** [comment]
@pyhalov Bah let us keep the current 'data-xkb' name, updated.

**Comment by 3eka** [comment]
Hi @alarcher ,

this morning I have updated this package and keyboard stopped to work (writing this from reverted BE).
Dou you have idea what would be starting point to investigate problem (note that I had to ssh from  another node in order to reach box).

I am using USB keyboard attached to USB 2.x PCI Card

Change:
```
  x11/keyboard/data-xkb
    0.5.11-2013.0.0.0 -> 2.20-2017.0.0.0
```
Regards.

**Comment by pyhalov** [comment]
As I understand, it stopped working in X11. Can you reset all x11 xkb settings? Does it work then?

**Comment by alarcher** [comment]
Non-working keyboard would mean missing keyboard definition.
I tested with english UK, swedish and norwegian.
This package is plain keyboard definition that everyone uses but your particular layout may be affected.

**Comment by 3eka** [comment]
Hi,
not sure how to check... I just have update OI.
From /etc/X11/xorg.conf
```
Section "ServerLayout"
    Identifier     "Layout0"
    Screen      0  "Screen0" 0 0
    Screen      1  "Screen1" RightOf "Screen0"
    InputDevice    "Keyboard0" "CoreKeyboard"
    InputDevice    "Mouse0" "CorePointer"
    Option         "Xinerama" "0"
EndSection
...
Section "InputDevice"
    # generated from default
    Identifier     "Keyboard0"
    Driver         "keyboard"
EndSection
```
Nothing else is related to keyboard.

From shell (after log-in to MATE; after reverting BE):
```
$ kbd  -l
type=6
layout=9 (0x09)
delay(ms)=500
rate(ms)=40
```
BUT, I could not reach that point, since MATE did not accepted/recognized keyboard.

Thank you

**Comment by 3eka** [comment]
E.G: How to reset all xkb settings?

**Comment by pyhalov** [comment]
https://www.illumos.org/issues/7866

**Pull request merged**
