### PR TITLE
[IN DISCUSSION] Provide packages for different NVidia driver types

### PR DESCRIPTION
**Pull request by jimklimov**
Renamed NVidia-340.x component dir and added an NVidia-384.x component dir, and a "nvidia" metapackage to require either of these variants (and which other packages like xorg require in turn). This is needed because different driver line-ups support different chips, and are still re-released regularly. This approach with separately named packages, rather than providing `nvidia@0.(340|384|...).(respinNum)` packages allows users to more easily bolt the release-line they want, to support their actual hardware (and not get "upgraded" to incompatible newest driver). It also allows us to provide (or end-users to build for themselves) different driver lines at a later time, to support newer or older hardware.

### CODE REVIEW

**Comment by jimklimov** [comment]
Screenshot of a driver "upgrade" session:

````
$ sudo pkg install -v pkg://oi-userland-jim/driver/graphics/nvidia
WARNING: The boot environment being modified is not the active one.  Changes
made in the active BE will not be reflected on the next boot.

           Packages to install:          1
            Packages to update:          1
     Estimated space available:   39.60 GB
Estimated space to be consumed: 1007.02 MB
       Create boot environment:        Yes
     Activate boot environment:        Yes
Create backup boot environment:         No
          Rebuild boot archive:        Yes

Changed packages:
oi-userland-jim
  driver/graphics/nvidia-384
    None -> 0.384.69-2017.0.0.0
openindiana.org -> oi-userland-jim
  driver/graphics/nvidia
    0.340.102-2017.0.0.0 -> 1.0.0-2017.0.0.0

Editable files to change:
  Install:
    kernel/drv/nvidia_modeset.conf
  Update:
    kernel/drv/nvidia.conf

Planning linked: 0/1 done; 1 working: zone:test-giz-1
Linked image 'zone:test-giz-1' output:
|      Estimated space available:  39.59 GB
| Estimated space to be consumed: 669.11 MB
|           Rebuild boot archive:        No
`
Planning linked: 1/1 done
DOWNLOAD                                PKGS         FILES    XFER (MB)   SPEED
Completed                                2/2         85/85    66.7/66.7    0B/s

Downloading linked: 0/1 done; 1 working: zone:test-giz-1
Downloading linked: 1/1 done

PHASE                                          ITEMS
Removing old actions                           18/18
Installing new actions                       104/104
Updating modified actions                      80/80
Updating package state database                 Done 
Updating package cache                           1/1 
Updating image state                            Done 
Creating fast lookup database                   Done 
Reading search index                            Done 
Updating search index                            2/2 
...
````

**Comment by pyhalov** [comment]
@jimklimov Does new driver work for you (on some hardware)? 
@xen0l What do you think about delivering two incompatible packages? Should we tweak them to make it possible to install both?

**Comment by jimklimov** [comment]
Probably they won't install both "as is" due to delivery of same un-editable files. I hope there is a way to "replace" packages, without reinstalling xorg ultimately. :)

**Comment by jimklimov** [comment]
I did not yet try on hardware, but there are quite a few reports on https://wiki.openindiana.org/oi/Graphics+Adapters that a 384.69 driver worked for them. Perhaps we can ask someone to test, whose hardware is known to work for sure thanks to different installation methods - at least fails on mine will be inconclusive as no driver worked so far ;)

**Comment by pyhalov** [comment]
I think about 'pkg install pkg:/*'. One of OI Hipster goals was to make all packages coinstallable, and I think we are very good in this. I understand the benefits on having 2 driver versions, but I'll think twice before breaking this general rule. Can we mediate them? ;)

**Comment by jimklimov** [comment]
Yes, I assume that mediation is possible, both for kernel modules and for libs and other dirs. Probably it would make sense to mediate on a complete directory level (different releases serve different sets of files), e.g. make say `/usr/share/nvidia-(340|384|...)/(X11|lib|...)` and mediate one of these to `/usr/share/nvidia` and point `/usr/X11/NVidia` and whatnot to this common point. Or maybe `/usr/X11/NVidia/ => /usr/share/NVidia-xxx/X11/`, but not file links to avoid extra confusion.

**Comment by jimklimov** [comment]
I've tried to boot this yesterday but while proper nvidia driver version
and two videoadapters were reported in xorg.log (intel and nvidia), it
failed to bind any driver. So we need a known-working setup to test this
package.

Vesa at least left the text mode but did not display any image on laptop
LCD either.

**Comment by kenmays** [comment]
Optimally, we should add the Nvidia 304.135 driver. This provides driver coverage for the Nvidia 6 and 7-series and related Quadro cards.

**Comment by jimklimov** [comment]
Per @kenmays comments, added NVidia-304 drivers to the mix. Still pondering how to mediate these setups, if possible at all.

**Comment by pyhalov** [comment]
Just an idea of a hack to 'mediate' drivers. Deliver drivers in some out-of /kernel directory and have a service, which on boot will copy necessary driver version to /kernel and regenerate boot archive (if necessary) based on nvidia mediator. But I'm not sure what to do about /etc/driver_aliases . We could deliver them as devices_supported_by_older + devices_supported_by_newer driver. Sounds a bit hacky, but could work... @xen0l, @alarcher , @jimklimov - what do you think?

**Comment by kenmays** [comment]
1. Mediation of drivers and separate directory - review
2. Bump to Xserver 1.19.5 - Yes
3. Bump Intel driver to git current - Yes

--------------------------------------------
On Sun, 10/15/17, Alexander Pyhalov <notifications@github.com> wrote:

 Subject: Re: [OpenIndiana/oi-userland] [IN DISCUSSION] Provide packages for different NVidia driver types (#3458)
 To: "OpenIndiana/oi-userland" <oi-userland@noreply.github.com>
 Cc: "kenmays" <maybird1776@yahoo.com>, "Mention" <mention@noreply.github.com>
 Date: Sunday, October 15, 2017, 3:23 PM
 
 Just an idea of a hack to
 'mediate' drivers. Deliver drivers in some out-of
 /kernel directory and have a service, which on boot will
 copy necessary driver version to /kernel and regenerate boot
 archive (if necessary) based on nvidia mediator. But I'm
 not sure what to do about /etc/driver_aliases . We could
 deliver them as devices_supported_by_older +
 devices_supported_by_newer driver. Sounds a bit hacky, but
 could work... @xen0l, @alarcher , @jimklimov - what do
 you think?
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by optarg** [comment]
So, I have nvidia-384 working on my desktop. I opened a PR in @jimklimov's branch with some changes (mostly cosmetic, but some not) that will hopefully show up here. I still have a few things I'd like to look at--like the nvidia_modeset driver having to be explicity modloaded after being unloaded on boot--but not knowing when I'll get around to that, I figured I'd share my progress in case anyone else wants to play with it.

**Comment by jimklimov** [comment]
As a somewhat unpredictable direction of evolution, the mediated-installation approach is explored in a different PR #3673 which starts where this one stopped so far.

**Comment by jimklimov** [comment]
I do not intend to follow up with this half-solution (the mediation idea seems a lot neater, and the other PR #3673 was quite an effort to bring into shape after two years of staleness ;) - too much to do it twice for this one too in vain).

**Pull request closed without merging**
