### PR TITLE
Upgraded to ntfs-3g_ntfsprogs 2021.8.22

### PR DESCRIPTION
**Pull request by jpandre**
This fixes vulnerability threats caused by maliciously tampered NTFS
partitions
See : https://sourceforge.net/p/ntfs-3g/mailman/message/37343528/

### CODE REVIEW

**Comment by jpandre** [comment]
Wanted to add I kept "BUILD_BITS=32" in the Makefile, which was inserted by Alexander Pyhalov on Apr 14, 2020 for some reason unknown to me.

**Comment by pyhalov** [comment]
ntfsprogs were initially 32-bit. Perhaps, it's fine to build them 64 and 32-bit (as the deliver library). If library is unused currenrly, perhaps, they can be built 64-bit only. Anyway, switching to 64-bit ntfsprogs needs testing.

**Comment by jpandre** [comment]
Being all in user space, it does not really matter whether 32 or 64-bit, and I have tested both. I personally use 64-bit mode.

**Comment by AndWac** [comment]
Can you give me a hint when you are done with updating the PR?

**Comment by jpandre** [comment]
Hi Andreas,

I'm done now.

Actually, it was not my intention to merge libfuse into the ntfs-3g update.
However these are related, as OpenIndiana ships ntfs-3g with the external (unsupported) libfuse.

Sorry for the confusion.

Jean-Pierre

Andreas Wacknitz wrote on 9/1/21 5:49 PM:

**Comment by AndWac** [comment]
Your patches against libfuse won't work as expected. You'll need to separate them from this PR and also increment libfuse's COMPONENT_REVISION.

**Comment by AndWac** [comment]
Furtermore I recommend to work on a separate branch. Otherwise you'll sooner or later get in trouble.

**Pull request closed without merging**
