### PR TITLE
Update texinfo to 6.5

### PR DESCRIPTION
**Pull request by Mno-hime**

### CODE REVIEW

**Comment by pyhalov** [comment]
IIRC, gcc depend on texinfo. Have you checked that they build fine (especially old ones, including openindiana/illumos-gcc)?

**Comment by Mno-hime** [comment]
illumos-gcc needs a patch, will provide it later today here or to separate PR. GCC 4.9 and GCC 6 are fine. Can't test GCC 3.4 as dl.openindiana.org is down.

**Comment by pyhalov** [comment]
dlc is up again

**Comment by Mno-hime** [comment]
GCC 3.4 need the same kind of patch illumos-gcc does.

**Comment by Mno-hime** [comment]
Fixes for GCCs in #4749.

**Pull request merged**
