### PR TITLE
libreoffice: update to 7.5.4.2

### PR DESCRIPTION
**Pull request by iigs**
Besides the version bump, the most important change is getting the downloaded third part libraries updated.  Re-added mariadb-connector support.  No update to python uno access.  It does not appear that there are ant new regressions.

### CODE REVIEW

**Comment by AndWac** [comment]
There seems to be a problem with a checksum:
Source https://dev-www.libreoffice.org/src/libcmis-0.5.2.tar.xz...
    downloading... ok
    validating signature... checking local signature... not found
    signature validation failed

    validating hash... invalid hash!
    expected: sha256:0d08a99ed46cde43b5ad2672b5d8770c8eb85d0d26cb8f1f85fd9befe1e9ceb9
    actual:   sha256:d7b18d9602190e10d437f8a964a32e983afd57e2db316a07d87477a79f5000a2
    payload:  False
ERROR: This download failed to validate.

**Comment by iigs** [comment]
I see the problems in the Makefile and understand why I missed it (files were cached in archive and my renumber of the COMPONENT_ARCHIVE_URL_26 and higher did not get the COMPONENT_ARCHIVE_## number corrected).  I will test download of the files and a full build before submitting changes.

**Comment by AndWac** [comment]
Any news here?

**Comment by iigs** [comment]
This is my first attempt to make changes to a pull request.  I am hoping that I did this successfully.

**Pull request merged**
