### PR TITLE
Add subdir macros

### PR DESCRIPTION
**Pull request by alarcher**
Similar to the macros defined in the x11 gate, to be reused for consistency.

### CODE REVIEW

**Comment by pyhalov** [comment]
Where is it going to be used?

**Comment by alarcher** [comment]
This is a macro used in x11 components but also may avoid redefining them in other components.

**Comment by pyhalov** [comment]
I'm asking because of inconsistency between LIB/BIN macroses. So I'm interested in real use cases.

**Comment by alarcher** [comment]
It is basically always the case except for very few uses of isaexec.

**Comment by pyhalov** [comment]
Perhaps, I miss something.
BINSUBDIR32 = $(MACH32) will make BINSUBDIR32=i86 , which we usually don't use except for very few uses of isaexec, so why it's not empty?

**Comment by alarcher** [comment]
Let me check I am on the phone and I replied maybe too fast.

**Comment by alarcher** [comment]
OK I can drop the BINSUBDIR but I'd like to keep LIBSUBDIR which is also named as ARCHLIBSUBDIR for example in xf86-video-*.
I can use ARCHLIBSUBDIR and modify my x11 components to match the existing one.

**Comment by pyhalov** [comment]
Sounds good

**Pull request merged**
