### PR TITLE
pcs: manifest change

### PR DESCRIPTION
**Pull request by alarcher**
@grueni

### CODE REVIEW

**Comment by pyhalov** [comment]
Can we somehow patch it to pull specific version of dependencies? Otherwise it'll be always broken

**Comment by Mno-hime** [comment]
I suggest to update the package while at it as there are three CVEs.

**Comment by alarcher** [comment]
@pyhalov @Mno-hime Should ask @grueni to update it or remove it.

**Comment by pyhalov** [comment]
Why remove? pcs is an alternative to crmsh , we should provide it for cluster management.

**Comment by alarcher** [comment]
@pyhalov I do not know what it is used for, just saying that if someone should update it that won't be me :P

**Comment by Mno-hime** [comment]
Ported those patches but the generated sample-manifest doesn't look too good, too much stuff is missing. If someone wanted to drag this further: https://github.com/Mno-hime/oi-userland/tree/pcs_0.9.168.

Here are those CVEs, but they need some porting as well: https://github.com/ClusterLabs/pcs/compare/0.9.163...0.9.164.

**Comment by grueni** [comment]
I will check next it next week.
Unfortunately I am actually very engaged by my daily business and so very short in time.

Von: Michal Nowak [mailto:notifications@github.com]
Gesendet: Samstag, 10. August 2019 19:10
An: OpenIndiana/oi-userland
Cc: Grüninger, Andreas (LGL Extern); Mention
Betreff: Re: [OpenIndiana/oi-userland] pcs: manifest change (#5215)


Ported those patches but the generated sample-manifest doesn't look too good, too much stuff is missing. If someone wanted to drag this further: https://github.com/Mno-hime/oi-userland/tree/pcs_0.9.168.

Here are those CVEs, but they need some porting as well: ClusterLabs/pcs@0.9.163...0.9.164<https://github.com/ClusterLabs/pcs/compare/0.9.163...0.9.164>.

**Comment by grueni** [comment]
Please see in https://github.com/OpenIndiana/oi-userland/pull/5240

**Pull request closed without merging**
