### PR TITLE
[PARKED] Update libusb-1 to 1.0.23 + fix control transfers

### PR DESCRIPTION
**Pull request by jimklimov**
This PR follows from a merger of #5382 and #5277 

CC people involved in those PRs: @zykh @citrus-it @Mno-hime @pyhalov

### CODE REVIEW

**Comment by Mno-hime** [comment]
@jimklimov Please, rebase and resolve conflicts, I am happy to test then.

**Comment by jimklimov** [comment]
@Mno-hime : I believe this PR to be the rebase of my earlier #5382 (the proposed fix for control transfer code) over your update of libusb itself in #5277 - at least, this current PR is not in conflict with oi-userland upstream and includes both those change sets :)

And I don't see any newer commits in your PR at the moment to re-rebase over again :)

**Comment by Mno-hime** [comment]
@jimklimov I meant rebase on top of `oi/hipster`. See the text below: "This branch cannot be rebased due to conflicts: Rebasing the commits of this branch on top of the base branch cannot be performed automatically due to conflicts encountered while reapplying the individual commits from the head branch."

**Comment by jimklimov** [comment]
@Mno-hime : sorry for stalling, this browser tab fell out of my focus for a while :(
Rebased against today's `oi/hipster` ...

And can not re-open the PR :\ Made another in #5709

**Pull request closed without merging**
