### PR TITLE
openldap - update to version 2.6.2

### PR DESCRIPTION
**Pull request by fritzkink**

### CODE REVIEW

**Comment by AndWac** [comment]
When build this it fails every first try:
..
make[4]: Leaving directory '/export/home/andreas/oi-userland/components/network/openldap/build/i86/servers/slapd/overlays'
make[3]: Leaving directory '/export/home/andreas/oi-userland/components/network/openldap/build/i86/servers/slapd'
make[2]: *** [Makefile:300: all-common] Error 1
make[2]: Leaving directory '/export/home/andreas/oi-userland/components/network/openldap/build/i86/servers'
make[1]: *** [Makefile:321: all-common] Error 1
make[1]: Leaving directory '/export/home/andreas/oi-userland/components/network/openldap/build/i86'
gmake: *** [/export/home/andreas/oi-userland/make-rules/configure.mk:183: /export/home/andreas/oi-userland/components/network/openldap/build/i86/.built] Error 2

Re-running from this state successfully finishes then.

**Comment by fritzkink** [comment]
I guess this happened because default perl changed. It should now work independently from default perl version (basically it is because perl changed from 32-bit to 64-bit)

**Comment by AndWac** [comment]
The build still fails here.

**Comment by fritzkink** [comment]
ok I fixed only half of the 32-bit build. Now everything is running.

**Pull request merged**
