### PR TITLE
Update qtcreator to v7.0.1 (Based on qt5.15.3)

### PR DESCRIPTION
**Pull request by shuryanc**
Update qtcreator to v7.0.1 and made it based on qt5.15.3

### CODE REVIEW

**Comment by AndWac** [comment]
Doesn't build here:
[ 87%] Linking CXX shared library ../../../lib/amd64/qtcreator/plugins/libAndroid.so
make[3]: Leaving directory '/export2/home/andreas/oi-userland/components/editor/qtcreator/build/amd64'
[ 87%] Built target Android
make[2]: Leaving directory '/export2/home/andreas/oi-userland/components/editor/qtcreator/build/amd64'
make[1]: *** [Makefile:136: all] Error 2
make[1]: Leaving directory '/export2/home/andreas/oi-userland/components/editor/qtcreator/build/amd64'
gmake: *** [/export2/home/andreas/oi-userland/make-rules/cmake.mk:179: /export2/home/andreas/oi-userland/components/editor/qtcreator/build/amd64/.built] Error 2

**Comment by shuryanc** [comment]
I tried to build again but cannot reproduce. Could you build with VERBOSE=1 (i.e. gmake publish VERBOSE=1) to see more details?

**Comment by AndWac** [comment]
Is it possible to change from this dynamic downloads of the sources by git to something based on archives? It is really hard to get this through the build server. The same is true for megasync which is being build by every jenkins run.

**Comment by hoewweken** [comment]
The link would be
https://download.qt.io/official_releases/qtcreator/7.0/7.0.1/qt-creator-opensource-src-7.0.1.tar.xz

**Pull request merged**
