### PR TITLE
Bump hunspell to 1.6.2

### PR DESCRIPTION
**Pull request by alarcher**
Only one dependent component: library/spell-checking/enchant

### CODE REVIEW

**Comment by pyhalov** [comment]
And qt5. have you checked that it likes this update?

**Comment by pyhalov** [comment]
ping

**Comment by alarcher** [comment]
@pyhalov In deep shit for work, no time sorry.

**Comment by pyhalov** [comment]
no problems

**Comment by pyhalov** [comment]
any news on it?

**Comment by alarcher** [comment]
@pyhalov I have rebuilt qt5 with it on wednesday, no problem.

**Comment by pyhalov** [comment]
Please, create PR to rebuild dependent components.

**Comment by alarcher** [comment]
@pyhalov This will have to wait until next week i am afraid.

**Comment by alarcher** [comment]
@pyhalov Rebuild of qt5 is in #3739 with enchant.

**Pull request merged**
