### PR TITLE
Upgrade of mercurial to 5.9.3 with python 3.7 and 3.9

### PR DESCRIPTION
**Pull request by jgmills**
Mercurial is a distributed revision control tool.  This PR upgrades mercurial from 5.3.2 to 5.9.3, with python versions 3.7 and 3.9 .  The old mercurial used python versions 2.7 and 3.5 .  This PR also obsoletes the old mercurial packages.

The changes are mainly to accomodate the mercurial version upgrades and the python changes.  The Makefile also omits the manpages.patch target, as it is really documentation for developers.  It also extends the test blacklist to omit four failing tests.  Some of the patch files are deleted, as they are no longer needed.  Some are modified to accomodate the new mercurial version.

The manifest file mercurial-PYVER.p5m is also changed to accomodate the mercurial version upgrade.  In addition, it uses mediator=python3 to accomodate the python upgrade, and uses the OI python-3-soabi transform to convert ".so" to ".cpython-3X.so".  It also omits two license files, as these are no longer needed.

The build, install, and publish steps were all successful.  The built-in test target produced zero failures with 876 passed tests.  Both python versions produced the same result.

### CODE REVIEW

**Comment by AndWac** [comment]
Neither your commit message nor the PR title match your files and comment.

**Comment by jgmills** [comment]
Thanks for noticing my copying error.  The commit title should be:

Upgrade of mercurial to 5.9.3 with python 3.7 and 3.9

I know how to change the commit message, but I don't believe it's possible to change the PR title except by deleting and replacing it.

**Comment by AndWac** [comment]
Am 05.11.21 um 19:10 schrieb Gary Mills:
>
> Thanks for noticing my copying error. The commit title should be:
>
> Upgrade of mercurial to 5.9.3 with python 3.7 and 3.9
>
> I know how to change the commit message, but I don't believe it's
> possible to change the PR title except by deleting and replacing it.
>
>
At least I have an edit button next to the title (right hand).

**Comment by jgmills** [comment]
Yes, I have the Edit button too: I didn't notice it before.  I see you corrected the PR title.

I just force-pushed the branch again.  I see that that fixed the commit title.  I presume everything is okay now.

**Review by AndWac — APPROVED** [review]

**Pull request merged**
