### PR TITLE
Update gobject-introspection to 1.43.3

### PR DESCRIPTION
**Pull request by mtelka**

### CODE REVIEW

**Comment by pyhalov** [comment]
Please, move it to some appropriate category (http://wiki.openindiana.org/oi/Categories+layout), perhaps, library/

**Comment by mtelka** [comment]
Moved.

**Comment by pyhalov** [comment]
Please, merge commits.

**Comment by mtelka** [comment]
Why? I prefer to see both changes separated.

**Comment by pyhalov** [comment]
I'd say moving to subcategory is a part of touching component, so shouldn't be separated. I made separate commit with just move step only when basic work on updating wasn't mine.

**Comment by mtelka** [comment]
Move and update are two separate and not related tasks.  I prefer to see two separate commits for that.  If you do not want two commits in one PR, then I'll split this PR to two PRs.

**Pull request merged**
