### PR TITLE
caja: update to 1.26.0

### PR DESCRIPTION
**Pull request by timmooney**
I don't think I can add the "needs testing" or "needs review" tags, but this one especially really needs other eyes testing this update, especially our local changes for timeslider integration.

This is the 4th and last package in "Group 3" of the MATE package updates:

Group 3:
- `mate-panel` #7465 
- `eom` #7466 
- `mate-settings-daemon` #7467
- `caja`

**I don't use timeslider**, and I wasn't aware until this update the size of our local patchset for `caja`.  Several parts of the patch needed to be adjusted for changed code, so it would be really great to have people that use the `timeslider` functionality test the updated version.  If there are reviewers that are very familiar with the original patches, having them review the changes would also be good.

### CODE REVIEW

**Comment by AndWac** [comment]
The time-slider patch doesn't seem to be correct. Pushing the "Browse the current location snapshot history" immediately dumps core.

**Comment by AndWac** [comment]
╰─➤  mdb core
Loading modules: [ libc.so.1 libumem.so.1 libnvpair.so.1 libuutil.so.1 libavl.so.1 libsmbios.so.1 libtopo.so.1 ld.so.1 ]
> ::stack
libc.so.1`_lwp_kill+0xa()
libc.so.1`raise+0x1e(6)
libc.so.1`abort+0x58()
libglib-2.0.so.0.6600.8`g_assertion_message+0x19d()
libglib-2.0.so.0.6600.8`g_assertion_message_expr+0x53()
0x5882b9()
get_column_order+0xa0()
default_visible_columns_changed_callback+0x2b()
libgobject-2.0.so.0.6600.8`g_closure_invoke+0x195()
libgobject-2.0.so.0.6600.8`signal_emit_unlocked_R+0x10a2()
libgobject-2.0.so.0.6600.8`g_signal_emit_valist+0xa15()
libgobject-2.0.so.0.6600.8`g_signal_emit+0x7d()
libgio-2.0.so.0.6600.8`g_settings_real_change_event+0x72()
libgio-2.0.so.0.6600.8`_g_cclosure_marshal_BOOLEAN__POINTER_INTv+0x69()
libgobject-2.0.so.0.6600.8`_g_closure_invoke_va+0x1ad()
libgobject-2.0.so.0.6600.8`g_signal_emit_valist+0x2ed()
libgobject-2.0.so.0.6600.8`g_signal_emit+0x7d()
libgio-2.0.so.0.6600.8`settings_backend_changed+0x93()
libgio-2.0.so.0.6600.8`g_settings_backend_invoke_closure+0x22()
libglib-2.0.so.0.6600.8`g_main_context_invoke_full+0x45()
libgio-2.0.so.0.6600.8`g_settings_backend_dispatch_signal+0x10b()
libdconfsettings.so`dconf_engine_change_fast+0x16f()
libdconfsettings.so`dconf_settings_backend_write+0x44()
libgio-2.0.so.0.6600.8`g_settings_backend_write+0x35()
libgio-2.0.so.0.6600.8`g_settings_set_value+0x1c4()
zfs_bar_show_column+0x114()
libgobject-2.0.so.0.6600.8`g_closure_invoke+0x195()
libgobject-2.0.so.0.6600.8`signal_emit_unlocked_R+0x10a2()
libgobject-2.0.so.0.6600.8`g_signal_emit_valist+0xa15()
libgobject-2.0.so.0.6600.8`g_signal_emit+0x7d()
libgtk-3.so.0.2404.27`gtk_widget_show+0xb6()
action_restore_callback+0xdf()
libgobject-2.0.so.0.6600.8`g_closure_invoke+0x195()
libgobject-2.0.so.0.6600.8`signal_emit_unlocked_R+0x10a2()
libgobject-2.0.so.0.6600.8`g_signal_emit_valist+0xa15()
libgobject-2.0.so.0.6600.8`g_signal_emit+0x7d()
libgtk-3.so.0.2404.27`_gtk_action_emit_activate+0x41()

**Comment by timmooney** [comment]
Thanks Andreas.  That button is completely grayed out for me, likely because I've never done anything with timeslider.

I'll take a look at the patch and what's going on around `get_column_order` and see if I can spot anything that might be the problem.

**Comment by AndWac** [comment]
Am 27.12.21 um 18:10 schrieb Tim Mooney:
>
> Thanks Andreas. That button is completely grayed out for me, likely
> because I've never done anything with timeslider.
>
The button is only usable, if you visit a folder for that snapshots
exists. In order to be able to test time-slider you'll need to do two
things:

1. activate one of the auto-snapshot services, eg. pfexec svcadm enable
auto-snapshot:hourly
2. configure time-slider (choose the ZFS filesystems that should be
snapshotted, eg. by running time-slider-setup (with appropriate
privileges)).

When you have snapshots the button can be pressed and then you'll get
the core dump.

**Comment by timmooney** [comment]
> The button is only usable, if you visit a folder for that snapshots exists. In order to be able to test time-slider you'll need to do two things: 1. activate one of the auto-snapshot services, eg. pfexec svcadm enable auto-snapshot:hourly 2. configure time-slider (choose the ZFS filesystems that should be snapshotted, eg. by running time-slider-setup (with appropriate privileges)). When you have snapshots the button can be pressed and then you'll get the core dump.

Thanks for the instructions, I just configured `time-slider` for directories under my home on my build box (to keep the snapshots small; I don't have a lot of extra space on my build box).  All of the `auto-snapshot` services were already enabled, so I just disabled some of them and left `hourly` and `daily` enabled.

Interestingly, now that I have a single snapshot, I can press the "Browse the current location snapshot history" and it doesn't segfault for me.  It's fine so far.  I can also use the "camera" button to take a snapshot, and that works too.  I even had the browse window open when an hourly snapshot was taken, and I could see it inserted into the timeline before "Now".

Were you attempting to browse a "system" directory when caja crashed, or was it one of your own directories?   I'm just trying to narrow down what I might need to do to reproduce the crash.

I do see a few warnings while compiling `caja-directory.c` that are related to the patch, I'll start by looking into those.   Looking at the code, there's also a suspicious looking `g_free(path)` in `collect_all_directories` that I need to investigate.

**Comment by AndWac** [comment]
I tried the history browser in my own home folder. I just retried it and now it works as expected. So the problem seems to be gone for me. Probably there is a missing zero size check leading to the segfault.

**Pull request merged**
