### PR TITLE
elinks: Move to web section and make 64bit only

### PR DESCRIPTION
**Pull request by hliebel**

### CODE REVIEW

**Review by alarcher — CHANGES_REQUESTED** [review]
Need to investigate why the encoding is wrong with the 64-bit version. Accented characters cannot be displayed.

**Comment by hliebel** [comment]
Which page did you use for your test?
I looked up some random site that looked ok:
-> elinks https://ascii.cl/es/
Compared to Firefox it just removes the accents for me, looks ok. I'm running a default US english install of OI, Do you use a different localisation or fonts?

**Comment by alarcher** [comment]
@hliebel My locale is fr_FR.UTF-8

**Comment by alarcher** [comment]
@hliebel i just tried to open the same page on Debian for comparison: elinks is not able to open it, so it seems our elinks is less broken ^ ^

**Comment by alarcher** [comment]
Actually it is now completely broken with a bunch of websites...

**Comment by pyhalov** [comment]
This has been already made.

**Comment by alarcher** [comment]
@pyhalov The encodings on the 64-bit build were completely broken so I assume that the merged version has been tested and works correctly?

**Comment by pyhalov** [comment]
@Mno-hime  ?

**Comment by Mno-hime** [comment]
With `LC_ALL=de_DE.UTF-8` I see "tofu" in `F10` menus characters in both 32- and 64-bit `elinks`. When pointer cursor to a link it's somewhat doubling the text of the link with 32-bit elinks... So I guess it is broken either way?

**Pull request closed without merging**
