### PR TITLE
Mate 1.18 update

### PR DESCRIPTION
**Pull request by kenmays**
Updates Mate 1.18 desktop

### CODE REVIEW

**Review by alarcher — COMMENTED** [review]
Cool :) Just make sure to squash the two commits for mate-desktop.

**Review by alarcher — COMMENTED** [review]
mate-system-monitor: patch 03 should be removed as it has been integrated.

**Review by alarcher — COMMENTED** [review]
mate-control-center: manifest should be updated.

**Comment by alarcher** [comment]
@pyhalov I have been running this for a week now.

**Comment by pyhalov** [comment]
Are there any inter-dependencies?

**Comment by pyhalov** [comment]
If there are none, I'm fine with merging this either as one commit or as series of commits if history is cleaned up

**Comment by alarcher** [comment]
I have built everything at once so I believe it is only about squashing some commits.

**Comment by alarcher** [comment]
Squashed commits in #4453 Thanks very much for doing this @kenmays

**Pull request closed without merging**
