### PR TITLE
Update hplip to 3.19.12

### PR DESCRIPTION
**Pull request by pyhalov**

### CODE REVIEW

**Comment by pyhalov** [comment]
@timmooney Are you interested in reviewing it?

**Comment by pyhalov** [comment]
I have no actual means to test it...

**Comment by timmooney** [comment]
I do not know if I will have time to build and test.  I only have access to HP printers (and only a couple models of those), so I wouldn't be able to test the multi-function aspects of hplip, just the printing.

I looked through the diff and all the changes looked good to me.

**Comment by hoewweken** [comment]
Did a short test, scan over net works as usual with "scanimage",
scanning via USB does not, but that never worked for me on OI.
So no differences to the previous version.
I Did hope that with the link to libusb-1 and python 3.5 there could ba a change..

BUT theres a package missing with hp-scan
error: hp-scan requires the Python Imaging Library (PIL). Exiting.

From what i see theres no PIL package for python-35, we need
pkg:/library/python/python-imaging-35


From my point of view we could even go to the up-to-date-Version 3.20.3

COMPONENT_NAME=         hplip
COMPONENT_VERSION=      3.20.3
COMPONENT_PROJECT_URL= https://developers.hp.com/hp-linux-imaging-and-printing
COMPONENT_SRC=          $(COMPONENT_NAME)-$(COMPONENT_VERSION)
COMPONENT_ARCHIVE=      $(COMPONENT_SRC).tar.gz
COMPONENT_ARCHIVE_HASH= sha256:41097ec52af5cce51ec7b0200d9f9ec82649b58ae7105259e82130e9cf63066a

With this 3.20.3 - build all the same here, "works for me"

i use an old Deskjet_2050_J510_series MFP btw.

**Comment by pyhalov** [comment]
Does it work with #5605 ? @hoewweken

**Comment by hoewweken** [comment]
WIth PR 5605, pillow ist build, installed, hp-scan error is gone, 
hp-scan works as expected on my machine with my scanner (NET ok, no USB as usual in my env).

**Comment by hoewweken** [comment]
$ pkg info hplip
             Name: print/filter/hplip
          Summary: hpijs - HP InkJet Server
         Category: System/Printing
            State: Installed
        Publisher: userland
          Version: 3.20.3
           Branch: 2020.0.0.0
   Packaging Date: 13 March 2020 at 19:39:21
Last Install Time:  7 September 2019 at 19:52:20
 Last Update Time: 13 March 2020 at 19:41:51
             Size: 45.01 MB
             FMRI: pkg://userland/print/filter/hplip@3.20.3-2020.0.0.0:20200313T193921Z
       Source URL: http://sourceforge.net/projects/hplip/files/hplip/3.20.3/hplip-3.20.3.tar.gz
      Project URL: https://developers.hp.com/hp-linux-imaging-and-printing
$ pkg info pillow
             Name: library/python/pillow
          Summary: Python image processing library
         Category: Development/Python
            State: Installed
        Publisher: userland
          Version: 6.2.2
           Branch: 2020.0.0.0
   Packaging Date: 14 March 2020 at 09:01:49
Last Install Time: 14 March 2020 at 09:07:30
             Size: 0.00 B
             FMRI: pkg://userland/library/python/pillow@6.2.2-2020.0.0.0:20200314T090149Z
       Source URL: pypi:///Pillow==6.2.2
      Project URL: https://pypi.org/project/Pillow/

**Pull request merged**
