### PR TITLE
Update libusb-1 to 1.0.23

### PR DESCRIPTION
**Pull request by Mno-hime**
Changelog: https://github.com/libusb/libusb/blob/master/ChangeLog

SunOS patches merged upstream.

ABI Checker (WIP): https://abi-laboratory.pro/index.php?view=timeline&l=libusb

**Testing**
- xsane scans fine
- camera displays photos correctly: Canon Digital IXUS 100 IS works fine with `gphoto2` and `gtkam` (photo retrieva/removal, metadata, camera auto-detection, ...)

### CODE REVIEW

**Comment by pyhalov** [comment]
If you have time, you can look at patch attached to https://github.com/libusb/libusb/issues/586 to remove list_* functions usage (alternative to 06-disable-functions-requiring-list-api.patch).

**Comment by Mno-hime** [comment]
Brought in other Solaris changes merged upstream yesterday. Needs some testing though.

**Comment by Mno-hime** [comment]
Implemented test target. The `stress` program works in GZ:
```
 newman  ~  ./stress.amd64 
Starting test run: init_and_exit...
Success (0)
Starting test run: get_device_list...
Success (0)
Starting test run: many_device_lists...
Success (0)
Starting test run: default_context_change...
Success (0)
---
Ran 4 tests
Passed 4 tests
Failed 0 tests
Error in 0 tests
Skipped 0 tests
 newman  ~  ./stress.i86 
Starting test run: init_and_exit...
Success (0)
Starting test run: get_device_list...
Success (0)
Starting test run: many_device_lists...
Success (0)
Starting test run: default_context_change...
Success (0)
---
Ran 4 tests
Passed 4 tests
Failed 0 tests
Error in 0 tests
Skipped 0 tests
```

**Comment by Mno-hime** [comment]
**Testing**
- [x] printing
- [ ] scanning
- [ ] camera
- [ ] cell phone MTP

**Comment by Mno-hime** [comment]
Scanning works, MTP didn't work with my Nexus 5X (Android 8.1), `gphoto` fails on file listing and file retrieval, see the debuginfo https://paste.ec/paste/Hew-hlF4#Faa1tG0RWh+kHI2ZMqsSZSVXe7Ikk4Db+fKiIAu+r6B. With the old `libusb-1` it works.

**Comment by jimklimov** [comment]
There are quite a few build warnings about `usbi_dbg()` routine, falling into categories:
1) empty logs, e.g.:
````
  CC       libusb_1_0_la-core.lo
In file included from /export/home/jim/shared/oi-userland/components/library/libusb-1/libusb-1.0.23/libusb/core.c:44:0:
/export/home/jim/shared/oi-userland/components/library/libusb-1/libusb-1.0.23/libusb/core.c: In function 'libusb_get_device_list':
/export/home/jim/shared/oi-userland/components/library/libusb-1/libusb-1.0.23/libusb/core.c:815:11: warning: zero-length gnu_printf format string [-Wformat-zero-length]
  usbi_dbg("");
           ^
/export/home/jim/shared/oi-userland/components/library/libusb-1/libusb-1.0.23/libusb/libusbi.h:238:71: note: in definition of macro '_usbi_log'
 #define _usbi_log(ctx, level, ...) usbi_log(ctx, level, __FUNCTION__, __VA_ARGS__)
                                                                       ^~~~~~~~~~~
/export/home/jim/shared/oi-userland/components/library/libusb-1/libusb-1.0.23/libusb/core.c:815:2: note: in expansion of macro 'usbi_dbg'
  usbi_dbg("");
  ^~~~~~~~
````

2) Different int types mapped to generic format strings (perhaps better use PRIi64 etc?):

````
/export/home/jim/shared/oi-userland/components/library/libusb-1/libusb-1.0.23/libusb/os/sunos_usb.c: In function 'sunos_add_devices':
/export/home/jim/shared/oi-userland/components/library/libusb-1/libusb-1.0.23/libusb/os/sunos_usb.c:664:12: warning: format '%llx' expects argument of type 'long long unsigned int', but argument 7 has type 'long unsigned int' [-Wformat=]
   usbi_dbg("Device %s %s id=0x%llx, devcount:%d, bdf=%x",
            ^


/export/home/jim/shared/oi-userland/components/library/libusb-1/libusb-1.0.23/libusb/os/sunos_usb.c:664:12: warning: format '%d' expects argument of type 'int', but argument 8 has type 'size_t {aka long unsigned int}' [-Wformat=]
   usbi_dbg("Device %s %s id=0x%llx, devcount:%d, bdf=%x",
            ^


/export/home/jim/shared/oi-userland/components/library/libusb-1/libusb-1.0.23/libusb/os/sunos_usb.c:664:12: warning: format '%x' expects argument of type 'unsigned int', but argument 9 has type 'uint64_t {aka long unsigned int}' [-Wformat=]
   usbi_dbg("Device %s %s id=0x%llx, devcount:%d, bdf=%x",
            ^

````

**Comment by jimklimov** [comment]
Tested the binary library from this PR on the OmniOS system where I have NUT monitoring the USB UPS for the past year or two (with an older build of OI libusb-1 patched like in #5382), and it failed with the not-patched library:

````
...
   5.164516     [D5] Exponent = 0
   5.164536     [D2] Path: UPS.PowerSummary.iDeviceChemistry, Type: Feature, ReportID: 0x10, Offset: 0, Size: 8, Value: 5
   5.164555     [D3] hid_ups_walk(): BP1
   5.164575     [D3] hid_ups_walk(): BP2
   5.164593     [D3] ups_infoval_set(): BP0
   5.164612     [D3] ups_infoval_set(): BP1
   5.164630     [D3] hu_find_infoval: BP0
   5.164649     [D3] hu_find_infoval: BP1: func=40d872 value=5
   5.164668     [D3] stringid_conversion_fun=5
   5.164688     [D3] HIDGetIndexString(): BP0 name='USB communication driver (libusb 1.0)' ver='0.9'
   5.164706     [D3] libusb1:nut_libusb_get_string(): BP0
   5.164726     [D3] libusb1:nut_libusb_get_string(): BP1
Segmentation Fault (core dumped)
````

Applying the patch proposed in #5382 did fix this segfault.

**Comment by jimklimov** [comment]
Posted #5491 with sources for the successfully tested merger of PRs #5382 and #5277

**Comment by pyhalov** [comment]
Merged as #5709

**Pull request closed without merging**
