### PR TITLE
Obsolete deprecated x11/network/rstart

### PR DESCRIPTION
**Pull request by mtelka**
See https://gitlab.freedesktop.org/xorg/app/rstart

### CODE REVIEW

**Comment by AndWac** [comment]
This one failed:
oi@hipster:~$ pfexec pkg install userland-incorporation@0.5.11-2024.0.0.22863
Creating Plan (Solver setup): |
pkg install: No matching version of consolidation/userland/userland-incorporation can be installed:
  Reject:  pkg://openindiana.org/consolidation/userland/userland-incorporation@0.5.11-2024.0.0.22863
  Reason:  No version matching 'incorporate' dependency consolidation/X/X-incorporation@0.5.11-2024.0.0.8 can be installed
    ----------------------------------------
    Reject:  pkg://openindiana.org/consolidation/X/X-incorporation@0.5.11-2024.0.0.8
    Reason:  No version matching 'incorporate' dependency library/motif/libdpstkxm@0.5.11-2013.0.0.0 can be installed
      ----------------------------------------
      Reject:  pkg://openindiana.org/library/motif/libdpstkxm@0.5.11-2013.0.0.0
      Reason:  No version matching 'require' dependency consolidation/X/X-incorporation can be installed
      ----------------------------------------
    Reason:  No version matching 'incorporate' dependency x11/network/rstart@1.0.3-2013.0.0.0 can be installed
      ----------------------------------------
      Reject:  pkg://openindiana.org/x11/network/rstart@1.0.3-2013.0.0.0
      Reason:  Excluded by proposed incorporation 'consolidation/userland/userland-incorporation'
      ----------------------------------------
    ----------------------------------------


oi@hipster:~$ pfexec pkg uninstall X-incorporation rstart library/motif/libdpstkxm
Creating Plan (Solver setup): -
pkg uninstall: Unable to remove 'consolidation/X/X-incorporation@0.5.11-2024.0.0.8' due to the following packages that depend on it:
  system/kernel/hardware-cursor@0.5.11-2013.0.0.0
  x11/library/dps@7.5-2013.0.0.0
  x11/library/libowconfig@0.5.11-2013.0.0.0
  x11/network/x11-network-proxies@7.5-2013.0.0.0
  x11/server/xorg/driver/xorg-video@0.5.11-2023.0.0.3

**Comment by AndWac** [comment]
I have manually uninstalled the offending packages:
oi@hipster:~$ pfexec pkg uninstall X-incorporation rstart library/motif/libdpstkxm system/kernel/hardware-cursor x11/library/dps x11/library/libowconfig x11/network/x11-network-proxies x11/server/xorg/driver/xorg-video

**Comment by mtelka** [comment]
Sorry, I missed that the `incorporate` dependency constraints package uninstalls too.  I'll fix it shortly.

**Comment by mtelka** [comment]
... but, OTOH, I'm not sure why it does so.  I think the dependency evaluation in `pkg` is flawed.

**Pull request merged**
