### PR TITLE
build-essential: add python runtime packages

### PR DESCRIPTION
**Pull request by alarcher**
Required by illumos-gate as suggest by @jlevon

### CODE REVIEW

**Comment by pyhalov** [comment]
They are not strictly required and make build essential much less essential. Also note, that illumos-gate can be built without one of the pythons. Likely it's better to be added to illumos-gate component REQUIRED_PACKAGES.

**Review by xen0l — APPROVED** [review]

**Comment by pyhalov** [comment]
Should we also add runtime/gcc-7 there? 
Or better split out illumos-gate build dependencies from build-essential?

**Comment by Mno-hime** [comment]
Maybe these Python runtimes and gcc-7 can at least/also be added as `REQUIRED_PACKAGES` to illumos-gate component so it's obvious what's required.

**Comment by pyhalov** [comment]
@alarcher  Please, rebase :)

**Comment by pyhalov** [comment]
@alarcher Also, what do you think about splitting illumos build dependencies in separate package?

**Comment by pyhalov** [comment]
Merged as https://github.com/OpenIndiana/oi-userland/pull/5139

**Pull request closed without merging**
