### PR TITLE
Remove dependency on deprecated developer/library/lint

### PR DESCRIPTION
**Pull request by AndWac**

### CODE REVIEW

**Comment by pyhalov** [comment]
It's only one part of the problem. Another one I to drop lint-libraries.mk and lint libraries from oi-userland

**Review by pyhalov — APPROVED** [review]

**Comment by pyhalov** [comment]
```
$ git grep lint-libraries.mk |cut -d : -f 1 
components/archiver/bzip2/Makefile                                                                                                                                                                                               
components/library/gd2/Makefile                                                                                                                                                                                                  
components/library/lcms2/Makefile                                                                                                                                                                                                
components/library/libxml2/Makefile                                                                                                                                                                                              
components/library/openssl/openssl-1.0.2/Makefile                                                                                                                                                                                
components/library/readline/Makefile                                                                                                                                                                                             
components/library/trousers/Makefile                                                                                                                                                                                             
components/library/zlib/Makefile                                                                                                                                                                                                 
components/python/python34/Makefile                                                                                                                                                                                              
components/python/python35/Makefile                                                                                                                                                                                              
components/text/tidy/Makefile
make-rules/common.mk
make-rules/lint-libraries.mk
make-rules/lint-libraries.mk
```

**Comment by AndWac** [comment]
Shall I create another PR or will you take over?

**Comment by pyhalov** [comment]
Merge this and create one more.

**Pull request merged**
