### PR TITLE
golang 1.8.7 and 1.10.5

### PR DESCRIPTION
**Pull request by Mno-hime**

### CODE REVIEW

**Review by Toasterson — CHANGES_REQUESTED** [review]
Can you build glang 1.8.7 on your computer?
I am getting

##### Building Go bootstrap tool.
cmd/dist
ERROR: Cannot find /export/home/toast/workspace/openindiana/userland/components/developer/golang-18/build/amd64/golang1.4.3/bin/go.
Set $GOROOT_BOOTSTRAP to a working Go tree >= Go 1.4.
gmake: *** [/export/home/toast/workspace/openindiana/userland/make-rules/justmake.mk:62: /export/home/toast/workspace/openindiana/userland/components/developer/golang-18/build/amd64/.built] Error 1

**Comment by Toasterson** [comment]
golang 1.10 builds and publishes.

**Comment by alarcher** [comment]
Hmm... I cannot comment for now... since the update of gcc-7 and gcc-8 weird things happen... now elfedit core dumps...

**Comment by Toasterson** [comment]
Ah thats the core I am getting too...

You mean this?
core 'core' of 20949:    /usr/bin/elfedit -re dyn:runpath /export/home/toast/workspace/openindi
 fffffd7fe74d4311 strncpy () + 71
 000000000040b935 init_obj_state () + 105
 000000000040e3e5 main () + 1d5
 000000000040a3f3 _start_crt () + 83
 000000000040a358 _start () + 18

I am running gcc version 6.4.0 (OpenIndiana 6.4.0-OI-3) btw. 

But I guess thats for another PR.

**Comment by alarcher** [comment]
@Toasterson Nice to know.. I thought I screwed up somewhere... Thanks :)

**Comment by alarcher** [comment]
@Toasterson @Mno-hime Both build and publish on my system.

**Comment by Toasterson** [comment]
Yeah I can not get it to build. @Mno-hime If you can build it I will unblock it. As in that case it is something wrong with my System

**Comment by Mno-hime** [comment]
@Toasterson Yes, it publishes for me fine.

The core comes from illumos binary and I can see it for 1.10.4 build as well. Likely https://www.illumos.org/issues/9833. I don't think it should block this PR.

**Review by alarcher — APPROVED** [review]
Works for me.

**Review by Toasterson — APPROVED** [review]

**Comment by Toasterson** [comment]
Cool then I'll Unblock

**Pull request merged**
