### PR TITLE
lasso: Fix building with library/security/openssl-3

### PR DESCRIPTION
**Pull request by klausz65**
Please merge this one first, because Pull Request: #19931 (mod_auth_mellon) depends on this one.

### CODE REVIEW

**Comment by mtelka** [comment]
@klausz65 hint: to make sure that #19931 is merged after this one just mark it as a Draft.

**Comment by klausz65** [comment]
Thanks Marcel

**Comment by klausz65** [comment]
Of course the initial checks by jenkins are faling, because patch: 01-new-libs.patch depends on new openssl-3 and the new xmlsec-1.3.6.

**Comment by klausz65** [comment]
Without this PR there is already 1 test failing.

**Comment by AndWac** [comment]
This doesn't build here, too:
Undefined			first referenced
 symbol  			    in file
xmlSecCryptoAppKeyLoadEx            ../lasso/.libs/liblasso.so
ld: fatal: symbol referencing errors. No output written to .libs/perfs
collect2: error: ld returned 1 exit status

**Comment by klausz65** [comment]
Have you already installed the new xmlsec?

**Comment by AndWac** [comment]
No, your xmlsec PR is still a draft, but this is not.

**Comment by klausz65** [comment]
sorry maked for review now.

**Pull request merged**
