### PR TITLE
perl - added package Razor2

### PR DESCRIPTION
**Pull request by fritzkink**

### CODE REVIEW

**Comment by mtelka** [comment]
@fritzkink please close this PR and then do following:

1. create new git branch in your local git repo and switch to it (for example: `git checkout -b razor oi/hipster`)
2. set WS_TOOLS: `WS_TOOLS=$(git rev-parse --show-toplevel)/tools`
3. run `$WS_TOOLS/perl-integrate-module Razor2::Client::Agent` (wait, this could be very slow - several minutes)
4. review what was automatically created using `git show` - it should be okay (I checked it), you do not need to manually change anything.
5. push your new Razor2::Client::Agent integration to github: `git push -v ...`
6. create new PR.

Thanks.

PS: Yes, the new perl module integration is usually very easy: just one command needs to be run without any manual work!
PS2: Please note this is NOT true for `NetAddr::IP`.  The `NetAddr::IP` module needs some special handling.  I'm going to check `Encode-Detect` and `Clone` and I'll let you know.

**Comment by AndWac** [comment]
@mtelka: Can you create a PR with some kind of howto for perl packages in our doc folder, please?

**Comment by fritzkink** [comment]
It ist not that simple. 
`ipadm show-addr                              ipadm: Could not get address: Object not found`

`ipadm` does not work in a non-global zone with Shared-IP which is the case in my environment. So `gmake env-check` does not work for me and therefor the build fails. What now?

**Comment by mtelka** [comment]
> @mtelka: Can you create a PR with some kind of howto for perl packages in our doc folder, please?

It is in progress.  The current version is here: https://github.com/mtelka/oi-userland/blob/pim-doc/doc/perl-modules.md

**Comment by mtelka** [comment]
> It ist not that simple. `ipadm show-addr ipadm: Could not get address: Object not found`
> 
> `ipadm` does not work in a non-global zone with Shared-IP which is the case in my environment. So `gmake env-check` does not work for me and therefor the build fails. What now?

I do not know if the new package integration/build is supposed to work in non-global zone.  If it is not, then you should switch to GZ.  If it is, then `gmake env-check` (or `ipadm` ???) needs to be fixed.  As a quick workaround you could remove the `@/usr/sbin/ipadm show-addr` line from `make-rules/environment.mk`.

**Comment by mtelka** [comment]
> As a quick workaround you could remove the `@/usr/sbin/ipadm show-addr` line from `make-rules/environment.mk`.

... or change it to `-@/usr/sbin/ipadm show-addr`

**Comment by fritzkink** [comment]
To be honest I get too much problems and I don't have the time currently to debug all the what went wrong. Some examples:

$WS_TOOLS/perl-integrate-module Razor2::Client::Agent
WARNING: Failed to get abstract for module Razor2::Client::Agent from metacpan
ERROR: 'gmake sample-manifest' failed!
WARNING: test unsupported for 5.36
ERROR: 'gmake publish' failed!

second run

$WS_TOOLS/perl-integrate-module Razor2::Client::Agent
WARNING: Failed to get abstract for module Razor2::Client::Agent from metacpan
ERROR: 'gmake sample-manifest' failed!
WARNING: test unsupported for 5.34
ERROR: 'gmake publish' failed!

Note the different perl versions. If I run 'gmake sample-manifest' manually it just works.
To make use of the scripts they must be robust. It will for sure save some work but currently it creates a lot more trouble - but i can talk only for me. 
BTW a shared-IP zone is a perfect zone for doing such a work, my zones are working for more than a decade for all kind of work loads.

**Comment by mtelka** [comment]
> To make use of the scripts they must be robust.

I agree.   Please run `$WS_TOOLS/perl-integrate-module Razor2::Client::Agent` in clean workspace (e.g. in up-to-date `oi/hipster` git branch) and then `git format-patch HEAD^`.  It should create file named `0001-Add-Razor2-Client-Agent-perl-module.patch` (or similar) then please send the file to me by email.  I'll look at it and if there is some bug in the `perl-integrate-module` script I'll fix it.

Thanks.

**Comment by mtelka** [comment]
> Please run `$WS_TOOLS/perl-integrate-module Razor2::Client::Agent` in clean workspace (e.g. in up-to-date `oi/hipster` git branch) and then `git format-patch HEAD^`. It should create file named `0001-Add-Razor2-Client-Agent-perl-module.patch` (or similar) then please send the file to me by email.

... together with output of the `$WS_TOOLS/perl-integrate-module Razor2::Client::Agent` command itself.

**Comment by mtelka** [comment]
> I agree. Please run `$WS_TOOLS/perl-integrate-module Razor2::Client::Agent` in clean workspace (e.g. in up-to-date `oi/hipster` git branch) and then `git format-patch HEAD^`. It should create file named `0001-Add-Razor2-Client-Agent-perl-module.patch` (or similar) then please send the file to me by email. I'll look at it and if there is some bug in the `perl-integrate-module` script I'll fix it.

... or, instead of `git format-patch HEAD^`, etc. you could simply push the changeset to your github repo and I'll look at it there.

**Comment by mtelka** [comment]
> > It ist not that simple. `ipadm show-addr ipadm: Could not get address: Object not found`
> > `ipadm` does not work in a non-global zone with Shared-IP which is the case in my environment. So `gmake env-check` does not work for me and therefor the build fails. What now?
> 
> I do not know if the new package integration/build is supposed to work in non-global zone. If it is not, then you should switch to GZ. If it is, then `gmake env-check` (or `ipadm` ???) needs to be fixed. As a quick workaround you could remove the `@/usr/sbin/ipadm show-addr` line from `make-rules/environment.mk`.

Apparently, this is something that worked in past, but stopped recently: https://www.illumos.org/issues/14930.

**Comment by mtelka** [comment]
> Apparently, this is something that worked in past, but stopped recently: https://www.illumos.org/issues/14930.

A fix for this bug was integrated today to illumos-gate, so it should appear in OI tomorrow.

**Comment by alarcher** [comment]
@fritzkink Ping me when it is ready to merge.

**Comment by mtelka** [comment]
@alarcher, unfortunately, this is not ready yet.

**Comment by AndWac** [comment]
Superceded by #9199

**Pull request closed without merging**
