### PR TITLE
multimedia/yt-dlp: update to 2024.3.10

### PR DESCRIPTION
**Pull request by mtelka**

### CODE REVIEW

**Comment by 3eka** [comment]
Just updated:
```
:; yt-dlp --version
/usr/lib/python3.9/site-packages/requests/__init__.py:109: RequestsDependencyWarning: urllib3 (2.1.0) or chardet (5.2.0)/charset_normalizer (3.3.2) doesn't match a supported version!
  warnings.warn(
2024.03.10
```

Regards.

**Comment by mtelka** [comment]
`/usr/lib/python3.9/site-packages/requests` ?  Really?

**Comment by 3eka** [comment]
Well, no idea... Just have tried it

**Comment by mtelka** [comment]
> Well, no idea... Just have tried it

The `/usr/lib/python3.9/site-packages/requests/__init__.py` file is not provided by any OpenIndiana package, so you apparently installed it manually (likely using `pip`).  This is discouraged and unsupported.

Your `/usr/lib/python3.9/site-packages/` directory should be (almost) empty.  If you have more that these there:
```
$ ls /usr/lib/python3.9/site-packages/
README.txt
rrdtool-0.1.10-py3.9.egg-info
rrdtool.cpython-39.so
vendor-packages.pth
$
```
then you should expect anything, even worse things than the warning you saw.

**Comment by 3eka** [comment]
OK,
seems that I did installed (back in 2020/2021/2022) some packages via pip:
```
:; ls -hl /usr/lib/python3.9/site-packages/ | wc -l
55
```
So, what would be best way to clean that (self made) mess?

Thanks for pointers, sorry for noise...

**Comment by mtelka** [comment]
> So, what would be best way to clean that (self made) mess?

`pip uninstall`? `rm -rf`?

**Comment by 3eka** [comment]
Many thanks! 
*pfexec rm -rf ...* did a job

**Pull request merged**
