### PR TITLE
dbus-glib 0.110

### PR DESCRIPTION
**Pull request by Mno-hime**
Tested: `lshal`

### CODE REVIEW

**Comment by pyhalov** [comment]
Does illumos-gate builds fine with it?

**Comment by Mno-hime** [comment]
I think so, as I had it installed in the zone when rebuilding illumos-gate for the DBus 1.12 PR.

**Comment by pyhalov** [comment]
For test target to be successful dbus-daemon should be present in $PATH. Please, fix this.

**Comment by Mno-hime** [comment]
The test target works for me with the new DBus, the fix in DBus is here: https://github.com/OpenIndiana/oi-userland/pull/4297/files#diff-3996e4ed855c54e429a0ff7908195d21. If I remember correctly, `dbus-run-session` was unable to exec `dbus-daemon` as it can't find it in the `$PATH`. This is addressed by the patch above. In light of this you'd still rather see `dbus-daemon` in `/usr/bin/`?

**Comment by pyhalov** [comment]
No

**Pull request merged**
