### PR TITLE
Remove gtkhtml

### PR DESCRIPTION
**Pull request by AndWac**

### CODE REVIEW

**Comment by pyhalov** [comment]
Should we update it?

**Comment by AndWac** [comment]
Or better delete it. It used to be the HTML rendering engine for evolution. But we don't provide evolution anymore and I can't find any other dependant.

**Comment by pyhalov** [comment]
Is it   still developed? If no, drop it.

**Comment by AndWac** [comment]
The latest release seems to be 4.10.0 from September, 2015.
This version needs gail (libgail?) which we dropped.

**Review by pyhalov — APPROVED** [review]
Don't forget to mention this on http://wiki.openindiana.org/oi/oi_hipster

**Pull request merged**
