### PR TITLE
codeblocks: bugfix

### PR DESCRIPTION
**Pull request by dbh201**
Fixes a couple of upstream bugs involving setting the exec prefix and plugin dir at runtime.

### CODE REVIEW

**Comment by AndWac** [comment]
Does not build here:
In file included from /export/home/andreas/oi-userland/components/editor/codeblocks/codeblocks-20.03/src/include/scripting/bindings/sc_base_types.h:27:0,
                 from /export/home/andreas/oi-userland/components/editor/codeblocks/codeblocks-20.03/src/sdk/scripting/bindings/sc_wxtypes.cpp:18:
/export/home/andreas/oi-userland/components/editor/codeblocks/codeblocks-20.03/src/include/scripting/sqplus/sqplus.h:1759:16: note: candidate: template<class Func> SqPlus::SQClassDef<TClassType>& SqPlus::SQClassDef<TClassType>::func(Func, const SQChar*) [with Func = Func; TClassType = wxFileName]
   SQClassDef & func(Func pfunc,const SQChar * name_) {
                ^~~~
/export/home/andreas/oi-userland/components/editor/codeblocks/codeblocks-20.03/src/include/scripting/sqplus/sqplus.h:1759:16: note:   template argument deduction/substitution failed:
/export/home/andreas/oi-userland/components/editor/codeblocks/codeblocks-20.03/src/sdk/scripting/bindings/sc_wxtypes.cpp:357:57: note:   couldn't deduce template parameter 'Func'
                 func(&wxFileName::Normalize, "Normalize").
                                                         ^
/export/home/andreas/oi-userland/components/editor/codeblocks/codeblocks-20.03/src/sdk/scripting/bindings/sc_wxtypes.cpp:362:33: error: expected primary-expression before '>' token
                 func<WXFN_SETCWD>(&wxFileName::SetCwd, "SetCwd").
                                 ^
/export/home/andreas/oi-userland/components/editor/codeblocks/codeblocks-20.03/src/sdk/scripting/bindings/sc_wxtypes.cpp:362:35: error: left operand of comma operator cannot resolve address of overloaded function
                 func<WXFN_SETCWD>(&wxFileName::SetCwd, "SetCwd").
                                   ^~~~~~~~~~~
/export/home/andreas/oi-userland/components/editor/codeblocks/codeblocks-20.03/src/sdk/scripting/bindings/sc_wxtypes.cpp:363:17: error: request for member 'func' in '((void)0, "SetCwd")', which is of non-class type 'const char [7]'
                 func(&wxFileName::SetExt, "SetExt").
                 ^~~~
/export/home/andreas/oi-userland/components/editor/codeblocks/codeblocks-20.03/src/sdk/scripting/bindings/sc_wxtypes.cpp:368:42: error: expected primary-expression before '>' token
                 func<WXFN_ISFILEWRITEABLE>(&wxFileName::IsFileWritable,"IsFileWritable");
                                          ^
/export/home/andreas/oi-userland/components/editor/codeblocks/codeblocks-20.03/src/sdk/scripting/bindings/sc_wxtypes.cpp:368:44: error: left operand of comma operator cannot resolve address of overloaded function
                 func<WXFN_ISFILEWRITEABLE>(&wxFileName::IsFileWritable,"IsFileWritable");
                                            ^~~~~~~~~~~
make[5]: *** [Makefile:539: sc_wxtypes.lo] Error 1
make[5]: *** Waiting for unfinished jobs....
make[5]: Leaving directory '/export/home/andreas/oi-userland/components/editor/codeblocks/build/amd64/src/sdk/scripting/bindings'
make[4]: *** [Makefile:487: all-recursive] Error 1
make[4]: Leaving directory '/export/home/andreas/oi-userland/components/editor/codeblocks/build/amd64/src/sdk/scripting'
make[3]: *** [Makefile:1109: all-recursive] Error 1
make[3]: Leaving directory '/export/home/andreas/oi-userland/components/editor/codeblocks/build/amd64/src/sdk'
make[2]: *** [Makefile:545: all-recursive] Error 1
make[2]: Leaving directory '/export/home/andreas/oi-userland/components/editor/codeblocks/build/amd64/src'
make[1]: *** [Makefile:676: all-recursive] Error 1
make[1]: Leaving directory '/export/home/andreas/oi-userland/components/editor/codeblocks/build/amd64'
gmake: *** [/export/home/andreas/oi-userland/make-rules/configure.mk:174: /export/home/andreas/oi-userland/components/editor/codeblocks/build/amd64/.built] Error 2

**Comment by dbh201** [comment]
Not sure why it's compiling successfully here, but it looks like it could be a gcc-7 template issue.

**Comment by AndWac** [comment]
Different errors now:
/export/home/andreas/oi-userland/components/editor/codeblocks/codeblocks-20.03/src/sdk/scripting/bindings/sc_wxtypes.cpp:362:33: error: expected primary-expression before '>' token
  362 |                 func<WXFN_SETCWD>(&wxFileName::SetCwd, "SetCwd").
      |                                 ^
/export/home/andreas/oi-userland/components/editor/codeblocks/codeblocks-20.03/src/sdk/scripting/bindings/sc_wxtypes.cpp:362:35: error: left operand of comma operator cannot resolve address of overloaded function
  362 |                 func<WXFN_SETCWD>(&wxFileName::SetCwd, "SetCwd").
      |                                   ^~~~~~~~~~~~~~~~~~~
/export/home/andreas/oi-userland/components/editor/codeblocks/codeblocks-20.03/src/sdk/scripting/bindings/sc_wxtypes.cpp:363:17: error: request for member 'func' in '((void)0, "SetCwd")', which is of non-class type 'const char [7]'
  363 |                 func(&wxFileName::SetExt, "SetExt").
      |                 ^~~~
/export/home/andreas/oi-userland/components/editor/codeblocks/codeblocks-20.03/src/sdk/scripting/bindings/sc_wxtypes.cpp:368:42: error: expected primary-expression before '>' token
  368 |                 func<WXFN_ISFILEWRITEABLE>(&wxFileName::IsFileWritable,"IsFileWritable");
      |                                          ^
/export/home/andreas/oi-userland/components/editor/codeblocks/codeblocks-20.03/src/sdk/scripting/bindings/sc_wxtypes.cpp:368:44: error: left operand of comma operator cannot resolve address of overloaded function
  368 |                 func<WXFN_ISFILEWRITEABLE>(&wxFileName::IsFileWritable,"IsFileWritable");
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
make[5]: *** [Makefile:539: sc_wxtypes.lo] Error 1

**Comment by dbh201** [comment]
I'm not sure what's happening there, since it compiles successfully on gcc-7 and gcc-10, both here and on the jenkins server.

Can you show the full libtool command for sc_wxtypes.cpp? I.E. `libtool: compile: <tons of parameters> -o .libs/sc_wxtypes.o`

**Comment by AndWac** [comment]
pkg5 needs an update

**Comment by AndWac** [comment]
I have successfully published this from my 2nd build system.

**Pull request merged**
