### PR TITLE
Binutils: bump to 2.31.1

### PR DESCRIPTION
**Pull request by kenmays**

### CODE REVIEW

**Comment by pyhalov** [comment]
- test results differ and should be updated
- manifests should be updated
- needs sufficient testing (at least, building illumos-gate)

**Comment by alarcher** [comment]
@kenmays @pyhalov Fixed manifest and tests, will test further in the gcc-8 zone.

**Comment by alarcher** [comment]
@pyhalov Published to gcc-8 build zone and illumos-gate published.

**Comment by alarcher** [comment]
@pyhalov I have rebuilt a few components and illumos-gate from last night, which I am running now.

**Comment by kenmays** [comment]
@alarcher - All binutils 2.31.1 tests passed. No issues. illumos-gate-5267591

**Comment by alarcher** [comment]
@pyhalov Should we squash and merge this?

**Comment by pyhalov** [comment]
I'm fine with it.

**Pull request merged**
