### PR TITLE
10913 & 11075: remove 32-bit nvidia driver and vendor headers

### PR DESCRIPTION
**Pull request by Mno-hime**
**10913 ELF file /a/kernel/drv/nvidia is 32-bit and will be excluded**

No 32-bit kernel, no 32-bit driver.

**11075 OpenGL headers get removed after removing driver/graphics/nvidia for update**

Remove vendored headers from and ancient Solaris nvidia driver.

### CODE REVIEW

**Comment by alarcher** [comment]
Be careful to modify ogl-select to use mesa headers instead of the removed ones:
https://github.com/OpenIndiana/oi-userland/blob/1ed47a2077bfb7e671c15a56afc3d9451fba23d7/components/x11/ogl-select/files/nvidia_vendor_select

**Comment by Mno-hime** [comment]
Thanks for pointing that out @alarcher. Now I also fixed `ogl-select`.

Testing after `svccfg -s ogl-select setprop options/vendor = nvidia` and service restart:
```
$ ll -R /var/run/opengl/
/var/run/opengl/:
total 24
drwxr-xr-x   2 root     root         369 Jun 11 20:50 include/
drwxr-xr-x   3 root     root         373 Jun 11 20:50 lib/
drwxr-xr-x   3 root     root         245 Jun 11 20:50 server/

/var/run/opengl/include:
total 32
lrwxrwxrwx   1 root     root          33 Jun 11 20:50 gl.h -> ../../../../usr/include/mesa/gl.h
lrwxrwxrwx   1 root     root          36 Jun 11 20:50 glext.h -> ../../../../usr/include/mesa/glext.h
lrwxrwxrwx   1 root     root          34 Jun 11 20:50 glx.h -> ../../../../usr/include/mesa/glx.h
lrwxrwxrwx   1 root     root          37 Jun 11 20:50 glxext.h -> ../../../../usr/include/mesa/glxext.h

/var/run/opengl/lib:
total 32
lrwxrwxrwx   1 root     root           5 Jun 11 20:50 64 -> amd64/
drwxr-xr-x   2 root     root         252 Jun 11 20:50 amd64/
lrwxrwxrwx   1 root     root          31 Jun 11 20:50 libEGL.so.1 -> /usr/X11/lib/NVIDIA/libEGL.so.1*
lrwxrwxrwx   1 root     root          30 Jun 11 20:50 libGL.so.1 -> /usr/X11/lib/NVIDIA/libGL.so.1*

/var/run/opengl/lib/amd64:
total 16
lrwxrwxrwx   1 root     root          37 Jun 11 20:50 libEGL.so.1 -> /usr/X11/lib/NVIDIA/amd64/libEGL.so.1*
lrwxrwxrwx   1 root     root          36 Jun 11 20:50 libGL.so.1 -> /usr/X11/lib/NVIDIA/amd64/libGL.so.1*

/var/run/opengl/server:
total 16
drwxr-xr-x   2 root     root         183 Jun 11 20:50 amd64/
lrwxrwxrwx   1 root     root          48 Jun 11 20:50 libglx.so -> /usr/X11/lib/modules/extensions/NVIDIA/libglx.so*

/var/run/opengl/server/amd64:
total 8
lrwxrwxrwx   1 root     root          54 Jun 11 20:50 libglx.so -> /usr/X11/lib/modules/extensions/NVIDIA/amd64/libglx.so*
```

**Comment by alarcher** [comment]
@Mno-hime Are we ready for merging then?

**Comment by Mno-hime** [comment]
> @Mno-hime Are we ready for merging then?

I think so.

**Pull request merged**
