### PR TITLE
perl/HTTP-Message: update to 6.37; rebuild for perl 5.36 and to get p…

### PR DESCRIPTION
**Pull request by mtelka**
…ackages for perl 5.22 and 5.24 obsoleted

### CODE REVIEW

**Comment by AndWac** [comment]
At the moment our build server has obscure problems. Publishing
slim_source failed with different errors. /data is almost full:
NAME                                    USED  AVAIL  REFER MOUNTPOINT
data                                   91.0G  5.36G    31K  /data

The new package versions from slim_source made it into
userland-incorporation but it looks like they didn't make it into the repo.
This prevents from installing latest package releases...

Am 16.07.22 um 18:05 schrieb Marcel Telka:

**Comment by mtelka** [comment]
> At the moment our build server has obscure problems. Publishing slim_source failed with different errors. /data is almost full: NAME                                    USED  AVAIL  REFER MOUNTPOINT data                                   91.0G  5.36G    31K  /data The new package versions from slim_source made it into userland-incorporation but it looks like they didn't make it into the repo. This prevents from installing latest package releases...

Is this something I can help with?

**Comment by AndWac** [comment]
Am 16.07.22 um 18:23 schrieb Marcel Telka:
>
>     At the moment our build server has obscure problems. Publishing
>     slim_source failed with different errors. /data is almost full:
>     NAME USED AVAIL REFER MOUNTPOINT data 91.0G 5.36G 31K /data The
>     new package versions from slim_source made it into
>     userland-incorporation but it looks like they didn't make it into
>     the repo. This prevents from installing latest package releases...
>
> Is this something I can help with?
>
I am not sure why publishing openindiana/slim_source fails. The latest
PR we have merged shouldn't be the reason. Maybe it's because we are
running out of disk space. But we never really had much disk space on
the build VM.

**Comment by AndWac** [comment]
Am 16.07.22 um 18:23 schrieb Marcel Telka:
>
>     At the moment our build server has obscure problems. Publishing
>     slim_source failed with different errors. /data is almost full:
>     NAME USED AVAIL REFER MOUNTPOINT data 91.0G 5.36G 31K /data The
>     new package versions from slim_source made it into
>     userland-incorporation but it looks like they didn't make it into
>     the repo. This prevents from installing latest package releases...
>
> Is this something I can help with?
>
If I try to publish openindiana/slim_source on my local machine, it
fails after a few seconds with Error 1.
And I get a mail with several build errors inside. Something is broken.
Either by the latest illumos-gate changes, our oi-userland changes or
the slim_source changes. The latter looking harmless. Can you have a
look at it?

**Comment by mtelka** [comment]
I tried few builds and I believe the problem is caused by recent changes in the slim_source gate:

```
commit cd9236d74a32f6d089f2d4ba5b6e327ed0d6135d
Author:     Till Wegmueller <toasterson@gmail.com>
AuthorDate: Thu Jul 14 16:51:06 2022 -0300
Commit:     Till Wegmueller <toasterson@gmail.com>
CommitDate: Thu Jul 14 17:03:51 2022 -0300

    Adding varpd patch:
```

**Comment by mtelka** [comment]
... it was merged today:

```
commit 4bde8d8fd8eaa6ba36c153f18721ca04fe89b72b
Merge: 00ad03b cd9236d
Author:     Andreas Wacknitz <A.Wacknitz@gmx.de>
AuthorDate: Sat Jul 16 14:41:16 2022 +0200
Commit:     GitHub <noreply@github.com>
CommitDate: Sat Jul 16 14:41:16 2022 +0200

    Merge pull request #68 from Toasterson/oi/hipster
    
    Adding varpd patch
```

**Comment by AndWac** [comment]
Am 16.07.22 um 19:19 schrieb Marcel Telka:
>
> I tried few builds and I believe the problem is caused by recent
> changes in the slim_source gate:
>
> |commit cd9236d74a32f6d089f2d4ba5b6e327ed0d6135d Author: Till
> Wegmueller ***@***.***> AuthorDate: Thu Jul 14 16:51:06 2022
> -0300 Commit: Till Wegmueller ***@***.***> CommitDate: Thu
> Jul 14 17:03:51 2022 -0300 Adding varpd patch: |

|I have tried to build slim_source locally with and without the latest
patch.
Both tries failed with the same errors. The problem is located
elsewhere. Most probably in a broken Perl toolchain.|

**Pull request merged**
