### PR TITLE
abiword: Add package

### PR DESCRIPTION
**Pull request by ghost**
Add the word processor Abiword, a lightweight alternative to LibreOffice Writer.
Needs #7734 merged first.

### CODE REVIEW

**Comment by AndWac** [comment]
This does not publish here:
/home/andreas/oi-userland/components/desktop/abiword/build/manifest-i386-abiword.depend
/usr/bin/pkgdepend resolve -e /export/home/andreas/oi-userland/components/desktop/abiword/build/resolve.deps -m /export/home/andreas/oi-userland/components/desktop/abiword/build/manifest-i386-abiword.depend
/export/home/andreas/oi-userland/components/desktop/abiword/build/manifest-i386-abiword.depend has unresolved dependency '
    depend type=require fmri=__TBD pkg.debug.depend.file=libgoffice-0.10.so.10 \
        pkg.debug.depend.reason=usr/lib/amd64/libabiword-3.0.so \
        pkg.debug.depend.type=elf \
        pkg.debug.depend.path=lib/64 \
        pkg.debug.depend.path=usr/gcc/7/lib/amd64 \
        pkg.debug.depend.path=usr/lib/64'.
/export/home/andreas/oi-userland/components/desktop/abiword/build/manifest-i386-abiword.depend has unresolved dependency '
    depend type=require fmri=__TBD pkg.debug.depend.file=libical.so.1 \
        pkg.debug.depend.reason=usr/lib/amd64/libabiword-3.0.so \
        pkg.debug.depend.type=elf \
        pkg.debug.depend.path=lib/64 \
        pkg.debug.depend.path=usr/gcc/7/lib/amd64 \
        pkg.debug.depend.path=usr/lib/64'.
gmake: *** [/export/home/andreas/oi-userland/make-rules/ips.mk:502: /export/home/andreas/oi-userland/components/desktop/abiword/build/.resolved-i386] Error 1

Reason: on my machine (and on the officical build server) library/desktop/goffice is installed (because it's a dependency of gnumeric). You'll need to install this package and rebuild abiword with it. gmake sample-manifest might create a different sample-manifest and gmake REQUIRED_PACKAGES will add library/desktop/goffice.

**Comment by ghost** [comment]
I added goffice as dependency.
Recompiled it locally and it still works fine here.

**Comment by AndWac** [comment]
Another problem is missing library/libical dependency:
/export/home/andreas/oi-userland/components/desktop/abiword/build/manifest-i386-abiword.depend has unresolved dependency '
    depend type=require fmri=__TBD pkg.debug.depend.file=libical.so.1 \
        pkg.debug.depend.reason=usr/lib/amd64/libabiword-3.0.so \
        pkg.debug.depend.type=elf \
        pkg.debug.depend.path=lib/64 \
        pkg.debug.depend.path=usr/gcc/7/lib/amd64 \
        pkg.debug.depend.path=usr/lib/64'.
gmake: *** [/export/home/andreas/oi-userland/make-rules/ips.mk:502: /export/home/andreas/oi-userland/components/desktop/abiword/build/.resolved-i386] Error 1

**Comment by ghost** [comment]
Fixed that,too.

**Comment by AndWac** [comment]
And the next missing build dependency is library/spell-checking/enchant:
/home/andreas/oi-userland/components/desktop/abiword/build/manifest-i386-abiword.depend
/usr/bin/pkgdepend resolve -e /export/home/andreas/oi-userland/components/desktop/abiword/build/resolve.deps -m /export/home/andreas/oi-userland/components/desktop/abiword/build/manifest-i386-abiword.depend
/export/home/andreas/oi-userland/components/desktop/abiword/build/manifest-i386-abiword.depend has unresolved dependency '
    depend type=require fmri=__TBD pkg.debug.depend.file=libenchant.so.1 \
        pkg.debug.depend.reason=usr/lib/amd64/libabiword-3.0.so \
        pkg.debug.depend.type=elf \
        pkg.debug.depend.path=lib/64 \
        pkg.debug.depend.path=usr/gcc/7/lib/amd64 \
        pkg.debug.depend.path=usr/lib/64'.
gmake: *** [/export/home/andreas/oi-userland/make-rules/ips.mk:502: /export/home/andreas/oi-userland/components/desktop/abiword/build/.resolved-i386] Error 1

**Comment by ghost** [comment]
Enchant is installed,but I updated it to version 2 because another package I'm trying to package needs the updated version.
I'll try to build Abiword again with Enchant 2,but then I need to submit the updated Enchant package first,before Abiword can be built on the build server.

**Comment by ghost** [comment]
I pushed a new fix but this will **NOT** work yet as it contains patches for Abiword to work with the latest Enchant version that is not yet in the repository but only locally on my computer.I'll push it when a important question in the IRC is answered,and then Abiword should finally work (at least I hope so)

**Comment by AndWac** [comment]
When you upgrade a package you'll need to make sure that all packages dependent on it still work.
pkg search -r -H -o pkg.name "depend:require:library/spell-checking/enchant
will tell you which packages might be affected. Probably they need to be rebuild with the new enchant version.

**Comment by AndWac** [comment]
Sorry, I hit the wrong button :/

**Comment by ghost** [comment]
I submitted a pull request for the new enchant just now.
After it's merged and built,the Abiword package should finally build successfully.

**Pull request merged**
