### PR TITLE
Compiz 1

### PR DESCRIPTION
**Pull request by pyhalov**

### CODE REVIEW

**Comment by pyhalov** [comment]
PRs #5513, #5514. #5515, #5517 depend on each other and should be merged in this exact order. 
I've tested that basic compiz functions work on desktop with NVidia. 
I encourage you to build and test it.

**Comment by alarcher** [comment]
@pyhalov Thank you, I'll have a look this week-end.

**Comment by Mno-hime** [comment]
>  I encourage you to build and test it.

Doing it now.

**Comment by Mno-hime** [comment]
`libcompizconfig` fails to build with:
```
checking for COMPIZ... no
configure: error: Package requirements ("compiz") were not met:
No package 'compiz' found
```
Perhaps it should be moved to a later ring and `REQUIRED_PACKAGES += desktop/compiz` added.

**Comment by Mno-hime** [comment]
Other than that looks good.

Will keep it running on my Intel GPU, good so far.

**Comment by alarcher** [comment]
@pyhalov All three PRs build with gcc 7.5 :)

**Pull request merged**
