### PR TITLE
pacemaker: fix gcc-10 build

### PR DESCRIPTION
**Pull request by alarcher**

### CODE REVIEW

**Review by AndWac — APPROVED** [review]
How can we proceed with #5246?

**Comment by alarcher** [comment]
> How can we proceed with #5246?

I do not know how pacemaker works so I would follow your decision. If you prefer I can build pacemaker 2.0 in the gcc-10 zone and patch if needed. We could then close this PR.
As you like.

**Comment by AndWac** [comment]
I don't use it yet but I'd like to do so in the future (another item on my todo list). Maybe grueni will answer here...

**Comment by alarcher** [comment]
> I don't use it yet but I'd like to do so in the future (another item on my todo list). Maybe grueni will answer here...

I guess we'll merge this one for now, just to make my build one is happy ;)

**Comment by grueni** [comment]
Sorry for to be unresponsive for such a long time.
The new version of pacemaker 2.0.2 and 2.0.3 work without problems.

**Pull request merged**
