### PR TITLE
10172 Add zstd 1.3.8, support zstd compressed archives in oi-userland

### PR DESCRIPTION
**Pull request by Mno-hime**
Tested standalone and via `gtar`.

### CODE REVIEW

**Comment by pyhalov** [comment]
Please, fix commit message for first commit -  '10172 Add zstd 1.3.8'

**Comment by Mno-hime** [comment]
What you mean by "fixing it"? Removing the text, keeping just the "header" line?

**Comment by pyhalov** [comment]
Yes

**Comment by Mno-hime** [comment]
OK, done.

**Pull request merged**
