### PR TITLE
Additional X11 proto from x-S12

### PR DESCRIPTION
**Pull request by alarcher**
No license file provided in dri3proto tarball.

### CODE REVIEW

**Comment by pyhalov** [comment]
Is dri3proto.license empty?

**Comment by pyhalov** [comment]
Should components/meta-packages/x11-protocols/x11-protocols.p5m be updated?

**Comment by alarcher** [comment]
No license is provided in the tarball and I have not been able to find the exact file on the web.
You are right, I missed the meta-package.

**Comment by pyhalov** [comment]
I see (expected) MIT license in dri3proto-1.0/dri3proto.h

**Comment by alarcher** [comment]
License fixed and additional commit to add them to x11-protocols.

**Pull request merged**
