### PR TITLE
appstream: update to 1.0.4

### PR DESCRIPTION
**Pull request by AndWac**

### CODE REVIEW

**Comment by mtelka** [comment]
@AndWac are all tests passing for you?

**Comment by AndWac** [comment]
No:
-as-test_pool             OK
+as-test_pool             FAIL   killed by signal 6 SIGABRT
But that also happens with the previous version.

**Comment by mtelka** [comment]
Yes.  Same here.  Something apparently changed since the 1.0.3 integration and so the testing fails now.  It should be investigated (or at least test results should be updated).

**Comment by AndWac** [comment]
The test fails because it's missing the samples folder. Alas CLONEY doesn't work because meson complains about two meson.build files.

**Comment by AndWac** [comment]
With the samples folder in place all tests are ok.

**Comment by AndWac** [comment]
Or not, the trick was working for 1.0.3 but failed now.

**Comment by AndWac** [comment]
Running the test manually within the tests folder finishes ok, though.

**Pull request merged**
