### PR TITLE
9953 Update gcr to 3.28.0

### PR DESCRIPTION
**Pull request by Mno-hime**

### CODE REVIEW

**Comment by Mno-hime** [comment]
gcr works fine, I am asked for the key password and then I am correctly connected via SSH to the host, but the `agent key RSA SHA256:XXX returned incorrect signature type` did not disappeared.

**Comment by pyhalov** [comment]
gnome-keyring also needs updating

**Comment by 3eka** [comment]
While there, can you check (3.18.0 version):
```
:; gcr-viewer /path/to/cert/file.crt
[exit]
p11-kit: couldn't open config file: /etc/pkcs11/pkcs11.conf: Error 0
```
missing dir/file - or - wrong location, please?

Thanks

**Comment by Mno-hime** [comment]
With v3.28.0:
```
{global} newman@lenovo:~ $ gcr-viewer /etc/certs/ca-certificates.crt 
p11-kit: couldn't open config file: /etc/pkcs11/pkcs11.conf: Error 0

** (gcr-viewer:3370): WARNING **: 08:51:32.160: invalid two's complement integer
```
Otherwise it appears to work fine.

Looking at openSUSE Leap 42.3, `/etc/pkcs11/` dir come from p11-kit package, but `/etc/pkcs11/pkcs11.conf` is not there as well. Look at our `library/desktop/p11-kit` might reveal what's happening there.

**Comment by 3eka** [comment]
On my /hipster:
```
:; locate /pkcs11.conf 
/etc/crypto/pkcs11.conf

:; pkg search -l /etc/crypto/pkcs11.conf
INDEX      ACTION VALUE                  PACKAGE
path       file   etc/crypto/pkcs11.conf pkg:/SUNWcs@0.5.11-2018.0.0.17736

:; ls -al /etc/crypto/pkcs11.conf
-rw-r--r-- 1 root sys 1,9K Oct  3  2015 /etc/crypto/pkcs11.conf
```
Regards

**Comment by pyhalov** [comment]
This is an another configuration file. Perhaps, we should ship /etc/pkcs11/pkcs11.conf.example as /etc/pkcs11/pkcs11.conf or like pkcs11.conf.example. Not sure.

**Comment by Mno-hime** [comment]
https://github.com/OpenIndiana/oi-userland/pull/4672 fixes [9953](https://www.illumos.org/issues/9953), this PR is a build requirement.

**Comment by Mno-hime** [comment]
@3eka https://github.com/OpenIndiana/oi-userland/pull/4674 fixes the `gcr-viewer` "error".

**Pull request merged**
