### PR TITLE
gcc can assert with -msave-args

### PR DESCRIPTION
**Pull request by citrus-it**
During the gcc11 libstdc++ -m64/-msave-args testsuite phase, the compiler aborts and the tests are not run
(see the test output at https://github.com/OpenIndiana/oi-userland/blob/oi/hipster/components/developer/gcc-11/test/results-i386.master )

```
In file included from _build/gcc-11.3.0/gcc-11.3.0-build/x86_64-pc-solaris2.11/libstdc++-v3/include/vector:67,
                 from _build/gcc-11.3.0/gcc-11.3.0/libstdc++-v3/testsuite/util/testsuite_abi.h:23,
                 from _build/gcc-11.3.0/gcc-11.3.0/libstdc++-v3/testsuite/util/testsuite_abi.cc:22:
_build/gcc-11.3.0/gcc-11.3.0-build/x86_64-pc-solaris2.11/libstdc++-v3/include/bits/stl_vector.h: In destructor 'std::vector<_Tp, _Alloc>::~vector() [with _Tp = std::__cxx11::basic_string<char>; _Alloc = std::allocator<std::__cxx11::basic_string<char> >]':
_build/gcc-11.3.0/gcc-11.3.0-build/x86_64-pc-solaris2.11/libstdc++-v3/include/bits/stl_vector.h:683: internal compiler error: in add_dwarf_attr, at dwarf2out.c:4437
```

### CODE REVIEW

**Comment by citrus-it** [comment]
The raw test results are not sorted so here's the difference between the test summaries.
Although I find that I don't get 100% consistent results between test runs anyway, it's clear that the situation with `-msave-args` has improved here, particularly for libstdc++.

I wonder if it would be worth including/generating this summary output in the `test` directory to make it easier to see when a gcc update regresses?

```
build:oi-userland:gcc11% egrep ' Summary (for .*)?===$|^#' test/results-i386.master >| new
build:oi-userland:gcc11% git show hipster:./test/results-i386.master | egrep ' Summary (for .*)?===$|^#' >| old
build:oi-userland:gcc11% gdiff -u old new
```

```diff
@@ -6,53 +6,50 @@
 # of unresolved testcases      726
 # of unsupported tests         9327
                === g++ Summary for unix/-m64/-msave-args ===
-# of expected passes           197357
-# of unexpected failures       6579
+# of expected passes           197366
+# of unexpected failures       6561
 # of unexpected successes      6
 # of expected failures         1070
 # of unresolved testcases      726
 # of unsupported tests         9327
                === g++ Summary ===
-# of expected passes           394730
-# of unexpected failures       13133
+# of expected passes           394739
+# of unexpected failures       13115
 # of unexpected successes      12
 # of expected failures         2140
 # of unresolved testcases      1452
 # of unsupported tests         18654
                === gcc Summary for unix/-m64 ===
-# of expected passes           159809
+# of expected passes           159802
 # of unexpected failures       186
 # of unexpected successes      36
 # of expected failures         928
 # of unresolved testcases      1
-# of unsupported tests         2879
+# of unsupported tests         2880
                === gcc Summary for unix/-m64/-msave-args ===
-# of expected passes           159686
-# of unexpected failures       287
+# of expected passes           159678
+# of unexpected failures       288
 # of unexpected successes      37
 # of expected failures         927
 # of unresolved testcases      1
-# of unsupported tests         2898
+# of unsupported tests         2899
                === gcc Summary ===
-# of expected passes           319495
-# of unexpected failures       473
+# of expected passes           319480
+# of unexpected failures       474
 # of unexpected successes      73
 # of expected failures         1855
 # of unresolved testcases      2
-# of unsupported tests         5777
+# of unsupported tests         5779
                === gfortran Summary for unix/-m64 ===
-# of expected passes           56598
-# of unexpected failures       24
+# of expected passes           56622
 # of expected failures         222
 # of unsupported tests         93
                === gfortran Summary for unix/-m64/-msave-args ===
-# of expected passes           56598
-# of unexpected failures       24
+# of expected passes           56622
 # of expected failures         222
 # of unsupported tests         93
                === gfortran Summary ===
-# of expected passes           113196
-# of unexpected failures       48
+# of expected passes           113244
 # of expected failures         444
 # of unsupported tests         186
                === objc Summary for unix/-m64 ===
@@ -70,40 +67,33 @@
                === libatomic Summary for unix/-m64 ===
 # of expected passes           54
                === libatomic Summary for unix/-m64/-msave-args ===
-# of expected passes           12
-# of unexpected failures       42
-# of unresolved testcases      21
+# of expected passes           54
                === libatomic Summary ===
-# of expected passes           66
-# of unexpected failures       42
-# of unresolved testcases      21
+# of expected passes           108
                === libgomp Summary for unix/-m64 ===
 # of expected passes           8439
 # of expected failures         4
 # of unsupported tests         536
                === libgomp Summary for unix/-m64/-msave-args ===
-# of expected passes           7527
-# of unexpected failures       903
+# of expected passes           8438
+# of unexpected failures       1
 # of expected failures         4
-# of unresolved testcases      449
 # of unsupported tests         536
                === libgomp Summary ===
-# of expected passes           15966
-# of unexpected failures       903
+# of expected passes           16877
+# of unexpected failures       1
 # of expected failures         8
-# of unresolved testcases      449
 # of unsupported tests         1072
                === libstdc++ Summary for unix/-m64 ===
-# of expected passes           14674
-# of unexpected failures       26
-# of expected failures         105
+# of expected passes           3474
+# of unexpected failures       9
+# of expected failures         5
 # of unresolved testcases      1
-# of unsupported tests         724
+# of unsupported tests         101
                === libstdc++ Summary for unix/-m64/-msave-args ===
-# of unresolved testcases      4
                === libstdc++ Summary ===
-# of expected passes           14674
-# of unexpected failures       26
-# of expected failures         105
-# of unresolved testcases      5
-# of unsupported tests         724
+# of expected passes           3474
+# of unexpected failures       9
+# of expected failures         5
+# of unresolved testcases      1
+# of unsupported tests         101
```

**Comment by citrus-it** [comment]
For some reason, the test output was missing the libstdc++ -m64/-msave-args output, I ran that again by hand:

```
af@hipster:~/oi-userland/components/developer/gcc-11/build/amd64$ gmake -j8 -k check-target-libstdc++-v3 RUNTESTFLAGS=--target_board=unix//-m64/-msave-args

Schedule of variations:
    unix//-m64/-msave-args

Running target unix//-m64/-msave-args
                === libstdc++ Summary ===

# of expected passes            14684
# of unexpected failures        16
# of expected failures          105
# of unresolved testcases       1
# of unsupported tests          724
```

**Comment by richlowe** [comment]
This looks right to me.  Should this be PR'd to illumos/gcc too?  It seems like it was wrong even before GCC checked for it?
(I don't think the GCC 11 PR made it to illumos/gcc yet?  There's some outstanding PRs from you I'm not sure about the state of too?)

**Comment by citrus-it** [comment]
> This looks right to me. Should this be PR'd to illumos/gcc too? It seems like it was wrong even before GCC checked for it?

Since it doesn't seem to matter in gcc10 if you assert the same attribute several times, I wasn't intending to.

> (I don't think the GCC 11 PR made it to illumos/gcc yet?

No, not yet, it is probably time now that things have settled a bit, although gate has not yet moved to a gcc10 primary so there is no urgency. OmniOS bloody/r151042 is using a gcc10 primary, with just a couple of extra patches which haven't made it to gate yet.

> There's some outstanding PRs from you I'm not sure about the state of too?)

I should probably just close the ones against gcc9 since we aren't going to use that for gate.
The other two were important for any system that switched to a 64-bit native binutils tool set, and who were building userland with the illumos gcc7 and wanted to use the native stack protector instead of the supplied libssp. I'm not sure that anyone is still building userland with gcc7 but we have long since moved on in omnios and I don't have the time to do the regression testing there at the moment.

**Comment by AndWac** [comment]
Am 01.05.22 um 12:16 schrieb Andy Fiddaman:
>
>     This looks right to me. Should this be PR'd to illumos/gcc too? It
>     seems like it was wrong even before GCC checked for it?
>
> Since it doesn't seem to matter in gcc10 if you assert the same
> attribute several times, I wasn't intending to.
>
>     (I don't think the GCC 11 PR made it to illumos/gcc yet?
>
> No, not yet, it is probably time now that things have settled a bit,
> although gate has not yet moved to a gcc10 primary so there is no
> urgency. OmniOS bloody/r151042 is using a gcc10 primary, with just a
> couple of extra patches which haven't made it to gate yet.
>
>     There's some outstanding PRs from you I'm not sure about the state
>     of too?)
>
> I should probably just close the ones against gcc9 since we aren't
> going to use that for gate.
> The other two were important for any system that switched to a 64-bit
> native binutils tool set, and who were building userland with the
> illumos gcc7 and wanted to use the native stack protector instead of
> the supplied libssp. I'm not sure that anyone is still building
> userland with gcc7 but we have long since moved on in omnios and I
> don't have the time to do the
>
OI userland is still being build with gcc-7 because Aurélien is busy
with his university career and other things.

**Pull request merged**
