### PR TITLE
Add Awesome window manager

### PR DESCRIPTION
**Pull request by dsendkowski**

### CODE REVIEW

**Comment by pyhalov** [comment]
Got the following error: 
```
make[3]: Leaving directory '/export/home/alp/srcs/tests/oi-userland/components/desktop/awesome/build/amd64'
[100%] Built target man
ld: warning: file /usr/lib/64/libm.so: linked to /usr/lib/amd64/libm.so: attempted multiple inclusion of file
ld: warning: file /usr/lib/64/liblua5.3.so: attempted multiple inclusion of file
ld: warning: file /usr/lib/64/libm.so: linked to /usr/lib/amd64/libm.so: attempted multiple inclusion of file
Undefined                       first referenced
 symbol                             in file
lua_insert                          CMakeFiles/awesome.dir/dbus.c.o
lua_remove                          CMakeFiles/awesome.dir/dbus.c.o
```
This is on
```
[ 65%] Linking C executable awesome
```

**Comment by dsendkowski** [comment]
I guess this happens because you have `runtime/lua-53` installed. There are neither `lua_insert` nor `lua_remove` methods in `liblua5.3.so` library.
There is `runtime/lua` in the `REQUIRED_PACKAGES`, which ships `liblua.so` with these missing methods.

**Comment by pyhalov** [comment]
Build server has both installed, as well as my build zone. Perhaps, component needs patching to choose correct lua version or to work with lua 5.3?

**Comment by dsendkowski** [comment]
Ok, I installed `runtime/lua-53` and can reproduce this error.
CMake finds `lua-53` but then claims it is 5.2.4:
```
-- Found Lua: /usr/lib/64/liblua5.3.so;/usr/lib/64/libm.so (found version "5.2.4") 
```
Adding this option to Makefile fixes the issue:
```
CMAKE_OPTIONS +="-DLUA_LIBRARY=/usr/lib/64/liblua.so"
```

but I'm not sure if this is an acceptable solution?

**Comment by dsendkowski** [comment]
I'm afraid I hit this CMake bug https://gitlab.kitware.com/cmake/cmake/issues/16404.

**Comment by pyhalov** [comment]
Can you use workarounds, suggested in bug report?

**Comment by dsendkowski** [comment]
Ok, now it builds with `runtime/lua-53`.

**Pull request merged**
