### PR TITLE
Bump ffmpeg to 2.8.10

### PR DESCRIPTION
**Pull request by alarcher**
- ABI compatible
- enabled test suite, at least one test failing
- added REQUIRED_PACKAGES

### CODE REVIEW

**Comment by pyhalov** [comment]
It seems that somehow tests use installed ffmpeg, not the one we've just built. If I install new ffmpeg in build zone, all tests succeed.

**Comment by alarcher** [comment]
I totally missed that... that's even better then, thanks :)

**Comment by alarcher** [comment]
@pyhalov Feel free to merge if you are happy with your testing.

**Comment by pyhalov** [comment]
Don't you wish to fix 'gmake check'  to avoid using system ffmpeg ? :)

**Comment by pyhalov** [comment]
@alarcher : are you going to fix this issue with tests using installed ffmpeg?

**Comment by alarcher** [comment]
@pyhalov yes but my internet connection was too bad so I could not work on the build machine.

**Comment by pyhalov** [comment]
Modified version merged in https://github.com/OpenIndiana/oi-userland/pull/2733

**Pull request closed without merging**
