### PR TITLE
Use OI ntp vendor zone in ntp.client and add some security tweaks

### PR DESCRIPTION
**Pull request by xen0l**

### CODE REVIEW

**Comment by pyhalov** [comment]
What about delivering default ntp.conf and enabling ntp service by defautl?

**Comment by pyhalov** [comment]
Enabling it by default perhaps is not good, as it's installed by default

**Comment by AndWac** [comment]
Am 29.06.16 um 09:36 schrieb Alexander Pyhalov:

> What about delivering default ntp.conf and enabling ntp service by 
> defautl?
> 
> I like the idea.

**Comment by pyhalov** [comment]
Seems to be ready

**Pull request merged**
