### PR TITLE
dovecot - The Secure IMAP server latest version 2.3.18

### PR DESCRIPTION
**Pull request by fritzkink**

### CODE REVIEW

**Comment by AndWac** [comment]
There are some dependencies missing.

**Comment by fritzkink** [comment]
needs some more work

**Comment by hoewweken** [comment]
Hello Fritz!
Do you have a clue why the group dovecot is "invalid" ?

Installing new actions                        1/2941Action install failed for 'dovecot' (pkg://openindiana.org/mail/dovecot):
  ActionExecutionError: Requested operation failed for package pkg://openindiana.org/mail/dovecot@2.3.18,5.11-2022.0.0.0:20220205T202616Z:
**dovecot is an unknown or invalid group**

The Boot Environment zbe failed to be updated. A snapshot was taken before the failed attempt and is mounted here /tmp/tmpajp_iavh. Use 'beadm unmount zbe-1' and then 'beadm activate zbe-1' if you wish to boot to this BE.

pkg: Requested operation failed for package pkg://openindiana.org/mail/dovecot@2.3.18,5.11-2022.0.0.0:20220205T202616Z:
dovecot is an unknown or invalid group
root@mail2:~# groupadd dovecot
UX: groupadd: ERROR: dovecot is already in use.  Choose another.

**Comment by hoewweken** [comment]
The group numbers seem to be relevant, this works:
<pre>
root@mail2:~# groupdel dovecot
root@mail2:~# groupdel dovenull
root@mail2:~# groupadd -g 100 dovecot
root@mail2:~# groupadd -g 101 dovenull
root@mail2:~# groupadd -g 5000 vmail  
root@mail2:~# pkg install dovecot
</pre>

**Comment by fritzkink** [comment]
Hmm, I did not have this problem. Just worked in a zone.

Am 09.02.2022 um 20:09 schrieb hoewweken:

**Pull request merged**
