### PR TITLE
automake: add version 1.16.1

### PR DESCRIPTION
**Pull request by alarcher**
@pyhalov This new version generates scripts that assume GNU make... Components using PATH.illumos break.

### CODE REVIEW

**Comment by Mno-hime** [comment]
@alarcher Can you give an example of component, which fails to build?

I just locally pre-published liboil, which does not have `PATH.gnu` and executes `automake` in `COMPONENT_PREP_ACTION` while having automake mediator set to 1.16.

I looked into FreeBSD ports and pkgsrc and haven't found any patch to address this issue (assuming they are in similar situation as we are) in their automake 1.16.1.

**Comment by Mno-hime** [comment]
OK, I see it with `gobject-introspection` v1.60.0.

**Comment by Mno-hime** [comment]
@alarcher Upstream [did not agreed on a solution](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=35848) to this. Best take seems to be to [take the patch](https://github.com/oracle/solaris-userland/blob/master/components/automake/automake-1.16/patches/01_better-error-msg.patch) and fix broken components on case by case basis (either by forcing `gmake` or disabling dependency tracking per the improved help text).

**Comment by alarcher** [comment]
@Mno-hime Can we not just force GNU make in the offending section?

**Comment by Mno-hime** [comment]
@alarcher in case of `gobject-introspection` both `CONFIGURE_ENV += MAKE=gmake` and `CONFIGURE_OPTIONS += --disable-dependency-tracking` work. We use both in one or two dozens of instances in oi-userland already.

Unless any of them is present:
```
config.status:1445: executing depfiles commands
config.status:1522: cd .       && sed -e '/# am--include-marker/d' Makefile         | make -f - am--depfiles
mksh: Fatal error in reader: = missing from replacement macro reference
Current working directory /export/home/newman/ws/oi-userland/components/library/gobject-introspection/build/i86
config.status:1527: $? = 1
config.status:1522: cd tests       && sed -e '/# am--include-marker/d' Makefile         | make -f - am--depfiles
config.status:1527: $? = 0
config.status:1522: cd tests/offsets       && sed -e '/# am--include-marker/d' Makefile         | make -f - am--depfiles
mksh: Fatal error in reader: = missing from replacement macro reference
Current working directory /export/home/newman/ws/oi-userland/components/library/gobject-introspection/build/i86/tests/offsets
config.status:1527: $? = 1
config.status:1522: cd tests/scanner       && sed -e '/# am--include-marker/d' Makefile         | make -f - am--depfiles
make: Fatal error in reader: standard input, line 337: Badly formed macro assignment
Current working directory /export/home/newman/ws/oi-userland/components/library/gobject-introspection/build/i86/tests/scanner
config.status:1527: $? = 1
config.status:1522: cd tests/repository       && sed -e '/# am--include-marker/d' Makefile         | make -f - am--depfiles
config.status:1527: $? = 0
config.status:1531: error: in `/export/home/newman/ws/oi-userland/components/library/gobject-introspection/build/i86':
config.status:1533: error: Something went wrong during bootstrapping of makefile
    fragments for automatic dependency tracking. If the GNU make is not
    used by default, consider to rerun the configure script with MAKE="gmake".
    You can also try to rerun configure with the '--disable-dependency-tracking'
    option to at least be able to build the package (albeit without support
    for automatic dependency tracking).
See `config.log' for more details
```
I guess enhancing illumos make is another possibility.

**Comment by alarcher** [comment]
@Mno-him I meant hardcoding /usr/bin/gmake instead of $MAKE where -f --am-depfiles is used because users compiling their own source are likely to encounter the issue. Fixing in our oi-userland does not help other use cases.

**Comment by Mno-hime** [comment]
@alarcher Oh, you mean here in the automake-116 component? Like this?
```patch
--- automake-1.16.1/m4/depout.m4	2018-02-26 21:38:27.000000000 +0000
+++ automake-1.16.1/m4/depout.m4.new	2019-08-25 14:59:06.741043451 +0000
@@ -62,4 +62,4 @@ AC_DEFUN([_AM_OUTPUT_DEPENDENCY_COMMANDS
 AC_DEFUN([AM_OUTPUT_DEPENDENCY_COMMANDS],
 [AC_CONFIG_COMMANDS([depfiles],
      [test x"$AMDEP_TRUE" != x"" || _AM_OUTPUT_DEPENDENCY_COMMANDS],
-     [AMDEP_TRUE="$AMDEP_TRUE" MAKE="${MAKE-make}"])])
+     [AMDEP_TRUE="$AMDEP_TRUE" MAKE="${MAKE-gmake}"])])
```
Or `/usr/bin/gmake`. So we could still mangle `MAKE` in component Makefile. It works for the gobject-introspection component.

**Comment by alarcher** [comment]
@Mno-hime Should we merge this PR?

**Review by Mno-hime — APPROVED** [review]

**Comment by Mno-hime** [comment]
@alarcher I believe so.

**Pull request merged**
