### PR TITLE
Rhythmbox

### PR DESCRIPTION
**Pull request by pyhalov**

### CODE REVIEW

**Comment by 3eka** [comment]
Hi,
this is not working on my /hipster
```
$ uname -rosv
SunOS 5.11 illumos-a5f6629 Solaris
```
Error is 
```
$ rhythmbox
... # million gtk-*.css errors here

Couldn't start playback
Failed to create audio output element; check your installation
```
Also, cannot change any option (check boxes are clickable).
Am I doing something wrong?

Thanks

**Comment by pyhalov** [comment]
do you have fully up-to-date system with latest nimbus theme installed?

**Comment by 3eka** [comment]
Yes
```
$ pkg info nimbus
             Name: gnome/theme/nimbus
          Summary: Engine for Sun Nimbus GTK2 Theme
         Category: Desktop (GNOME)/Theming
            State: Installed
        Publisher: openindiana.org
          Version: 0.1.9
           Branch: 2017.0.0.10
   Packaging Date: March 27, 2017 09:53:45 AM
Last Install Time: March 28, 2017 07:11:21 AM
             Size: 4.12 MB
             FMRI: pkg://openindiana.org/gnome/theme/nimbus@0.1.9-2017.0.0.10:20170327T095345Z
      Project URL: https://java.net/projects/solaris-desktop/pages/Home
       Source URL: https://github.com/aszeszo/archives/raw/master/nimbus-0.1.9.tar.bz2
```
BTW, I have switched to MATE

**Comment by pyhalov** [comment]
do you have all gstreamer1 plugins installed?

**Comment by 3eka** [comment]
Have these:
```
$ pkg list | grep gstreamer1
library/audio/gstreamer1                          1.10.3-2017.0.0.0          i--
library/audio/gstreamer1/plugin/base              1.10.3-2017.0.0.0          i--
```
and it looks like it is all?
```
$ pkg search -r gstreamer1
INDEX                ACTION VALUE                                    PACKAGE
com.oracle.info.name set    gstreamer1                               pkg:/library/audio/gstreamer1@1.10.3-2017.0.0.0
pkg.fmri             set    openindiana.org/library/audio/gstreamer1 pkg:/library/audio/gstreamer1@1.10.3-2017.0.0.0
```
Regards.

**Comment by pyhalov** [comment]
pkg install '\*gstreamer1/plugin\*'

**Comment by 3eka** [comment]
Nice, 
but not working:
```
$ pfexec pkg refresh --full
$ pfexec pkg install -vn 'gstreamer1/plugin'

pkg install: The following pattern(s) did not match any allowable packages.  Try
using a different matching pattern, or refreshing publisher information:

        gstreamer1/plugin
```
Publishers:
```
$ pkg publisher
PUBLISHER                   TYPE     STATUS P LOCATION
openindiana.org              origin   online F https://pkg.openindiana.org/hipster/
hipster-encumbered              origin   online F https://pkg.openindiana.org/hipster-encumbered/
localhostoih                origin   online F http://sfe.opencsw.org/localhostoih/
```
Regards

**Comment by pyhalov** [comment]
pkg install -vn '\*gstreamer1/plugin\*' (with asterisks)

**Comment by 3eka** [comment]
Sorry, somehow copy-paste removed stars, and I was not looking :-(

**Comment by 3eka** [comment]
I would expect that to be installed with latest **rhythmbox** package:
```
Changed packages:
hipster-encumbered
  library/audio/gstreamer1/plugin/bad
    None -> 1.10.3-2017.0.0.0
  library/audio/gstreamer1/plugin/libav
    None -> 1.10.4-2017.0.0.0
  library/audio/gstreamer1/plugin/ugly
    None -> 1.10.3-2017.0.0.0
openindiana.org
  library/audio/gstreamer1/plugin/good
    None -> 1.10.3-2017.0.0.0
```
Testing: opened URL stream, started to play and died:
```
Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/artsearch/local.py", line 129, in _enum_children_cb
    enumfiles = parent.enumerate_children_finish(result)
GLib.Error: g-io-error-quark: Operation not supported by backend (15)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/artsearch/local.py", line 136, in _enum_children_cb
    self.callback(self.callback_args)
  File "/usr/lib/rhythmbox/plugins/artsearch/artsearch.py", line 59, in search_done
    self.next_search()
  File "/usr/lib/rhythmbox/plugins/artsearch/artsearch.py", line 55, in next_search
    search.search(self.key, self.last_time, self.store, self.search_done, None)
  File "/usr/lib/rhythmbox/plugins/artsearch/musicbrainz.py", line 111, in search
    self.try_search_artist_album(key, store, callback, args)
  File "/usr/lib/rhythmbox/plugins/artsearch/musicbrainz.py", line 97, in try_search_artist_album
    callback(*args)
  File "/usr/lib/rhythmbox/plugins/artsearch/artsearch.py", line 59, in search_done
    self.next_search()
  File "/usr/lib/rhythmbox/plugins/artsearch/artsearch.py", line 55, in next_search
    search.search(self.key, self.last_time, self.store, self.search_done, None)
  File "/usr/lib/rhythmbox/plugins/artsearch/lastfm.py", line 156, in search
    callback (args)
  File "/usr/lib/rhythmbox/plugins/artsearch/artsearch.py", line 59, in search_done
    self.next_search()
  File "/usr/lib/rhythmbox/plugins/artsearch/artsearch.py", line 49, in next_search
    key = RB.ExtDBKey.create_storage("album", self.key.get_field("album"))
TypeError: Argument 1 does not allow None as a value
```
Thanks for your help.

**Comment by pyhalov** [comment]
Can you try version from my test repo (look at email)

**Comment by 3eka** [comment]
Hi,
tried and it
```
pkg://userland/gnome/media/rhythmbox@3.4.1,5.11-2017.0.0.0:20170328T154115Z
```
also reproduces 10 seconds of URL, and stops.
FLAC reproduction works fine, as well ass MP3...

So far, only networks stream seems to be problem, example: ‎http://mp3.harmonyfm.de/harmonyfm/hqlivestream.mp3

Regards.

**Comment by pyhalov** [comment]
Do you see the same crash?

**Comment by pyhalov** [comment]
works here.. Don't have sound output here, but at least rhythmbox does something...

**Pull request merged**
