### PR TITLE
X11 docs update

### PR DESCRIPTION
**Pull request by alarcher**

### CODE REVIEW

**Comment by AndWac** [comment]
I got a different sample-manifest for xorg-docs (and publishing errors because of them). Is there a missing dependency?

╰─➤  git diff sample-manifest.p5m 
diff --git a/components/x11/xorg-docs/manifests/sample-manifest.p5m b/components/x11/xorg-docs/manifests/sample-manifest.p5m
index 661e56018..a1299e222 100644
--- a/components/x11/xorg-docs/manifests/sample-manifest.p5m
+++ b/components/x11/xorg-docs/manifests/sample-manifest.p5m
@@ -24,87 +24,43 @@ set name=org.opensolaris.consolidation value=$(CONSOLIDATION)
 license $(COMPONENT_LICENSE_FILE) license='$(COMPONENT_LICENSE)'
 
 file path=usr/share/doc/X11/License.html
-file path=usr/share/doc/X11/License.html.db
-file path=usr/share/doc/X11/License.pdf.db
 file path=usr/share/doc/X11/License.txt
 file path=usr/share/doc/X11/License.xml
 file path=usr/share/doc/X11/MAINTAINERS
 file path=usr/share/doc/X11/README.html
-file path=usr/share/doc/X11/README.html.db
-file path=usr/share/doc/X11/README.pdf.db
 file path=usr/share/doc/X11/README.txt
 file path=usr/share/doc/X11/README.xml
 file path=usr/share/doc/X11/ReleaseNotes.html
-file path=usr/share/doc/X11/ReleaseNotes.html.db
-file path=usr/share/doc/X11/ReleaseNotes.pdf.db
 file path=usr/share/doc/X11/ReleaseNotes.txt
 file path=usr/share/doc/X11/ReleaseNotes.xml
 file path=usr/share/doc/X11/Versions.html
-file path=usr/share/doc/X11/Versions.html.db
-file path=usr/share/doc/X11/Versions.pdf.db
 file path=usr/share/doc/X11/Versions.txt
 file path=usr/share/doc/X11/Versions.xml
-file path=usr/share/doc/X11/Xserver/XACE-Spec.html
-file path=usr/share/doc/X11/Xserver/XACE-Spec.html.db
-file path=usr/share/doc/X11/Xserver/XACE-Spec.pdf.db
-file path=usr/share/doc/X11/Xserver/XACE-Spec.txt
 file path=usr/share/doc/X11/Xserver/XACE-Spec.xml
-file path=usr/share/doc/X11/Xserver/analysis.html
-file path=usr/share/doc/X11/Xserver/analysis.html.db
-file path=usr/share/doc/X11/Xserver/analysis.pdf.db
-file path=usr/share/doc/X11/Xserver/analysis.txt
 file path=usr/share/doc/X11/Xserver/analysis.xml
-file path=usr/share/doc/X11/Xserver/appgroup.html
-file path=usr/share/doc/X11/Xserver/appgroup.html.db
-file path=usr/share/doc/X11/Xserver/appgroup.pdf.db
-file path=usr/share/doc/X11/Xserver/appgroup.txt
 file path=usr/share/doc/X11/Xserver/appgroup.xml
-file path=usr/share/doc/X11/Xserver/secint.html
-file path=usr/share/doc/X11/Xserver/secint.html.db
-file path=usr/share/doc/X11/Xserver/secint.pdf.db
-file path=usr/share/doc/X11/Xserver/secint.txt
 file path=usr/share/doc/X11/Xserver/secint.xml
 file path=usr/share/doc/X11/ctext/ctext.html
-file path=usr/share/doc/X11/ctext/ctext.html.db
-file path=usr/share/doc/X11/ctext/ctext.pdf.db
 file path=usr/share/doc/X11/ctext/ctext.txt
 file path=usr/share/doc/X11/ctext/ctext.xml
 file path=usr/share/doc/X11/fonts/fonts.html
-file path=usr/share/doc/X11/fonts/fonts.html.db
-file path=usr/share/doc/X11/fonts/fonts.pdf.db
 file path=usr/share/doc/X11/fonts/fonts.txt
 file path=usr/share/doc/X11/fonts/fonts.xml
-file path=usr/share/doc/X11/graphics/dps.html
-file path=usr/share/doc/X11/graphics/dps.html.db
-file path=usr/share/doc/X11/graphics/dps.pdf.db
-file path=usr/share/doc/X11/graphics/dps.txt
 file path=usr/share/doc/X11/graphics/dps.xml
 file path=usr/share/doc/X11/icccm/icccm.html
 file path=usr/share/doc/X11/icccm/icccm.txt
 file path=usr/share/doc/X11/icccm/icccm.xml
 file path=usr/share/doc/X11/input/XKB-Config.html
-file path=usr/share/doc/X11/input/XKB-Config.html.db
-file path=usr/share/doc/X11/input/XKB-Config.pdf.db
 file path=usr/share/doc/X11/input/XKB-Config.txt
 file path=usr/share/doc/X11/input/XKB-Config.xml
 file path=usr/share/doc/X11/input/XKB-Enhancing.html
-file path=usr/share/doc/X11/input/XKB-Enhancing.html.db
-file path=usr/share/doc/X11/input/XKB-Enhancing.pdf.db
 file path=usr/share/doc/X11/input/XKB-Enhancing.txt
 file path=usr/share/doc/X11/input/XKB-Enhancing.xml
-file path=usr/share/doc/X11/platforms/Darwin.html
-file path=usr/share/doc/X11/platforms/Darwin.html.db
-file path=usr/share/doc/X11/platforms/Darwin.pdf.db
-file path=usr/share/doc/X11/platforms/Darwin.txt
 file path=usr/share/doc/X11/platforms/Darwin.xml
 file path=usr/share/doc/X11/platforms/Solaris.html
-file path=usr/share/doc/X11/platforms/Solaris.html.db
-file path=usr/share/doc/X11/platforms/Solaris.pdf.db
 file path=usr/share/doc/X11/platforms/Solaris.txt
 file path=usr/share/doc/X11/platforms/Solaris.xml
 file path=usr/share/doc/X11/xlfd/xlfd.html
-file path=usr/share/doc/X11/xlfd/xlfd.html.db
-file path=usr/share/doc/X11/xlfd/xlfd.pdf.db
 file path=usr/share/doc/X11/xlfd/xlfd.txt
 file path=usr/share/doc/X11/xlfd/xlfd.xml
 file path=usr/share/man/man7/X.7

**Comment by alarcher** [comment]
> I got a different sample-manifest for xorg-docs (and publishing errors because of them). Is there a missing dependency?
> 
> ╰─➤ git diff sample-manifest.p5m diff --git a/components/x11/xorg-docs/manifests/sample-manifest.p5m b/components/x11/xorg-docs/manifests/sample-manifest.p5m index 661e56018..a1299e222 100644 --- a/components/x11/xorg-docs/manifests/sample-manifest.p5m +++ b/components/x11/xorg-docs/manifests/sample-manifest.p5m @@ -24,87 +24,43 @@ set name=org.opensolaris.consolidation value=$(CONSOLIDATION) license (COMPONENTLICENSEFILE)license=′(COMPONENT_LICENSE)'
> 
> file path=usr/share/doc/X11/License.html -file path=usr/share/doc/X11/License.html.db -file path=usr/share/doc/X11/License.pdf.db file path=usr/share/doc/X11/License.txt file path=usr/share/doc/X11/License.xml file path=usr/share/doc/X11/MAINTAINERS file path=usr/share/doc/X11/README.html -file path=usr/share/doc/X11/README.html.db -file path=usr/share/doc/X11/README.pdf.db file path=usr/share/doc/X11/README.txt file path=usr/share/doc/X11/README.xml file path=usr/share/doc/X11/ReleaseNotes.html -file path=usr/share/doc/X11/ReleaseNotes.html.db -file path=usr/share/doc/X11/ReleaseNotes.pdf.db file path=usr/share/doc/X11/ReleaseNotes.txt file path=usr/share/doc/X11/ReleaseNotes.xml file path=usr/share/doc/X11/Versions.html -file path=usr/share/doc/X11/Versions.html.db -file path=usr/share/doc/X11/Versions.pdf.db file path=usr/share/doc/X11/Versions.txt file path=usr/share/doc/X11/Versions.xml -file path=usr/share/doc/X11/Xserver/XACE-Spec.html -file path=usr/share/doc/X11/Xserver/XACE-Spec.html.db -file path=usr/share/doc/X11/Xserver/XACE-Spec.pdf.db -file path=usr/share/doc/X11/Xserver/XACE-Spec.txt file path=usr/share/doc/X11/Xserver/XACE-Spec.xml -file path=usr/share/doc/X11/Xserver/analysis.html -file path=usr/share/doc/X11/Xserver/analysis.html.db -file path=usr/share/doc/X11/Xserver/analysis.pdf.db -file path=usr/share/doc/X11/Xserver/analysis.txt file path=usr/share/doc/X11/Xserver/analysis.xml -file path=usr/share/doc/X11/Xserver/appgroup.html -file path=usr/share/doc/X11/Xserver/appgroup.html.db -file path=usr/share/doc/X11/Xserver/appgroup.pdf.db -file path=usr/share/doc/X11/Xserver/appgroup.txt file path=usr/share/doc/X11/Xserver/appgroup.xml -file path=usr/share/doc/X11/Xserver/secint.html -file path=usr/share/doc/X11/Xserver/secint.html.db -file path=usr/share/doc/X11/Xserver/secint.pdf.db -file path=usr/share/doc/X11/Xserver/secint.txt file path=usr/share/doc/X11/Xserver/secint.xml file path=usr/share/doc/X11/ctext/ctext.html -file path=usr/share/doc/X11/ctext/ctext.html.db -file path=usr/share/doc/X11/ctext/ctext.pdf.db file path=usr/share/doc/X11/ctext/ctext.txt file path=usr/share/doc/X11/ctext/ctext.xml file path=usr/share/doc/X11/fonts/fonts.html -file path=usr/share/doc/X11/fonts/fonts.html.db -file path=usr/share/doc/X11/fonts/fonts.pdf.db file path=usr/share/doc/X11/fonts/fonts.txt file path=usr/share/doc/X11/fonts/fonts.xml -file path=usr/share/doc/X11/graphics/dps.html -file path=usr/share/doc/X11/graphics/dps.html.db -file path=usr/share/doc/X11/graphics/dps.pdf.db -file path=usr/share/doc/X11/graphics/dps.txt file path=usr/share/doc/X11/graphics/dps.xml file path=usr/share/doc/X11/icccm/icccm.html file path=usr/share/doc/X11/icccm/icccm.txt file path=usr/share/doc/X11/icccm/icccm.xml file path=usr/share/doc/X11/input/XKB-Config.html -file path=usr/share/doc/X11/input/XKB-Config.html.db -file path=usr/share/doc/X11/input/XKB-Config.pdf.db file path=usr/share/doc/X11/input/XKB-Config.txt file path=usr/share/doc/X11/input/XKB-Config.xml file path=usr/share/doc/X11/input/XKB-Enhancing.html -file path=usr/share/doc/X11/input/XKB-Enhancing.html.db -file path=usr/share/doc/X11/input/XKB-Enhancing.pdf.db file path=usr/share/doc/X11/input/XKB-Enhancing.txt file path=usr/share/doc/X11/input/XKB-Enhancing.xml -file path=usr/share/doc/X11/platforms/Darwin.html -file path=usr/share/doc/X11/platforms/Darwin.html.db -file path=usr/share/doc/X11/platforms/Darwin.pdf.db -file path=usr/share/doc/X11/platforms/Darwin.txt file path=usr/share/doc/X11/platforms/Darwin.xml file path=usr/share/doc/X11/platforms/Solaris.html -file path=usr/share/doc/X11/platforms/Solaris.html.db -file path=usr/share/doc/X11/platforms/Solaris.pdf.db file path=usr/share/doc/X11/platforms/Solaris.txt file path=usr/share/doc/X11/platforms/Solaris.xml file path=usr/share/doc/X11/xlfd/xlfd.html -file path=usr/share/doc/X11/xlfd/xlfd.html.db -file path=usr/share/doc/X11/xlfd/xlfd.pdf.db file path=usr/share/doc/X11/xlfd/xlfd.txt file path=usr/share/doc/X11/xlfd/xlfd.xml file path=usr/share/man/man7/X.7

Probably... I will check.

**Comment by AndWac** [comment]
There is still something wrong:

diff --git a/components/x11/xorg-docs/manifests/sample-manifest.p5m b/components/x11/xorg-docs/manifests/sample-manifest.p5m
index e52ad698d..a1299e222 100644
--- a/components/x11/xorg-docs/manifests/sample-manifest.p5m
+++ b/components/x11/xorg-docs/manifests/sample-manifest.p5m
@@ -36,17 +36,9 @@ file path=usr/share/doc/X11/ReleaseNotes.xml
 file path=usr/share/doc/X11/Versions.html
 file path=usr/share/doc/X11/Versions.txt
 file path=usr/share/doc/X11/Versions.xml
-file path=usr/share/doc/X11/Xserver/XACE-Spec.html
-file path=usr/share/doc/X11/Xserver/XACE-Spec.txt
 file path=usr/share/doc/X11/Xserver/XACE-Spec.xml
-file path=usr/share/doc/X11/Xserver/analysis.html
-file path=usr/share/doc/X11/Xserver/analysis.txt
 file path=usr/share/doc/X11/Xserver/analysis.xml
-file path=usr/share/doc/X11/Xserver/appgroup.html
-file path=usr/share/doc/X11/Xserver/appgroup.txt
 file path=usr/share/doc/X11/Xserver/appgroup.xml
-file path=usr/share/doc/X11/Xserver/secint.html
-file path=usr/share/doc/X11/Xserver/secint.txt
 file path=usr/share/doc/X11/Xserver/secint.xml
 file path=usr/share/doc/X11/ctext/ctext.html
 file path=usr/share/doc/X11/ctext/ctext.txt
@@ -54,8 +46,6 @@ file path=usr/share/doc/X11/ctext/ctext.xml
 file path=usr/share/doc/X11/fonts/fonts.html
 file path=usr/share/doc/X11/fonts/fonts.txt
 file path=usr/share/doc/X11/fonts/fonts.xml
-file path=usr/share/doc/X11/graphics/dps.html
-file path=usr/share/doc/X11/graphics/dps.txt
 file path=usr/share/doc/X11/graphics/dps.xml
 file path=usr/share/doc/X11/icccm/icccm.html
 file path=usr/share/doc/X11/icccm/icccm.txt
@@ -66,8 +56,6 @@ file path=usr/share/doc/X11/input/XKB-Config.xml
 file path=usr/share/doc/X11/input/XKB-Enhancing.html
 file path=usr/share/doc/X11/input/XKB-Enhancing.txt
 file path=usr/share/doc/X11/input/XKB-Enhancing.xml
-file path=usr/share/doc/X11/platforms/Darwin.html
-file path=usr/share/doc/X11/platforms/Darwin.txt
 file path=usr/share/doc/X11/platforms/Darwin.xml
 file path=usr/share/doc/X11/platforms/Solaris.html
 file path=usr/share/doc/X11/platforms/Solaris.txt

**Comment by alarcher** [comment]
I'll have a look tomorrow.

**Review by Toasterson — APPROVED** [review]

**Comment by Toasterson** [comment]
Works on oibuild zone. Merging

**Pull request merged**
