### PR TITLE
Add name and notices

### PR DESCRIPTION
**Pull request by alarcher**
Bring back components from the release engineering consolidation:
- name is set to the latest snapshot,
- notices are copied from existing but the version in French is fixed because it had lost all the non-ASCII characters (accents, cedilla, ...),
- version and license are the same as original components,
- dates are updated.

### CODE REVIEW

**Comment by pyhalov** [comment]
Can we generate date in /etc/release while publishing the package? Does it sound sane?

**Comment by alarcher** [comment]
Sure.

**Comment by alarcher** [comment]
Updated.

**Comment by alarcher** [comment]
Commit added to retire consolidation.

**Pull request merged**
