### PR TITLE
curl: update to 7.71.1

### PR DESCRIPTION
**Pull request by pyhalov**

### CODE REVIEW

**Comment by AndWac** [comment]
I think we need to rebuild dependant packages because there has been an incompatible change in curl between 7.61.1 and 7.62 according to https://abi-laboratory.pro/index.php?view=compat_report&l=curl&v1=7.61.1&v2=7.62.0&obj=534a5&kind=abi

**Comment by pyhalov** [comment]
The incompatibility report is caused by this commit - https://github.com/curl/curl/commit/3f3b26d6feb0667714902e836af608094235fca2 . What actually can go wrong is error reporting, if I understand this correctly. I'm not sure if ti's serious enough to justify mass rebuild, but would keep it in mind if something goes wrong.

**Comment by AndWac** [comment]
Hi,
does this build failure look like a problem with the new curl?

libtool: compile:  /usr/gcc/7/bin/gcc -DHAVE_CONFIG_H -I. -I/oibuild/oi-userland/components/library/libetpan/libetpan-1.7/src/low-level/feed -I../../.. -I../../../include -I/oibuild/oi-userland/components/library/libetpan/libetpan-1.7/src/data-types -I/oibuild/oi-userland/components/library/libetpan/libetpan-1.7/src/low-level/imf -D_REENTRANT -m32 -O3 -W -Wall -MT newsfeed_private.lo -MD -MP -MF .deps/newsfeed_private.Tpo -c /oibuild/oi-userland/components/library/libetpan/libetpan-1.7/src/low-level/feed/newsfeed_private.c -o newsfeed_private.o >/dev/null 2>&1
libtool: compile:  /usr/gcc/7/bin/gcc -DHAVE_CONFIG_H -I. -I/oibuild/oi-userland/components/library/libetpan/libetpan-1.7/src/low-level/feed -I../../.. -I../../../include -I/oibuild/oi-userland/components/library/libetpan/libetpan-1.7/src/data-types -I/oibuild/oi-userland/components/library/libetpan/libetpan-1.7/src/low-level/imf -D_REENTRANT -m32 -O3 -W -Wall -MT newsfeed_item_enclosure.lo -MD -MP -MF .deps/newsfeed_item_enclosure.Tpo -c /oibuild/oi-userland/components/library/libetpan/libetpan-1.7/src/low-level/feed/newsfeed_item_enclosure.c -o newsfeed_item_enclosure.o >/dev/null 2>&1
/oibuild/oi-userland/components/library/libetpan/libetpan-1.7/src/low-level/feed/newsfeed.c: In function 'curl_error_convert':
/oibuild/oi-userland/components/library/libetpan/libetpan-1.7/src/low-level/feed/newsfeed.c:538:3: error: duplicate case value
   case CURLE_SSL_CACERT:
   ^~~~
/oibuild/oi-userland/components/library/libetpan/libetpan-1.7/src/low-level/feed/newsfeed.c:533:3: note: previously used here
   case CURLE_SSL_PEER_CERTIFICATE:
   ^~~~
libtool: compile:  /usr/gcc/7/bin/gcc -DHAVE_CONFIG_H -I. -I/oibuild/oi-userland/components/library/libetpan/libetpan-1.7/src/low-level/feed -I../../.. -I../../../include -I/oibuild/oi-userland/components/library/libetpan/libetpan-1.7/src/data-types -I/oibuild/oi-userland/components/library/libetpan/libetpan-1.7/src/low-level/imf -D_REENTRANT -m32 -O3 -W -Wall -MT parser_atom03.lo -MD -MP -MF .deps/parser_atom03.Tpo -c /oibuild/oi-userland/components/library/libetpan/libetpan-1.7/src/low-level/feed/parser_atom03.c -o parser_atom03.o >/dev/null 2>&1
libtool: compile:  /usr/gcc/7/bin/gcc -DHAVE_CONFIG_H -I. -I/oibuild/oi-userland/components/library/libetpan/libetpan-1.7/src/low-level/feed -I../../.. -I../../../include -I/oibuild/oi-userland/components/library/libetpan/libetpan-1.7/src/data-types -I/oibuild/oi-userland/components/library/libetpan/libetpan-1.7/src/low-level/imf -D_REENTRANT -m32 -O3 -W -Wall -MT parser_rdf.lo -MD -MP -MF .deps/parser_rdf.Tpo -c /oibuild/oi-userland/components/library/libetpan/libetpan-1.7/src/low-level/feed/parser_rdf.c -o parser_rdf.o >/dev/null 2>&1
libtool: compile:  /usr/gcc/7/bin/gcc -DHAVE_CONFIG_H -I. -I/oibuild/oi-userland/components/library/libetpan/libetpan-1.7/src/low-level/feed -I../../.. -I../../../include -I/oibuild/oi-userland/components/library/libetpan/libetpan-1.7/src/data-types -I/oibuild/oi-userland/components/library/libetpan/libetpan-1.7/src/low-level/imf -D_REENTRANT -m32 -O3 -W -Wall -MT date.lo -MD -MP -MF .deps/date.Tpo -c /oibuild/oi-userland/components/library/libetpan/libetpan-1.7/src/low-level/feed/date.c -o date.o >/dev/null 2>&1
libtool: compile:  /usr/gcc/7/bin/gcc -DHAVE_CONFIG_H -I. -I/oibuild/oi-userland/components/library/libetpan/libetpan-1.7/src/low-level/feed -I../../.. -I../../../include -I/oibuild/oi-userland/components/library/libetpan/libetpan-1.7/src/data-types -I/oibuild/oi-userland/components/library/libetpan/libetpan-1.7/src/low-level/imf -D_REENTRANT -m32 -O3 -W -Wall -MT newsfeed_item.lo -MD -MP -MF .deps/newsfeed_item.Tpo -c /oibuild/oi-userland/components/library/libetpan/libetpan-1.7/src/low-level/feed/newsfeed_item.c -o newsfeed_item.o >/dev/null 2>&1
libtool: compile:  /usr/gcc/7/bin/gcc -DHAVE_CONFIG_H -I. -I/oibuild/oi-userland/components/library/libetpan/libetpan-1.7/src/low-level/feed -I../../.. -I../../../include -I/oibuild/oi-userland/components/library/libetpan/libetpan-1.7/src/data-types -I/oibuild/oi-userland/components/library/libetpan/libetpan-1.7/src/low-level/imf -D_REENTRANT -m32 -O3 -W -Wall -MT parser_rss20.lo -MD -MP -MF .deps/parser_rss20.Tpo -c /oibuild/oi-userland/components/library/libetpan/libetpan-1.7/src/low-level/feed/parser_rss20.c -o parser_rss20.o >/dev/null 2>&1
libtool: compile:  /usr/gcc/7/bin/gcc -DHAVE_CONFIG_H -I. -I/oibuild/oi-userland/components/library/libetpan/libetpan-1.7/src/low-level/feed -I../../.. -I../../../include -I/oibuild/oi-userland/components/library/libetpan/libetpan-1.7/src/data-types -I/oibuild/oi-userland/components/library/libetpan/libetpan-1.7/src/low-level/imf -D_REENTRANT -m32 -O3 -W -Wall -MT parser_atom10.lo -MD -MP -MF .deps/parser_atom10.Tpo -c /oibuild/oi-userland/components/library/libetpan/libetpan-1.7/src/low-level/feed/parser_atom10.c -o parser_atom10.o >/dev/null 2>&1
make[8]: *** [Makefile:573: newsfeed.lo] Error 1

**Comment by pyhalov** [comment]
Yes, https://github.com/dinhvh/libetpan/commit/945f3702182a7b7920c440512c15cce23ad1bacd

**Pull request merged**
