### PR TITLE
fontconfig: fix pkg-config file

### PR DESCRIPTION
**Pull request by alarcher**

### CODE REVIEW

**Comment by Mno-hime** [comment]
@alarcher Is this expected to fix this weird font https://openqa.oi.mnowak.cz/tests/3969#step/pkg_update_to_latest_packages/22? I think it started with this https://hipster.openindiana.org/jenkins/job/oi-userland/4253/ batch of updates.

**Comment by alarcher** [comment]
@Mno-hime No it is a build issue, but fontconfig is known for not reloading the configuration properly in some configurations. Logging out and logging in again should be enough.

**Comment by alarcher** [comment]
@Mno-hime If this is a real problem for some configurations we can change the default font configuration. On my systems nothing changed after update.

**Comment by Mno-hime** [comment]
You are right @alarcher, it was just a transient problem, to get rid of it now it will only update to new BE.

**Pull request merged**
