### PR TITLE
Rebuild components due to gpgme update

### PR DESCRIPTION
**Pull request by pyhalov**
Merge this and #5418 after #5440

### CODE REVIEW

**Comment by Mno-hime** [comment]
It seems that Samba also depends on GPGME?

**Review by Mno-hime — APPROVED** [review]

**Comment by gc-hpc-admin** [comment]
Sorry, I do not know how to ask elsewhere:
Is there a reason why oi-userland does not provide a "prep-git.mk" as solaris-userland does (see: https://github.com/oracle/solaris-userland/blob/master/make-rules/prep-git.mk)

It would be quite helpful to have it since downloading the tarball from git very often does somenasty things with the directory name etc.

Simply clone the repo and checking out would help a lot.
If there is no reason against having prep-git.mk I would wok on that and create a pull request.

**Comment by chincheta0815** [comment]
Sorry, I do not know how to ask elsewhere:
Is there a reason why oi-userland does not provide a "prep-git.mk" as solaris-userland does (see: https://github.com/oracle/solaris-userland/blob/master/make-rules/prep-git.mk)

It would be quite helpful to have it since downloading the tarball from git very often does somenasty things with the directory name etc.

Simply clone the repo and checking out would help a lot.
If there is no reason against having prep-git.mk I would work on that and create a pull request.

**Comment by Mno-hime** [comment]
> Sorry, I do not know how to ask elsewhere:

The oi-dev mailing list seems to be a right place for this type of conversation :).

> Is there a reason why oi-userland does not provide a "prep-git.mk" as solaris-userland does (see: https://github.com/oracle/solaris-userland/blob/master/make-rules/prep-git.mk)
> ...
> If there is no reason against having prep-git.mk I would work on that and create a pull request.

Probably no reason other than we didn't fee the need to bring it over. Feel free to go ahead and port it.

We use a similar technique in some components which are just a shell around projects we host on GitHub and don't make proper tarball releases, e.g. https://github.com/OpenIndiana/oi-userland/blob/oi/hipster/components/openindiana/pkg/Makefile#L20.

**Pull request merged**
