### PR TITLE
DBI-PostgreSQL: fix GCC 6 build

### PR DESCRIPTION
**Pull request by pyhalov**
Not for merging.
@alarcher - for your gcc 6 branch

### CODE REVIEW

**Comment by pyhalov** [comment]
@alarcher - close PR after merging commit to your branch

**Comment by pyhalov** [comment]
This one is not correct. LD_OPTIONS is set incorrectly for 64-bit build

**Comment by pyhalov** [comment]
Should be fixed by #3803

**Comment by alarcher** [comment]
@pyhalov Cherry-picked thank you.

**Pull request closed without merging**
