### PR TITLE
Bump libpciaccess to 0.13.5

### PR DESCRIPTION
**Pull request by alarcher**

### CODE REVIEW

**Review by pyhalov — APPROVED** [review]

**Comment by pyhalov** [comment]
Feel free to merge it when you think that it's ready.

**Comment by alarcher** [comment]
OK. I will merge after some further testing.

**Comment by alarcher** [comment]
@pyhalov @gwr Namely I am worried about https://cgit.freedesktop.org/xorg/lib/libpciaccess/commit/?id=0bd248f852f1f2a37396c98519eee6f50c434848 and https://cgit.freedesktop.org/xorg/lib/libpciaccess/commit/?id=fe556c48dad96717b0ba71d489575c6b90b46448

**Comment by alarcher** [comment]
Breaks Intel HD 2000 on my test machine.

**Pull request closed without merging**
