### PR TITLE
python/cssselect: add 1.2.0

### PR DESCRIPTION
**Pull request by iigs**
This is one of three missing dependencies for inkscape.
python-integrate-project script does not work for me.

### CODE REVIEW

**Comment by mtelka** [comment]
What exactly means _does not work_?

**Comment by mtelka** [comment]
I tried to run `$WS_TOOLS/python-integrate-project cssselect` and it completed (almost) successfully.  The only problem was that we do miss `sybil` so tests were not run.

**Comment by AndWac** [comment]
@mtelka: We still don't have official documentation for python- and perl-integrate-project tools. Maybe it's time to add them?

**Comment by iigs** [comment]
I run $FULL_PATH/python-integrate-project cssselect

This is the output:

ERROR: 'gmake refresh-patches' failed!
WARNING: pytest is called directly in tox.ini
WARNING: sphinx-build is called directly in tox.ini
ERROR: 'gmake test-env-check' failed for 3.9!
FATAL: 'git commit' failed!

The last line is an expected failure since git commit command does not work in my local oi-userland repo.

**Comment by mtelka** [comment]
> @mtelka: We still don't have official documentation for python- and perl-integrate-project tools. Maybe it's time to add them?

Yes, we don't :-(.  The work in progress for Perl is [here](https://github.com/mtelka/oi-userland/blob/pim-doc/doc/perl-modules.md) (not updated since Sep 2022, unfortunately).  In any case both `perl-integrate-module` and `python-integrate-project` are simple  shell scripts :-).  And there are plenty of usage examples... Also, I'm here to answer questions.

**Comment by mtelka** [comment]
> I run $FULL_PATH/python-integrate-project cssselect
> 
> This is the output:
> 
> ERROR: 'gmake refresh-patches' failed! WARNING: pytest is called directly in tox.ini WARNING: sphinx-build is called directly in tox.ini ERROR: 'gmake test-env-check' failed for 3.9! FATAL: 'git commit' failed!
> 
> The last line is an expected failure since git commit command does not work in my local oi-userland repo.

If you see `ERROR`s with some `gmake` command then you just need to run that command to see error details.  In this case I assume you do not have `quilt` installed.  The `git commit` failure is really strange (why it does not work in your local repo?) and you should fix it, I think.  How do you commit without working `git commit`?

**Comment by mtelka** [comment]
This needs `sybil` to run tests and `sybil` needs `testfixtures` and `seedir` to run its tests.

**Comment by mtelka** [comment]
And `testfixtures` needs `sybil` to run its tests :-).

**Comment by mtelka** [comment]
Please re-run `python-integrate-project` once #16482 is merged and you install `sybil` on your end.

**Comment by iigs** [comment]
Installed quilt, seedir, sybil, and dependencies.  python-integrate-projec produced files.  No stdout/stderr during gmake build and gmake install so I can't confirm this did the right thing.  I just blindly committed the files it produced.

**Comment by mtelka** [comment]
> Installed quilt, seedir, sybil, and dependencies. python-integrate-projec produced files. No stdout/stderr during gmake build and gmake install so I can't confirm this did the right thing. I just blindly committed the files it produced.

I'm sorry, but that sounds weird.  Could you please paste the full output of the `python-integrate-project` command?

**Comment by iigs** [comment]
```
$FULL_PATH/python-integrate-project cssselect
WARNING: pytest is called directly in tox.ini
WARNING: sphinx-build is called directly in tox.ini
FATAL: 'git commit' failed!
```
After the last WARNiING, but before FATAL, I expect to see the output of gmake build and gmake install.

**Comment by mtelka** [comment]
> ```
> $FULL_PATH/python-integrate-project cssselect
> WARNING: pytest is called directly in tox.ini
> WARNING: sphinx-build is called directly in tox.ini
> FATAL: 'git commit' failed!
> ```
> 
> After the last WARNiING, but before FATAL, I expect to see the output of gmake build and gmake install.

Why?  The `python-integrate-project` tool is designed to do not produce output if everything works as expected.

Could you please fix your `git commit`?  It will allow you to use full power of the `python-integrate-project` tool.  It will also avoid typos in commit messages, like your `1.20` here.  Thank you.

BTW, the `python-integrate-project` output is okay, except the `git commit` FATAL failure.

**Comment by iigs** [comment]
If I had a cookbook set of steps to do everything that is needed with git and the steps to change my local repo so commit can work, I would make the change.  I don't have either.

I will guarantee you that it will be harder to troubleshoot problems with the use of python-integrate-project without having the output of gmake build and gmake install.

**Comment by mtelka** [comment]
> If I had a cookbook set of steps to do everything that is needed with git and the steps to change my local repo so commit can work, I would make the change. I don't have either.

Could you please paste output from your failing `git commit`?  It is hard to help when we do not know what exactly is failing.

> I will guarantee you that it will be harder to troubleshoot problems with the use of python-integrate-project without having the output of gmake build and gmake install.

... and without `gmake test` too.  Since the test is ran twice, then you should expect two `gmake test` outputs.  In addition, the test is run twice for every Python version we support.  Currently it is single version only, so testing is ran twice only, but when we add more Python versions then you will have four, six, or even more `gmake test` outputs...

No, I'm kidding.  Effectively you do not need those outputs for regular `python-integrate-project` usage at all.  If there is a problem, then yes, you need as much outputs as possible but the `python-integrate-project` tool is not here to help you to solve integration problems.

BTW, I have one secret to share with you: `python-integrate-project` calls neither `gmake build` nor `gmake install`. :-)

Please note that I ran the `python-integrate-project` tool either manually or via cron jobs more than 200.000 times so far and I can guarantee you that it works exactly as it was designed and fulfills its purpose perfectly.  Or almost perfectly: there are always areas for improvements.

**Comment by iigs** [comment]
Just for the record, the other two python dependencies needed for inkscape are scour and numpy.  I already have completely working recipes to build these modules without using python-integrate-project.
So I started looking at getting scour to build using python-integrate-project and can't get it to work.

Because commits do not work, I can test build scour any place I want in the oi-userland tree.  I will choose a place that I can easily rm afterwards--I choose to build in openindiana/test-foo.

So I run $FULL_PATH/python-integrate-project -d openindiana/test-foo scour
and get this output:
WARNING: No license file found
ERROR: Makefile is not complete (TODO found)
ERROR: 'gmake publish' failed!
FATAL: 'git commit' failed!

OK.  I look at examples of python-integrate-project.conf.

I create a file openindiana/test-foo/python-integrate-project.conf with this:
%hook-begin%
LICENSE_FILE='scour.license'

I then run $FULL_PATH/python-integrate-project -d openindiana/test-foo scour
and get this output:
WARNING: No license file found
ERROR: Makefile is not complete (TODO found)
ERROR: 'gmake publish' failed!
FATAL: 'git commit' failed!

and the file openindiana/test-foo/python-integrate-project.conf is gone.

**Comment by mtelka** [comment]
> Just for the record, the other two python dependencies needed for inkscape are scour and numpy.

I think this is off-topic here.  Please focus on completion of cssselect.  Thank you.

BTW, the `python-integrate-project.conf` needs to be committed to git before you run the `python-integrate-project` script.  See also 3e [here](https://github.com/mtelka/oi-userland/blob/pim-doc/doc/perl-modules.md).

**Comment by iigs** [comment]
As far as I can tell, this PR is complete.

If python-integrate-project.conf  needs to be committed in order to build a package, I am unable to follow that since that breaks my work flow to build packages.  I don't have to commit in parts for building regular packages--committing in parts requires a more savvy experience level of git in order to avoid breaking git repos.

Can python-integrate-project be supported without needing to commit python-integrate-project.conf independently of the rest of the files for the package?

**Pull request merged**
