### PR TITLE
golang-16: update to 1.6.3

### PR DESCRIPTION
**Pull request by avsej**

### CODE REVIEW

**Comment by xen0l** [comment]
LGTM

**Comment by pyhalov** [comment]
@avsej , have you checked that list of delivered files didn't change?

**Comment by avsej** [comment]
@pyhalov yes. nothing has changed. it is a security update: https://github.com/golang/go/issues?utf8=%E2%9C%93&q=milestone%3AGo1.6.3

**Comment by pyhalov** [comment]
Thanks, LGTM

**Pull request merged**
