### PR TITLE
mozilla-nspr: obsolete header-nspr; prefer 64 bit; move 32 bit support to separate package

### PR DESCRIPTION
**Pull request by mtelka**
The `library/nspr/header-nspr` package currently contains an (incomplete) set of developer files (includes and the `nspr-config` script).  I see no reason to have such files living separately so I merged all files from `library/nspr/header-nspr` to the main `library/nspr` package.

Previously, the `/usr/bin/nspr-config` script was for 32 bit.  Now the 64-bit is preferred so the `/usr/bin/nspr-config` script is for 64 bit while the 32-bit one is in `/usr/bin/i86/nspr-config`.

Finally, the 32-bit related stuff was split out to new `library/nspr/32` package.

### CODE REVIEW

**Comment by mtelka** [comment]
This is blocked by #19221.

**Comment by AndWac** [comment]
#19221 is already merged

**Comment by mtelka** [comment]
> #19221 is already merged

Thank you.  I need to refresh, update (add illumos-gate patch) and re-test this one.  Should be done today.

**Comment by mtelka** [comment]
rebase only

**Comment by mtelka** [comment]
Added patch for `illumos-gate/exception_lists/packaging.deps` to make sure the build of the `illumos-gate` component succeeds.  The patch will be upstreamed later together with other similar changes in `packaging.deps`.

**Pull request merged**
