### PR TITLE
[WIP] VirtualBox guest additions

### PR DESCRIPTION
**Pull request by alarcher**
@pyhalov @xen0l @kenmays @jimklimov @AndWac FYI

### CODE REVIEW

**Review by xen0l — APPROVED** [review]
I don't see anything wrong with this. This will help me with vagrant box creation as I can just rely on 'pkg install' rather than on mounting the cd and using it.

**Comment by pyhalov** [comment]
besides mising p5m :)

**Comment by alarcher** [comment]
@pyhalov @xen0l Need to find the time to write the install stage as there is no install facility in the build system.

**Comment by kenmays** [comment]
@alarcher - Track the support ticket with the Virtualbox engineers and within our [bugtracker](https://www.illumos.org/issues/9752) so we can continue maintenance support with them.

**Comment by pyhalov** [comment]
I also have https://github.com/pyhalov/oi-userland/commit/550fd476fc541292569b2705976dcb0d5a95d21a

**Comment by pyhalov** [comment]
We already ship VirtualBox guest addition.

**Pull request closed without merging**
