### PR TITLE
Mate 1.24 part4

### PR DESCRIPTION
**Pull request by mvwieringen**
More updates for mate 1.24 update merge after 3 other parts.

### CODE REVIEW

**Comment by pyhalov** [comment]
Please, update sample-manifests

**Comment by mvwieringen** [comment]
Updated the sample-manifests and copied the changes to the p5m files where needed.

**Comment by AndWac** [comment]
Ok, I have build all packages from part1 to part4.
The following packages are missing:
atril, caja-extensions, mate-control-center, mate-power-manager, mate-system-monitor, mate-themes, and mate-utils.
Do you have any plans to update these packages, too?

**Comment by mvwieringen** [comment]
> Ok, I have build all packages from part1 to part4.
> The following packages are missing:
> atril, caja-extensions, mate-control-center, mate-power-manager, mate-system-monitor, mate-themes, and mate-utils.
> Do you have any plans to update these packages, too?

See the closed pull request as to why they are missing. If you take a look at my repo you will find part 5 and 6. Part 5 contains mate-system-monitor but that needs a way newer libgtop which I also took a stab at but its really difficult as the old ancient version now in OpenIndiana is from 2016 and hacked heavily. I mostly got it to compile with transplanting some big chunks and fixing bigger bugs. It however means rebuilding some stuff like libgksu etc. It looks promising and the version of mate-system-monitor from early testing looks to still function ok and show things like memory and processes.

As to the next e.g. things in part6 atril needs some extra stuff as that is now an external dependency and some others needs udisk2 which will be lets say challenging as its pretty Linux only software from the first look.

to quote the original pull request:

The following are more involving due to missing support on OI:

- mate-control-center needs polkit available in solaris-userland but that
  needs mozjs-60 which is much more work but also available in solaris-userland
- atril needs external libtexlive which used to be internal not available in solaris-userland
- caja-extensions
- mate-power-manager
- mate-utils

**Comment by mvwieringen** [comment]
> * mate-control-center needs polkit available in solaris-userland but that
>   needs mozjs-60 which is much more work but also available in solaris-userland
Fixed this by removing the new time-admin applet which is of little use anyway.

> * atril needs external libtexlive which used to be internal not available in solaris-userland
Created a new package with just enough to make things compile. 

> * caja-extensions
> * mate-power-manager
> * mate-utils
Also compile now by disabling udisk2 support which is a Linux only library anyway.

**Comment by mvwieringen** [comment]
Testing notes:

- Installed fresh new VM with latest OI version
- Create build environment
- Build mvw/mate-1.24-[0-4]
  - pkg update in between branches

Tests performed:
  - Started programs that work ok (with remote X display on SUNRay):
    - atril
    - caja
    - engrampa
    - eom
    - mate-system-log
    - mate-power-statistics
    - mate-dictionary
    - mate-screenshot
    - mate-search-tool
    - mate-disk-usage-analyzer
    - mate-power-manager
    - mate-power-preferences
    - mate-about
    - mate-system-monitor
    - mate-notification-properties
    - mate-session-properties
    - mate-terminal
    - mate-volume-control
    - mate-calc
    - mate-calc-cmd
    - mate-about
    - mate-color-select
    - mate-doc-common
    - mate-wm
    - mate-terminal.wrapper
    - mate-window-properties
    - mate-typing-monitor
    - mate-control-center
    - pluma

  - Upgraded sunray server with new packages tested:
    - atril
    - caja
    - engrampa
    - eom
    - mate-system-log
    - mate-power-statistics
    - mate-dictionary
    - mate-screenshot
    - mate-search-tool
    - mate-disk-usage-analyzer
    - mate-power-manager
    - mate-power-preferences
    - mate-about
    - mate-system-monitor
    - mate-notification-properties
    - mate-session-properties
    - mate-terminal
    - mate-volume-control
    - mate-calc
    - mate-calc-cmd
    - mate-about
    - mate-color-select
    - mate-doc-common
    - mate-wm
    - mate-terminal.wrapper
    - mate-window-properties
    - mate-typing-monitor
    - mate-control-center
    - pluma
   
  - Problems found:
    - Strange black border around windows of 2 mm
      - maybe theme problem gtk border
      - Only on sunray install not on laptop with native install
    - Pressing help button in most (all ?) programs
      - leads to core dump from WebKitWebProces
        - error: 
          Error compiling builtin:
          Fatal error compiling builtin function 'apply':

          Stack from pstack:

          f3e92023 WTFCrash (f3f905e0, 803bfb0, 803bfd8, f363d520, 803bfc0, facadbc2) + 23
          f363d589 ???????? (803c018, fb580af0, f363d090, f363d7e8, 80f6288, 8105550)
          f363d7e8 _ZN3JSC18BuiltinExecutables23createBuiltinExecutableERKNS_10SourceCodeERKNS_10IdentifierENS_16ConstructAbilityE (81052a8, 8105550, 8115d74, 1, fb580af0, f3f70000) + 28
          f363fc75 _ZN3JSC18BuiltinExecutables36functionPrototypeApplyCodeExecutableEv (81052a8, fac93ce0, fb580af0, c5d0, f3c3e763, 84740a8) + 65
          f3e8f5f1 _ZN3JSC35functionPrototypeApplyCodeGeneratorERNS_2VME (80f6288, 4, f3c8e510, 0, 803c0d0, fac93ce0) + 21
          f3c3e763 _ZN3JSC17FunctionPrototype21addFunctionPropertiesEPNS_9ExecStateEPNS_14JSGlobalObjectEPPNS_10JSFunctionES7_S7_ (83400c0, 845c0d0, 845c0a0, 803c270, 803c274, 803c278) + 83
          ...

**Comment by mvwieringen** [comment]
Some packages don't fully build die to the fact its complains about ITS rules for some message files. For now I just touched the output file and published the packages which at least let you test them but it doesn't have the correct language files.

**Comment by AndWac** [comment]
The aforementioned ITS related errors affect mate-power-manager and mate-system-monitor.
I have build all packages now, will install them on my desktop and will report back.

**Comment by AndWac** [comment]
- atril works
- caja works; time-slide seems to work in caja, too. I can browse snapshots.
- engrampa works
- mozo works
- mate-utils work
- mate-terminal works
- marco works

**Comment by AndWac** [comment]
Isn't this one ready? It is still marked as draft.

**Comment by mvwieringen** [comment]
It still has the problem with ITS in the Makefile which affect mate-power-manager and mate-system-monitor.
Let me see if I can patch around that.

**Comment by AndWac** [comment]
Dammit! Now I remember. That won't run through our jenkins as it is.

**Comment by mvwieringen** [comment]
Ah seems its related to policy-kit stuff which I think we can drop anyway. Lets me try to fix that and I will push an extra commit to this branch in the coming hour or so.

**Comment by AndWac** [comment]
Ok, otherwise we need to backout the failing packages.

**Comment by mvwieringen** [comment]
I will drop the two failing packages and create a part 5 branch in which I fix those. Then we can merge part 4 and I have time to fix part 5.

**Comment by AndWac** [comment]
ok

**Comment by mvwieringen** [comment]
Ok done. Think the other two are also obvious its related to polkit for which we already have some patches just need more. Working on that now. Hope to finish today and otherwise tomorrow so we can finish the mate-1.24 merge.

**Comment by AndWac** [comment]
Ok, fine. Thanks for all your hard work!

**Pull request merged**
