### PR TITLE
Prefer 32-bit build for legacy components

### PR DESCRIPTION
**Pull request by mtelka**
This is an attempt to solve issue we discussed in #8540.  Untested.  Please test before merge.

### CODE REVIEW

**Comment by Toasterson** [comment]
Can you solve the merge confilct?

**Comment by mtelka** [comment]
> Can you solve the merge confilct?

Done, I think.  Thanks.

**Comment by Toasterson** [comment]
Tested with components under openindian directory. So far all failures also happen with or without this change. @mtelka do you know any component I could test with? Otherwise I would say merge and fix the failures.

**Comment by mtelka** [comment]
> Tested with components under openindian directory. So far all failures also happen with or without this change.

What fails there? For example `openindiana/illumos-gate` does not fail without this change.

> do you know any component I could test with?

Sorry, no.

> Otherwise I would say merge and fix the failures.

I prefer just fix failures (without merging this) :-).

**Comment by Toasterson** [comment]
Ok, I am a bit lost what to do here. Shall we merge and see what happens or close and fix legacy components to not be legacy anymore?

**Comment by mtelka** [comment]
> Ok, I am a bit lost what to do here. Shall we merge and see what happens or close and fix legacy components to not be legacy anymore?

I prefer not to merge this, but fix all problems instead.  To do so, we need a list of components with problems.  I'm not aware of any component failing because of this.  Everything I encountered I just fixed.

**Comment by AndWac** [comment]
Alas it's tedious to find failing packages as some package builds will only fail during mass builds (eg. by running gmake publish in the top level folder) and build ok when build separately.
I hope that #9560 will fix at least some of those problems.
I am also in favor to close this PR and find and fix failing builds systematically.

**Comment by Toasterson** [comment]
Then we have a decision :) Closing.

**Pull request closed without merging**
