### PR TITLE
caja: update to 1.22.0

### PR DESCRIPTION
**Pull request by pyhalov**

### CODE REVIEW

**Comment by Mno-hime** [comment]
Thanks @pyhalov, you saved me some headaches, will move this to https://github.com/OpenIndiana/oi-userland/pull/4909.

**Comment by pyhalov** [comment]
It still needs debugging and fixing.

**Comment by pyhalov** [comment]
@Mno-hime Hi. Can you test this? 

What else do we miss for mate 1.22?

**Comment by Mno-hime** [comment]
Thanks for the additional fixes.

> @Mno-hime Hi. Can you test this?

I will once we have all the pieces.

> What else do we miss for mate 1.22?

See https://github.com/OpenIndiana/oi-userland/pull/4911#issuecomment-481691584.

**Review by Mno-hime — APPROVED** [review]
For testing note, see https://github.com/OpenIndiana/oi-userland/pull/4908#issuecomment-488266449. Integrated to MATE 1.22 PRs. Will close this one.

**Pull request closed without merging**
