### PR TITLE
geoip-database: automatic version on rebuild

### PR DESCRIPTION
**Pull request by dbh201**

### CODE REVIEW

**Comment by erwinlem** [comment]
Could you also make sure the file GeoIP.dat.gz is mirrored on dlc.openindiana.org? That file has no version number so it will be overwritten tomorrow. And that prevents me from building it because the hash is different.

**Comment by dbh201** [comment]
The hashes aren't all that useful since mailfud.org doesn't put their checksums with the updates. Would it be better to just do the Makefile like this? This Makefile can just be rebuilt on a schedule to keep the package updated. Not sure how it's going to affect version-locking though.

**Comment by AndWac** [comment]
We should try to get secure checksums. If they aren't supported by the original project we should have at least our own in order to prevent later corruptions or manipulations.

**Comment by dbh201** [comment]
So, to update this from here on, just change the version number and delete the sha256sums.txt file. Running `gmake publish` should do the rest.

**Pull request merged**
