### PR TITLE
Restore empty archives directory from commit 0865640df

### PR DESCRIPTION
**Pull request by cstes**
Add an emoty archives/.gitkeep file

See old commit 0865640df to restore old setup

### CODE REVIEW

**Review by mtelka — COMMENTED** [review]
-1

**Comment by mtelka** [comment]
But I must admit it is strange that the file was removed as a part of random package update (wireshark).

**Comment by cstes** [comment]
I propose to close #9788 and simply provide an emoty archives directory by default as it was in the past.

**Comment by cstes** [comment]
I don't mind closing this PR because manually creating the archives directory is no problem for me ....   Also it is trivial to add this file back in the future ...  I always found it very sueful.

**Comment by cstes** [comment]
Trvivial to add archives/.githkeep if necessary

**Pull request closed without merging**
