### PR TITLE
Help Emacs find CA certs bundle

### PR DESCRIPTION
**Pull request by Mno-hime**
With this fix, Emacs displays the Package Manager without warning that it can't check sites certificate's validity.

### CODE REVIEW

**Comment by AndWac** [comment]
Michal, I am not able to publish emacs in my build environments (builds fail with segfaults).
I have compiled the patched gnutls.el into an .elc file in my emacs and put it into /usr/share/emacs/26.1/list/net/gnutls.elc. But I still get the TLS handshake error.

**Comment by Mno-hime** [comment]
@AndWac I think you can add the line to `init.el`, per https://blog.vifortech.com/posts/emacs-tls-fix/.

Or, unpack this file [tls.elc.gz](https://github.com/OpenIndiana/oi-userland/files/3780762/tls.elc.gz) to `/usr/share/emacs/26.3/lisp/net/tls.elc`.

Also, I can provide installable packages, let me know.

**Comment by AndWac** [comment]
@Mno-hime I did both, replaced /usr/share/emacs/26.3/lisp/net/tls.elc and added 
(require 'gnutls)                                                                                                                    
(add-to-list 'gnutls-trustfiles "/etc/certs/ca-certificates.crt")                                                                                                           
to my init.el but TLS handshake still fails.
So, please be so kind to provide the installable package in order to check the last path, too.

**Comment by Mno-hime** [comment]
@AndWac Can you post the error?

See ftp://openqa.oi.mnowak.cz/emacs.p5p for the package.

It has:
- pkg://userland/editor/gnu-emacs/gnu-emacs-no-x11
- pkg://userland/editor/gnu-emacs/gnu-emacs-lisp
- pkg://userland/editor/gnu-emacs/gnu-emacs-x11
- pkg://userland/editor/gnu-emacs/gnu-emacs-gtk
- pkg://userland/editor/gnu-emacs

`pkg apply-hot-fix` was fixed recently, so, it might work now, or employ `pkg set-publisher -g file:///path_to_emacs.p5p userland; pkg install $pkg`.

Let me know how it went. It fixed the TLS problem for me.

**Comment by AndWac** [comment]
@Mno-hime Still not working; messages:
No projects needed to be removed.
For information about GNU Emacs and the GNU system, type C-h C-a.
No projects needed to be removed. [2 times]
Importing package-keyring.gpg...done
gnutls.c: [0] (Emacs) Received alert:  Handshake failed

╭─andreas@saturn ~  ‹master*› 
╰─➤  pfexec pkg set-publisher -g file:///./export/home/andreas/Downloads/emacs.p5p userland
╭─andreas@saturn ~  ‹master*› 
╰─➤  pfexec pkg install pkg://userland/editor/gnu-emacs/gnu-emacs-no-x11 pkg://userland/editor/gnu-emacs/gnu-emacs-lisp pkg://userland/editor/gnu-emacs/gnu-emacs-x11 pkg://userland/editor/gnu-emacs/gnu-emacs-gtk pkg://userland/editor/gnu-emacs

╭─andreas@saturn ~  ‹master*› 
╰─➤  pkg list -a | grep emacs                                                                                                                                         130 ↵
SUNWgnu-emacs                                     23.1-0.133                 --r
SUNWgnu-emacs-el                                  23.1-0.133                 --r
SUNWgnu-emacs-gtk                                 23.1-0.133                 --r
SUNWgnu-emacs-nox                                 23.1-0.133                 --r
SUNWgnu-emacs-x                                   23.1-0.133                 --r
editor/gnu-emacs (userland)                       26.3-2019.0.0.0            i--
editor/gnu-emacs/gnu-emacs-gtk (userland)         26.3-2019.0.0.0            i--
editor/gnu-emacs/gnu-emacs-lisp (userland)        26.3-2019.0.0.0            i--
editor/gnu-emacs/gnu-emacs-no-x11 (userland)      26.3-2019.0.0.0            i--
editor/gnu-emacs/gnu-emacs-x11 (userland)         26.3-2019.0.0.0            i--

**Comment by Mno-hime** [comment]
@AndWac OK, but I wasn't fixing that :). What I fix is a problem with the packages-hosting repo is claimed to have unknown certificate (which is true as the CA bundle wasn't located).

About this one... Reading https://debbugs.gnu.org/cgi/bugreport.cgi?bug=31313#22 I think the problem might be that GNU TLS v2 is in the standard path and GNU TLS v3 is moved to a special path, and that `gnutls-cli` is of a 2.12.x version and v3 `gnutls-cli` is not being shipped at all. This should be fixed once https://github.com/OpenIndiana/oi-userland/pull/5295 is integrated.

In the bug report they ask for `(gnutls-available-p)`. Can you provide it (whatever it is)?

**Comment by AndWac** [comment]
(ClientHello\ Padding Session\ Ticket Extended\ Master\ Secret Encrypt-then-MAC ClientHello\ Padding ALPN Heartbeat SRTP Signature\ Algorithms SRP Supported\ ECC\ Point\ Formats Supported\ curves ...)

**Pull request merged**
