### PR TITLE
net-snmp: bug 828449 (Debian), fix from solaris (Oracle)

### PR DESCRIPTION
**Pull request by grueni**

### CODE REVIEW

**Comment by pyhalov** [comment]
Hi. 
Can you reorganize this PR in two commits, so that one contains fix for snmpd crash, and another - OpenSSL 1.1.0 fixes (preferably, as one patch)?

**Comment by grueni** [comment]
Better now?

**Comment by Mno-hime** [comment]
@grueni Did you have a chance to run the test suite (there appears to be some) or test it in some other way?

**Comment by grueni** [comment]
I added test/results-* and the transform in the Makefile. Tests are passed with OK.

**Pull request merged**
