### PR TITLE
Bump automake to 1.15.1

### PR DESCRIPTION
**Pull request by alarcher**
Been using this since early September.

### CODE REVIEW

**Comment by pyhalov** [comment]
While here, can you move all automake/autoconf components to developer? So that they become developer/automake-115, developer/autoconf-2.13, developer/autoconf and so on?

**Comment by alarcher** [comment]
@pyhalov Done.

**Comment by pyhalov** [comment]
In your gcc-6 experiment, did you use this automake?

**Comment by alarcher** [comment]
No I did not but I can install it in the build zone if you like.

**Comment by pyhalov** [comment]
It would be natural testing :)

**Comment by alarcher** [comment]
@pyhalov I have rebuilt all the components so far in the gcc6 zone with this automake.

**Review by pyhalov — APPROVED** [review]

**Pull request merged**
