### PR TITLE
Bump startup-notification to 0.12

### PR DESCRIPTION
**Pull request by dsendkowski**
Required by awesome window manager, which I'm trying to add.

### CODE REVIEW

**Comment by pyhalov** [comment]
Please, move startup-notifications to library category https://wiki.openindiana.org/oi/Categories+layout

**Comment by dsendkowski** [comment]
You mean move the whole `startup-notification` directory from `components` to `components/library` ?

**Comment by pyhalov** [comment]
yes

**Comment by dsendkowski** [comment]
OK, `startup-notification` moved.

**Pull request merged**
