### PR TITLE
Firefox to 68 ESR

### PR DESCRIPTION
**Pull request by Mno-hime**
solaris-userland has Firefox 68 ESR: https://github.com/oracle/solaris-userland/tree/master/components/desktop/firefox. I pulled their patches here. What we need now:

1. New Rust (solaris-userland has it too).
2. Manually install `cbindgen` (a Rust crate): `cargo install --version 0.8.7 cbindgen` (this should be packaged in some way, or at least pulled to `CARGO_HOME` during the Firefox build), or as internal component of the Firefox userland component.

### CODE REVIEW

**Comment by alarcher** [comment]
@Mno-hime I can help you with this one if you need.

**Comment by Toasterson** [comment]
Made fixups and got as far compiling icu. icu updates build and are pending. https://github.com/Toasterson/oi-userland/tree/firefox68

**Comment by Toasterson** [comment]
I managed to get firefox to configure but I am stuck at building it with

```text
In file included from <built-in>:2:
In file included from /vagrant/components/web/firefox/firefox-68.6.0/media/ffvpx/libavutil_visibility.h:26:
In file included from /vagrant/components/web/firefox/firefox-68.6.0/media/ffvpx/libavutil/log.h:25:
In file included from /vagrant/components/web/firefox/firefox-68.6.0/media/ffvpx/libavutil/avutil.h:296:
In file included from /vagrant/components/web/firefox/firefox-68.6.0/media/ffvpx/libavutil/common.h:36:
/usr/clang/9.0/lib/clang/9.0.1/include/stdint.h:217:25: error: typedef redefinition with different types ('int16_t' (aka 'short') vs 'int')
typedef __int_least16_t int_fast16_t;
                        ^
/usr/include/sys/int_types.h:136:15: note: previous definition is here
typedef int                     int_fast16_t;
                                ^
In file included from <built-in>:2:
In file included from /vagrant/components/web/firefox/firefox-68.6.0/media/ffvpx/libavutil_visibility.h:26:
In file included from /vagrant/components/web/firefox/firefox-68.6.0/media/ffvpx/libavutil/log.h:25:
In file included from /vagrant/components/web/firefox/firefox-68.6.0/media/ffvpx/libavutil/avutil.h:296:
In file included from /vagrant/components/web/firefox/firefox-68.6.0/media/ffvpx/libavutil/common.h:36:
/usr/clang/9.0/lib/clang/9.0.1/include/stdint.h:218:26: error: typedef redefinition with different types ('uint16_t' (aka 'unsigned short') vs 'unsigned int')
typedef __uint_least16_t uint_fast16_t;
                         ^
/usr/include/sys/int_types.h:147:23: note: previous definition is here
typedef unsigned int            uint_fast16_t;
                                ^
In file included from <built-in>:2:
In file included from /vagrant/components/web/firefox/firefox-68.6.0/media/ffvpx/libavutil_visibility.h:26:
In file included from /vagrant/components/web/firefox/firefox-68.6.0/media/ffvpx/libavutil/log.h:25:
In file included from /vagrant/components/web/firefox/firefox-68.6.0/media/ffvpx/libavutil/avutil.h:296:
In file included from /vagrant/components/web/firefox/firefox-68.6.0/media/ffvpx/libavutil/common.h:36:
/usr/clang/9.0/lib/clang/9.0.1/include/stdint.h:224:23: error: typedef redefinition with different types ('signed char' vs 'char')
typedef __INT8_TYPE__ int8_t;
                      ^
/usr/include/sys/int_types.h:75:16: note: previous definition is here
typedef char                    int8_t;
                                ^
3 errors generated.
```

Has anybody an idea how to solve clang header conflicts?

**Comment by pyhalov** [comment]
Perhaps, just add `ifndef int8_t` and similar guards to clang headers ?

**Comment by Toasterson** [comment]
To get it building it is probably the easiest hack. But how would one package that for clang? I assume adding ifndef to the headers during building breaks clang build, As that means the definitions change for everything.

**Comment by Toasterson** [comment]
And down the rabbit hole we go. It is a header conflict between clang9 and illumos. I opened https://www.illumos.org/issues/12430 for this. We probably have to make a patch to clang where we exclude our headers using our ifndef guards and make clang aware of our header guards

**Comment by despair86** [comment]
i've been using http://www.basilisk-browser.org/ for a bit now because it's downright painless to build compared to upstream navigator for a while (and new web platform features added/reimplemented in C++ from rust etc)
can even be built 32-bit to use flash, icedtea or other plugins

**Comment by hoewweken** [comment]
Firefox 78 ESR is out on solaris-userland.
https://github.com/oracle/solaris-userland/tree/master/components/desktop/firefox

Carsten Grzemba has recently sucessfully build 68 ERS, maybe we should continue the work and get 78 running as we are already at work here..

**Comment by Toasterson** [comment]
Carsten is already building ESR 78. We should close this PR and open one for ESR 78.

**Pull request closed without merging**
