### PR TITLE
Update crypto/ca-certificates (NSS) to 3.41

### PR DESCRIPTION
**Pull request by Mno-hime**
* Updated `mk-ca-bundle.pl` to the latest code on the curl master
* Regenerated set of certificates (StartCom, WoSign, Symantec are gone)

Only `package/pkg` seems to depend on it?

### CODE REVIEW

**Comment by pyhalov** [comment]
Almost everything, relying on HTTPS or SSL depends on it. You can check if curl or wget is happy with new bundle.

**Comment by Mno-hime** [comment]
Both `curl` and `wget` say about https://www.howsmyssl.com/: "Your SSL client is Probably Okay".

**Comment by 3eka** [comment]
What about aria2 ?

**Comment by Mno-hime** [comment]
`aria2` works for me as well.

**Comment by pyhalov** [comment]
Should we merge this?

**Comment by Mno-hime** [comment]
I run it for some 5 days on my desktop, I think we can merge it.

**Pull request merged**
