### PR TITLE
objfw: Remove hacks now that clang is fixed

### PR DESCRIPTION
**Pull request by Midar**
Pending on #13974

### CODE REVIEW

**Comment by Midar** [comment]
Merged with #13974 so it can be merged in one go.

**Comment by mtelka** [comment]
> Merged with #13974 so it can be merged in one go.

Sorry, this won't work because both components would be compiled concurrently so objfw will be compiled with previous clang-17, not the one without the patch (#13974).

You need the clang-17 patch removal to be merged first, then you need to wait until new clang-17 is built, published and updated on the build server and then finally you can add the workaround removal.

**Comment by Midar** [comment]
Ah, I see. Ok, will remove.

**Comment by Midar** [comment]
Reopening.

**Comment by Midar** [comment]
clang update is live now, marking as ready for review.

**Pull request merged**
