### PR TITLE
gcc-7: bump to 7.5.0

### PR DESCRIPTION
**Pull request by alarcher**

### CODE REVIEW

**Comment by pyhalov** [comment]
1) Has test output changed?
2) Have you built illumos-gate with this GCC version?

**Comment by alarcher** [comment]
@pyhalov Hello, the testsuite is still running (usually takes a day and then I can build illumos-gate) and I need to follow-up with illumos-gcc people regarding the patchset, more updates tomorrow. So testing is still needed.

**Comment by alarcher** [comment]
@pyhalov Aside from that we should look into switching from gcc-6 to gcc-7 for userland, what is your take on that?

**Comment by pyhalov** [comment]
On what ? On this PR? Update test results and merge it if testing is fine.

**Comment by alarcher** [comment]
@pyhalov No no we should talk about the userland compiler update in another PR, just raising the question before I forget.

**Comment by alarcher** [comment]
@pyhalov illumos is now compiled with gcc 7.5 and running on the build machine.

**Comment by pyhalov** [comment]
Feel free to merge it as one commit.

**Pull request merged**
