### PR TITLE
virtualbox: update 7.0.18

### PR DESCRIPTION
**Pull request by cgrzemba**
Update Virtualbox 7.0.18 and build with gcc13

### CODE REVIEW

**Comment by 3eka** [comment]
Thanks for update... BUT

With new BE I got new VB, so tried to start VM and got this (in log):
```
00:00:01.260440 VirtualBox VM 7.0.18 r162988 solaris.amd64 (May 22 2024 16:22:46) release log
00:00:01.260442 Log opened 2024-05-23T08:36:21.863916000Z
00:00:01.260443 Build Type: release
00:00:01.260446 OS Product: SunOS
00:00:01.260447 OS Release: 5.11
00:00:01.260447 OS Version: illumos-cd9ea253fe
00:00:01.260523 DMI Product Name: To Be Filled By O.E.M.
00:00:01.260551 DMI Product Version: To Be Filled By O.E.M.
00:00:01.261471 Firmware type: BIOS
00:00:01.262097 Host RAM: 16309MB (15.9GB) total, 9856MB (9.6GB) available
00:00:01.262101 Executable: /opt/VirtualBox/amd64/VBoxHeadless
00:00:01.262102 Process ID: 3828
00:00:01.262102 Package type: SOLARIS_64BITS_GENERIC (OSE)
00:00:01.263353 Installed Extension Packs:
00:00:01.263365   Oracle VM VirtualBox Extension Pack (Version: 6.1.28 r147628; VRDE Module: VBoxVRDP; Crypto Module:  unusable because of 'VBoxExtPackVMRegister returned VERR_VERSION_MISMATCH, pReg=0000000000000000 ErrInfo='Helper version mismatch - expected 0x30000 got 0x50000'')
00:00:01.263848 Console: Machine state changed to 'Starting'
00:00:01.269062 Console: Machine state changed to 'PoweredOff'
00:00:01.270443 Power up failed (vrc=VINF_SUCCESS, hrc=NS_ERROR_FAILURE (0X80004005))
00:00:01.286330 VBoxHeadless: exiting
```

Failed (see 6.1.18 is mentioned there). No idea how to fix it.. 
Have you?

Regards.

**Comment by mtelka** [comment]
> Failed (see 6.1.18 is mentioned there). No idea how to fix it..

By uninstalling the Extension Pack?

**Comment by 3eka** [comment]
Sorry, being stupid...
```
:; ls -dlh /opt/VirtualBox/ExtensionPacks/*
drwxr-xr-x 6 root root  13 Nov 15  2021 /opt/VirtualBox/ExtensionPacks/Oracle_VM_VirtualBox_Extension_Pack
-r--r--r-- 1 root bin  67K May 23 09:15 /opt/VirtualBox/ExtensionPacks/VNC-7.0.18.vbox-extpack
```
I should check that first: seems logic was changed...

So, will try after:
`:; pfexec rm -rf /opt/VirtualBox/ExtensionPacks/Oracle_VM_VirtualBox_Extension_Pack`

Many thanks and apologies...

**Comment by 3eka** [comment]
And it looks like Extension_Pack from our pkg is not complete/broken:
```
:; cd /nobackup/tmp
:; aria2c https://download.virtualbox.org/virtualbox/7.0.18/Oracle_VM_VirtualBox_Extension_Pack-7.0.18.vbox-extpack

; ls -hal /opt/VirtualBox/ExtensionPacks/VNC-7.0.18.vbox-extpack  /nobackup/tmp/Oracle_VM_VirtualBox_Extension_Pack-7.0.18.vbox-extpack
-rw-r--r-- 1 predrag_zecevic admin 18M May  2 13:59 /nobackup/tmp/Oracle_VM_VirtualBox_Extension_Pack-7.0.18.vbox-extpack

:; file /opt/VirtualBox/ExtensionPacks/VNC-7.0.18.vbox-extpack  /nobackup/tmp/Oracle_VM_VirtualBox_Extension_Pack-7.0.18.vbox-extpack
/opt/VirtualBox/ExtensionPacks/VNC-7.0.18.vbox-extpack:                gzip compressed data, max compression, from Unix, original size modulo 2^32 245760
/nobackup/tmp/Oracle_VM_VirtualBox_Extension_Pack-7.0.18.vbox-extpack: gzip compressed data, last modified: Thu May  2 09:53:57 2024, max compression, from Unix, original size modulo 2^32 74833920

:; gzip -l /opt/VirtualBox/ExtensionPacks/VNC-7.0.18.vbox-extpack
         compressed        uncompressed  ratio uncompressed_name
              67851               67840   0.0% /opt/VirtualBox/ExtensionPacks/VNC-7.0.18.vbox-extpack
# v.s.
:; gzip -l /nobackup/tmp/Oracle_VM_VirtualBox_Extension_Pack-7.0.18.vbox-extpack
         compressed        uncompressed  ratio uncompressed_name
           18264093            74833920  75.6% /nobackup/tmp/Oracle_VM_VirtualBox_Extension_Pack-7.0.18.vbox-extpack

```

**Comment by mtelka** [comment]
Why do you think those two files are related?

**Comment by 3eka** [comment]
So, replaced one from package:
`:; pfexec VBoxManage extpack install --replace /nobackup/tmp/Oracle_VM_VirtualBox_Extension_Pack-7.0.18.vbox-extpack`
But VM still refuses to start (which is another story):
```
00:00:01.306946 VirtualBox VM 7.0.18 r162988 solaris.amd64 (May 22 2024 16:22:46) release log
00:00:01.306948 Log opened 2024-05-23T11:33:56.475765000Z
00:00:01.306949 Build Type: release
00:00:01.306952 OS Product: SunOS
00:00:01.306953 OS Release: 5.11
00:00:01.306954 OS Version: illumos-cd9ea253fe
00:00:01.307028 DMI Product Name: To Be Filled By O.E.M.
00:00:01.307056 DMI Product Version: To Be Filled By O.E.M.
00:00:01.307822 Firmware type: BIOS
00:00:01.308511 Host RAM: 16309MB (15.9GB) total, 8633MB (8.4GB) available
00:00:01.308516 Executable: /opt/VirtualBox/amd64/VBoxHeadless
00:00:01.308516 Process ID: 5579
00:00:01.308517 Package type: SOLARIS_64BITS_GENERIC (OSE)
00:00:01.309876 Installed Extension Packs:
00:00:01.309890   Oracle VM VirtualBox Extension Pack (Version: 7.0.18 r162988; VRDE Module: VBoxVRDP; Crypto Module: VBoxPuelCrypto)
00:00:01.310333 Console: Machine state changed to 'Starting'
00:00:01.313431 Console: Machine state changed to 'PoweredOff'
00:00:01.314816 Power up failed (vrc=VINF_SUCCESS, hrc=NS_ERROR_FAILURE (0X80004005))
00:00:01.329644 VBoxHeadless: exiting
```
IMHO, VirtualBox package does NOT deliver proper extpack ...

Considering new error, will check around

**Comment by 3eka** [comment]
UPDATE:
* Error above was caused by zpool holding raw zvol (VM storage) being not mounted - please ignore me for that
* I can confirm that after re-installing expack (downloaded from https://download.virtualbox.org/) for VirtulBox 7.0.18 at least for headless VMs are staring and working as before.

**Comment by 3eka** [comment]
Also, once in VM, this works (CentOS 8 guest):
```
:; bash /media/sf_VBoxCDROM/VBoxLinuxAdditions.run
Verifying archive integrity...  100%   MD5 checksums are OK. All good.
Uncompressing VirtualBox 7.0.18 Guest Additions for Linux  100%  
VirtualBox Guest Additions installer
Removing installed version 6.1.48 of VirtualBox Guest Additions...
...
VirtualBox Guest Additions: Building the modules for kernel 
4.18.0-552.3.1.el8.x86_64.
VirtualBox Guest Additions: Running kernel modules will not be replaced until 
the system is restarted or 'rcvboxadd reload' triggered
VirtualBox Guest Additions: reloading kernel modules and services
VirtualBox Guest Additions: kernel modules and services 7.0.18 r162988 reloaded
...
```
Many thanks for bringing latest VirtualBox to us !

**Pull request merged**
