### PR TITLE
Update X11 drivers

### PR DESCRIPTION
**Pull request by alarcher**
This will be updated when libs and apps are merged #2360.

### CODE REVIEW

**Comment by xen0l** [comment]
Was this already merged or why did you close it?

**Comment by alarcher** [comment]
Github closed the ticket automatically when I disabled the branch by mistake in my space.

**Comment by pyhalov** [comment]
This should be merged after xorg 1.17

**Comment by alarcher** [comment]
Queued in PR #2451 with updated branch.

**Pull request closed without merging**
