### PR TITLE
Add check 0.9.14

### PR DESCRIPTION
**Pull request by alarcher**
More unit testing for C ...

### CODE REVIEW

**Comment by 0xffea** [comment]
LGTM.

It has tests in the dir 'tests' but how to run them all?

**Comment by alarcher** [comment]
gmake check runs the tests but it seems the profiling tests take a while, I am not sure if it is a good idea to activate them.

**Comment by pyhalov** [comment]
If checks are passed, why not enable it? They run only on explicit request.

**Comment by alarcher** [comment]
Checks added.
It seems some tests that are not supposed to be executed, according to the configuration, are and fail: the system still returns 7 tests PASSED and exits normally.

**Comment by pyhalov** [comment]
Could you add some comment to makefile: like 
failed tests: a,b,c (or 14 failed tests...). So that someone who touches this component later will not be surprised about these failures?

**Comment by alarcher** [comment]
Should we instead deliver a file for components with failed tests instead of commenting in the Makefile ? Maybe providing the log of failed tests would help pinpoint issues in the long run and identify easily which components have issues by find . -type f -name "*.test.failed" for instance.
Otherwise I do as you say and I will open a ticket containing more information.

**Comment by pyhalov** [comment]
Honestly, I don't know. Perhaps, it's a topic for oi-dev ML. For now I think comment will be enough.

**Comment by alarcher** [comment]
OK. My build zone is not functional now (mount error after an update). I will update asap.

**Comment by alarcher** [comment]
Updated description of tests result.

**Pull request merged**
