### PR TITLE
Add PostgreSQL 11.1

### PR DESCRIPTION
**Pull request by pyhalov**

### CODE REVIEW

**Comment by Mno-hime** [comment]
I'll have a look tomorrow.

**Comment by Mno-hime** [comment]
Does the `test` target work for you? I get:

```make
[postgresql-11] oi:~/ws/oi-userland/components/database/postgresql-11 $ cat build/test/amd64/test-64-results
make[1]: Entering directory '/export/home/newman/ws/oi-userland/components/database/postgresql-11/build/amd64'
/usr/gnu/bin/make -C src/test/regress check
make[2]: Entering directory '/export/home/newman/ws/oi-userland/components/database/postgresql-11/build/amd64/src/test/regress'
/usr/gnu/bin/make -C ../../../src/port all
make[3]: Entering directory '/export/home/newman/ws/oi-userland/components/database/postgresql-11/build/amd64/src/port'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/export/home/newman/ws/oi-userland/components/database/postgresql-11/build/amd64/src/port'
/usr/gnu/bin/make -C ../../../src/common all
make[3]: Entering directory '/export/home/newman/ws/oi-userland/components/database/postgresql-11/build/amd64/src/common'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/export/home/newman/ws/oi-userland/components/database/postgresql-11/build/amd64/src/common'
/usr/gnu/bin/make -C ../../../contrib/spi
make[3]: Entering directory '/export/home/newman/ws/oi-userland/components/database/postgresql-11/build/amd64/contrib/spi'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/export/home/newman/ws/oi-userland/components/database/postgresql-11/build/amd64/contrib/spi'
rm -rf ./testtablespace
mkdir ./testtablespace
PATH="/export/home/newman/ws/oi-userland/components/database/postgresql-11/build/amd64/tmp_install/usr/postgres/11/bin:$PATH" LD_LIBRARY_PATH="/export/home/newman/ws/oi-userland/components/database/postgresql-11/build/amd64/tmp_install/usr/postgres/11/lib/amd64" ../../../src/test/regress/pg_regress --temp-instance=./tmp_check --inputdir=. --bindir= --dlpath=. --max-concurrent-tests=20 --schedule=./parallel_schedule
============== creating temporary instance ==============
============== initializing database system ==============

pg_regress: initdb failed
Examine /export/home/newman/ws/oi-userland/components/database/postgresql-11/build/amd64/src/test/regress/log/initdb.log for the reason.
Command was: "initdb" -D "/export/home/newman/ws/oi-userland/components/database/postgresql-11/build/amd64/src/test/regress/./tmp_check/data" --no-clean --no-sync > "/export/home/newman/ws/oi-userland/components/database/postgresql-11/build/amd64/src/test/regress/log/initdb.log" 2>&1
make[2]: *** [GNUmakefile:132: check] Error 2
make[2]: Leaving directory '/export/home/newman/ws/oi-userland/components/database/postgresql-11/build/amd64/src/test/regress'
make[1]: *** [GNUmakefile:67: check] Error 2
make[1]: Leaving directory '/export/home/newman/ws/oi-userland/components/database/postgresql-11/build/amd64'
```

`$PATH` seems to be wrong.

**Comment by pyhalov** [comment]
Works here.
Does it work for you if you add COMPONENT_TEST_ENV += PATH=$(PATH)?

**Comment by Mno-hime** [comment]
```make
PATH="/export/home/newman/ws/oi-userland/components/database/postgresql-11/build/amd64/tmp_install/usr/postgres/11/bin:$PATH" LD_LIBRARY_PATH="/export/home/newman/ws/oi-userland/components/database/postgresql-11/build/amd64/tmp_install/usr/postgres/11/lib/amd64" ../../../src/test/regress/pg_regress --temp-instance=./tmp_check --inputdir=. --bindir=     --dlpath=. --max-concurrent-tests=20  --schedule=./parallel_schedule  
============== creating temporary instance            ==============
============== initializing database system           ==============
============== starting postmaster                    ==============

pg_regress: postmaster did not respond within 60 seconds
Examine /export/home/newman/ws/oi-userland/components/database/postgresql-11/build/amd64/src/test/regress/log/postmaster.log for the reason
```
`postmaster.log`:
```
2019-01-30 07:30:52.759 CET [5755] LOG:  listening on Unix socket "/tmp/pg_regress-u2aqol/.s.PGSQL.60849"
2019-01-30 07:30:52.771 CET [5757] LOG:  database system was shut down at 2019-01-30 07:30:52 CET
2019-01-30 07:30:52.777 CET [5755] LOG:  database system is ready to accept connections
```

**Comment by Mno-hime** [comment]
That fix worked for me, thanks.

However, I see various "Undefined symbol XXX" allover the place. Like:
```
/usr/gcc/6/bin/gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -m64 -O3  -fPIC -shared -Wl,-Bsymbolic -o ltree_plpython2.so ltree_plpython.o  -L../../src/port -L../../src/common  -m64  -Wl,-R'/usr/postgres/11/lib/amd64'   -L/usr/lib -lpython2.7 -lsocket -lnsl -ldl -lm
Undefined                       first referenced
 symbol                             in file
pfree                               ltree_plpython.o
pg_detoast_datum                    ltree_plpython.o
errmsg                              ltree_plpython.o
errfinish                           ltree_plpython.o
errstart                            ltree_plpython.o
errcode                             ltree_plpython.o
ld: warning: symbol referencing errors
```
Though, the build won't fail.

**Comment by pyhalov** [comment]
They use symbolic binding and should be defined in server itself.

**Review by Mno-hime — APPROVED** [review]

**Pull request merged**
