### PR TITLE
Added opencolorio-2.1.1

### PR DESCRIPTION
**Pull request by shuryanc**
For opencolorio which needed by krita.

### CODE REVIEW

**Comment by shuryanc** [comment]
Could you merge this?

**Comment by AndWac** [comment]
Something seems to be wrong:
...
-- Configuring done
CMake Error in tests/cpu/CMakeLists.txt:
  Imported target "expat::expat" includes non-existent path

    "/usr/lib/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in src/OpenColorIO/CMakeLists.txt:
  Imported target "expat::expat" includes non-existent path

    "/usr/lib/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

**Review by Toasterson — APPROVED** [review]

**Comment by Toasterson** [comment]
Works as expected here.

**Comment by AndWac** [comment]
The build on our build server fails exactly with the error message I reported earlier.

**Comment by Toasterson** [comment]
Seems to be an expat bug https://github.com/AcademySoftwareFoundation/OpenColorIO/issues/1415

Although weird it did not happen on oibuild and only on hipster zone.

Upstream issue. https://github.com/libexpat/libexpat/issues/501

**Pull request merged**
