### PR TITLE
cryptography: add Python 3.7 and 3.9

### PR DESCRIPTION
**Pull request by balrog-nona**
It builds, install and published fine. There are no failed tests, only passed and skipped ones.

When installed locally, I tested it indirectly via `pkg` since it uses cryptography and it looks to me it worked. But since cryptography is such a crucial component, I'm happy to perform more tests if provided with some guidelines.

This PR must be merged after #6655

### CODE REVIEW

**Comment by AndWac** [comment]
Does not build here:
WARNING: The wheel package is not available.
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-4gjh2czi/cffi_ed024d7c47ad407d8eded9e33af4da1f/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-4gjh2czi/cffi_ed024d7c47ad407d8eded9e33af4da1f/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-4hm61_39
       cwd: /tmp/pip-wheel-4gjh2czi/cffi_ed024d7c47ad407d8eded9e33af4da1f/
  Complete output (12 lines):
  ld: fatal: file _configtest.o: wrong ELF class: ELFCLASS64
  ld: fatal: file processing errors. No output written to _configtest
  collect2: error: ld returned 1 exit status
  Note: will not use '__sync_synchronize()' in the C code
  ***** The above error message can be safely ignored.

  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help

  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for cffi
ERROR: Failed to build one or more wheels

**Comment by balrog-nona** [comment]
> Does not build here:
> WARNING: The wheel package is not available.
> ERROR: Command errored out with exit status 1:
> command: /usr/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-4gjh2czi/cffi_ed024d7c47ad407d8eded9e33af4da1f/setup.py'"'"'; **file**='"'"'/tmp/pip-wheel-4gjh2czi/cffi_ed024d7c47ad407d8eded9e33af4da1f/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-4hm61_39
> cwd: /tmp/pip-wheel-4gjh2czi/cffi_ed024d7c47ad407d8eded9e33af4da1f/
> Complete output (12 lines):
> ld: fatal: file _configtest.o: wrong ELF class: ELFCLASS64
> ld: fatal: file processing errors. No output written to _configtest
> collect2: error: ld returned 1 exit status
> Note: will not use '__sync_synchronize()' in the C code
> ***** The above error message can be safely ignored.
> 
> usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
> or: setup.py --help [cmd1 cmd2 ...]
> or: setup.py --help-commands
> or: setup.py cmd --help
> ## error: invalid command 'bdist_wheel'
> 
> ERROR: Failed building wheel for cffi
> ERROR: Failed to build one or more wheels

This can be because your environment is missing cffi package - I get the same error until new cffi is installed. The environment must be prepared before this PR - first build and install components from PR #6654, than from PR #6655 and after all that the change from this PR should work.

**Comment by AndWac** [comment]
After merging the dependencies we have now two conflicts. Can you resolve them?

**Comment by balrog-nona** [comment]
> After merging the dependencies we have now two conflicts. Can you resolve them?

Did it, thanks.

**Review by AndWac — APPROVED** [review]

**Pull request merged**
