### PR TITLE
Bump valgrind to 3.13.0

### PR DESCRIPTION
**Pull request by alarcher**

### CODE REVIEW

**Comment by alarcher** [comment]
Should be safe to merge.

**Comment by pyhalov** [comment]
Got build failure on gmake test:
```
/export/home/alp/srcs/tests/oi-userland/components/developer/valgrind/valgrind-3.13.0/memcheck/tests/x86-solaris/scalar.c:3:20: fatal error: scalar.h: No such file or directory
 #include "scalar.h"
                    ^
compilation terminated.
```

**Comment by pyhalov** [comment]
test results differ:
```
openexr/build/test/i86/results-32.snapshot       2017-06-23 01:08:17.457381517 +0000
@@ -17227,6 +17227,15 @@
          3x8
          2x8
          1x8
+      Inverse, AVX: 
+         8x8
+         7x8
+         6x8
+         5x8
+         4x8
+         3x8
+         2x8
+         1x8
 ok
```

**Comment by alarcher** [comment]
@pyhalov my machine does not have AVX

**Comment by pyhalov** [comment]
How can we make tests reproducible? Remove architecture-dependent results? Avoid shipping results relying on tests just pass?

**Comment by alarcher** [comment]
@pyhalov Do we talk about valgrind here or openexr? It seems you posted on the wrong PR. If it is openexr, I'll look at disabling AVX.

**Comment by pyhalov** [comment]
Yes, wrong PR

**Comment by alarcher** [comment]
@pyhalov Do you need something more on this PR?

**Pull request merged**
