### PR TITLE
python/py3c: move from library/py3c; rename package to normalize it; update to 1.4

### PR DESCRIPTION
**Pull request by mtelka**

### CODE REVIEW

**Comment by mtelka** [comment]
@klausz65, please try to build this, then uninstall `library/py3c` and install `library/python/py3c` and try to use the package.  Please report back how it works.  Thank you.

**Review by klausz65 — APPROVED** [review]
A new subversion is able to build/publish using this version of py3c

**Comment by mtelka** [comment]
Thank you, @klausz65.

**Comment by AndWac** [comment]
We seem to have a problem with the changes.
╰─➤  pkg contents -r library/python/py3c-39
PATH
usr/include/python3.9/py3c/capsulethunk.h
usr/include/python3.9/py3c/comparison.h
usr/include/python3.9/py3c/compat.h
usr/include/python3.9/py3c/fileshim.h
usr/include/python3.9/py3c/py3c.h
usr/include/python3.9/py3c/py3shims.h
usr/include/python3.9/py3c/tpflags.h
usr/lib/amd64/pkgconfig/py3c.pc
usr/lib/amd64/pkgconfig/py3c.pc-3.9

But subversion wants py3.h in /usr/include:
/export/home/andreas/oi-userland/components/developer/subversion/subversion-1.14.2/subversion/bindings/swig/python/libsvn_swig_py/swigutil_py3c.h:47:10: fatal error: py3c.h: No such file or directory
   47 | #include <py3c.h>
      |          ^~~~~~~~

**Comment by AndWac** [comment]
That was a false alarm, I didn't see the error in the subversion PR.

**Pull request merged**
