### PR TITLE
[PARKED] Update libusb-1 to 1.0.23 + fix control transfers 

### PR DESCRIPTION
**Pull request by jimklimov**
Re-posting of https://github.com/OpenIndiana/oi-userland/pull/5491 since that one got closed and can't re-open due to a requested re-basing + force-pushing of the origin.

### CODE REVIEW

**Comment by pyhalov** [comment]
@jimklimov Do you remember why this PR wasn't merged?

**Comment by pyhalov** [comment]
@OpenIndiana/developers Can someone test it?

**Comment by jimklimov** [comment]
Not sure, I think Michal wanted to review it when the changes were based differently than in original PR, but then it maybe fell between cracks. From my practice circa last year, with these changes in place, communications of NUT with USB UPSes from OmniOS and OI (same binary lib built on OI) was far more stable and reliable than with original system libs. Per comments from author of the changes, he was not satisfied with them fully, there might be some edge cases, but AFAIK there was no progress made/required since he posted that. So this change might be not perfect, but should be better than what is there :-)

**Review by pyhalov — APPROVED** [review]

**Comment by pyhalov** [comment]
I'm going to merge this in several days, but want to see more testing...

**Pull request merged**
