### PR TITLE
vlc: update to 2.2.5.1

### PR DESCRIPTION
**Pull request by pyhalov**

### CODE REVIEW

**Comment by alarcher** [comment]
You are probably missing a build dependency to Lua in REQUIRED_PACKAGES.

**Comment by pyhalov** [comment]
No, there's ```REQUIRED_PACKAGES += runtime/lua```

**Comment by alarcher** [comment]
`
Couldn't find 'usr/lib/vlc/lua/sd/metachannels.luac' in any of the specified search directories
`

runtime/lua and runtime/lua-53 are installed.

**Comment by pyhalov** [comment]
It's removed from manifest, as you can see.

**Pull request merged**
