### PR TITLE
transforms: set default openssl mediator

### PR DESCRIPTION
**Pull request by alarcher**
@AndWac Could you try this on your build server?

### CODE REVIEW

**Comment by AndWac** [comment]
Sure, what tests do you have in mind? I have created new openssl and openssl-11 packages. Shall I install them?

**Comment by alarcher** [comment]
@AndWac Yes if you rebuild and install new packages you should see the mediator set as vendor by default then if you change the version it should show as system.

**Comment by AndWac** [comment]
After installing the two new packages:
pkg mediator openssl
MEDIATOR            VER. SRC. VERSION IMPL. SRC. IMPLEMENTATION
openssl             local     1.0     vendor     openssl

pfexec pkg set-mediator -V 1.1 openssl
pkg mediator openssl
MEDIATOR            VER. SRC. VERSION IMPL. SRC. IMPLEMENTATION
openssl             local     1.1     system     openssl

**Comment by alarcher** [comment]
@AndWac Perfect thanks!

**Review by AndWac — APPROVED** [review]

**Pull request closed without merging**
