### PR TITLE
Upgrade fuse kernel module to 1.4

### PR DESCRIPTION
**Pull request by jpandre**
This is a maintenance version incorporating a bunch of fixes
(no new features)

### CODE REVIEW

**Review by AndWac — COMMENTED** [review]
You need to remove the COMPONENT_REVISION if the COMPONENT_VERSION changes.

**Review by Mno-hime — COMMENTED** [review]
Thanks @jpandre for working on this. Can you share how you tested this and what "version" (commit) of illumos you used, please?

**Comment by jpandre** [comment]
This module was left in a bad state when Oracle took over Sun, and I had to debug and fix it so that it can be used for ntfs-3g (see http://jp-andre.pagesperso-orange.fr/openindiana-ntfs-3g.html).
With it, ntfs-3g passes the 2340 tests of Posix file systems and all my regression tests (which are the same as the ones I use on Linux). However I have not tested it myself with other file systems.

**Comment by jpandre** [comment]
Oh, you also wanted the illumos versions. Not sure what you expect, but the unames of the systems I ran the tests on are :
SunOS optiplex 5.11 illumos-47b8d4b884 i86pc i386 i86pc Solaris
SunOS openindiana 5.11 illumos-22cc575561 i86pc i386 i86pc Solaris
These must be 2018 and 2017 versions.
I also ran the tests on VirtualBox using an earlier version (probably 2016) :
SunOS openindiana 5.11 illumos-93cf283 i86pc i386 i86pc Solaris.

**Pull request merged**
