### PR TITLE
Obsolete GNU TLS 2

### PR DESCRIPTION
**Pull request by Mno-hime**
Context: https://openindiana.org/pipermail/oi-dev/2016-December/005045.html

Rebuild xmlsec1 and wireshark with GNU TLS 3 and obsolete GNU TLS v2.

Now, when a component tries to build with GNU TLS and does not specify v3 paths, it fails. No miscompilations with v2 GNU TLS.

- [x] "gnutls.c: [0] (Emacs) Received alert: Handshake failed" (https://github.com/OpenIndiana/oi-userland/pull/5370#issuecomment-547559090)

### CODE REVIEW

**Review by AndWac — APPROVED** [review]

**Comment by pyhalov** [comment]
Should we put GNU TLS 3 in standard paths ? What has Solaris done?

**Comment by AndWac** [comment]
Yes, I think we should do that. It will simplify build receipes.

**Comment by Mno-hime** [comment]
> Should we put GNU TLS 3 in standard paths ? What has Solaris done?

Yes, we should. Solaris dropped GNU TLS 2 and moved GNU TLS 3 to standard path: https://github.com/oracle/solaris-userland/commit/04cd39407251ca234f64485042a9a925860a7b04.

**Comment by Mno-hime** [comment]
> > Should we put GNU TLS 3 in standard paths ? What has Solaris done?
> 
> Yes, we should. Solaris dropped GNU TLS 2 and moved GNU TLS 3 to standard path: [oracle/solaris-userland@04cd394](https://github.com/oracle/solaris-userland/commit/04cd39407251ca234f64485042a9a925860a7b04).

Done, see aa5f7bb14a4f0a9b23c90b5e1ebe1a35fa4d6429.

**Comment by Mno-hime** [comment]
Next step: Remove those special GNU TLS 3 variables from dependent components.

**Comment by Mno-hime** [comment]
GNU TLS 3 dependents to rebuild: https://github.com/OpenIndiana/oi-userland/pull/5460 (merge adter this one).

**Review by pyhalov — APPROVED** [review]

**Comment by pyhalov** [comment]
There's a tricky issue. 
After this PR we'll have inconsistent system - GNU TLS 2 has gone, but build host has dependency on it. Manual intervention will be required - remove all packages, dependent on GNU TLS v2, rebuild packages with GNU TLS v3, install removed packages.

**Comment by Mno-hime** [comment]
Thanks, that did not occur to me. Will do it like this.

**Pull request merged**
