### PR TITLE
10181 Update vte-291 to 0.54.3 

### PR DESCRIPTION
**Pull request by Mno-hime**

### CODE REVIEW

**Comment by pyhalov** [comment]
Why do we want to rebuild mate-terminal?  vte 0.54.1 should be ABI-compatible to 0.54.3.

**Comment by Mno-hime** [comment]
I couldn't find vte on ABI tracker, so just to be on safe side.

**Comment by pyhalov** [comment]
Well, it's minor update to GNOME-supplied library. It doesn't change SONAME. It should be ABI-safe.

**Comment by Mno-hime** [comment]
MATE Terminal rebuild is gone.

**Pull request merged**
