### PR TITLE
net-snmp: rebuild for perl 5.34

### PR DESCRIPTION
**Pull request by mtelka**

### CODE REVIEW

**Comment by mtelka** [comment]
I noticed the build failed.  I'll look at it.

**Comment by AndWac** [comment]
tils/net-snmp/build/manifest-i386-net-snmp-base.mangled >/jenkins/jobs/oi-userland/workspace/components/sysutils/net-snmp/build/manifest-i386-net-snmp-base.depend
Couldn't find 'amd64/sun/agent/modules/entityMib/libentity.so' needed for 'usr/lib/amd64/libentity.so' in any of the specified search directories:
        /jenkins/jobs/oi-userland/workspace/components/sysutils/net-snmp
        /jenkins/jobs/oi-userland/workspace/components/sysutils/net-snmp/build
        /jenkins/jobs/oi-userland/workspace/components/sysutils/net-snmp/build/prototype/amd64
        /jenkins/jobs/oi-userland/workspace/components/sysutils/net-snmp/build/prototype/i386
        /jenkins/jobs/oi-userland/workspace/components/sysutils/net-snmp/build/prototype/i386/mangled
        /jenkins/jobs/oi-userland/workspace/components/sysutils/net-snmp/net-snmp-5.8
Couldn't find 'i86/sun/agent/modules/entityMib/libentity.so' needed for 'usr/lib/libentity.so' in any of the specified search directories:
        /jenkins/jobs/oi-userland/workspace/components/sysutils/net-snmp
        /jenkins/jobs/oi-userland/workspace/components/sysutils/net-snmp/build
        /jenkins/jobs/oi-userland/workspace/components/sysutils/net-snmp/build/prototype/amd64
        /jenkins/jobs/oi-userland/workspace/components/sysutils/net-snmp/build/prototype/i386
        /jenkins/jobs/oi-userland/workspace/components/sysutils/net-snmp/build/prototype/i386/mangled
        /jenkins/jobs/oi-userland/workspace/components/sysutils/net-snmp/net-snmp-5.8
gmake: *** [/jenkins/jobs/oi-userland/workspace/make-rules/ips.mk:497: /jenkins/jobs/oi-userland/workspace/components/sysutils/net-snmp/build/manifest-i386-net-snmp-base.depend] Error 1

**Comment by mtelka** [comment]
Interresting.  I just built it and I do have them:

```
$ find build/ -name libentity.so -ls
    56041     46 -rwxr-xr-x   1 marcel   staff       46088 Jul 11 22:29 build/prototype/i386/usr/lib/libentity.so
    54305     57 -rwxr-xr-x   1 marcel   staff       57200 Jul 11 22:28 build/amd64/sun/agent/modules/entityMib/libentity.so
    47552     46 -rwxr-xr-x   1 marcel   staff       46088 Jul 11 22:17 build/i86/sun/agent/modules/entityMib/libentity.so
$
```

**Comment by AndWac** [comment]
I have fixed it on the build server by manually cleaning and running gmake pre-publish.

**Comment by mtelka** [comment]
The build passed now.  Great, thanks!

**Pull request merged**
