### PR TITLE
SQLITE_ENABLE_COLUMN_METADATA

### PR DESCRIPTION
**Pull request by ghost**
Trying to build gnome-db with system sqlite instead of embedded one.

### CODE REVIEW

**Review by AndWac — COMMENTED** [review]
Please set the COMPONENT_REVISION.

**Review by AndWac — COMMENTED** [review]
If firefox needs "-O2 -fno-schedule-insns2 -fno-lifetime-dse -fno-delete-null-pointer-checks"
do we need the same here?

**Comment by alarcher** [comment]
That very much depends on the code here... The problematic part in Firefox is mainly the JS code that relies on undefined behaviour. My guess is to just run the test suite... Any segfault at object destruction (in particular at exit) hints that -fno-lifetime-dse may be required.

**Comment by ghost** [comment]
sqlite test suite passed for me

**Comment by alarcher** [comment]
Are we able to add support for the testsuite so that we can compare results are version bumps?

**Comment by ghost** [comment]
That I am unsure about or beyond me right now.

**Comment by alarcher** [comment]
Apparently there is no testsuite. I guess you should just install the new sqlite package on your system and check that Firefox + other dependencies are not broken.

**Comment by ghost** [comment]
OK. Will do.

**Comment by ghost** [comment]
I am happy, actually impressed due to the number of segfaults I get building things.
Open hundreds of sites I had bookmarked, somtimes as many as sixty at a time.
No chatter from firefox run in terminal window so I could see errors.
My sites are not facebook and the like though.

**Comment by alarcher** [comment]
Out of curiosity, do you run the latest Firefox package that I pushed yesterday?

**Comment by ghost** [comment]
Yes, I am normally right with you on updated stuff. If I remember, I update firefox twice in last day.
web/browser/firefox                               52.8.0-2018.0.0.2          i--
web/data/firefox-bookmarks                        52.8.0-2018.0.0.2          i--

**Comment by alarcher** [comment]
Great thanks, sorry about the double update yesterday... -Os is broken on gcc-7 so I changed to -O2 then figured out that -O2 is broken on gcc-8 unless some optimizations are disabled. We have now the same compilation flags as other recipes out there.

So should I gather that the PR can be merged?

**Comment by ghost** [comment]
I do not see problems but I am no expert either. Works for me.

**Comment by alarcher** [comment]
@agrellum I'll let @pyhalov look at it as I do not want to break anything.

**Comment by ghost** [comment]
I will need to add the functions I need to the sqlite mapfile so they are global and not local.
They are there just not useable yet.
Will work on so more before commit.

**Comment by ghost** [comment]
I am deleting this one. I already have libgda built with the embedded one and only have a few tests failing. Anjuta builds against it and passes all tests and seems to run OK. I think I would be missing to many functions and maybe it is better security wise to leave it as it is.

**Pull request closed without merging**
