### PR TITLE
Initial commit of XCB components

### PR DESCRIPTION
**Pull request by alarcher**
Hi,
here is an initial commit of the XCB components. 
Since alanc pointed me to the xnv-gate I found that facet.devel=true is applied to a header files and xml files in:

https://hg.java.net/hg/solaris-x11~x-s12-clone/file/8028b18c77b1/pkg/manifests/x11-library-libxcb.p5m

Should I enforce the same attributes ?
Also I am not sure how to enforce build dependencies.
Thank you for your help and comments.
Best regards,

Aurelien

### CODE REVIEW

**Comment by pyhalov** [comment]
Aurélien, could you use git commit -ammend or git rebase -i to merge (squash) related commits - so that history in the main repository remains clear (for example, one commit per initial files of a new component )

**Comment by alarcher** [comment]
Hi Alexander,
I will do it, sorry I do not know git well.

**Comment by pyhalov** [comment]
You shouldn't deliver _.la files. Static libraries (_.a files) should be delivered only when they are strictly necessary (e.g. if this library is not delivered as dynamic library and there are external consumers).

**Comment by alarcher** [comment]
OK I will remove the unwanted files.

**Comment by alarcher** [comment]
I removed the static lib files and tried to clean the commits as you asked.
Thank you for pointing me to the rebase command.

**Comment by pyhalov** [comment]
Please, if components have inter-dependencies, do it in several commits. If they are delivered in one commit, server will try to build it in parallel and build will fail.

**Comment by pyhalov** [comment]
Please, if components have inter-dependencies, do it in several commits. If they are delivered in one commit, server will try to build it in parallel and build will fail.

**Comment by pyhalov** [comment]
Please, if components have inter-dependencies, do it in several commits. If they are delivered in one commit, server will try to build it in parallel and build will fail.

**Comment by pyhalov** [comment]
(and in several pull requests)

**Comment by alarcher** [comment]
Sorry I did not know about that. :S

**Pull request merged**
