### PR TITLE
Bump PNG libraries

### PR DESCRIPTION
**Pull request by alarcher**

### CODE REVIEW

**Comment by pyhalov** [comment]
Were other libpng* updated?

**Comment by jimklimov** [comment]
Recipe-wise, LGTM. Is it possible to use macros for bumping the SONAME versions, as I did in a few recipes where SO version is like component version? This could simplify maintentance in the long run.

**Comment by alarcher** [comment]
It seems other libpngs can be bumped to 1.2.58 and 1.4.21.

**Comment by pyhalov** [comment]
@alarcher : can you include their update in this PR?

**Pull request merged**
