### PR TITLE
net-snmp: move 32 bit support to separate package

### PR DESCRIPTION
**Pull request by mtelka**

### CODE REVIEW

**Comment by mtelka** [comment]
Added patch for `illumos-gate/exception_lists/packaging.deps` to make sure the build of the `illumos-gate` component succeeds.  The patch will be upstreamed later together with other similar changes in `packaging.deps`.

**Comment by AndWac** [comment]
libtool: link: (cd ".libs" && rm -f "libnetsnmpagent.so.40" && ln -s "libnetsnmpagent.so.40.2.1" "libnetsnmpagent.so.40")
libtool: link: (cd ".libs" && rm -f "libnetsnmpagent.so.40" && ln -s "libnetsnmpagent.so.40.2.1" "libnetsnmpagent.so.40")
ln: failed to create symbolic link 'libnetsnmpagent.so.40': File exists
make[1]: *** [Makefile:970: libnetsnmpagent.la] Error 1
make[1]: *** Waiting for unfinished jobs....
libtool: link: (cd ".libs" && rm -f "libnetsnmpagent.so" && ln -s "libnetsnmpagent.so.40.2.1" "libnetsnmpagent.so")
libtool: link: ( cd ".libs" && rm -f "libnetsnmpagent.la" && ln -s "../libnetsnmpagent.la" "libnetsnmpagent.la" )
: libnetsnmpagent.la -lnetsnmp -lnetsnmphelpers
make[1]: Leaving directory '/jenkins/jobs/oi-userland/workspace/components/sysutils/net-snmp/build/amd64/agent'
make: *** [Makefile:671: subdirs] Error 1
gmake: *** [/jenkins/jobs/oi-userland/workspace/make-rules/configure.mk:188: /jenkins/jobs/oi-userland/workspace/components/sysutils/net-snmp/build/amd64/.built] Fehler 2

**Comment by mtelka** [comment]
How can I reproduce that?  It works here.  Isn't there some garbage from previous builds in the `components/sysutils/net-snmp/build` dir?  IOW, was `gmake clobber` executed before the build?

**Comment by mtelka** [comment]
Also, the check passed: https://jenkins.openindiana.aurora-opencloud.org/blue/organizations/jenkins/OpenIndiana%20Organisation%2Foi-userland/detail/PR-19259/2/pipeline

**Comment by mtelka** [comment]
I even tried this:
```
env - gmake build
rm build/amd64/.built
env - gmake build
```
And it passed (surprisingly :-)).

**Pull request merged**
