### PR TITLE
nasm: update to 2.15.3

### PR DESCRIPTION
**Pull request by AndWac**
Tests run fine.
sample-manifest didn't change.

### CODE REVIEW

**Comment by pyhalov** [comment]
Have you tried to build something, requiring nasm?

**Comment by AndWac** [comment]
No, there doesn't seem to be any dependant packages, at least
pkg search -r -H -o pkg.name "depend::developer/assembler/nasm" only showed build-essential.
I just run the internal test suite.

**Comment by pyhalov** [comment]
Of course, there will be no runtime dependency, but there are build time dependencies,

**Comment by AndWac** [comment]
Ok, I successfully build x265 and libreoffice. I even installed that libreoffice and it worked like before (albeit I don't know where the assembler comes into play so I am not sure whether it really get used when I played with lo writer).

**Review by pyhalov — APPROVED** [review]

**Pull request merged**
