### PR TITLE
Bump mesa to 12.0.5

### PR DESCRIPTION
**Pull request by alarcher**
Last bug fix release in the mesa 12 series.

### CODE REVIEW

**Comment by pyhalov** [comment]
@gwr, will it affect your work on drm?

**Comment by alarcher** [comment]
@pyhalov @gwr I queued this PR because this fix could be of interest:

> Anuj Phogat (1):
>       i965: Fix GPU hang related to multiple render targets and alpha testing

No hurry, just putting it on the menu.

**Comment by gwr** [comment]
mesa appears to consume just libdrm headers, so I don't forsee any impact on the drm work.

**Comment by alarcher** [comment]
@pyhalov @gwr I intended to provide 12.0.5 (i.e keep mesa 12) in the hipster repository and move to Xorg 1.18.4 when the testing is satisfactory. In the meantime I bumped to mesa 13 on my machine to keep one testing move ahead.

**Comment by alarcher** [comment]
@pyhalov did you have the opportunity to test it?

**Comment by pyhalov** [comment]
@alarcher: shoud I? :)

**Comment by alarcher** [comment]
@pyhalov I did not have trouble on my machines but you never know ;)

**Comment by pyhalov** [comment]
Tested on VirtualBox. Compiz runs fine...

**Pull request merged**
