### PR TITLE
Add mupdf 1.11

### PR DESCRIPTION
**Pull request by alarcher**
Libraries only delivered as static.

### CODE REVIEW

**Comment by pyhalov** [comment]
Is it a build dependency for something or a separate pdf reader? If it's a separate reader, why do we need one more?

**Comment by alarcher** [comment]
The main interest is the epub reader. I tried Atril's Epub support but it fails to open samples from Adobe while MuPDF has not failed on any.

**Comment by pyhalov** [comment]
Perhaps, we could update fbreader?

**Comment by alarcher** [comment]
OK. I thought the project was dead.

**Comment by pyhalov** [comment]
It's in strange shape. New mobile versions are appearing. New desktop version is promised. Old desktop versions are 0.12.10 and 0.99.6 , but they are rather old...

**Comment by pyhalov** [comment]
@alarcher Do you have interest in updating it?

**Comment by pyhalov** [comment]
@alarcher What are we going to do with this PR? Will you update it or should I close it for now?

**Comment by alarcher** [comment]
Since nowadays I cannot ensure that I can maintain it I'll just close.

**Pull request closed without merging**
