### PR TITLE
Support OpenIndiana and Solaris in the Vagrantfile

### PR DESCRIPTION
**Pull request by cstes**
The Vagrantfile did not work on OI because the Solaris and OI platforms themselves were not dealt with in this Vagrantfile.

With this fix the VM is correctly deployed but not updated.

There still is a missing pkg update in the Vagrantfile and it currently seems to fail with:

default: pkg install: No matching version of metapackages/build-essential can be installed:
Reason:  No version matching 'require' dependency crypto/gnupg can be installed

This is due I think to the current openindiana image (box) in the vagrant cloud or to missing pkg update before the pkg install build-essential

in any case this doesn't matter for this particular commit

### CODE REVIEW

**Comment by pyhalov** [comment]
Looks good, but could we fix it all? 
For example, create new BE, upadte it, install required packages there and reboot? Will it work?

**Comment by cstes** [comment]
I added a pkg update to the Vagrantfile and that works.

However it still fails I think I have to pkg install -R into the new BE or reboot

 .... lots of messages by "vagrant up"

    default:  Actions: 22962/22969 actions (Updating modified actions)
    default:  Actions: Completed 22969 actions in 24.43 seconds.
    default:  Done
    default:  Done
    default:  Done
    default:  Done
    default: 
    default: A clone of openindiana-2021:03:02 exists and has been updated and activated.
    default: On the next boot the Boot Environment openindiana-2021:09:15 will be
    default: mounted on '/'.  Reboot when ready to switch to this updated BE.
    default: 
    default: 
    default: ---------------------------------------------------------------------------
    default: NOTE: Please review release notes posted at:
    default: 
    default: https://docs.openindiana.org/release-notes/latest-changes/
    default: ---------------------------------------------------------------------------
    default: 
    default:  Startup: Refreshing catalog 'openindiana.org' ... Done
    default: 
    default: pkg install: No matching version of metapackages/build-essential can be installed:
    default:   Reject:  pkg://openindiana.org/metapackages/build-essential@1.0-2020.0.1.22
    default:   Reason:  No version matching 'require' dependency crypto/gnupg can be installed
    default:     ----------------------------------------
    default:     Reject:  pkg://openindiana.org/crypto/gnupg@2.3.1-2020.0.1.0
    default:              pkg://openindiana.org/crypto/gnupg@2.3.2-2020.0.1.0
    default:     Reason:  This version is excluded by installed incorporation consolidation/userland/userland-incorporation@0.5.11-2020.0.1.13917
    default:     ----------------------------------------
    default: /bin/sh: git: not found [No such file or directory]
    default: make-rules/shared-macros.mk:1423: /make-rules/component.mk: No such file or directory
    default: gmake: *** No rule to make target '/make-rules/component.mk'.  Stop.
    default: Planning: Solver setup ... Startup: Refreshing catalog 'userland' ... Done
    default:  Startup: Caching catalogs ... Done
    default: VM is ready, happy contributing!

**Comment by cstes** [comment]
Perhaps after the pkg update I could use "pkg install -R build-essential" with a -R option

**Comment by pyhalov** [comment]
Yes, after updating you have to install packages to new BE, mounting it and using -R option. Don't know how reboot can be integrated in vagrant logic.

**Comment by cstes** [comment]
The best solution would be not to do a "pkg update" but rather run the "pkg update" once and update the openindiana box in the vagrant cloud.   If the image in the vagrant cloud is updated, then the pkg update must not be ran every time someone does a "vagrant up".   The openindiana/hipster box in the vagrant cloud is not recent.  That's the real problem.   For this commit - the Vagrantfile will work fine once the box is updated.

**Comment by pyhalov** [comment]
Does someone remember who updated OI image in Vagrant cloud last time? @Toasterson @xen0l ?

**Comment by AndWac** [comment]
Am 9/15/21 um 9:26 PM schrieb Alexander Pyhalov:
>
> Does someone remember who updated OI image in Vagrant cloud last time?
> @Toasterson <https://github.com/Toasterson> @xen0l
> <https://github.com/xen0l> ?
>
AFAIR it was toasterson.

**Comment by cstes** [comment]
if the image - the vagrant box - were updated, I think the Vagrantfile as is , will work.

**Review by Toasterson — APPROVED** [review]

**Comment by Toasterson** [comment]
@cstes The Problem with the uninstallable error occurs if your current box image is older than the last repository cleanup. I regenerated the boxes for OI on 1st of September. Huh.... I just had a look and it seems that Vagrant cloud has a bug in version sorting. The image from march was shown as more up to date as the one from 7 days ago...... I removed the offending images. please update boxes and test again. The current version is v202109

**Review by Toasterson — APPROVED** [review]

**Comment by Toasterson** [comment]
@cstes Cool. Whats the reason for not using prtconf -m?

**Comment by cstes** [comment]
OpenIndiana prtconf -m was a good solution but it seems Solaris does not have that switch 
[prtconf manpage](
https://docs.oracle.com/cd/E88353_01/html/E72487/prtconf-8.html#REFMAN8prtconf-8)

Regarding your work to update the OpenIndiana image in the vagrant cloud, thanks it works now !!

$vagrant box list                              
You appear to be running Vagrant outside of the official installers.
Note that the installers are what ensure that Vagrant has all required
dependencies, and Vagrant assumes that these dependencies exist. By
running outside of the installer environment, Vagrant may not function
properly. To remove this warning, install Vagrant using one of the
official packages from vagrantup.com.

openindiana/hipster (virtualbox, 20210302)


Note the ID of 20210302

I then did:

$ vagrant box remove openindiana/hipster

Removing box 'openindiana/hipster' (v20210302) with provider 'virtualbox'...

After that, the updated image was correctly fetched 

The issue may be that the new ID is v202109 so not in the same format as the box from march 2021.

Anyway this is great, thanks for updating the vagrant box at Hashicorp vagrant cloud ...

**Comment by cstes** [comment]
Basically by adding the missing /solaris/ platform this commit fixes the following error:

oi-userland$ vagrant up
Vagrant failed to initialize at a very early stage:

There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
an invalid or undefined variable.

Path: oi-userland/Vagrantfile
Line number: 57
Message: undefined method `/'

So the Vagrantfile as currently shipped by oi-userland fails on Solaris and OpenIndiana with a message "undefined method /"

this is because mem and ncpus are not defined except for Windows, Mac, Linux

**Comment by cstes** [comment]
Really cool

On OpenIndiana in oi-userland just type "vagrant up" and it provisions now a VM

   ...
   default:  Actions: Completed 39827 actions in 34.85 seconds.
    default:  Done
    default:  Done
    default:  Done
    default:  Done
    default: setup components
    default: make[1]: Entering directory '/vagrant/components'
    default: building tools...
    default: make[2]: Entering directory '/vagrant/tools'
    default: make[2]: Leaving directory '/vagrant/tools'
    default: /bin/mkdir -p /vagrant/i386/pkglint-cache
    default: make[1]: Leaving directory '/vagrant/components'
    default:  Startup: Refreshing catalog 'userland' ... Done
    default:  Startup: Caching catalogs ... Done
    default: VM is ready, happy contributing!

So it works 

$ vagrant ssh                                   
You appear to be running Vagrant outside of the official installers.
Note that the installers are what ensure that Vagrant has all required
dependencies, and Vagrant assumes that these dependencies exist. By
running outside of the installer environment, Vagrant may not function
properly. To remove this warning, install Vagrant using one of the
official packages from vagrantup.com.

The illumos Project     illumos-77161fd3d7      September 2021
vagrant@openindiana:~$ cat /etc/release 
             OpenIndiana Hipster 2021.04 (powered by illumos)
        OpenIndiana Project, part of The Illumos Foundation (C) 2010-2020
                        Use is subject to license terms.
                           Assembled 30 April 2021
vagrant@openindiana:~$ pkg list userland-incorporation
NAME (PUBLISHER)                                  VERSION                    IFO
consolidation/userland/userland-incorporation     0.5.11-2020.0.1.14408      i--
vagrant@openindiana:~$ pkg list build-essential
NAME (PUBLISHER)                                  VERSION                    IFO
metapackages/build-essential                      1.0-2020.0.1.22            i--

**Comment by cstes** [comment]
Hopefully this commit can be merged, the idea is to fix the error when you run 

"vagrant up" 

on OpenIndiana because the Vagrantfile as shipped was only supporting Linux, Mac,Windows

It seems to work fine now, thanks to the updated Vagrant box for openindiana

**Pull request merged**
