### PR TITLE
Add golang 1.9 to oi-userland

### PR DESCRIPTION
**Pull request by xen0l**
```
Couldn't find 'usr/lib/golang/1.9/test/fixedbugs/issue181.9.go' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
Couldn't find 'usr/lib/golang/1.9/test/fixedbugs/issue71.9.go' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
Couldn't find 'usr/lib/golang/1.9/test/fixedbugs/issue81.9.go' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
Couldn't find 'usr/lib/golang/1.9/test/fixedbugs/bug1.9.go' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
Couldn't find 'usr/lib/golang/1.9/test/fixedbugs/issue1.902.go' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
Couldn't find 'usr/lib/golang/1.9/test/fixedbugs/issue1.902b.go' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
Couldn't find 'usr/lib/golang/1.9/test/fixedbugs/issue1.906.go' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
Couldn't find 'usr/lib/golang/1.9/test/fixedbugs/issue1.911.go' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
Couldn't find 'usr/lib/golang/1.9/test/fixedbugs/issue1.915.go' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
Couldn't find 'usr/lib/golang/1.9/test/fixedbugs/issue1.918.go' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
Couldn't find 'usr/lib/golang/1.9/test/fixedbugs/issue1.920.dir/a.go' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
Couldn't find 'usr/lib/golang/1.9/test/fixedbugs/issue1.920.dir/b.go' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
Couldn't find 'usr/lib/golang/1.9/test/fixedbugs/issue1.920.go' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
Couldn't find 'usr/lib/golang/1.9/test/fixedbugs/issue1.925.go' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
Couldn't find 'usr/lib/golang/1.9/test/fixedbugs/issue1.926.go' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
Couldn't find 'usr/lib/golang/1.9/test/fixedbugs/issue1.944.go' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
Couldn't find 'usr/lib/golang/1.9/test/fixedbugs/issue1.945.go' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
Couldn't find 'usr/lib/golang/1.9/test/fixedbugs/issue1.947.go' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
Couldn't find 'usr/lib/golang/1.9/test/fixedbugs/issue1.948.go' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
Couldn't find 'usr/lib/golang/1.9/test/fixedbugs/issue1.949.go' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
Couldn't find 'usr/lib/golang/1.9/test/fixedbugs/issue1.958.go' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
Couldn't find 'usr/lib/golang/1.9/test/fixedbugs/issue1.961.go' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
Couldn't find 'usr/lib/golang/1.9/test/fixedbugs/issue1.975.go' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
Couldn't find 'usr/lib/golang/1.9/test/fixedbugs/issue1.977.go' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
Couldn't find 'usr/lib/golang/1.9/test/fixedbugs/issue1.985.go' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
Couldn't find 'usr/lib/golang/1.9/test/fixedbugs/issue1.987.go' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
Couldn't find 'usr/lib/golang/1.9/test/fixedbugs/issue1.988.go' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
Couldn't find 'usr/lib/golang/1.9/test/fixedbugs/issue1.994.go' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
Couldn't find 'usr/lib/golang/1.9/test/fixedbugs/issue1.999.go' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
Couldn't find 'usr/lib/golang/1.9/test/fixedbugs/issue11.90.go' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
Couldn't find 'usr/lib/golang/1.9/test/fixedbugs/issue11.99.go' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
Couldn't find 'usr/lib/golang/1.9/test/fixedbugs/issue131.9.go' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
Couldn't find 'usr/lib/golang/1.9/src/internal/trace/testdata/http_1.9_good' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
Couldn't find 'usr/lib/golang/1.9/src/internal/trace/testdata/stress_1.9_good' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
Couldn't find 'usr/lib/golang/1.9/src/internal/trace/testdata/stress_start_stop_1.9_good' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
Couldn't find 'usr/lib/golang/1.9/src/compress/gzip/issue1.937_test.go' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
Couldn't find 'usr/lib/golang/1.9/src/go/internal/gcimporter/testdata/issue1.920.go' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
Couldn't find 'usr/lib/golang/1.9/src/archive/tar/testdata/issue1.968.tar' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
Couldn't find 'usr/lib/golang/1.9/src/archive/tar/testdata/issue111.9.tar' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
Couldn't find 'usr/lib/golang/1.9/misc/cgo/test/issue1.925.go' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
Couldn't find 'usr/lib/golang/1.9/misc/cgo/test/issue1.930.go' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
Couldn't find 'usr/lib/golang/1.9/misc/cgo/test/issue201.9.go' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
Couldn't find 'usr/lib/golang/1.9/misc/cgo/errors/issue11.97a.go' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
Couldn't find 'usr/lib/golang/1.9/misc/cgo/errors/issue11.97b.go' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
Couldn't find 'usr/lib/golang/1.9/misc/cgo/errors/issue131.9.go' in any of the specified search directories:
        /export/home/xenol/code/oi-userland/components/developer/golang-19
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386
        /export/home/xenol/code/oi-userland/components/developer/golang-19/build/prototype/i386/mangled
        /export/home/xenol/code/oi-userland/components/developer/golang-19/golang-1.9
```
@Toasterson have you met with something similar while packaging go 1.8? I didn't.

### CODE REVIEW

**Comment by Toasterson** [comment]
Not updated Manifest? gmake samplemanifesit maybe looks like a package disapeared or changed paths.

**Comment by Toasterson** [comment]
Actually it is a problem with he Go source. The directory is a compile cache which generates many files which have different names per compile run. And we always need two compile runs one for the sample manifest and one for the final packaging. go 1.9 introduces go clean -cache to clean that directory

**Comment by Toasterson** [comment]
@xen0l #4132 just got merged with golang 1.10 if you still want go 1.9 additionally you can pull the changes needed from there.

**Comment by Mno-hime** [comment]
Now we have Go 1.8 and 1.10, can we close this?

**Comment by xen0l** [comment]
Yes

**Pull request closed without merging**
