### PR TITLE
glib: update to 2.62

### PR DESCRIPTION
**Pull request by pyhalov**
Depends on #5425  amd #5423 .
Needs better testing.
This also changes python used by glib tools to python3.5.

### CODE REVIEW

**Comment by Mno-hime** [comment]
I'll put it into my system to see how things play out but... should we rebuild package requiring glib2? There's a backward incompatibility in 2.59.1, see https://abi-laboratory.pro/index.php?view=timeline&l=glib.

**Comment by pyhalov** [comment]
It seems, there isn't (if we did everything correctly and haven't messed up library defines ;)). 
The ABI tracker tells us about g_slice_debug_tree_statistics(), but it was present only in debug build - `elfdump /usr/lib/libglib-2.0.so|grep g_slice_debug_tree_statistics`  shows nothing, also look at https://gitlab.gnome.org/GNOME/glib/issues/1607 .
However, there could be issue that older apps fail to build with new glib, and this should be checked.

**Comment by Mno-hime** [comment]
I see, we might get away with it :). So far looks good.

**Comment by pyhalov** [comment]
@Mno-hime Please, push your changes again, I've accidentally pushed more than I wanted.

**Comment by Mno-hime** [comment]
> @Mno-hime Please, push your changes again, I've accidentally pushed more than I wanted.

Just pushed 9355702bcb0cd55f2434ffe8092f644ac5a195a8.

**Comment by pyhalov** [comment]
Not sure, why test output differs.

**Pull request merged**
