### PR TITLE
libusb-1: update to 1.0.22

### PR DESCRIPTION
**Pull request by pyhalov**

### CODE REVIEW

**Review by Mno-hime — COMMENTED** [review]
Build requires `system/header/header-ugen` otherwise fails with:
```
libusb-1.0.22/libusb/os/sunos_usb.c:38:43: fatal error: sys/usb/clients/ugen/usb_ugen.h: No such file or directory
 #include <sys/usb/clients/ugen/usb_ugen.h>
```

**Review by Mno-hime — COMMENTED** [review]
libgphoto2 2.5.18 refused libusb-1 1.0.22:
```
checking for libusb-1.0 to use... autodetect
checking for libusb-1.0 >= 1.0.0... yes
checking for libusb_strerror... no
checking libusb.h usability... yes
checking libusb.h presence... yes
checking for libusb.h... yes
checking for function libusb_init in libusb-1.0... no
checking for libusb to use... autodetect
checking for libusb >= 0.1.5... yes
checking usb.h usability... yes
checking usb.h presence... yes
checking for usb.h... yes
checking for function usb_open in libusb... yes
checking libusb library flags... "-lusb"
checking libusb cpp flags... ""
...
  USB ports
    libusb-1.0:                    no
    libusb:                        yes
```

**Comment by pyhalov** [comment]
mtp-* examples stuck at end of data transfer

**Comment by pyhalov** [comment]
It's still slow as hell,  but at least seems to be working

**Comment by pyhalov** [comment]
@Mno-hime Please, test it with your apps. It should be the same as the old one...

**Comment by pyhalov** [comment]
'LIBUSB_DEBUG=4 gphoto2 -l' sometimes crashes with
```
fdebeea8 libusb-1.0.so.0.1.0`usbi_signal_transfer_completion+0x1a(8088988, 100, 
0, 8083420)
fdebeef8 libusb-1.0.so.0.1.0`sunos_async_callback+0x158(80889f0, 8, fdebef48, 
feec7f0d, fef59980, 0)
fdebef28 libc.so.1`notify_thread+0x37(fdf400c0, feef2700, 0, fef52000, fed40a00
, fed40a08)
fdebef48 libc.so.1`notifier+0x11(fdf400c0, c, fdebefc8, fdebef88, fe0e4240, 0)
fdebefc8 libc.so.1`tpool_worker+0x1ab(fdf400c0, 0, 0, 0)
fdebefe8 libc.so.1`_thrp_setup+0x88(fe0e4240)
fdebeff8 libc.so.1`_lwp_start(fe0e4240, 0, 0, 0, 0, 0)
```

**Comment by Mno-hime** [comment]
Tested with `gphoto2`/`libgphoto2` from my PRs, it works for me, core dumps are only when run in `gdb`. The worst part is that after every 10th `gphoto2` execution the USB stack dies on my X220:
```
usba: [ID 691482 kern.warning] WARNING: /pci@0,0/pci17aa,21da@1a (ehci0): Unrecoverable USB Hardware Error
```
But for the original report on ml we likely need https://www.illumos.org/issues/8550 as well (patch on developer ml).

**Comment by Mno-hime** [comment]
Dumps core in GDB:
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 16 (LWP 16)]
0xfe6be100 in sunos_async_callback () from /usr/lib/libusb-1.0.so.0
```
`gphoto2 -a` now exits with `0`.
Once dumped core on `gphoto2 --list-files`.

**Comment by pyhalov** [comment]
@Mno-hime Can you add gcc_OPT = -ggdb and show the stack trace?

**Comment by Mno-hime** [comment]
[bt.txt](https://github.com/OpenIndiana/oi-userland/files/2036979/bt.txt)

**Comment by pyhalov** [comment]
Do you still have this core? Can you print *tpriv in threads 19 and 21 ? I don't understand how aiocb can become 0 unless it was never initialized.

**Comment by Mno-hime** [comment]
[core.zip](https://github.com/OpenIndiana/oi-userland/files/2038167/core.zip)

**Comment by Mno-hime** [comment]
Maybe, if we are not able to fix it in it's entirety, we are better off with this PR & gphoto2/libgphoto2 PRs merged. For me it works in most cases.

**Comment by pyhalov** [comment]
OK. Don't forget to file a bug about this issue so that we remember about it.

**Comment by Mno-hime** [comment]
Thanks. Filed as https://www.illumos.org/issues/9614.

**Pull request merged**
