### PR TITLE
Add MEGAsync-4.6.3

### PR DESCRIPTION
**Pull request by shuryanc**
This is to add MEGAsync.
Not so sure the best way to create the makefile.
To sum up, it requires 
1. cloning submodule to src/MEGASync/mega
2. run autogen.sh and configure in src/MEGASync/mega
3. run qmake and lrelease in src
4. run make in src

### CODE REVIEW

**Comment by AndWac** [comment]
Does not publish here because of missing file:
pkgsend: Action payload 'LICENCE.md' was not found in any of the provided locations:

**Comment by shuryanc** [comment]
Fixed.

**Comment by AndWac** [comment]
No, still not fixed. Did you run "gmake publish" on your system?

**Comment by shuryanc** [comment]
Yes, I ran gmake publish. Still comment "missing LICENCE.md"? If yes, the remaining method I can think of is to move the license file to the package root folder.

**Comment by AndWac** [comment]
Then your gmake publish should have been failed. We only look at the packages folder (where the manifest is) and the top level source folder for a license file. If it is not there you'll need to add it to your commit.

**Comment by shuryanc** [comment]
Not sure why I was able to build it. Anyway, changed the license file to be moved to source dir and tested. Wish this time can be good.

**Comment by AndWac** [comment]
pkgsend: Action payload 'LICENCE.md' was not found in any of the provided locations:
/export/home/andreas/oi-userland/components/network/megasync/build/prototype/i386/mangled
/export/home/andreas/oi-userland/components/network/megasync/build/prototype/i386
/export/home/andreas/oi-userland/components/network/megasync/build
/export/home/andreas/oi-userland/components/network/megasync
MEGAsync-v4.6.3.0_Linux
gmake: *** [/export/home/andreas/oi-userland/make-rules/ips.mk:555: /export/home/andreas/oi-userland/components/network/megasync/build/manifest-i386-megasync.published] Error 1

**Comment by shuryanc** [comment]
Added licence.md separately to the package folder.

**Pull request merged**
