### PR TITLE
7755 library/gnu-libiconv should not deliver files to /usr/gnu/ prefix

### PR DESCRIPTION
**Pull request by pyhalov**

### CODE REVIEW

**Comment by tomww** [comment]
Could gnu-libiconv package get an automatic uninstall/retirement?
That would help to not keep a dead package.
Thank you!

**Comment by pyhalov** [comment]
It will be removed automatically.

**Comment by pyhalov** [comment]
smbclient/smbd seems to work fine, but we also have to remove all '-liconv's from pkgconfig files.

**Comment by pyhalov** [comment]
Added noincorporate attribute.

**Review by xen0l — APPROVED** [review]

**Pull request merged**
