### PR TITLE
1/4 Update MPFR to 4.0.2

### PR DESCRIPTION
**Pull request by Mno-hime**
https://abi-laboratory.pro/index.php?view=timeline&l=mpfr

This updates MPFR to 4.0.2, updated mpc to 1.1.0 (so it builds with MPFR 4), and rebuilds GAWK, which depends on MPFR.

The build should happen like this (3 and 4 are interchangeable):
1. Build new MPFR,
2. install new MPFR with `libmpfr.so.4` compat link (needed to rebuild gawk as it requires gawk to work)
3. build mpc,
4. build GAWK,
5. remove `libmpfr.so.4 compat link` compat link.

**Can the build system handle it like this automatically?**

~`tset_float128` test case fails on 32-bit (test case wasn't included before), discussing it with upstream: https://sympa.inria.fr/sympa/arc/mpfr/2019-02/msg00002.html.~

### CODE REVIEW

**Comment by alarcher** [comment]
The test failure is the reason I did not update the component earlier.
Would be nice to know the back story before merging.

On 2/2/19, Michal Nowak <notifications@github.com> wrote:
> https://abi-laboratory.pro/index.php?view=timeline&l=mpfr
>
> This updates MPFR to 4.0.2, updated mpc to 1.1.0 (so it builds with MPFR 4),
> and rebuilds GAWK, which depends on MPFR.
>
> The build should happen like this (3 and 4 are interchangeable):
> 1. Build new MPFR,
> 2. install new MPFR with `libmpfr.so.4` compat link (needed to rebuild gawk
> as it requires gawk to work)
> 3. build mpc,
> 4. build GAWK,
> 5. remove `libmpfr.so.4 compat link` compat link.
>
> Can the build system handle it like this automatically?
>
> `tset_float128` test case fails on 32-bit (test case wasn't included
> before), discussing it with upstream:
> https://sympa.inria.fr/sympa/arc/mpfr/2019-02/msg00002.html.
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/OpenIndiana/oi-userland/pull/4738
>
> -- Commit Summary --
>
>   * Update MPFR to 4.0.2
>   * Update mpc to 1.1.0
>   * Rebuild gawk with MPFR 4
>   * MPFR: Remove libmpfr.so.4 compat link
>
> -- File Changes --
>
>     M components/library/mpc/Makefile (35)
>     M components/library/mpc/manifests/sample-manifest.p5m (16)
>     M components/library/mpc/mpc.p5m (13)
>     M components/library/mpfr/Makefile (47)
>     D components/library/mpfr/Solaris/libmpfr-64.pc (10)
>     D components/library/mpfr/Solaris/libmpfr.3 (28)
>     D components/library/mpfr/Solaris/libmpfr.pc (10)
>     D components/library/mpfr/llib-lmpfr (37)
>     M components/library/mpfr/manifests/sample-manifest.p5m (20)
>     M components/library/mpfr/mpfr.p5m (20)
>     A components/library/mpfr/patches/01-add-usr-include-gmp-to-cflags.patch
> (8)
>     D components/library/mpfr/patches/mpfr-3.1.6-p1.patch (285)
>     M components/text/gawk/Makefile (30)
>
> -- Patch Links --
>
> https://github.com/OpenIndiana/oi-userland/pull/4738.patch
> https://github.com/OpenIndiana/oi-userland/pull/4738.diff
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/OpenIndiana/oi-userland/pull/4738
>


-- 
---
Praise the Caffeine embeddings

**Comment by Mno-hime** [comment]
@alarcher Upstream altered the test case for us, now it passes. PR updated.

**Comment by pyhalov** [comment]
> https://abi-laboratory.pro/index.php?view=timeline&l=mpfr
> 
> This updates MPFR to 4.0.2, updated mpc to 1.1.0 (so it builds with MPFR 4), and rebuilds GAWK, which depends on MPFR.
> 
> The build should happen like this (3 and 4 are interchangeable):
> 
>     1. Build new MPFR,
> 
>     2. install new MPFR with `libmpfr.so.4` compat link (needed to rebuild gawk as it requires gawk to work)

Should we add it to mpfr package?

**Comment by Mno-hime** [comment]
The first patch adds it only for amd64, because GAWK is 64-bit-only. You mean to have `libmpfr.so.4` link for both archs permanently? I think we don't need it for OI as deps are rebuilt?

**Comment by pyhalov** [comment]
There are two questions: 
a) Are libs compatible? If not, we should avoid creating symlinks and issue HEADS UP.
b) How are we going to update build server, if they are not compatible?

**Comment by Mno-hime** [comment]
Ad (a): I don't know. According to ABI Tracker nothing was removed, but the soname changed. What I do know is that they are compatible enough for GAWK to be rebuild with the help of temporary `libmpfr.so.4` link. GAWK needs GAWK for the configuration part (or at least that's where the GAWK build fails with updated MPFR and without the link).

Ad (b): Now the lineup is in form of commits, can redo to PRs:
* Build new MPFR (the 1st commit),
* install new MPFR with `libmpfr.so.4`, compat link included (needed to rebuild gawk as it requires gawk to work)
* build mpc,
* build GAWK,
* remove `libmpfr.so.4 compat link` compat link (4th patch)

Makes sense?

**Comment by pyhalov** [comment]
Yes.

**Comment by pyhalov** [comment]
@Mno-hime Can you split it to several PRs to build it properly on the build server?

**Comment by alarcher** [comment]
@Mno-hime Could we deal with this one to vacuum the PR queue a bit?

**Comment by Mno-hime** [comment]
I keep this in mind, but it needs to wait.

**Comment by Mno-hime** [comment]
Merge lineup:
1. mpfr: https://github.com/OpenIndiana/oi-userland/pull/4738 (this PR)
2. mpc: https://github.com/OpenIndiana/oi-userland/pull/5304
3. gawk rebuild: https://github.com/OpenIndiana/oi-userland/pull/5305
4. compat link removal: https://github.com/OpenIndiana/oi-userland/pull/5306

**Comment by alarcher** [comment]
@Mno-hime You should remove the three commits which were moved to the subsequent PRs.

**Comment by Mno-hime** [comment]
> @Mno-hime You should remove the three commits which were moved to the subsequent PRs.

Right. Thanks for noticing.

**Pull request merged**
