### PR TITLE
move stardict to desktop folder

### PR DESCRIPTION
**Pull request by AndWac**
I'm not sure this package is worth it (it's not satisfactorily working for me).
The check for additional build dependencies (via grep PKG_CHECK_MODULES configuration.ac) didn't reveal anything.

### CODE REVIEW

**Comment by AndWac** [comment]
I could update to 3.0.4 (new archive url at sf; one patch upstreamed) but that would remove stardict-editor. What do you think?

**Comment by pyhalov** [comment]
I honestly don't know, haven't used stardict for ages and have never used its editor.

**Comment by AndWac** [comment]
Ok, how to proceed? If you merge this as is nothing should be lost. Or should I close this PR and we will delete this package?

**Comment by alarcher** [comment]
@AndWac Just for information, you can update this page whenever you add/fix REQUIRED_PACKAGES: https://wiki.openindiana.org/oi/Build+dependencies

**Pull request merged**
