### PR TITLE
X 201610 Part 6: Xorg 1.18.4 and TurboVNC

### PR DESCRIPTION
**Pull request by alarcher**
NOTE: #2451 and #2971 should be merged immediately after publication of this PR on the build server.

### CODE REVIEW

**Comment by pyhalov** [comment]
This PR depends on ATI driver. It would be good to have it working. Or we should decide if we drop ATI support.

**Comment by pyhalov** [comment]
@alarcher have you tested updated Xorg with recent gfx-drm drivers? Does svcadm disable ligtdm still leads to system crash?

**Comment by pyhalov** [comment]
As for updated ATI driver, I remember suggested fixed ATI driver worked for several people, but not for me.

**Comment by alarcher** [comment]
@pyhalov My intel machine is at home with a bad internet connection, I cannot complete updates without several timeouts... I should install you new ISOs on my laptop during the vacation to update you...

**Comment by alarcher** [comment]
Updated with the xorg118 branch commits.

**Comment by pyhalov** [comment]
So, let's merge it?

**Comment by alarcher** [comment]
Let me check @gwr latest PR in gfx-drm first.
Also we need to make sure that nobody updates between the merge of Xorg and the drivers otherwise their graphical interface will be broken.

**Comment by pyhalov** [comment]
Yes, that's the usual case :)

**Pull request merged**
