### PR TITLE
gst-plugins-base1: update to 1.24.5

### PR DESCRIPTION
**Pull request by mtelka**
This needs more work since many tests fails.

### CODE REVIEW

**Comment by AndWac** [comment]
Any progress here? I have checked our actual gstreamer-plugins-base1. It has a similar number of errors in the test suite. Furthermore I have updated already a local installation and didn't experience problems (or rather different behavior) on it. So maybe this is equally good to what we already have and we can proceed with it.

**Comment by mtelka** [comment]
This PR shows that the previous number of test failures was 3, while the new number is 20.  Or, is the `results-all.master` file in git outdated?  IIRC, I didn't try to run tests for `1.22.10` so I do not know if the recorded test results are valid or not.

What are the test results you get with `1.22.10` and with `1.24.5`?

**Comment by mtelka** [comment]
The current test results in git (for version `1.22.10`) says:
```
Ok:                 120 
Expected Fail:      0   
Fail:               3   
Unexpected Pass:    0   
Skipped:            3   
Timeout:            0
```
I ran tests for version `1.22.10` and I've got this:
```
Ok:                 103 
Expected Fail:      0   
Fail:               19  
Unexpected Pass:    0   
Skipped:            3   
Timeout:            1
```
So either the `results-all.master` file is not up-to-date in git, or I'm doing something wrong, or something changed significantly so I'm getting way more failures now.

Anyway, the current test results for `1.22.10` are very similar to `1.24.5` results:
```
Ok:                 106 
Expected Fail:      0   
Fail:               20  
Unexpected Pass:    0   
Skipped:            2   
Timeout:            3
```

@AndWac, if you are getting similar results with `1.22.10` (ca 103 passed tests only), then I'm okay with merging this.  I wanted to be careful to do not introduce any regression and so I marked this as a draft...

**Comment by AndWac** [comment]
I get different results on different machines. The stability of the tests isn't great. My best results at the moment are:
1.22.10:
-Ok:                 120
+Ok:                 104
 Expected Fail:      0
-Fail:               3
+Fail:               18
 Unexpected Pass:    0
 Skipped:            3
-Timeout:            0
+Timeout:            1

And with your PR based 1.24.5 (on the same machine):
-Ok:                 106
+Ok:                 107
 Expected Fail:      0
-Fail:               20
+Fail:               19
 Unexpected Pass:    0
 Skipped:            2
 Timeout:            3

**Pull request merged**
