### PR TITLE
Bump libgsf to 1.14.41

### PR DESCRIPTION
**Pull request by ghost**
Getting ready for Gnumeric

### CODE REVIEW

**Comment by pyhalov** [comment]
I could be picky, but I think it should be 2 commits (in one PR)
1) bump libgsf
2) bump goffice

**Comment by pyhalov** [comment]
Does goffice depend on new libgsf? If so, there should be 2 PRs.

**Comment by ghost** [comment]
1 commit each libgsf, goffice, and gnumeric. Do I need PR now for goffice

**Comment by ghost** [comment]
Added PR for goffice. Hope this does it.

**Pull request merged**
