### PR TITLE
meson: bump to 0.51.1

### PR DESCRIPTION
**Pull request by alarcher**
@Mno-hime @pyhalov Now the fun begins... reinventing recipes for illumos like linker, libm, etc...

### CODE REVIEW

**Comment by alarcher** [comment]
@Mno-hime Feel free to add commits on top of that.

**Comment by Mno-hime** [comment]
@alarcher See: https://github.com/Mno-hime/oi-userland/tree/meson/components/developer/meson.

I ported pkgsrc patches (https://github.com/NetBSD/pkgsrc/commits/trunk/devel/py-meson) to 0.48. Some ported hunks are a bit naive (e.g. ` = 4`...). I also included at least one patch from https://github.com/alanc/meson/commits/solaris. We may need more of them.

Test suite gives at least some positive results.

**Comment by alarcher** [comment]
Hi, since you were added to the developer team you can now push to the
branch: we can share it to patch and test with the same changesets.
Feel free add whichever you feel is necessary and I'll test and patch
further. We can ping-pong that way.

**Comment by Mno-hime** [comment]
I see, makes sense.

**Comment by alarcher** [comment]
@Mno-hime I wanted to add you so that we can collaborate in an easier way. I usually open a [WIP] PR for tasks that are not yet finished but have progressed enough to get feedback. For example I'll open a PR for Xorg and Mesa next week to discuss updates of some patches.

**Comment by siteshwar** [comment]
@Mno-hime I am looking forward to see this getting merged. Once `meson` lands in OpenIndiana, we will be able to start building upstream ksh on it.

**Comment by chincheta0815** [comment]
What is the status of this PR?
What is specifically missing to make it worth a merge?

**Comment by chincheta0815** [comment]
I worked a little bit on meson. I mainly updated the version and updated the patches. All files are still work in progress. Some things might not be elegant, they just work...

Up to now a test throws an error (test_compiler_detection). After that the code runs into linker issues. I did not get these solved as python is hard to read for me. Maybe I am also puzzled by OI/Solaris ld...

**Comment by chincheta0815** [comment]
Latest state can be found here: https://github.com/chincheta0815/meson/tree/add.SunOS

**Comment by alarcher** [comment]
Let us iterate.

**Pull request merged**
