### PR TITLE
Bump libsamplerate to 1.0.9

### PR DESCRIPTION
**Pull request by alarcher**

### CODE REVIEW

**Review by AndWac — CHANGES_REQUESTED** [review]
Why didn't you move it to an appropriate category?
I propose to move it either to multimedia or library folder.

Regards,
Andreas

**Comment by alarcher** [comment]
That's actually why I touched the component in the first place and then I forgot ;)

**Comment by pyhalov** [comment]
Sorry, did they really changed license from GPL to BSD?

**Comment by alarcher** [comment]
Yes they did. :)

**Pull request merged**
