### PR TITLE
Update lynx to 2.8.8 and integrate Solaris Userland Gate patches

### PR DESCRIPTION
**Pull request by AndWac**
I have removed patch 01 because it seems to be integrated upstream.
The new patches 02 and 03 are unmodified taken from Solaris Userland Gate.
This time I set the IPS_COMPONENT_VERSION as mentioned by Alexander.

Regards
Andreas

### CODE REVIEW

**Comment by pyhalov** [comment]
please, merge all commits in one

**Comment by AndWac** [comment]
How so?

I am farily new to git and github. I tried "git rebase -i HEAD~3" on my branch. But that offered me only this:
pick 70e097c Update firefox to 43.0.3
pick 609f2a8 Add IPS_COMPONENT_VERSION to lynx-Makefile
pick 899bf21 Update lynx to 2.8.8 and integrate patches from Solaris Userland Gate

So I can squash 609f2a8 into 70e097c. But I doubt that this would that be correct.
So when I pick all the three then
git status gives me:
"
On branch oi/hipster
Your branch and 'origin/oi/hipster' have diverged,
and have 3 and 5 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

nothing to commit, working directory clean
"
Shall I push this to my GitHub branch and create a new pull request? I am puzzled...

Regards
Andreas

**Comment by alarcher** [comment]
First, you should create a separate branch for each "feature" for easier management of your changes.
Then, everytime you need to synchronize your branch with oi/hipster, instead of a merge do "git pull --rebase origin oi/hipster", this will put your commits on top of the stack.
Best regards

Aurelien

**Comment by AndWac** [comment]
Am 04.01.16 um 15:15 schrieb Aurélien Larcher:

> First, you should create a separate branch for each "feature" for 
> easier management of your changes.
> 
> That's what I did for lynx-2.8.8.
> 
> Then, everytime you need to synchronize your branch with oi/hipster, 
> instead of a merge do "git pull --rebase origin oi/hipster", this will 
> put your commits on top of the stack.
> 
> Ok, I will try that in future. But how to get rid of the momentary 
> situation?

Best regards
Andreas

**Comment by alarcher** [comment]
Do "git pull --rebase origin oi/hipster" on your branch, it will remove the merge commits and put your commits on top. Then you can "git rebase -i HEAD~3" to squash the last three commits.
Best regards

Aurelien

**Comment by AndWac** [comment]
I don't know whether the pull request is correct now. At least my local working directory seems to be clean:
root@oibuild:~/projects/oi-userland-work# git log --oneline
c1acee7 Update lynx to 2.8.8 and integrate patches from Solaris Userland Gate
e58e9d7 Merge pull request #1619 from alarcher/check_0.10.0
c36f90a Bump check to 0.10.0
6b14e1a Merge pull request #1617 from pyhalov/firefox
70e097c Update firefox to 43.0.3
...

**Comment by alarcher** [comment]
This looks good now.

**Pull request merged**
