### PR TITLE
Fixed fbreader for Qt5.15.3

### PR DESCRIPTION
**Pull request by shuryanc**
Original:
These are some affected packages fixed by me.
@hoewweken You may let me know if you want to push your fix here.

Updated on 4th May:
Fixed fbreader for Qt5.15.3

### CODE REVIEW

**Comment by hoewweken** [comment]
Hi! I have nothing at the moment, my build system is not ready. With a new created fresh build zone on a fresh updated (pkg refresh --full && pkg update..) global zone i get build errors with virtualbox for example, that you don't have i suppose..

`In file included from <command-line>:0:0:
/ws/code/components/sysutils/virtualbox/build/i86/src/VBox/Additions/x11/vboxvideo/VBoxVideoIPRT.h:62:10: fatal error: compiler.h: No such file or directory
 #include "compiler.h"  /* Can pull in <sdtint.h>.  Must come after xf86_ansic.h on XFree86. */
          ^~~~~~~~~~~~
compilation terminated.
kmk: [/ws/code/components/sysutils/virtualbox/build/i86/kBuild/footer-pass2-compiling-targets.kmk:272: /ws/code/components/sysutils/virtualbox/build/i86/out/solaris.x86/release/obj/vboxvideo_drv_system/pointer.o] Error 1
kmk: Exiting with status 2
gmake: [/ws/code/make-rules/configure.mk:183: /ws/code/components/sysutils/virtualbox/build/i86/.built] Error 2
`
i am sorry that i cannot help right now!

**Comment by shuryanc** [comment]
> Hi! I have nothing at the moment, my build system is not ready. With a new created fresh build zone on a fresh updated (pkg refresh --full && pkg update..) global zone i get build errors with virtualbox for example, that you don't have i suppose..
> 
> `In file included from <command-line>:0:0: /ws/code/components/sysutils/virtualbox/build/i86/src/VBox/Additions/x11/vboxvideo/VBoxVideoIPRT.h:62:10: fatal error: compiler.h: No such file or directory #include "compiler.h" /* Can pull in <sdtint.h>. Must come after xf86_ansic.h on XFree86. */ ^~~~~~~~~~~~ compilation terminated. kmk: [/ws/code/components/sysutils/virtualbox/build/i86/kBuild/footer-pass2-compiling-targets.kmk:272: /ws/code/components/sysutils/virtualbox/build/i86/out/solaris.x86/release/obj/vboxvideo_drv_system/pointer.o] Error 1 kmk: Exiting with status 2 gmake: [/ws/code/make-rules/configure.mk:183: /ws/code/components/sysutils/virtualbox/build/i86/.built] Error 2 ` i am sorry that i cannot help right now!

Nevermind, I'll fix the remaining packages.

**Comment by AndWac** [comment]
You don't need to have all your changes in a single commit. In fact, it's better to have one commit per package. This way you can easily cherry-pick commits if needed.

**Comment by alarcher** [comment]
This probably means that QT5_LIBDIR and QT5_BINDIR macros should be defined in shared-macros.mk.

**Comment by shuryanc** [comment]
> This probably means that QT5_LIBDIR and QT5_BINDIR macros should be defined in shared-macros.mk.

Probably. Everytime the QT is upgraded, all qt affected packages have to change their qt path to the new version, which is a nightmare to maintain (especially for KDE related stuff that I was recently working on).

**Comment by shuryanc** [comment]
FYI, for qtcreator, will upgrade it to latest version to fit qt5.15

**Pull request merged**
