### PR TITLE
transforms/defaults: set perl mediator priority for runtime/perl pack…

### PR DESCRIPTION
**Pull request by mtelka**
…ages only

### CODE REVIEW

**Comment by Toasterson** [comment]
Do we have other `link mediator=perl mediator-version=5.36` actions that got affected? I only see normal updates here. If we need to update more packages we will need Revision bumps as this only takes affect for rebuilt packages.

**Comment by mtelka** [comment]
> Do we have other `link mediator=perl mediator-version=5.36` actions that got affected? I only see normal updates here. If we need to update more packages we will need Revision bumps as this only takes affect for rebuilt packages.

All perl related packages (those that deliver versioned man pages or binaries for perl; so usually perl modules) that were (re)built after 60713aad6 (merged on  2022-08-13) are affected (they have `mediator-priority=vendor` but they shouldn't).  Fortunately, this is currently harmless and would cause a problem only in a case when we would try to downgrade our default perl (which we do not plan to).  For example, if we would like to switch back to default perl 5.34 now, we would need to rebuild all affected packages to switch to perl 5.34 successfully.

Since this is harmless, there is no need to rebuild affected packages right now.  They will be rebuilt later either during their upgrade to their new version,  or after we integrate new perl major version.

**Comment by alarcher** [comment]
@mtelka Let me know when you would like this PR to be merged.

**Comment by Toasterson** [comment]
Thanks for the explanation. Merging now.

**Pull request merged**
