### PR TITLE
Update simplejson to 3.8.2

### PR DESCRIPTION
**Pull request by xen0l**

### CODE REVIEW

**Comment by pyhalov** [comment]
why not 3.8.2?

**Comment by pyhalov** [comment]
@danmcd : did you have issues with IPS and  latest simplejson?

**Comment by xen0l** [comment]
I bumped it to 3.8.2 as can be found in omnios.

**Comment by danmcd** [comment]
https://github.com/omniti-labs/omnios-build/tree/r151018/build/python26-simplejson

I've heard no complaints so far, and the pkg5 suite passed.  When you screw with these python things, running pkg5 is a good smoke test.

**Pull request merged**
