### PR TITLE
python/ansible-core: update to 2.15.0

### PR DESCRIPTION
**Pull request by mtelka**

### CODE REVIEW

**Comment by 3eka** [comment]
Hi @mtelka ,

how it is complicated to add vim ansible syntax? Maybe as separate package as well...
RedHat/CentOS has `vim-ansible` package for that (from EPEL repository).

Regards.

**Comment by mtelka** [comment]
@3eka where is source for vim-ansible?

**Comment by 3eka** [comment]
@mtelka 
I guess this one: https://github.com/pearofducks/ansible-vim/releases/tag/3.2
and
https://src.fedoraproject.org/rpms/vim-ansible/blob/rawhide/f/vim-ansible.spec

**Comment by mtelka** [comment]
No idea how easy or hard packaging of vim-ansible is.  Sorry, I'm not interested to do that work.

**Pull request merged**
