### PR TITLE
/usr/bin/compiz fails to fallback to metacity when $COMPIZ_BIN fails

### PR DESCRIPTION
**Pull request by olbohlen**
since we exec $COMPIZ_BIN, the || abort_with_metacity command will never be called.

### CODE REVIEW

**Comment by pyhalov** [comment]
@olbohlen : I'm going to bug you :)
1) Bump COMPONENT_REVISION
2) Merge all dozen of commits in one (I want to see ONE commit in PR)
3) As it's not so evident issue when unkown, I'd left some reference in bug tracker (perhaps the same as you left in PR) and used standard commit message: 'ISSUE_NUMBER Issue title'.
4) And now it's not mergable - needs rebasing on oi/hipster HEAD.

**Comment by olbohlen** [comment]
I will redo from start :)

**Comment by pyhalov** [comment]
any progress here?

**Comment by olbohlen** [comment]
I'm currently improving my git skills ;)

**Comment by olbohlen** [comment]
I'll create a new (clean) one.

**Pull request closed without merging**
