### PR TITLE
9705 ntp 4.2.8p12 (& sync with solaris-userland)

### PR DESCRIPTION
**Pull request by Mno-hime**
Changes: https://www.eecis.udel.edu/~ntp/ntp_spool/ntp4/ntp-4.2/NEWS

oracle/solaris-userland@df553ba
oracle/solaris-userland@5d10b3d

Following three tests are now ignored, due to CMAC not being set
properly (added via http://bugs.ntp.org/show_bug.cgi?id=3471):
```
crypto.c:111:test_MakeCMac:IGNORE: OpenSSL not found, skipping...
crypto.c:202:test_VerifyCMAC:IGNORE: OpenSSL not found, skipping...
packetProcessing.c:488:test_CorrectAuthenticatedPacketCMAC:IGNORE: OpenSSL CMAC not used, skipping...
```

### CODE REVIEW

**Comment by pyhalov** [comment]
Please, convert patches to unified diff format

**Comment by Mno-hime** [comment]
Converted.

**Comment by pyhalov** [comment]
Patches are incorrect - 
oi-userland/components/network/ntp/ntp-4.2.8p11 --strip=0 --backup --version-control=numbered < patches/30-zsavewarn.patch
patching file sntp/libopts/save.c
Reversed (or previously applied) patch detected!  Assume -R? [n]

**Comment by Mno-hime** [comment]
Sorry, should work by now.

**Comment by pyhalov** [comment]
Couldn't fix tests in this branch (one result is not reproducible - it likely depends on time zone), so merged https://github.com/OpenIndiana/oi-userland/pull/4409 instead.

**Comment by Mno-hime** [comment]
Cool, fine with me.

**Pull request closed without merging**
