### PR TITLE
Freeciv

### PR DESCRIPTION
**Pull request by jakegoerzen**
This is an update of Freeciv to version 3.0.0.

### CODE REVIEW

**Comment by AndWac** [comment]
Please squash your commits and probably remove or change the 2nd commit message.

**Comment by AndWac** [comment]
Do you need help squashing the commits?

**Comment by jakegoerzen** [comment]
I might need help squashing.  I also have a patch that I want to add (or perhaps get accepted upstream):

https://github.com/jakegoerzen/freeciv/commit/683996bf0bd9521444d267836bf94c650b75848d 

Starting with Freeciv version 3.0.0 IPv6 is required unless --enable-ipv6=test is set which restores previous version behavior.  This patch allows building with IPv6 on Solaris/Illumos.  I've used the same patch to build the OpenCSW packages.

**Comment by AndWac** [comment]
With squashing the commits you'll change the git history. Typically we only want a single commit per package (a PR may contain commits for more than one package) with a single commit message. Intermediate steps and fixes usually don't belong to the history. The final cleanup is called "squashing the commits". You can find several guides for it, eg. https://gitbetter.substack.com/p/how-to-squash-git-commits

**Comment by jakegoerzen** [comment]
Closing this PR since 3.0.1 is out.  I'll resubmit with newer version.

**Pull request closed without merging**
