### PR TITLE
Obsolete library/python/numpy{,-27}

### PR DESCRIPTION
**Pull request by mtelka**
No package depends on `numpy` and/or `numpy-27` so we can safely obsolete them. Please note python 2.7 is no longer supported for almost three years now.

### CODE REVIEW

**Comment by alarcher** [comment]
@mtelka @AndWac Unfortunately I use this package... Numpy is used by numericians as standalone, therefore no consumer in userland does not mean no consumer at all.

**Comment by mtelka** [comment]
> @mtelka @AndWac Unfortunately I use this package... Numpy is used by numericians as standalone, therefore no consumer in userland does not mean no consumer at all.

Ok.  Understood.  Sorry for that.  Please create a PR to build numpy for python 3.7/3.9.

**Comment by alarcher** [comment]
> > @mtelka @AndWac Unfortunately I use this package... Numpy is used by numericians as standalone, therefore no consumer in userland does not mean no consumer at all.
> 
> Ok. Understood. Sorry for that. Please create a PR to build numpy for python 3.7/3.9.

I have had the update to a more recent version in the pipeline for while for zero spare time to run and check the tests. I'll look into it.

**Comment by mtelka** [comment]
@alarcher FYI: https://github.com/numpy/numpy/issues/25366
Once that is resolved we can add `numpy` back.

**Comment by alarcher** [comment]
> @alarcher FYI: [numpy/numpy#25366](https://github.com/numpy/numpy/issues/25366) Once that is resolved we can add `numpy` back.

No problem thanks for the information :)

**Comment by mtelka** [comment]
Numpy is back via #16549.

**Pull request merged**
