### PR TITLE
Gstreamer plugins 1.12.2

### PR DESCRIPTION
**Pull request by alarcher**
Should check the removal of some plugins in gst-plugins-good.

### CODE REVIEW

**Comment by pyhalov** [comment]
What is the status of this PR?

**Comment by alarcher** [comment]
@pyhalov I use the packages on my workstation without issues, so it is a matter of getting confirmation from other testers.

**Comment by pyhalov** [comment]
It's matter of getting other testers. Does dependent software build fine? I'd merged this and got some testers until October.

**Comment by xen0l** [comment]
@pyhalov can we merge?

**Pull request merged**
