### PR TITLE
Update VirtualBox to 6.0.8

### PR DESCRIPTION
**Pull request by Mno-hime**
**Testing**

* Started OpenIndiana Live ISO image, Fedora & Ubuntu VMs

### CODE REVIEW

**Comment by timmooney** [comment]
I have a pending fix for shared-folder support in the virtualbox-additions package, my changes had been against 6.0.6.  Should I rework for 6.0.8, or open a pull request for 6.0.6.1?

**Comment by Mno-hime** [comment]
@timmooney Put a patch somewhere (here in comments or a branch in your oi-userland fork) and I try to merge it to this PR.

**Comment by timmooney** [comment]
This patch fixes the ability for an OI guest to mount a shared folder that has been shared from the host.  The patch just fixes the name that the 'vboxfsmount' utility gets installed as.  The OI mount command is looking for it as `/etc/fs/vboxfs/mount`, not `/etc/fs/vboxfs/vboxfsmount`.

I cut out the part of the patch to the Makefile that was updating COMPONENT_REVISION, I think it should still apply, but if not let me know and I'll get you the patch a different way.

```
diff --git a/components/sysutils/virtualbox/Makefile b/components/sysutils/virtualbox/Makefile
index 82512e018..37dac4d12 100644
--- a/components/sysutils/virtualbox/Makefile
+++ b/components/sysutils/virtualbox/Makefile
@@ -196,7 +197,7 @@ $(INSTALL_ADDITIONS):       $(INSTALL_64)
        cp $(VBOX_BINDIR)/vboxservice.xml $(PROTO_DIR)/var/svc/manifest/application/virtualbox
        cp $(VBOX_BINDIR)/vboxmslnk.xml $(PROTO_DIR)/var/svc/manifest/application/virtualbox
        $(MKDIR) $(PROTO_DIR)/etc/fs/vboxfs
-       cp $(VBOX_BINDIR)/vboxfsmount $(PROTO_DIR)/etc/fs/vboxfs
+       cp $(VBOX_BINDIR)/vboxfsmount $(PROTO_DIR)/etc/fs/vboxfs/mount
        $(MKDIR) $(PROTO_DIR)/etc/xdg/autostart
        cp $(VBOX_BINDIR)/vboxclient.desktop $(PROTO_DIR)/etc/xdg/autostart
        $(MKDIR) $(PROTO_DIR)/$(X11_SERVERDRV_DIR)
diff --git a/components/sysutils/virtualbox/virtualbox-additions.p5m b/components/sysutils/virtualbox/virtualbox-additions.p5m
index bcc371838..b8d384517 100644
--- a/components/sysutils/virtualbox/virtualbox-additions.p5m
+++ b/components/sysutils/virtualbox/virtualbox-additions.p5m
@@ -31,7 +31,7 @@ group gid=59 groupname=vboxsf
 # We can reconsider later and deliver vboxvideo_drv.so from VirtualBox sources
 depend type=require fmri=x11/server/xorg/driver/xorg-video-vboxvideo

-file path=etc/fs/vboxfs/vboxfsmount owner=root group=bin mode=0555
+file path=etc/fs/vboxfs/mount owner=root group=bin mode=0555
 file path=etc/xdg/autostart/vboxclient.desktop
 file path=lib/opengl/ogl_select/vbox_vendor_select mode=0555
 file path=usr/bin/VBoxClient
diff --git a/components/sysutils/virtualbox/virtualbox.p5m b/components/sysutils/virtualbox/virtualbox.p5m
index 17e5d9069..3bb0e2ff3 100644
--- a/components/sysutils/virtualbox/virtualbox.p5m
+++ b/components/sysutils/virtualbox/virtualbox.p5m
@@ -49,7 +49,7 @@ link path=opt/VirtualBox/64 target=$(MACH64)

 #file path=autoresponse
 #file path=checkinstall.sh
-#file path=etc/fs/vboxfs/vboxfsmount
+#file path=etc/fs/vboxfs/mount
 file path=etc/hostname.vboxnet0
 #file path=makepackage.sh
 file path=opt/VirtualBox/$(MACH64)/DbgPlugInDiggers.so
```

**Comment by Mno-hime** [comment]
Thanks @timmooney, shared folders now work for me.

**Pull request merged**
