### PR TITLE
Updated Protobuf to 3.5.1

### PR DESCRIPTION
**Pull request by Toasterson**
Notes: I have no machine to test SPARC compilation thus removing the blocking Patch for Now. @alarcher If you think it is still needed feel free to add.

Also some Libraries protobuf now depends are still 32bit only thus 64bit compilation fails disabled for now.

I have successfully compiled libArcus with this

### CODE REVIEW

**Comment by alarcher** [comment]
@Toasterson Any dependency that we should test rebuild with the new version?

**Comment by Toasterson** [comment]
I have tested a new Package libArcus. I have no clue what else uses protobuf. Any idea how to find out what does?

**Comment by alarcher** [comment]
@Toasterson 

helios> pkg search -r -o pkg.name "depend:require:library/c++/protobuf"
PKG.NAME
service/network/dns/powerdns-recursor
desktop/compiz/library/libcompizconfig
service/network/mosh

**Comment by Toasterson** [comment]
All those three compile. Do you have any use case for one of them? Or do you think compiling is enough?

**Comment by alarcher** [comment]
@Toasterson Should at least check that powerdns works as expected. Possibly just check that the testsuite is fine.

**Comment by Toasterson** [comment]
There does not seem to be a testsuite and I have no idea/time to configure a power-dns recursor

**Pull request merged**
