### PR TITLE
Update rust to 1.31.1

### PR DESCRIPTION
**Pull request by Mno-hime**
Can build Firefox 60 and such Firefox works.

Synced with pkgsrc.

Had to add `transform` to get rid of path-related issues on publish. Not sure if that is entirely correct.

### CODE REVIEW

**Review by pyhalov — APPROVED** [review]

**Comment by pyhalov** [comment]
<pre>
Source /export/archives/rust-1.31.0-x86_64-sun-solaris.tar.gz... not found, skipping file copy
Source https://us-east.manta.joyent.com/pkgsrc/public/pkg-bootstraps/rust-1.31.0-x86_64-sun-solaris.tar.gz... 
    downloading... 
    validating signature... skipping (no signature URL)
    validating hash... CRC check failed 0x5f80d089 != 0xff9de83L corruption detected
    expected: sha256:f083836b0d596814386c8bfff3be9b35e3ae9561148c2fd68afa45de7ca4f768
    actual:   sha256:81f306ea9ec8dc3347fe509f1ab927c4f00a85e06f70a826bcfaa1c05008997b
    payload:  sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
</pre>

**Review by pyhalov — CHANGES_REQUESTED** [review]
It seems bootstrap archive checksum is incorrect.

**Comment by Mno-hime** [comment]
I don't see the checksum problem, my `rust-1.31.0-x86_64-sun-solaris.tar.gz` has `f083836b0d596814386c8bfff3be9b35e3ae9561148c2fd68afa45de7ca4f768`.

See in your output:
>     validating hash... CRC check failed 0x5f80d089 != 0xff9de83L corruption detected
Maybe it wasn't downloaded correctly/completely in your case?

**Comment by pyhalov** [comment]
Should we merge this or will we bump directly to 1.32?

**Pull request merged**
