### PR TITLE
jenkins-core-weekly: move to openjdk11

### PR DESCRIPTION
**Pull request by gounthar**
Weekly versions of Jenkins will need JDK11 starting from June

### CODE REVIEW

**Review by AndWac — COMMENTED** [review]
This doesn't work as you expect it. You have only changed the automatically generated dependencies as the comment in front of your change states.
You'll need to teach the build to find the new JDK version and then regenerate the dependencies with
gmake REQUIRED_PACKAGES
and finally update the package's meta data file:
gmake update-metadata
Now the pkg5 file should be dirty and needs to be added to the commit.
Furthermore, with every change in the package we need either an incremented COMPONENT_VERSION or an incremented COMPONENT_REVISION. Otherwise the package won't get deployed for existing users.

**Comment by gounthar** [comment]
Thanks a lot @AndWac, it's my first time with OpenIndiana.
I will see if I can modify my proposal accordingly.

**Comment by gounthar** [comment]
Unfortunately, I have an [issue](https://www.illumos.org/issues/14708) with rebuilding.

**Comment by AndWac** [comment]
I have fixed the download issue.

**Comment by gounthar** [comment]
Thank you. Let me retry that.

**Comment by gounthar** [comment]
I unfortunately have another error:

```bash
Source /export/home/gounthar/oi-userland/archives/rrdtool-1.7.2.tar.gz... not found, skipping file copy
Source http://oss.oetiker.ch/rrdtool/pub/rrdtool-1.7.2.tar.gz...
    downloading...
    validating signature... skipping (no signature URL)
    validating hash... Not a gzipped file (b'<!') corruption detected
    expected: sha256:a199faeb7eff7cafc46fac253e682d833d08932f3db93a550a4a5af180ca58db
    actual:   sha256:88dcddf2a92b9dc9243e929340fdc6f3431b779e22438093d7a31a400f1c3909
    payload:  sha256:

WARN: Removing the corrupt downloaded file
Source http://dlc.openindiana.org/oi-userland/source-archives/rrdtool-1.7.2.tar.gz...
    downloading... I/O Error: Can't open url http://dlc.openindiana.org/oi-userland/source-archives/rrdtool-1.7.2.tar.gz:
HTTP Error 404: Not Found
failed
gmake[1]: *** [/export/home/gounthar/oi-userland/make-rules/prep-download.mk:80 : /export/home/gounthar/oi-userland/archives/rrdtool-1.7.2.tar.gz] Erreur 1
gmake: *** [Makefile:183 : image/rrdtool.nosetup] Erreur 2
```

**Comment by 3eka** [comment]
On the site https://oss.oetiker.ch/rrdtool/pub/ we see:
RRDtool Downloads moved to GitHub!

So, this is proper place for source file(s): 
https://github.com/oetiker/rrdtool-1.x/releases. You have to update 
building script.

Hope that helps a bit.
Regards.

**Comment by gounthar** [comment]
Ok, let me try something.
Thanks for your help. 🙏 
Corrected, thank you.

**Comment by gounthar** [comment]
I still have errors when publishing:

```bash
gmake publish
/usr/bin/pkgmogrify -D PERL_ARCH=i86pc-solaris-64int -D PERL_VERSION=5.22 -D PG_VERSION=12 -D PG_VERNUM=12 -D PG_BASEPKG=database/postgres-12 -D MYSQL_VERSION=10.1 -D MYSQL_VERNUM=101 -D MYSQL_BASEPKG=database/mariadb-101 -D IPS_COMPONENT_RE_VERSION=2\\.349 -D COMPONENT_RE_VERSION=2\\.349 -D sparc_ONLY=# -D sparc_EXCL= -D i386_ONLY= -D i386_EXCL=# -D PYTHON_2.7_ONLY=# -D PYTHON_2.7_EXCL= -D PYTHON_32_ONLY= -D COMPONENT_CLASSIFICATION="org.opensolaris.category.2008:Development/Java" -D PY3_ABI3_NAMING="#" -D PY3_CPYTHON_NAMING="" -D ARC_CASE="" -D TPNO="" -D MACH="i386" -D MACH32="i86" -D MACH64="amd64" -D BUILD_VERSION="5.11-2022.0.0.1" -D OS_VERSION="5.11" -D PKG_SOLARIS_VERSION="5.11" -D GNU_TRIPLET="i386-pc-solaris2.11" -D CONSOLIDATION="userland" -D COMPONENT_VERSION="2.349" -D IPS_COMPONENT_VERSION="2.349" -D HUMAN_VERSION="2.349" -D COMPONENT_ARCHIVE_URL="https://get.jenkins.io/war/2.349/jenkins.war" -D COMPONENT_PROJECT_URL="https://jenkins.io/changelog/" -D COMPONENT_NAME="jenkins" -D COMPONENT_FMRI="developer/jenkins-core-weekly" -D COMPONENT_LICENSE_FILE="jenkins.license" -D COMPONENT_SUMMARY="Jenkins is a Java-based CI automation server" -D COMPONENT_DESCRIPTION="" -D COMPONENT_LICENSE="MIT" -D HG_REPO="" -D HG_REV="" -D HG_URL="" -D COMPONENT_HG_URL="" -D COMPONENT_HG_REV="" -D GIT_COMMIT_ID="" -D GIT_REPO="" -D GIT_TAG="" -D PUBLISHER="userland" -D PUBLISHER_LOCALIZABLE="userland-localizable" -D USERLAND_GIT_REMOTE="https://github.com/gounthar/oi-userland.git" -D USERLAND_GIT_BRANCH="move-to-jdk11" -D USERLAND_GIT_REV="be544ea1e8c404172a89ff57bc309ed8649057b0" jenkins-core-weekly.p5m \
        /export/home/gounthar/oi-userland/transforms/license-changes /export/home/gounthar/oi-userland/transforms/variant-cleanup /export/home/gounthar/oi-userland/transforms/autopyc /export/home/gounthar/oi-userland/transforms/defaults /export/home/gounthar/oi-userland/transforms/actuators /export/home/gounthar/oi-userland/transforms/devel /export/home/gounthar/oi-userland/transforms/docs /export/home/gounthar/oi-userland/transforms/locale /export/home/gounthar/oi-userland/transforms/python-3-soabi /export/home/gounthar/oi-userland/transforms/python-3-no-32bit /export/home/gounthar/oi-userland/transforms/libtool-drop /export/home/gounthar/oi-userland/transforms/ignore-libs /export/home/gounthar/oi-userland/transforms/ignore-gcc-usr-lib /export/home/gounthar/oi-userland/transforms/publish-cleanup | \
        sed -e '/^$/d' -e '/^#.*$/d' | uniq >/export/home/gounthar/oi-userland/components/developer/jenkins-core-weekly/build/manifest-i386-jenkins-core-weekly.mogrified
/export/home/gounthar/oi-userland/tools/userland-mangler -D /export/home/gounthar/oi-userland/components/developer/jenkins-core-weekly/build/prototype/i386/mangled -d /export/home/gounthar/oi-userland/components/developer/jenkins-core-weekly/build/prototype/i386/mangled -d /export/home/gounthar/oi-userland/components/developer/jenkins-core-weekly/build/prototype/i386 -d /export/home/gounthar/oi-userland/components/developer/jenkins-core-weekly/build -d /export/home/gounthar/oi-userland/components/developer/jenkins-core-weekly -d jenkins-2.349 -m /export/home/gounthar/oi-userland/components/developer/jenkins-core-weekly/build/manifest-i386-jenkins-core-weekly.mogrified >/export/home/gounthar/oi-userland/components/developer/jenkins-core-weekly/build/manifest-i386-jenkins-core-weekly.mangled
/usr/bin/pkgdepend generate -m -d /export/home/gounthar/oi-userland/components/developer/jenkins-core-weekly/build/prototype/i386/mangled -d /export/home/gounthar/oi-userland/components/developer/jenkins-core-weekly/build/prototype/i386 -d /export/home/gounthar/oi-userland/components/developer/jenkins-core-weekly/build -d /export/home/gounthar/oi-userland/components/developer/jenkins-core-weekly -d jenkins-2.349 /export/home/gounthar/oi-userland/components/developer/jenkins-core-weekly/build/manifest-i386-jenkins-core-weekly.mangled >/export/home/gounthar/oi-userland/components/developer/jenkins-core-weekly/build/manifest-i386-jenkins-core-weekly.depend
/usr/bin/pkgdepend resolve -e /export/home/gounthar/oi-userland/components/developer/jenkins-core-weekly/build/resolve.deps -m /export/home/gounthar/oi-userland/components/developer/jenkins-core-weekly/build/manifest-i386-jenkins-core-weekly.depend
/export/home/gounthar/oi-userland/components/developer/jenkins-core-weekly/build/manifest-i386-jenkins-core-weekly.depend has unresolved dependency '
    depend type=require fmri=__TBD pkg.debug.depend.file=usr/bin/java'.
gmake: *** [/export/home/gounthar/oi-userland/make-rules/ips.mk:503 : /export/home/gounthar/oi-userland/components/developer/jenkins-core-weekly/build/.resolved-i386] Erreur 1
```

Could it be because of the availability of `openJDK11` for some platforms?

**Comment by AndWac** [comment]
No, you are doing it wrong. As I wrote before: manually changing REQUIRED_PACKAGES is not how to change the dependency. Most dependencies can be automatically detected by running "gmake REQUIRED_PACKAGES". This changes the Makefile by adding, changing, or deleting lines with REQUIRED_PACKAGES += ...
It prepends those lines with a comment stating it: "# Auto-generated dependencies". It is doing this by analysing the formerly built executables and libraries. You should only add more such lines with packages it couldn't detect properly (eg. because scripting languages like perl or python dynamically import packages).
What you really need to work out is to teach the package to use openjdk11 instead of openjdk8. At the moment openjdk8 is our default java runtime. You can check this by running "pkg mediator" and look for "java". The mediated version is typically found when not being told otherwise. How to tell to use a different version? That depends on the package to build. Most of the times it's sufficient to use the appropriate CONFIGURE_OPTIONS += ... settings in the Makefile.
Alas it might be more difficult for this package or even impossible (see the end of my explanations) as here we only fetch and deploy an archive (war). Probably it is possible here with manipulating the environment (eg. INSTALL_ENV).
You can always look for examples in other existing packages, eg. with
cd components
find . -name Makefile -exec grep CONFIGURE_OPTIONS {} \\; -print
This will list you Makefiles where configure options have been used (change the search text in order to find ENV manipulation). You need to find the correct one for jenkins.
Probably this isn't possible here. Then you have to switch all other packages that use OpenJDK8 to OpenJDK11 and finally change the mediator for java.

**Comment by gounthar** [comment]
Ok, I was sceptical about the workflow because it wouldn't work as expected.
I did the `gmake REQUIRED_PACKAGES` but it kept using the `openjdk8` dependency, so I overrided it by hand, which is not the way to do it. 😥
I guess switching all other packages to OpenJDK11 is a little too invasive and may lead to other issues.
I'll try your suggestion and see if I can get it to work for me.
Thanks for your patience.

**Comment by gounthar** [comment]
I guess this PR was way too ambitious for my knowledge about OpenIndiana.
Thanks for your patience 🙏

**Pull request closed without merging**
