### PR TITLE
bhyve-firmware-release-202308-1

### PR DESCRIPTION
**Pull request by hoewweken**
Hi!
Tried to 'simply' update the package.
I have troubles building the ols csm modules.
without them the package gets published..

You can easily see that i tried to use python-2.7 / GCC-10 but either way the build of the csm modules fails..
Help is appreciated :-)

### CODE REVIEW

**Comment by hoewweken** [comment]
Here is the python error i get with default python
```
gmake -C Tests
gmake[1]: Entering directory '/home1/home/steven/src/oi/oi-userland/components/openindiana/bhyve-fw/build/DEBUG.csm/BaseTools/Tests'
Traceback (most recent call last):
  File "/home1/home/steven/src/oi/oi-userland/components/openindiana/bhyve-fw/build/DEBUG.csm/BaseTools/Tests/RunTests.py", line 22, in <module>
    import TestTools
  File "/home1/home/steven/src/oi/oi-userland/components/openindiana/bhyve-fw/uefi-edk2-il-udk2014.sp1-3/BaseTools/Tests/TestTools.py", line 87
    print description, '(base64 encoded):'
          ^
SyntaxError: invalid syntax 
```

**Comment by hoewweken** [comment]
For the records, error with GCC-10:
```
gmake[2]: Entering directory '/home1/home/steven/src/oi/oi-userland/components/openindiana/bhyve-fw/build/DEBUG.csm/BaseTools/Source/C/GenVtf'
/usr/gcc/10/bin/gcc  -c -MD -fshort-wchar -fno-strict-aliasing -Wall -Werror -Wno-deprecated-declarations -nostdlib -c -g -m64  -I .. -I ../Include/Common -I ../Include/ -I ../Include/IndustryStandard -I ../Common/ -I .. -I . -I ../Include/X64/  -m64 GenVtf.c -o GenVtf.o
GenVtf.c: In function 'CreateFitTableAndInitialize':
GenVtf.c:1473:3: error: 'strncpy' output truncated before terminating nul copying 8 bytes from a string of the same length [-Werror=stringop-truncation]
 1473 |   strncpy ((CHAR8 *) &FitStartPtr->CompAddress, FIT_SIGNATURE, 8);  // "_FIT_   "
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

**Comment by hoewweken** [comment]
For the records, i believe i have activated python-2.7 and leaving GCC-4.4.4 now in the build, i get this ASM error (?):
```
...
test_sitecustomize (CheckPythonSyntax.Tests) ... ok

----------------------------------------------------------------------
Ran 247 tests in 1.178s

OK
gmake[1]: Leaving directory '/home1/home/steven/src/oi/oi-userland/components/openindiana/bhyve-fw/build/DEBUG.csm/BaseTools/Tests'
gmake: Leaving directory '/home1/home/steven/src/oi/oi-userland/components/openindiana/bhyve-fw/build/DEBUG.csm/BaseTools'
WORKSPACE: /home1/home/steven/src/oi/oi-userland/components/openindiana/bhyve-fw/build/DEBUG.csm
EDK_TOOLS_PATH: /home1/home/steven/src/oi/oi-userland/components/openindiana/bhyve-fw/build/DEBUG.csm/BaseTools
Copying $EDK_TOOLS_PATH/Conf/build_rule.template
     to $WORKSPACE/Conf/build_rule.txt
Copying $EDK_TOOLS_PATH/Conf/tools_def.template
     to $WORKSPACE/Conf/tools_def.txt
Copying $EDK_TOOLS_PATH/Conf/target.template
     to $WORKSPACE/Conf/target.txt
gmake: Entering directory '/home1/home/steven/src/oi/oi-userland/components/openindiana/bhyve-fw/build/DEBUG.csm/BhyvePkg/Csm/BhyveCsm16'
rm -f Bin/BhyveCsm16Asm.o Bin/BhyveCsm16.o Bin/Bios.o Bin/Legacy8254.o Bin/Keyboard.o Bin/Memory.o Bin/Mmu.o Bin/Printf.o Bin/String.o Bin/Video.o Bin/ter-u16n-IBM-CP437.o Bin/BhyveCsm16.raw.o Bin/BhyveCsm16.bin.map
/opt/gcc/4.4.4/bin/gcc -m64 -nostdinc -nostdlib -ffreestanding -DEFIAPI="__attribute__((ms_abi))" -DNO_BUILTIN_VA_FUNCS -DDEBUG_PORT=0x3f8 -DBUILD_DATE=\"12/24/23\" -I/home1/home/steven/src/oi/oi-userland/components/openindiana/bhyve-fw/build/DEBUG.csm/MdePkg/Include -I/home1/home/steven/src/oi/oi-userland/components/openindiana/bhyve-fw/build/DEBUG.csm/MdePkg/Include/X64 -I/home1/home/steven/src/oi/oi-userland/components/openindiana/bhyve-fw/build/DEBUG.csm/IntelFrameworkPkg/Include -I/home1/home/steven/src/oi/oi-userland/components/openindiana/bhyve-fw/build/DEBUG.csm/BhyvePkg/Include -c -o Bin/BhyveCsm16Asm.o BhyveCsm16Asm.S
/var/tmp//ccM4ayjR.s: Assembler messages:
/var/tmp//ccM4ayjR.s:374: Error: operand size mismatch for `push'
/var/tmp//ccM4ayjR.s:552: Error: operand size mismatch for `push'
gmake: *** [GNUmakefile:61: Bin/BhyveCsm16Asm.o] Error 1
gmake: Leaving directory '/home1/home/steven/src/oi/oi-userland/components/openindiana/bhyve-fw/build/DEBUG.csm/BhyvePkg/Csm/BhyveCsm16'
```
i will next try to build without DEBUG.csm to check if the error occurs only in the DEBUG.csm build...

**Comment by mtelka** [comment]
Please avoid using Python 2.7.  Thank you.

**Comment by hoewweken** [comment]
> Please avoid using Python 2.7. Thank you.

Yes i would like to :-)
I hoped that a simple update of the current part of this package would be 'easy' and of byte-size difficulty.
Then the reality hit me by having errors in the 'old' csm part.

Should we patch the csm part to build with python-3.x? Maybe.
Then, we still have the ASM errors...

After christmas i may have more time to investigate,
but what would you recommend ?

Leaving the old csm part out ?
..Or splitting the package into bhyve-firmware and bhyve-firmware-csm maybe ?

**Comment by hoewweken** [comment]
BTW, the release.csm build is hit by the ASM error, too..
```
Ran 247 tests in 1.175s

OK
gmake[1]: Leaving directory '/home1/home/steven/src/oi/oi-userland/components/openindiana/bhyve-fw/build/RELEASE.csm/BaseTools/Tests'
gmake: Leaving directory '/home1/home/steven/src/oi/oi-userland/components/openindiana/bhyve-fw/build/RELEASE.csm/BaseTools'
WORKSPACE: /home1/home/steven/src/oi/oi-userland/components/openindiana/bhyve-fw/build/RELEASE.csm
EDK_TOOLS_PATH: /home1/home/steven/src/oi/oi-userland/components/openindiana/bhyve-fw/build/RELEASE.csm/BaseTools
Copying $EDK_TOOLS_PATH/Conf/build_rule.template
     to $WORKSPACE/Conf/build_rule.txt
Copying $EDK_TOOLS_PATH/Conf/tools_def.template
     to $WORKSPACE/Conf/tools_def.txt
Copying $EDK_TOOLS_PATH/Conf/target.template
     to $WORKSPACE/Conf/target.txt
gmake: Entering directory '/home1/home/steven/src/oi/oi-userland/components/openindiana/bhyve-fw/build/RELEASE.csm/BhyvePkg/Csm/BhyveCsm16'
rm -f Bin/BhyveCsm16Asm.o Bin/BhyveCsm16.o Bin/Bios.o Bin/Legacy8254.o Bin/Keyboard.o Bin/Memory.o Bin/Mmu.o Bin/Printf.o Bin/String.o Bin/Video.o Bin/ter-u16n-IBM-CP437.o Bin/BhyveCsm16.raw.o Bin/BhyveCsm16.bin.map
/opt/gcc/4.4.4/bin/gcc -m64 -nostdinc -nostdlib -ffreestanding -DEFIAPI="__attribute__((ms_abi))" -DNO_BUILTIN_VA_FUNCS -DDEBUG_PORT=0x2f8 -DBUILD_DATE=\"12/24/23\" -I/home1/home/steven/src/oi/oi-userland/components/openindiana/bhyve-fw/build/RELEASE.csm/MdePkg/Include -I/home1/home/steven/src/oi/oi-userland/components/openindiana/bhyve-fw/build/RELEASE.csm/MdePkg/Include/X64 -I/home1/home/steven/src/oi/oi-userland/components/openindiana/bhyve-fw/build/RELEASE.csm/IntelFrameworkPkg/Include -I/home1/home/steven/src/oi/oi-userland/components/openindiana/bhyve-fw/build/RELEASE.csm/BhyvePkg/Include -c -o Bin/BhyveCsm16Asm.o BhyveCsm16Asm.S
/var/tmp//cc6xay2r.s: Assembler messages:
/var/tmp//cc6xay2r.s:374: Error: operand size mismatch for `push'
/var/tmp//cc6xay2r.s:552: Error: operand size mismatch for `push'
gmake: *** [GNUmakefile:61: Bin/BhyveCsm16Asm.o] Error 1
gmake: Leaving directory '/home1/home/steven/src/oi/oi-userland/components/openindiana/bhyve-fw/build/RELEASE.csm/BhyvePkg/Csm/BhyveCsm16'
```

**Comment by AndWac** [comment]
You'll need to patch the python code where it is using python-2.7 syntax. Eg. function calls need parenthesis in python-3.
Thus,
print description, '(base64 encoded):'
needs to be changed into
print (description, '(base64 encoded):')

**Comment by hoewweken** [comment]
Hmm.. there are a lot of 'hits' and it would be an amount of work - for a source from 2014 :-/

What was the reason for having the source from 2014 in here?
Was the support CSM dropped upstream ? Should we follow?
Why do I get assembler errors in the 2014 part - i didn't change anything in the Makefile but the 'new' part, and that builds out of the box ... (despite adding the python-2.7 things to get rid of the python errors..)

Maybe we should have a slpit-off like
bhyve-firmware
|-> depends on bhyve-firmware-uefi (recent default python)
|-> depends on bhyve-firmware-csm (python-2.7)

**Comment by Toasterson** [comment]
bhyve-csm is also the last consumer for python2.7 in omnios so there is no way around that. https://github.com/omniosorg/omnios-build/blob/master/build/bhyve-fw/build.sh

**Comment by Toasterson** [comment]
@hoewweken @mtelka I was talking to the bHyve people in the bHyve Users call, right now python2.7 is required for CSM builds even in our latest illumos fork. You must also use GCC 4.9 which is illumos gcc. CSM, the BIOS code, has been removed from the base UEFI firmware images, and no replacement is ready yet. So unless we want to strip BIOS boot from bHyve as the first OS we will need to build CSM with python2. There is a utility called 2to3 which can convert the code if you want to try but otherwise, those restrictions are upstream and need work before we can get rid of it.

**Comment by mtelka** [comment]
Sorry, `illumos-gcc` is `4.4.4`.  We no longer have `gcc 4.9`.

**Pull request closed without merging**
