### PR TITLE
(WIP) Meld bumped to 3.16.0

### PR DESCRIPTION
**Pull request by jimklimov**
Something strange with Python resolution of dependencies, pkg(5) complains :(

### CODE REVIEW

**Comment by pyhalov** [comment]
Please, rebase it...

**Comment by jimklimov** [comment]
I tried, there were some conflicts because its parent branch was squashed,
and then i had to run. Oh the evils of squashing ;p

## 

Typos courtesy of GMail on my Samsung Android
06.05.2016 16:23 пользователь "Alexander Pyhalov" notifications@github.com
написал:

**Comment by pyhalov** [comment]
you can try to create new pull request...

**Comment by jimklimov** [comment]
Re-based to simplify review :)

The packaging step still fails, I'm not sure how to deal with it:

```
/usr/bin/pkgdepend resolve  -m /home/jim/shared/oi-userland-gcm/components/developer/meld/build/manifest-i386-meld.depend
/home/jim/shared/oi-userland-gcm/components/developer/meld/build/manifest-i386-meld.depend has unresolved dependency '
    depend type=require fmri=__TBD pkg.debug.depend.file=gi/__init__.py \
        pkg.debug.depend.reason=usr/bin/meld pkg.debug.depend.type=python \
        pkg.debug.depend.path=usr/lib/meld \
        pkg.debug.depend.path=usr/lib/python2.7 \
        pkg.debug.depend.path=usr/lib/python2.7/vendor-packages/gtk-2.0'.
/home/jim/shared/oi-userland-gcm/components/developer/meld/build/manifest-i386-meld.depend has unresolved dependency '
    depend type=require fmri=__TBD pkg.debug.depend.file=gi/__init__.py \
        pkg.debug.depend.reason=usr/bin/meld pkg.debug.depend.type=python \
        pkg.debug.depend.path=usr/bin \
        pkg.debug.depend.path=usr/lib/python2.7 \
        pkg.debug.depend.path=usr/lib/python2.7/lib-dynload \
        pkg.debug.depend.path=usr/lib/python2.7/lib-old \
        pkg.debug.depend.path=usr/lib/python2.7/lib-tk \
        pkg.debug.depend.path=usr/lib/python2.7/plat-sunos5 \
        pkg.debug.depend.path=usr/lib/python2.7/site-packages \
        pkg.debug.depend.path=usr/lib/python2.7/vendor-packages \
        pkg.debug.depend.path=usr/lib/python27.zip'.
/home/jim/shared/oi-userland-gcm/components/developer/meld/build/manifest-i386-meld.depend has unresolved dependency '
    depend type=require fmri=__TBD pkg.debug.depend.reason=usr/bin/meld \
        pkg.debug.depend.type=python \
        pkg.debug.depend.file=64/conf.so \
        pkg.debug.depend.file=64/confmodule.so \
        pkg.debug.depend.file=conf.py \
        pkg.debug.depend.file=conf.pyc \
        pkg.debug.depend.file=conf.pyo \
        pkg.debug.depend.file=conf.so \
        pkg.debug.depend.file=conf/__init__.py \
        pkg.debug.depend.file=confmodule.so \
        pkg.debug.depend.path=usr/bin/meld \
        pkg.debug.depend.path=usr/lib/python2.7/lib-dynload/meld \
        pkg.debug.depend.path=usr/lib/python2.7/lib-old/meld \
        pkg.debug.depend.path=usr/lib/python2.7/lib-tk/meld \
        pkg.debug.depend.path=usr/lib/python2.7/meld \
        pkg.debug.depend.path=usr/lib/python2.7/plat-sunos5/meld \
        pkg.debug.depend.path=usr/lib/python2.7/site-packages/meld \
        pkg.debug.depend.path=usr/lib/python2.7/vendor-packages/meld \
        pkg.debug.depend.path=usr/lib/python27.zip/meld'.
/home/jim/shared/oi-userland-gcm/components/developer/meld/build/manifest-i386-meld.depend has unresolved dependency '
    depend type=require fmri=__TBD pkg.debug.depend.reason=usr/bin/meld \
        pkg.debug.depend.type=python \
        pkg.debug.depend.file=64/repository.so \
        pkg.debug.depend.file=64/repositorymodule.so \
        pkg.debug.depend.file=repository.py \
        pkg.debug.depend.file=repository.pyc \
        pkg.debug.depend.file=repository.pyo \
        pkg.debug.depend.file=repository.so \
        pkg.debug.depend.file=repository/__init__.py \
        pkg.debug.depend.file=repositorymodule.so \
        pkg.debug.depend.path=usr/lib/meld/gi \
        pkg.debug.depend.path=usr/lib/python2.7/gi \
        pkg.debug.depend.path=usr/lib/python2.7/vendor-packages/gtk-2.0/gi'.
/home/jim/shared/oi-userland-gcm/components/developer/meld/build/manifest-i386-meld.depend has unresolved dependency '
    depend type=require fmri=__TBD pkg.debug.depend.reason=usr/bin/meld \
        pkg.debug.depend.type=python \
        pkg.debug.depend.file=64/settings.so \
        pkg.debug.depend.file=64/settingsmodule.so \
        pkg.debug.depend.file=settings.py \
        pkg.debug.depend.file=settings.pyc \
        pkg.debug.depend.file=settings.pyo \
        pkg.debug.depend.file=settings.so \
        pkg.debug.depend.file=settings/__init__.py \
        pkg.debug.depend.file=settingsmodule.so \
        pkg.debug.depend.path=usr/bin/meld \
        pkg.debug.depend.path=usr/lib/python2.7/lib-dynload/meld \
        pkg.debug.depend.path=usr/lib/python2.7/lib-old/meld \
        pkg.debug.depend.path=usr/lib/python2.7/lib-tk/meld \
        pkg.debug.depend.path=usr/lib/python2.7/meld \
        pkg.debug.depend.path=usr/lib/python2.7/plat-sunos5/meld \
        pkg.debug.depend.path=usr/lib/python2.7/site-packages/meld \
        pkg.debug.depend.path=usr/lib/python2.7/vendor-packages/meld \
        pkg.debug.depend.path=usr/lib/python27.zip/meld'.
/home/jim/shared/oi-userland-gcm/components/developer/meld/build/manifest-i386-meld.depend has unresolved dependency '
    depend type=require fmri=__TBD pkg.debug.depend.reason=usr/bin/meld \
        pkg.debug.depend.type=python \
        pkg.debug.depend.file=64/gi.so \
        pkg.debug.depend.file=64/gimodule.so \
        pkg.debug.depend.file=gi.py \
        pkg.debug.depend.file=gi.pyc \
        pkg.debug.depend.file=gi.pyo \
        pkg.debug.depend.file=gi.so \
        pkg.debug.depend.file=gi/__init__.py \
        pkg.debug.depend.file=gimodule.so \
        pkg.debug.depend.path=usr/bin \
        pkg.debug.depend.path=usr/lib/python2.7 \
        pkg.debug.depend.path=usr/lib/python2.7/lib-dynload \
        pkg.debug.depend.path=usr/lib/python2.7/lib-old \
        pkg.debug.depend.path=usr/lib/python2.7/lib-tk \
        pkg.debug.depend.path=usr/lib/python2.7/plat-sunos5 \
        pkg.debug.depend.path=usr/lib/python2.7/site-packages \
        pkg.debug.depend.path=usr/lib/python2.7/vendor-packages \
        pkg.debug.depend.path=usr/lib/python27.zip'.
/home/jim/shared/oi-userland-gcm/components/developer/meld/build/manifest-i386-meld.depend has unresolved dependency '
    depend type=require fmri=__TBD pkg.debug.depend.file=meld/__init__.py \
        pkg.debug.depend.reason=usr/bin/meld pkg.debug.depend.type=python \
        pkg.debug.depend.path=usr/bin \
        pkg.debug.depend.path=usr/lib/python2.7 \
        pkg.debug.depend.path=usr/lib/python2.7/lib-dynload \
        pkg.debug.depend.path=usr/lib/python2.7/lib-old \
        pkg.debug.depend.path=usr/lib/python2.7/lib-tk \
        pkg.debug.depend.path=usr/lib/python2.7/plat-sunos5 \
        pkg.debug.depend.path=usr/lib/python2.7/site-packages \
        pkg.debug.depend.path=usr/lib/python2.7/vendor-packages \
        pkg.debug.depend.path=usr/lib/python27.zip'.
/home/jim/shared/oi-userland-gcm/components/developer/meld/build/manifest-i386-meld.depend has unresolved dependency '
    depend type=require fmri=__TBD pkg.debug.depend.reason=usr/bin/meld \
        pkg.debug.depend.type=python \
        pkg.debug.depend.file=64/repository.so \
        pkg.debug.depend.file=64/repositorymodule.so \
        pkg.debug.depend.file=repository.py \
        pkg.debug.depend.file=repository.pyc \
        pkg.debug.depend.file=repository.pyo \
        pkg.debug.depend.file=repository.so \
        pkg.debug.depend.file=repository/__init__.py \
        pkg.debug.depend.file=repositorymodule.so \
        pkg.debug.depend.path=usr/bin/gi \
        pkg.debug.depend.path=usr/lib/python2.7/gi \
        pkg.debug.depend.path=usr/lib/python2.7/lib-dynload/gi \
        pkg.debug.depend.path=usr/lib/python2.7/lib-old/gi \
        pkg.debug.depend.path=usr/lib/python2.7/lib-tk/gi \
        pkg.debug.depend.path=usr/lib/python2.7/plat-sunos5/gi \
        pkg.debug.depend.path=usr/lib/python2.7/site-packages/gi \
        pkg.debug.depend.path=usr/lib/python2.7/vendor-packages/gi \
        pkg.debug.depend.path=usr/lib/python27.zip/gi'.
/home/jim/shared/oi-userland-gcm/components/developer/meld/build/manifest-i386-meld.depend has unresolved dependency '
    depend type=require fmri=__TBD pkg.debug.depend.reason=usr/bin/meld \
        pkg.debug.depend.type=python \
        pkg.debug.depend.file=64/meldapp.so \
        pkg.debug.depend.file=64/meldappmodule.so \
        pkg.debug.depend.file=meldapp.py \
        pkg.debug.depend.file=meldapp.pyc \
        pkg.debug.depend.file=meldapp.pyo \
        pkg.debug.depend.file=meldapp.so \
        pkg.debug.depend.file=meldapp/__init__.py \
        pkg.debug.depend.file=meldappmodule.so \
        pkg.debug.depend.path=usr/bin/meld \
        pkg.debug.depend.path=usr/lib/python2.7/lib-dynload/meld \
        pkg.debug.depend.path=usr/lib/python2.7/lib-old/meld \
        pkg.debug.depend.path=usr/lib/python2.7/lib-tk/meld \
        pkg.debug.depend.path=usr/lib/python2.7/meld \
        pkg.debug.depend.path=usr/lib/python2.7/plat-sunos5/meld \
        pkg.debug.depend.path=usr/lib/python2.7/site-packages/meld \
        pkg.debug.depend.path=usr/lib/python2.7/vendor-packages/meld \
        pkg.debug.depend.path=usr/lib/python27.zip/meld'.
/home/jim/shared/oi-userland-gcm/components/developer/meld/build/manifest-i386-meld.depend has unresolved dependency '
    depend type=require fmri=__TBD pkg.debug.depend.reason=usr/bin/meld \
        pkg.debug.depend.type=python \
        pkg.debug.depend.file=64/gi.so \
        pkg.debug.depend.file=64/gimodule.so \
        pkg.debug.depend.file=gi.py \
        pkg.debug.depend.file=gi.pyc \
        pkg.debug.depend.file=gi.pyo \
        pkg.debug.depend.file=gi.so \
        pkg.debug.depend.file=gi/__init__.py \
        pkg.debug.depend.file=gimodule.so \
        pkg.debug.depend.path=usr/lib/meld \
        pkg.debug.depend.path=usr/lib/python2.7 \
        pkg.debug.depend.path=usr/lib/python2.7/vendor-packages/gtk-2.0'.
/home/jim/shared/oi-userland-gcm/make-rules/ips.mk:377: recipe for target '/home/jim/shared/oi-userland-gcm/components/developer/meld/build/.resolved-i386' failed
gmake: *** [/home/jim/shared/oi-userland-gcm/components/developer/meld/build/.resolved-i386] Error 1
```

**Comment by jimklimov** [comment]
In the end, Meld 3.x requires GTK+ 3.x and some other dependencies we don't have in the gate at sufficient version levels.
The newest still-compatible version is meld-1.8.6, for which the recipe is already in place.

**Comment by alarcher** [comment]
Could you list them on the Wiki ?
When I looked at inkscape, update of gtkmm, atkmm, glibmm and pangomm were required.
We need to think about an upgrade path.

**Comment by jimklimov** [comment]
@alarcher : according to the Meld 3.16 README, they want some things we have, and some we do not: Gtk+ 3.14 (we have 2.24.30), GtkSourceView 3.14 (we have 2.10.5), PyGObject 3.8 (we have 2.28.6).

In the changelog they occasionally bumped requirements of a new release, so it seems these minimal versions are really needed ;)

UPDATE: I looked at 'gtk2' package; we have also 'gtk3' (3.14.15) which is installed, but not `pygtk3` - overall the Meld 3.16 python scripts do not resolve some objects they need.

Running the `meld` script directly (which is a supported approach in the distro README) also issues errors:

```
$ ./meld
Traceback (most recent call last):
  File "./meld.orig", line 259, in <module>
    check_requirements()
  File "./meld.orig", line 161, in check_requirements
    gi.require_version("Gtk", "3.0")
  File "/usr/lib/python2.7/vendor-packages/gi/__init__.py", line 50, in require_version
    (namespace, version))
ValueError: Namespace Gtk not available for version 3.0
```

If I ease the requirement to Gtk 2.0, I get this:

```
Traceback (most recent call last):
  File "./meld", line 259, in <module>
    check_requirements()
  File "./meld", line 163, in check_requirements
    version = (Gtk.get_major_version(), Gtk.get_minor_version())
  File "/usr/lib/python2.7/vendor-packages/gi/module.py", line 270, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib/python2.7/vendor-packages/gi/module.py", line 101, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.Gtk' object has no attribute 'get_major_version'
```

The relevant block of code for the hack is:

```
    try:
        # FIXME: Extra clause for gi
        import gi
        gi.require_version("Gtk", "2.0")
        from gi.repository import Gtk
        version = (Gtk.get_major_version(), Gtk.get_minor_version())
        assert version >= gtk_requirement
    except (ImportError, AssertionError) as e:
        missing_reqs("GTK+", gtk_requirement, e)
```

So apparently our version does not have the needed features :-\

**Comment by jimklimov** [comment]
If I commented away the `Gtk` version check, it breaks on GtkSource(View) namespace. This may be because we only have Python Bindings for GtkSourceView `pygtksourceview-26` and the meld requirements are for Python 2.7 (checked - not 2.6, not 3.x)...

**Comment by pyhalov** [comment]
you can try building pygtksourceview (python/pygtksourceview) for both pythons (look at python/pygtk2)

**Pull request closed without merging**
