### PR TITLE
Golang 113

### PR DESCRIPTION
**Pull request by Toasterson**
This builds golang for both solaris and illumos GOOS architectures. Mediator uses the illumos versions and solaris version of commands is available in /usr/lib but not linked.

### CODE REVIEW

**Comment by Mno-hime** [comment]
I think this one needs sample manifest rebuild as well:
```
+file path=usr/lib/golang/$(COMPONENT_VERSION)/bin/illumos_amd64/go
+file path=usr/lib/golang/$(COMPONENT_VERSION)/bin/illumos_amd64/gofmt
...
+file path=usr/lib/golang/$(COMPONENT_VERSION)/pkg/illumos_amd64/archive/tar.a
+file path=usr/lib/golang/$(COMPONENT_VERSION)/pkg/illumos_amd64/archive/zip.a
+file path=usr/lib/golang/$(COMPONENT_VERSION)/pkg/illumos_amd64/bufio.a
+file path=usr/lib/golang/$(COMPONENT_VERSION)/pkg/illumos_amd64/bytes.a
...
```

**Comment by Mno-hime** [comment]
I've seen one fail (not in go 1.12):
```
go test proxy running at GOPROXY=http://127.0.0.1:62476/mod
go proxy: no archive rsc.io v1.5.2: file does not exist
go proxy: no archive rsc.io v1.0.0: file does not exist
go proxy: no archive rsc.io v1.0.0: file does not exist
go proxy: no archive rsc.io v1.0.0: file does not exist
go proxy: no archive rsc.io v1.0.0: file does not exist
go proxy: no archive rsc.io v1.1.0: file does not exist
go proxy: no archive rsc.io v1.5.1: file does not exist
go proxy: no archive example.com/newcycle v1.0.0: file does not exist
--- FAIL: TestScript (0.01s)
    --- FAIL: TestScript/mod_convert_git (0.12s)
        script_test.go:191: 
            # We should not create a go.mod file unless the user ran 'go mod init' explicitly.
            # However, we should suggest 'go mod init' if we can find an alternate config file. (0.025s)
            # The command we suggested should succeed. (0.057s)
            # We should not suggest creating a go.mod file in $GOROOT, even though there may be a .git/config there. (0.031s)
            > cd $GOROOT
            /export/home/newman/ws/oi-userland/components/developer/golang-113/build/amd64
            > ! go list .
            [stderr]
            goroutine 1 [running]:
            runtime/debug.Stack(0xc00015f230, 0xc0001f05b0, 0xc000173748)
            	/export/home/newman/ws/oi-userland/components/developer/golang-113/build/amd64/src/runtime/debug/stack.go:24 +0x9d
            runtime/debug.PrintStack()
            	/export/home/newman/ws/oi-userland/components/developer/golang-113/build/amd64/src/runtime/debug/stack.go:16 +0x22
            cmd/go/internal/modload.die()
            	/export/home/newman/ws/oi-userland/components/developer/golang-113/build/amd64/src/cmd/go/internal/modload/init.go:274 +0x2fe
            cmd/go/internal/modload.ModRoot(0xc0001861e0, 0x4e)
            	/export/home/newman/ws/oi-userland/components/developer/golang-113/build/amd64/src/cmd/go/internal/modload/init.go:253 +0x50
            cmd/go/internal/modload.ImportPathsQuiet.func1(0xc0001a4048, 0x1, 0x1, 0x1)
            	/export/home/newman/ws/oi-userland/components/developer/golang-113/build/amd64/src/cmd/go/internal/modload/load.go:109 +0x9e3
            cmd/go/internal/modload.ImportPathsQuiet.func2(0x9abd40, 0xc00015f110, 0x0)
            	/export/home/newman/ws/oi-userland/components/developer/golang-113/build/amd64/src/cmd/go/internal/modload/load.go:205 +0x62
            cmd/go/internal/modload.(*loader).load(0xc0001e8120, 0xc0001f0f30)
            	/export/home/newman/ws/oi-userland/components/developer/golang-113/build/amd64/src/cmd/go/internal/modload/load.go:601 +0x115f
            cmd/go/internal/modload.ImportPathsQuiet(0xc0000a4050, 0x1, 0x1, 0xc00015efc0, 0x8, 0x0, 0xc0001b9200)
            	/export/home/newman/ws/oi-userland/components/developer/golang-113/build/amd64/src/cmd/go/internal/modload/load.go:203 +0x2f4
            cmd/go/internal/modload.ImportPaths(0xc0000a4050, 0x1, 0x1, 0x0, 0xa3acec, 0x2)
            	/export/home/newman/ws/oi-userland/components/developer/golang-113/build/amd64/src/cmd/go/internal/modload/load.go:57 +0x5d
            cmd/go/internal/load.ImportPaths(0xc0000a4050, 0x1, 0x1, 0x9dd9e0, 0x10, 0xc000000300)
            	/export/home/newman/ws/oi-userland/components/developer/golang-113/build/amd64/src/cmd/go/internal/load/pkg.go:2014 +0x5f
            cmd/go/internal/load.PackagesAndErrors(0xc0000a4050, 0x1, 0x1, 0x0, 0x0, 0x0)
            	/export/home/newman/ws/oi-userland/components/developer/golang-113/build/amd64/src/cmd/go/internal/load/pkg.go:1961 +0xcd
            cmd/go/internal/load.Packages(0xc0000a4050, 0x1, 0x1, 0xc00018b500, 0x0, 0x0)
            	/export/home/newman/ws/oi-userland/components/developer/golang-113/build/amd64/src/cmd/go/internal/load/pkg.go:1938 +0x5a
            cmd/go/internal/list.runList(0xea87e0, 0xc0000a4050, 0x1, 0x1)
            	/export/home/newman/ws/oi-userland/components/developer/golang-113/build/amd64/src/cmd/go/internal/list/list.go:425 +0x21bc
            main.main()
            	/export/home/newman/ws/oi-userland/components/developer/golang-113/build/amd64/src/cmd/go/main.go:189 +0x57f
            go: cannot find main module, but found .git/config in /export/home/newman/ws/oi-userland
            	to create a module there, run:
            	cd ../../../../.. && go mod init
            [exit status 1]
            > ! stderr 'go mod init'
            FAIL: testdata/script/mod_convert_git.txt:19: unexpected match for `(?m)go mod init` found in stderr: go mod init
            
FAIL
FAIL	cmd/go	90.752s
```

**Comment by Toasterson** [comment]
@Mno-hime thanks for noticing. I always forget to run gmake test

This is an issue upstream you cannot run tests inside of a git repository as go modules assume they can control git.

If you copy the built binaries and GOROOT out from oi-userland into a seperate directory the tests pass.

I opened an issue with the go project under golang/go#34191

**Comment by Mno-hime** [comment]
> +file path=usr/lib/golang/$(COMPONENT_VERSION)/pkg/illumos_amd64/archive/tar.a
> +file path=usr/lib/golang/$(COMPONENT_VERSION)/pkg/illumos_amd64/archive/zip.a
> +file path=usr/lib/golang/$(COMPONENT_VERSION)/pkg/illumos_amd64/bufio.a
> +file path=usr/lib/golang/$(COMPONENT_VERSION)/pkg/illumos_amd64/bytes.a

@Toasterson what about these files? E.g. I see `solaris_amd64/archive/tar.a` in the sample manifest and the delivered .p5m but not `illumos_amd64/archive/tar.a`. Should we deliver both Solaris and illumos `archive/tar.a` et al.? I am sorry I did not understood the the GOOS topic you discuss in the PR description...

**Comment by Toasterson** [comment]
@alarcher @Mno-hime yes we should deliver them. as root they get autocompiled on the final system but not as non root user. I thought I included all pkg sub directories but now as we changed GOOS to illumos we need the illumos_amd64 files aswell.

The GOOS has now changed from solaris to illumos as we have sufficiently deiverged from solaris that go binaries compiled on solaris do not run on illumos any longer and vice versa

**Comment by Toasterson** [comment]
Turns out my manifest generation was still broken when i recreated it with GOOS=illumos. fixed now.

**Review by Mno-hime — APPROVED** [review]

**Pull request merged**
