### PR TITLE
Add nodejs-7 to oi-userland

### PR DESCRIPTION
**Pull request by AndWac**

### CODE REVIEW

**Review by xen0l — COMMENTED** [review]
What about also mediating npm.1?

**Comment by AndWac** [comment]
we could do that,
but we did not do that for node and node6 yet. Furthermore there are several other npm man pages (man1, 5, and 7). What should be done with them?

**Comment by xen0l** [comment]
@pyhalov what do you think about mediating npm manpages? If we didn't do it, I'd say to leave it as it is.

**Comment by pyhalov** [comment]
As we mediate npm, it will be good to mediate its manpage

**Comment by xen0l** [comment]
As discussed yesterday, @AndWac will provide npm man page mediation in subsequent PRs. I mark this for merging.

**Pull request merged**
