### PR TITLE
obsolete gstreamer-plugin-bad, -ugly and gst-ffmpeg

### PR DESCRIPTION
**Pull request by AndWac**
We don't have any dependencies on these packages left.

### CODE REVIEW

**Comment by mtelka** [comment]
The encumbered history was not build (or published) after this.  Actually, it was _never_ build/published since its introduction.  @AndWac, @Toasterson could you please check on the build server why it is so?  The build log at https://hipster.openindiana.org/jenkins/job/oi-encumbered/517/console shows that the history is published, but the ips repo does not have it.

Thank you.

**Comment by mtelka** [comment]
I think I found the root cause for the missing encumbered history: #19791

**Comment by mtelka** [comment]
@AndWac, @Toasterson something still does not work, because I still see no obsoleted packages in the repo:
```
# pkg refresh ; pkg list -afv library/audio/gstreamer/plugin/ffmpeg
FMRI                                                                         IFO
pkg://hipster-encumbered/library/audio/gstreamer/plugin/ffmpeg@0.10.13-2022.0.0.2:20220126T070329Z i--
#
```
After #19791 the history publish works properly here locally (see below), so it must be something on the build server.  Could you please double check there?  Thank you.
```
$ pkgrepo list -s i386/encumbered-repo/
PUBLISHER          NAME                                          O VERSION
hipster-encumbered audio/lame                                    o 3.99.5-2018.0.0.2:20241130T111734Z
hipster-encumbered audio/lame                                    o 3.99.5-2018.0.0.2:20241130T022358Z
hipster-encumbered audio/twolame                                 o 0.3.13-2018.0.0.1:20241130T111735Z
hipster-encumbered audio/twolame                                 o 0.3.13-2018.0.0.1:20241130T022359Z
hipster-encumbered developer/ffmpeg-6                              6.1.2-2024.0.0.0:20241112T154541Z
hipster-encumbered developer/ffmpeg-7                              7.1-2024.0.0.0:20241113T144154Z
hipster-encumbered developer/ffmpeg-7                              7.1-2024.0.0.0:20241113T130535Z
hipster-encumbered library/audio/gstreamer/plugin/bad            o 0.10.23-2022.0.0.7:20241130T111737Z
hipster-encumbered library/audio/gstreamer/plugin/bad            o 0.10.23-2022.0.0.7:20241130T022400Z
hipster-encumbered library/audio/gstreamer/plugin/ffmpeg         o 0.10.13-2022.0.0.3:20241130T111738Z
hipster-encumbered library/audio/gstreamer/plugin/ffmpeg         o 0.10.13-2022.0.0.3:20241130T022401Z
hipster-encumbered library/audio/gstreamer/plugin/ugly           o 0.10.19-2022.0.0.4:20241130T111740Z
hipster-encumbered library/audio/gstreamer/plugin/ugly           o 0.10.19-2022.0.0.4:20241130T022402Z
hipster-encumbered library/audio/gstreamer1/devtools               1.24.9-2024.0.0.0:20241113T200242Z
hipster-encumbered library/audio/gstreamer1/editing-services       1.24.9-2024.0.0.0:20241114T005637Z
hipster-encumbered library/audio/gstreamer1/editing-services       1.24.9-2024.0.0.0:20241114T003613Z
hipster-encumbered library/audio/gstreamer1/editing-services       1.24.9-2024.0.0.0:20241114T001102Z
hipster-encumbered library/audio/gstreamer1/editing-services       1.24.9-2024.0.0.0:20241114T000925Z
hipster-encumbered library/audio/gstreamer1/editing-services       1.24.9-2024.0.0.0:20241113T235639Z
hipster-encumbered library/audio/gstreamer1/plugin/bad             1.24.9-2024.0.0.0:20241112T153130Z
hipster-encumbered library/audio/gstreamer1/plugin/bad             1.24.9-2024.0.0.0:20241112T150647Z
hipster-encumbered library/audio/gstreamer1/plugin/bad             1.24.9-2024.0.0.0:20241112T141234Z
hipster-encumbered library/audio/gstreamer1/plugin/libav           1.24.9-2024.0.0.0:20241113T202722Z
hipster-encumbered library/audio/gstreamer1/plugin/libav           1.24.9-2024.0.0.0:20241113T202452Z
hipster-encumbered library/audio/gstreamer1/plugin/ugly            1.24.9-2024.0.0.0:20241110T213329Z
hipster-encumbered library/audio/gstreamer1/plugin/ugly            1.24.9-2024.0.0.0:20241110T210715Z
hipster-encumbered library/audio/gstreamer1/plugin/ugly            1.24.9-2024.0.0.0:20241110T210643Z
hipster-encumbered library/audio/gstreamer1/rtsp-server            1.24.9-2024.0.0.0:20241130T021811Z
hipster-encumbered library/audio/gstreamer1/rtsp-server            1.24.9-2024.0.0.0:20241113T103039Z
hipster-encumbered library/audio/gstreamer1/rtsp-server            1.24.9-2024.0.0.0:20241113T100652Z
hipster-encumbered library/ffmpeg-6                                6.1.2-2024.0.0.0:20241112T154542Z
hipster-encumbered library/ffmpeg-7                                7.1-2024.0.0.0:20241113T144158Z
hipster-encumbered library/ffmpeg-7                                7.1-2024.0.0.0:20241113T130538Z
hipster-encumbered video/ffmpeg                                    7.1-2024.0.0.0:20241113T144156Z
hipster-encumbered video/ffmpeg                                    7.1-2024.0.0.0:20241113T130536Z
$
```

**Comment by Toasterson** [comment]
I can see that the meta-package job succeeds in the logs while cleaning up the local repo copy, though it has not generated any packages. I assume the history script goes through the repo while doing work and works completely in there. In case of the build server we always work with a clean empty repo locally before syncing to the hosted one with pkgrecv as pkgsend somehow does more work inside the repo than it should it seems. or some other process inside IPS code. We published directly to the live repo before and that turned out to slow build times very very fast. 

@mtelka can you change the history behaviour so that we can maybe introduce a source repo where it should lookup which packages to obsolete? I guess this bug now also exists in oi-userland history process.

**Comment by mtelka** [comment]
I did few more tests and I found a scenario when it does not work.  The publish works twice, but 3rd and all subsequent publish attempts does nothing, until the next _clobber_:

```
$ cd components/encumbered/meta-packages/history
$ env - gmake clobber
...
$ env - gmake publish | grep PUBLISHED
PUBLISHED
PUBLISHED
PUBLISHED
PUBLISHED
PUBLISHED
$ env - gmake publish | grep PUBLISHED
PUBLISHED
PUBLISHED
PUBLISHED
PUBLISHED
PUBLISHED
$ env - gmake publish
generating metadata: encumbered/meta-packages/history
$ env - gmake publish
generating metadata: encumbered/meta-packages/history
$ env - gmake publish
generating metadata: encumbered/meta-packages/history
$ env - gmake publish
generating metadata: encumbered/meta-packages/history
$ env - gmake clobber
...
$ env - gmake publish | grep PUBLISHED
PUBLISHED
PUBLISHED
PUBLISHED
PUBLISHED
PUBLISHED
$
```

However, all components behave like that (1st and 2nd `publish` works, 3rd one and all subsequent does nothing), so this is probably not causing the missing encumbered history.  Just to be sure: Is `gmake clobber` (or something similar) called before the `gmake publish`?

> @mtelka can you change the history behaviour so that we can maybe introduce a source repo where it should lookup which packages to obsolete? I guess this bug now also exists in oi-userland history process.

I'm sorry, but I do not understand what you mean by that. :-(

**Comment by mtelka** [comment]
> I can see that the meta-package job succeeds in the logs while cleaning up the local repo copy, though it has not generated any packages.

Could you please share the full publish log for the `encumbered/meta-packages/history` component?  Thank you.

**Comment by Toasterson** [comment]
> However, all components behave like that (1st and 2nd `publish` works, 3rd one and all subsequent does nothing), so this is probably not causing the missing encumbered history. Just to be sure: Is `gmake clobber` (or something similar) called before the `gmake publish`?

No as we are building from top-level and thus a clobber would cause a full rebuild. So I can try that and trigger a build

> Could you please share the full publish log for the encumbered/meta-packages/history component? Thank you.
Of course in 517 and build 518 it looked like this. 
```
pkg://userland/audio/lame@3.99.5,5.11-2018.0.0.2:20241128T215615Z
PUBLISHED
pkg://userland/audio/twolame@0.3.13,5.11-2018.0.0.1:20241128T215616Z
PUBLISHED
pkg://userland/library/audio/gstreamer/plugin/bad@0.10.23,5.11-2022.0.0.7:20241128T215617Z
PUBLISHED
pkg://userland/library/audio/gstreamer/plugin/ffmpeg@0.10.13,5.11-2022.0.0.3:20241128T215617Z
PUBLISHED
pkg://userland/library/audio/gstreamer/plugin/ugly@0.10.19,5.11-2022.0.0.4:20241128T215618Z
PUBLISHED
generating metadata: encumbered/meta-packages/history
```
 After that like this
```
generating metadata: encumbered/meta-packages/history
```

I did a `gmake clobber` inside the history package directory now some packages have been published. https://hipster.openindiana.org/jenkins/job/oi-encumbered/529/console

And I see an obsoleted package here
```
pkg refresh ; pkg list -afv library/audio/gstreamer/plugin/ffmpeg
FMRI                                                                         IFO
pkg://hipster-encumbered/library/audio/gstreamer/plugin/ffmpeg@0.10.13-2022.0.0.3:20241201T085214Z --o
pkg://hipster-encumbered/library/audio/gstreamer/plugin/ffmpeg@0.10.13-2022.0.0.2:20220126T070329Z ---
```

**Comment by mtelka** [comment]
Great.  Thank you.  It behaves (mostly) as expected and it should work from now on for all future changes in the encumbered history.

(Mostly, because it should publish once not twice, but that's a minor problem.)

**Pull request merged**
