### PR TITLE
Update pciutils to 3.4.0

### PR DESCRIPTION
**Pull request by xen0l**

### CODE REVIEW

**Comment by xen0l** [comment]
Should we drop depend action from p5m file? pci.ids are delivered from illumos-gate. Any comments on this?

**Comment by pyhalov** [comment]
we have pci.ids package, which delivers usr/share/pci.ids.gz. I wonder if we really need it...

**Comment by pyhalov** [comment]
At least pciutils don't need it

**Comment by xen0l** [comment]
pcituils don't need it. I added that line a long time ago, so if we have a querying tools, we should also have a database to query. Should I make it instead dependent on illumos packages or remove it completely?

**Comment by pyhalov** [comment]
perhaps, depend on file?

**Pull request merged**
