### PR TITLE
libxcb should require libpthread-stubs

### PR DESCRIPTION
**Pull request by Mno-hime**
https://github.com/OpenIndiana/oi-userland/pull/3147#issuecomment-304537975

### CODE REVIEW

**Review by alarcher — CHANGES_REQUESTED** [review]
The package name is x11/library/libpthread-stubs

**Comment by Mno-hime** [comment]
Adressed.

**Review by alarcher — APPROVED** [review]

**Review by pyhalov — CHANGES_REQUESTED** [review]
Please, bump COMPONENT_REVISION

**Comment by Mno-hime** [comment]
Superseded by https://github.com/OpenIndiana/oi-userland/pull/3297.

**Pull request closed without merging**
