### PR TITLE
Added yaml-cpp-0.7.0

### PR DESCRIPTION
**Pull request by shuryanc**
For opencolorio which needed by krita.

### CODE REVIEW

**Comment by AndWac** [comment]
Running the tests fail miserably:

╰─➤  gmake test
(cd /export/home/andreas/oi-userland/components/library/yaml-cpp/build/amd64 ; \
	/usr/bin/env  \
	ctest \
	 )
Test project /export/home/andreas/oi-userland/components/library/yaml-cpp/build/amd64
    Start 1: yaml-cpp::test
1/1 Test #1: yaml-cpp::test ...................***Exception: SegFault  0.03 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.04 sec

The following tests FAILED:
	  1 - yaml-cpp::test (SEGFAULT)
Errors while running CTest
Output from these tests are in: /export/home/andreas/oi-userland/components/library/yaml-cpp/build/amd64/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.

**Comment by shuryanc** [comment]
Not sure how to fix it. But it works for my application.

**Comment by alarcher** [comment]
> Not sure how to fix it. But it works for my application.

Do you want me to have a look?

**Comment by shuryanc** [comment]
> > Not sure how to fix it. But it works for my application.
> 
> Do you want me to have a look?

Yes! It would be great if you can help.

**Comment by shuryanc** [comment]
Can it be merged first. Despite its test failed, but my application bssed on it is working.

**Pull request merged**
