### PR TITLE
8097 Better patch for callers of notify_notification_new()

### PR DESCRIPTION
**Pull request by jgmills**
This PR contains the updated patches for 8097 along with Makefile changes required whenever a component is changed.  All of the components required `gmake REQUIRED_PACKAGES' to add that section to the Makefiles.  These four had completely successful builds.

### CODE REVIEW

**Review by xen0l — COMMENTED** [review]
@jgmills changes looks good to me. However, if you are modifying patches and the component needs to be rebuiilt, you have to increase/add COMPONENT_REVISION, so the build server picks the change.

**Comment by jgmills** [comment]
Ah, that's what COMPONENT_REVISION is for.  I'll fix that and re-submit the PR.

**Comment by xen0l** [comment]
@jgmills, you dont have to create a new pr just uodate this one. First, commit changes locally, the run rebase (http://docs.openindiana.org/dev/userland/#submit-your-component). With this approach, you don't need to create new PR. By always creating a new PR and closing old ones, you are increasing the amount PRs closed without merge. So, please try to use the same workflow like the rest of us.

Reasons when to create a new PR can be: packaging bigger components, which need dependencies; the change is rather big and you want to split it into smaller much more easily reviewable pieces etc

**Comment by jgmills** [comment]
I don't believe this technique will work for me.  When I started this project in November, I followed the documented procedure that was available then.  It required creating a fork of oi-userland on github, and a local clone where I could do development and testing.  I still have a backlog of changes that I'd like to have integrated into oi-userland, with the old procedure.  I will take care to ensure that my PRs are complete and ready to merge.  I don't want to start over now.

Next time around, I will follow the new procedure just like the rest of you.

**Comment by alarcher** [comment]
@jgmills I do not understand the issue, you just need to push -f on the same branch and not close/open a new PR. What is the blocker?

**Comment by xen0l** [comment]
@jgmills the procedure hasn't changed, there always has been only one procedure - github workflow. You create a fork on your github account. You clone that repository locally and do your builds/changes/updates/additions/removal in it. Once happy, you commit locally and that you push those changes to your github fork. From there you open a pull request and it will be based on your changes in the branch you created PRs from. If you are asked to squash commits, you squash changes locally via rebase and force push to your branch. After it, the PR will be updated. 

What is your current workflow?

**Comment by jgmills** [comment]
I'm following the procedure at: https://wiki.openindiana.org/oi/Contributing+to+hipster .  It says to create a fork on github, and use that to create a local clone.  It makes no mention of rebasing, so I haven't been doing that.  The new procedure, which I just heard about, is at: http://docs.openindiana.org/dev/userland/ .  It doesn't mention a fork, but does describe rebasing.  The two procedures are different.  The new one is also much more detailed.

I do have a series of changes that I don't want to push to my fork on github.  I also have changes that I've already pushed, and already had integrated into oi-userland.  I don't want to push them either.  My procedure is to start a new branch, add a bunch of files to the commit list, and do a commit on my local clone.  Then I push the new branch to my github fork.  If the commit looks good there, I prepare a PR on github, and submit that to oi-userland.  If I have to update the PR, I found that `push -f' works to get the new changes to my fork, but I couldn't find a way on github to get them from my fork to oi-userland.  I found that I had to delete the branch and re-push it to get it all the way.  Afterwards, I undo the commit, reset the file list, and start on a new commit with different files.

My fork on github is from November, when I started this project.  I spent several months making changes to about 100 components since that time.  Once I completed that, I wanted to submit these changes to oi-userland.

**Comment by alarcher** [comment]
@jgmills The pull request is automatically updated after you 'push -f' to your fork. Therefore no additional work (like deleting the branch and recommiting) is required. The PR tracks any change to the branch in your fork.

**Comment by jgmills** [comment]
Well the `push -f' seems to have worked this time.  I'm not sure why it didn't last time.

In any case, I've updated all the COMPONENT_REVISION lines now.

**Pull request merged**
