### PR TITLE
Salt

### PR DESCRIPTION
**Pull request by pyhalov**

### CODE REVIEW

**Comment by Toasterson** [comment]
Erm this mediation will break salt when switching python versions

**Comment by pyhalov** [comment]
Does it work with python 3?

**Comment by pyhalov** [comment]
Perhaps, we can build with PYTHON_VERSIONS= 2.7 3.4 3.5?

**Comment by Toasterson** [comment]
Nope not yet. they are still in the process of. WHich is why i mediated it to mediator salt

**Comment by pyhalov** [comment]
OK, let's do links non-mediated for now.

**Comment by Toasterson** [comment]
works aswell

**Pull request merged**
