### PR TITLE
Revise build options for encumbered libmad-0.15.1b and add REQUIRED_PACKAGES (basically none)

### PR DESCRIPTION
**Pull request by jimklimov**
Sort of follow-up to https://github.com/OpenIndiana/oi-userland/pull/1919

### CODE REVIEW

**Comment by pyhalov** [comment]
Where are REQUIRED_PACKAGES? :)

**Comment by jimklimov** [comment]
```
+REQUIRED_PACKAGES += system/library
```

It is there, all one that was detected ;)

**Comment by pyhalov** [comment]
then change commit message, it's misleading :)

**Comment by jimklimov** [comment]
(?) The line is added, it contains a REQUIRED_PACKAGES definition, work was done to inspect if any are needed (it is not a recipe untouched by this rehaul)...

**Pull request merged**
