### PR TITLE
Mate 1.22 part1

### PR DESCRIPTION
**Pull request by Mno-hime**
I started every GUI application visible from the MATE menu and basic functionality is ensured.

However, there seems to be some problems with icons in the default Nimbus theme. Some icons may be missing (Rhythmbox, gThumb, gtkam), "Help" icon is too big so that buttons in the row are too big ("Add to panel"), odd theming on checkbox in context menu ("Lock icon"). See the screenshots.

rhythmbox
gthumb
gtkam

help-icon-nimbus

lock-to-panel

### CODE REVIEW

**Comment by Mno-hime** [comment]
Updated MATE PRs to 1.22.1. Everything seems to be fine, but those icons (in the PR description).

Tested caja integration with Time Slider. Snapshot browsing, description, removal, and creation were tested in caja, also file retrieval from snapshot to desktop works.

**Comment by pyhalov** [comment]
mate-panel depends on libmate-menu >= 1.21.0, so should likely belong to another PR.

**Comment by pyhalov** [comment]
@Mno-hime https://github.com/OpenIndiana/oi-userland/pull/4973 fixes help icon sizes. Don't see rhythmbox issues. Will look at gtkam 'view thumbnails' issue.

**Comment by pyhalov** [comment]
gtkam "View Thumbnails" empty icon is not related to Mate update.

**Comment by Mno-hime** [comment]
`mate-panel`: https://github.com/OpenIndiana/oi-userland/pull/4976

**Pull request merged**
