### PR TITLE
Remove missing files from manifests

### PR DESCRIPTION
**Pull request by pyhalov**

### CODE REVIEW

**Comment by alarcher** [comment]
Do you know which package is missing on the build server?

**Comment by pyhalov** [comment]
Likely, apache fop is required. But we don't have it....

**Comment by alarcher** [comment]
I do not have extra packages on the machine I used for bumping the version and generating the manifests so this comes as a surprise.

**Comment by pyhalov** [comment]
can you recheck that gmake clean publish actually works? Perhaps, you had files left from old build?

**Comment by alarcher** [comment]
I just checked and they publish correctly, I will try to understand the difference.

**Comment by pyhalov** [comment]
I see 
'configure: WARNING: fop not found - documentation targets will be skipped' while running  configure

**Comment by alarcher** [comment]
Yes I have the same, this does not seem to concern the missing files.

**Comment by alarcher** [comment]
@pyhalov In any case, thank you for pushing the fixed manifests. :)

**Pull request merged**
