### PR TITLE
Update zeromq3 to 3.2.5

### PR DESCRIPTION
**Pull request by jimklimov**
Also: move to subdir; prepare mediation for concurrent other major versions (zeromq4 package in the works). Install (update) log:

```
root@jimoi:/root# pkg install -v pkg://oi-userland-jim/library/c++/zeromq@3.2.5-2015.0.2.0:20160329T140135Z
           Packages to install:         1
            Packages to update:         1
           Mediators to change:         1
     Estimated space available:   4.69 GB
Estimated space to be consumed: 673.85 MB
       Create boot environment:        No
Create backup boot environment:       Yes
          Rebuild boot archive:        No

Changed mediators:
  mediator zeromq:
           version: None -> 3 (system default)

Changed packages:
oi-userland-jim
  library/c++/zeromq3
    None -> 3.2.5-2015.0.2.0
openindiana.org -> oi-userland-jim
  library/c++/zeromq
    3.2.4-2014.1.3.1 -> 3.2.5-2015.0.2.0

DOWNLOAD                                PKGS         FILES    XFER (MB)   SPEED
Completed                                2/2         51/51      0.5/0.5    0B/s

PHASE                                          ITEMS
Removing old actions                           51/51
Installing new actions                       116/116
Updating modified actions                        9/9
Updating package state database                 Done 
Updating package cache                           1/1 
Updating image state                            Done 
Creating fast lookup database                   Done 
Updating package cache                           3/3 

### Direct files (/usr/lib/*.so.3.0.0 and /usr/share/zeromq3) and mediated links:

root@jimoi:/root# ls -la /usr/lib/{,amd64/}*zmq* /usr/share/man/man7/zmq.7 /usr/include/zmq* /usr/share/zeromq3/
lrwxrwxrwx 1 root root     36 Mar 29 16:56 /usr/include/zmq_utils.h -> ../share/zeromq3/include/zmq_utils.h
lrwxrwxrwx 1 root root     30 Mar 29 16:56 /usr/include/zmq.h -> ../share/zeromq3/include/zmq.h
lrwxrwxrwx 1 root root     15 Mar 29 16:56 /usr/lib/amd64/libzmq.so -> libzmq.so.3.0.0
lrwxrwxrwx 1 root root     15 Mar 29 16:56 /usr/lib/amd64/libzmq.so.3 -> libzmq.so.3.0.0
-r-xr-xr-x 1 root bin  893192 Mar 29 16:56 /usr/lib/amd64/libzmq.so.3.0.0
lrwxrwxrwx 1 root root     15 Mar 29 16:56 /usr/lib/libzmq.so -> libzmq.so.3.0.0
lrwxrwxrwx 1 root root     15 Mar 29 16:56 /usr/lib/libzmq.so.3 -> libzmq.so.3.0.0
-r-xr-xr-x 1 root bin  787964 Mar 29 16:56 /usr/lib/libzmq.so.3.0.0
lrwxrwxrwx 1 root root     43 Mar 29 16:56 /usr/share/man/man7/zmq.7 -> ../../../share/zeromq3/share/man/man7/zmq.7

/usr/share/zeromq3/:
total 13
drwxr-xr-x   5 root sys   5 Mar 29 16:56 .
drwxr-xr-x 208 root sys 209 Mar 29 16:56 ..
drwxr-xr-x   2 root sys   4 Mar 29 16:56 include
drwxr-xr-x   4 root sys   4 Mar 29 16:56 lib
drwxr-xr-x   3 root sys   3 Mar 29 16:56 share


root@jimoi:/root# ls -la /usr/lib/{,amd64/}pkgconfig/*zmq*
lrwxrwxrwx 1 root root 52 Mar 29 16:56 /usr/lib/amd64/pkgconfig/libzmq.pc -> ../../../share/zeromq3/lib/amd64/pkgconfig/libzmq.pc
lrwxrwxrwx 1 root root 43 Mar 29 16:56 /usr/lib/pkgconfig/libzmq.pc -> ../../share/zeromq3/lib/pkgconfig/libzmq.pc
```

One nit that partially seems unclean and partially is what I intended is `pkgconfig` content - it refers to the common `/usr/lib/*` location (so updates may be seamless), but also references the specific version number:

```
root@jimoi:/root# cat /usr/lib/amd64/pkgconfig/libzmq.pc
prefix=/usr
exec_prefix=${prefix}
libdir=/usr/lib/amd64
includedir=${prefix}/include

Name: libzmq
Description: 0MQ c++ library
Version: 3.2.5
Libs: -L${libdir} -lzmq
Cflags: -I${includedir}
```

### CODE REVIEW

**Comment by pyhalov** [comment]
Why do we create library/zeromq ? Isn't library/zeromq[345] enough? I'd agree if it was subcategory with at least 5 subdirectories but in this case I don't see advantages.

**Comment by jimklimov** [comment]
This is part of a bigger bunch of PR's (the rest posted recently) that IMHO would be a hassle to re-make with little gain, on the practical side.

On the logical part, software should use (or migrate to) the newest ABI as specified on the project website, so any number of older releases might be provided for backwards compatibility of binaries that linked against those filenames - but should not pollute the `components/library/*` namespace that would have quite many objects anyhow.

NB: As proposed at the moment, each of those `zeromq[345]` PR recipes provides a `zeromq.p5m` to pull in the contemporary component. In practice (checked) only the highest built version is applied (even if it was not the newest binary in the timeline of builds), so the mediated links point to the best ABI in the published repository.

**Comment by pyhalov** [comment]
Mediated .so link is good when it's not used by distribution. What are current zeromq consumers? pyzeromq? Will it compile with new major version? If not, mediated link will create problems on build host.

**Comment by jimklimov** [comment]
If it won't compile, it will be updated to modern variant ;)

## 

Typos courtesy of GMail on my Samsung Android
29.03.2016 22:12 пользователь "Alexander Pyhalov" notifications@github.com
написал:

**Pull request merged**
