### PR TITLE
update to samba-4.11.5

### PR DESCRIPTION
**Pull request by chincheta0815**
I was trying to update to version 4.11.5 but got a weird compile issue...
There is a "-m32" in the compiler command, although the Makefile tells to use 64 bits...
Can someone please help me, as I do not know where to start...

`[2770/3882] Compiling source4/lib/registry/tools/regshell.c
17:19:42 runner ['/usr/gcc/6/bin/gcc', '-m64', '-D_SAMBA_BUILD_=4', '-DHAVE_CONFIG_H=1', '-m64', '-O3', '-std=c99', '-D_POSIX_PTHREAD_SEMANTICS', '-MMD', '-D_GNU_SOURCE=1', '-D_XOPEN_SOURCE_EXTENDED=1', '-DHAVE_CONFIG_H=1', '-fPIC', '-D__STDC_WANT_LIB_EXT1__=1', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_REENTRANT', '-DSTATIC_regshell_MODULES=NULL', '-DSTATIC_regshell_MODULES_PROTO=extern void __regshell_dummy_module_proto(void)', '-m32', '-Isource4/lib/registry', '-I../../source4/lib/registry', '-Iinclude/public', '-I../../include/public', '-Isource4', '-I../../source4', '-Ilib', '-I../../lib', '-Isource4/lib', '-I../../source4/lib', '-Isource4/include', '-I../../source4/include', '-Iinclude', '-I../../include', '-Ilib/replace', '-I../../lib/replace', '-I.', '-I../..', '-Ilib/crypto', '-I../../lib/crypto', '-Ilibrpc', '-I../../librpc', '-Isource4/param', '-I../../source4/param', '-Isource4/heimdal/lib/asn1', '-I../../source4/heimdal/lib/asn1', '-Isource4/heimdal_build', '-I../../source4/heimdal_build', '-Isource4/lib/cmdline', '-I../../source4/lib/cmdline', '-Isource3', '-I../../source3', '-Isource3/include', '-I../../source3/include', '-Isource3/lib', '-I../../source3/lib', '-Isource4/heimdal/lib/com_err', '-I../../source4/heimdal/lib/com_err', '-Isource4/heimdal/lib/krb5', '-I../../source4/heimdal/lib/krb5', '-Isource4/heimdal/lib/gssapi', '-I../../source4/heimdal/lib/gssapi', '-Ibin/default/source4/heimdal/lib/asn1', '-Isource4/heimdal/lib/asn1', '-Ilib/tdb/include', '-I../../lib/tdb/include', '-Ilib/tevent', '-I../../lib/tevent', '-Ilib/talloc', '-I../../lib/talloc', '-Ilib/popt', '-I../../lib/popt', '-Ilibcli/netlogon', '-I../../libcli/netlogon', '-Isource4/libcli', '-I../../source4/libcli', '-Ilib/util/charset', '-I../../lib/util/charset', '-Isource4/auth', '-I../../source4/auth', '-Ilibcli/auth', '-I../../libcli/auth', '-Isource4/heimdal/lib/hcrypto', '-I../../source4/heimdal/lib/hcrypto', '-Isource4/heimdal/lib', '-I../../source4/heimdal/lib', '-Isource4/heimdal/include', '-I../../source4/heimdal/include', '-Ilib/ldb/include', '-I../../lib/ldb/include', '-Ilib/ldb', '-I../../lib/ldb', '-Ilib/dbwrap', '-I../../lib/dbwrap', '-Ilibds/common', '-I../../libds/common', '-Isource4/auth/kerberos', '-I../../source4/auth/kerberos', '-Iauth/credentials', '-I../../auth/credentials', '-Isource4/lib/socket', '-I../../source4/lib/socket', '-Isource4/auth/gensec', '-I../../source4/auth/gensec', '-Isource4/cluster', '-I../../source4/cluster', '-Isource4/heimdal/lib/wind', '-I../../source4/heimdal/lib/wind', '-Ilib/async_req', '-I../../lib/async_req', '-Isource4/dsdb', '-I../../source4/dsdb', '-Iauth', '-I../../auth', '-Isource4/heimdal/lib/hx509', '-I../../source4/heimdal/lib/hx509', '-Ilibcli/util', '-I../../libcli/util', '-Isource4/lib/http', '-I../../source4/lib/http', '-Ilib/param', '-I../../lib/param', '-Ilibcli/smb', '-I../../libcli/smb', '-Ithird_party/popt', '-I../../third_party/popt', '-Ilibcli/smbreadline', '-I../../libcli/smbreadline', '-Ilib/ldb-samba', '-I../../lib/ldb-samba', '-Ithird_party/zlib', '-I../../third_party/zlib', '-Ilibcli/security', '-I../../libcli/security', '-Ilib/socket', '-I../../lib/socket', '-Ilibcli/nbt', '-I../../libcli/nbt', '-Isource3/librpc', '-I../../source3/librpc', '-Isource4/lib/messaging', '-I../../source4/lib/messaging', '-Isource3/param', '-I../../source3/param', '-Iauth/gensec', '-I../../auth/gensec', '-Ilib/tdr', '-I../../lib/tdr', '-Isource4/heimdal/lib/gssapi/gssapi', '-I../../source4/heimdal/lib/gssapi/gssapi', '-Isource4/heimdal/lib/gssapi/spnego', '-I../../source4/heimdal/lib/gssapi/spnego', '-Isource4/heimdal/lib/gssapi/krb5', '-I../../source4/heimdal/lib/gssapi/krb5', '-Isource4/heimdal/lib/gssapi/mech', '-I../../source4/heimdal/lib/gssapi/mech', '-Ilibcli/cldap', '-I../../libcli/cldap', '-Isource4/heimdal/lib/roken', '-I../../source4/heimdal/lib/roken', '-Isource4/libcli/ldap', '-I../../source4/libcli/ldap', '-Ilib/smbconf', '-I../../lib/smbconf', '-Insswitch/libwbclient', '-I../../nsswitch/libwbclient', '-Insswitch', '-I../../nsswitch', '-Ilib/audit_logging', '-I../../lib/audit_logging', '-Ilib/tsocket', '-I../../lib/tsocket', '-Ilib/compression', '-I../../lib/compression', '-Isource4/lib/stream', '-I../../source4/lib/stream', '-Ilibcli/registry', '-I../../libcli/registry', '-Iauth/kerberos', '-I../../auth/kerberos', '-Ilib/addns', '-I../../lib/addns', '-Ilibcli/drsuapi', '-I../../libcli/drsuapi', '-Isource4/lib/tls', '-I../../source4/lib/tls', '-Isource4/lib/events', '-I../../source4/lib/events', '-Isource4/heimdal/lib/hcrypto/libtommath', '-I../../source4/heimdal/lib/hcrypto/libtommath', '-Ilibcli/dns', '-I../../libcli/dns', '-Isource4/heimdal/base', '-I../../source4/heimdal/base', '-Iauth/ntlmssp', '-I../../auth/ntlmssp', '-Ilibcli/ldap', '-I../../libcli/ldap', '-Ilib/krb5_wrap', '-I../../lib/krb5_wrap', '-Ilib/tdb', '-I../../lib/tdb', '-Isource4/librpc', '-I../../source4/librpc', '-Ilibcli/lsarpc', '-I../../libcli/lsarpc', '-Ilib/pthreadpool', '-I../../lib/pthreadpool', '-Isource4/libcli/smb2', '-I../../source4/libcli/smb2', '-Idynconfig', '-I../../dynconfig', '-I/usr/include/p11-kit-1', '-I/usr/include/ncurses/ncurses', '-I/usr/include/ncurses', '-I/usr/include/jansson', '-D__EXTENSIONS__', '-D_XPG6', '../../source4/lib/registry/tools/regshell.c', '-c', '-o/export/home/github.com/oi-userland.git/components/network/samba/build/amd64/bin/default/source4/lib/registry/tools/regshell.c.15.o', '-D_LARGEFILE64_SOURCE', '-D_XOPEN_SOURCE=600', '-D__EXTENSIONS__=1', '-D_XPG6', '-I/usr/include/openldap']
`

### CODE REVIEW

**Comment by pyhalov** [comment]
Does it come from pkgconfig?

**Comment by chincheta0815** [comment]
> Does it come from pkgconfig?

After digging a while I would say: Yes.
But all attempts to change it did fail so far...
The build process does not use pkg-config and the *.pc files found in "/usr/*/amd64/". It uses them in the 32bits dirs.
Setting PKGCONFIG and PKG_CONFIG_PATH did not show an effect...
Strangely it worked with samba-4.11.4 perfectly...

**Comment by chincheta0815** [comment]
Got it. There was an issue with ncurses5-config.
There was no gnu-amd64 binary in the path...
Maybe it would make sense to add some kind of "PATH.gnu.$(BITS)" etc. to the macros?

**Comment by chincheta0815** [comment]
@pyhalov Just saw that you are appointed as an reviewer for some build-fixes. That here updates the samba packages and also fixes the build. Maybe this will avoid work for you.

**Pull request merged**
