### PR TITLE
perl-534: update to 5.34.1

### PR DESCRIPTION
**Pull request by mtelka**

### CODE REVIEW

**Comment by AndWac** [comment]
Did you run gmake test? I got new errors:
-All tests successful.
+Failed 9 tests out of 2543, 99.65% okay.
+	../cpan/ExtUtils-Install/t/Packlist.t
+	../cpan/ExtUtils-Install/t/can_write_dir.t
+	../cpan/ExtUtils-MakeMaker/t/Mkbootstrap.t
+	../cpan/ExtUtils-Manifest/t/Manifest.t
+	../cpan/IO-Compress/t/cz-14gzopen.t
+	../ext/File-Glob/t/basic.t
+	op/require_errors.t
+	op/stat.t
+	run/dtrace.t

**Comment by mtelka** [comment]
> Did you run gmake test? I got new errors:
> -All tests successful.
> +Failed 9 tests out of 2543, 99.65% okay.

Yes, I did.  At least twice and everything passed (IOW, no differences were found).  I'll try once more and let you know.

**Comment by mtelka** [comment]
Passed again:

```
$ md5sum build/test/amd64/results-64.snapshot test/results-i386.master 
2832657998ec8214a9a3e9e713d9e4ee  build/test/amd64/results-64.snapshot
2832657998ec8214a9a3e9e713d9e4ee  test/results-i386.master
$
```

Maybe the difference is that my system is 2 weeks old?  I'll try to update, reboot and try to run the test again.

**Comment by mtelka** [comment]
Updated (everything is up to date as of yesterday evening), rebooted, gmake clobber, gmake test => same results.
Maybe the list of installed packages differs in a way that causes test failures at your side?
BTW, I run tests as non-root user.

Could you please try to find why your tests fail?  Thanks.

**Comment by mtelka** [comment]
I just noticed that t/run/dtrace is usually skipped (likely because it needs to be run as root, or otherwise privileged user), but in your case it was executed and failed, so I assume you ran tests as root.

**Comment by AndWac** [comment]
My user account had escalated privileges. Removing them solved the different results problem.

**Pull request merged**
