### PR TITLE
openjdk-8: update to 1.8.152

### PR DESCRIPTION
**Pull request by prakashsurya**
This is my first attempt at contributing to oi-userland, so apologies if
I'm doing anything incorrectly. Further, I haven't tested this yet, but
I wanted to open the PR in hopes of getting some feedback in case I'm
doing something wrong (which could invalidate any testing that I do).

The changes to the `Makefile` are straightforward so I won't spend time
explaining those.

The changes to the `patches` directory were generated by replacing the
existing `patches` directory, with the `patches` directory from Joyent's
pkgsrc repository. For example:

    $ git clone https://github.com/OpenIndiana/oi-userland.git ~/oi-userland
    $ git clone https://github.com/joyent/pkgsrc.git ~/pkgsrc

    $ cd ~/pkgsrc
    $ git checkout 91fc60ec7ee226677915690b7dabe15eb43e235d

    $ cd ~/oi-userland/components/runtime/openjdk-8
    $ rm -r patches
    $ cp -r ~/pkgsrc/lang/openjdk8/patches .
    $ find patches -type f | sed -e "p;s/$/.patch/" | xargs -n2 mv

I don't know if this was the correct thing to do, so please let me know
if I should be updating the `patches` directory some other way.

If what I've done so far is correct, I'll look into testing this by
building and installing the new package, and then performaing a full
nightly build of illumos-gate with the new OpenJDK installed.

### CODE REVIEW

**Comment by pyhalov** [comment]
You shouldn't have replaced all patches directory. We and pkgsrc have a bit different openjdk layout and some patches were modified, some added. I'd just replaced the patches which were touched with last openjdk update. If everything is fine, you should see that pkgsrc update commit and our commit are mostly identical.

**Comment by prakashsurya** [comment]
@pyhalov does this look better?

**Comment by pyhalov** [comment]
Yes, seems fine.

**Comment by pyhalov** [comment]
Have you checked that 
- [ ] component builds
- [ ] no new files appeared (do gmake sample-manifest && compare results with git diff )
- [ ] new openjdk works as expected on simple hello worlds
- [ ] illumos-gate compiles with it
?

**Comment by prakashsurya** [comment]
I ran into a build failure when building this package last week. I'll try and pick this up again soon; got pulled off to work on something else.

**Comment by alarcher** [comment]
@prakashsurya Do you know if this version has gcc 6 friendly patches applied?

**Comment by alarcher** [comment]
@prakashsurya @pyhalov Since this version has gcc 6 patches applied I have built it, published it to the gcc-6 repository, rebuilt dependent components like tomcat, and just built illumos-gate in the same zone.

**Comment by prakashsurya** [comment]
Sorry for the delays. Do I still need to do more testing, or is what @alarcher has done sufficient?

**Comment by pyhalov** [comment]
Was merged as part of #3014

**Pull request closed without merging**
