### PR TITLE
gcc-7: add retpolines patch from rm

### PR DESCRIPTION
**Pull request by alarcher**

### CODE REVIEW

**Comment by pyhalov** [comment]
```
$ diff -u test/results-i386.master build/test/i86/results-32.snapshot 
--- test/results-i386.master    2019-06-20 08:46:44.126232751 +0000
+++ build/test/i86/results-32.snapshot  2019-08-10 06:01:14.569539372 +0000
@@ -87498,8 +87498,7 @@
 FAIL: gcc.dg/initpri1.c execution test
 FAIL: gcc.dg/initpri3.c execution test
 XPASS: gcc.dg/pr78768.c -Wformat-overflow (test for warnings, line 11)
-FAIL: gcc.dg/signbit-sa.c (test for excess errors)
-FAIL: gcc.dg/visibility-22.c execution test
+FAIL: gcc.dg/unroll-2.c  (test for warnings, line 28)
 XPASS: gcc.dg/guality/example.c   -O0  execution test
 XPASS: gcc.dg/guality/example.c   -O1  execution test
 XPASS: gcc.dg/guality/example.c   -O2  execution test
@@ -87584,7 +87583,6 @@
 FAIL: gcc.dg/guality/vla-1.c   -Os  line 17 sizeof (a) == 6
 FAIL: gcc.dg/guality/vla-1.c   -O2 -flto -flto-partition=none  line 17 sizeof (a) == 6
 FAIL: gcc.dg/guality/vla-1.c   -O2 -flto  line 17 sizeof (a) == 6
-FAIL: gcc.dg/torture/pr60092.c   -O0  execution test
 FAIL: gcc.target/i386/align-limit.c scan-assembler .p2align 6,,1
 FAIL: gcc.target/i386/avx512vl-pr79299-1.c (test for excess errors)
 FAIL: gcc.target/i386/avx512vl-pr79299-2.c (test for excess errors)
@@ -87601,18 +87599,9 @@
 FAIL: gcc.target/i386/indirect-thunk-7.c scan-assembler jmp[ \\t]*__x86_indirect_thunk_(r|e)ax
 FAIL: gcc.target/i386/indirect-thunk-attr-1.c scan-assembler jmp[ \\t]*__x86_indirect_thunk_(r|e)ax
 FAIL: gcc.target/i386/indirect-thunk-attr-2.c scan-assembler jmp[ \\t]*__x86_indirect_thunk_(r|e)ax
-FAIL: gcc.target/i386/indirect-thunk-attr-5.c scan-assembler call[ \\t]*__x86_indirect_thunk_(r|e)ax
-FAIL: gcc.target/i386/indirect-thunk-attr-6.c scan-assembler call[ \\t]*__x86_indirect_thunk_(r|e)ax
-FAIL: gcc.target/i386/indirect-thunk-attr-7.c scan-assembler jmp[ \\t]*__x86_indirect_thunk_(r|e)ax
 FAIL: gcc.target/i386/indirect-thunk-bnd-1.c scan-assembler bnd call[ \\t]*__x86_indirect_thunk_bnd_eax
 FAIL: gcc.target/i386/indirect-thunk-bnd-2.c scan-assembler bnd call[ \\t]*__x86_indirect_thunk_bnd_(r|e)ax
-FAIL: gcc.target/i386/indirect-thunk-extern-1.c scan-assembler jmp[ \\t]*__x86_indirect_thunk_(r|e)ax
-FAIL: gcc.target/i386/indirect-thunk-extern-2.c scan-assembler jmp[ \\t]*__x86_indirect_thunk_(r|e)ax
-FAIL: gcc.target/i386/indirect-thunk-extern-3.c scan-assembler call[ \\t]*__x86_indirect_thunk_(r|e)ax
-FAIL: gcc.target/i386/indirect-thunk-extern-4.c scan-assembler call[ \\t]*__x86_indirect_thunk_(r|e)ax
-FAIL: gcc.target/i386/indirect-thunk-extern-7.c scan-assembler jmp[ \\t]*__x86_indirect_thunk_(r|e)ax
 FAIL: gcc.target/i386/indirect-thunk-register-1.c scan-assembler jmp[ \\t]*__x86_indirect_thunk_(r|e)ax
-FAIL: gcc.target/i386/indirect-thunk-register-3.c scan-assembler jmp[ \\t]*__x86_indirect_thunk_(r|e)ax
 FAIL: gcc.target/i386/pad-1.c scan-assembler rep
 FAIL: gcc.target/i386/pad-2.c scan-assembler-times nop 8
 FAIL: gcc.target/i386/pad-5a.c scan-assembler-times nop 2
@@ -87639,7 +87628,6 @@
 FAIL: gcc.target/i386/ret-thunk-12.c scan-assembler call[ \\t]*__x86_indirect_thunk_(r|e)ax
 FAIL: gcc.target/i386/ret-thunk-12.c scan-assembler __x86_indirect_thunk_(r|e)ax:
 FAIL: gcc.target/i386/ret-thunk-13.c scan-assembler jmp[ \\t]*__x86_return_thunk
-FAIL: gcc.target/i386/ret-thunk-14.c scan-assembler call[ \\t]*__x86_indirect_thunk_(r|e)ax
 FAIL: gcc.target/i386/ret-thunk-15.c scan-assembler jmp[ \\t]*__x86_return_thunk
 FAIL: gcc.target/i386/ret-thunk-15.c scan-assembler call[ \\t]*__x86_indirect_thunk_(r|e)ax
 FAIL: gcc.target/i386/ret-thunk-22.c scan-assembler jmp[ \\t]*__x86_return_thunk_ecx
@@ -87663,8 +87651,8 @@
 
                === gcc Summary for unix/ ===
 
-# of expected passes           121279
-# of unexpected failures       138
+# of expected passes           121291
+# of unexpected failures       126
 # of unexpected successes      25
 # of expected failures         374
 # of unresolved testcases      2
@@ -137551,8 +137539,8 @@
 FAIL: gcc.dg/pr30949.c  (test for errors, line 9)
 FAIL: gcc.dg/pr30949.c (test for excess errors)
 FAIL: gcc.dg/pr30951.c (test for excess errors)
-ERROR: gcc.dg/pr30957-1.c: no files matched glob pattern "hard_float10262.c.[0-9][0-9][0-9]r.expand" for " dg-require-effective-target 4 hard_float "
-ERROR: gcc.dg/pr30957-1.c: no files matched glob pattern "hard_float10262.c.[0-9][0-9][0-9]r.expand" for " dg-require-effective-target 4 hard_float "
+ERROR: gcc.dg/pr30957-1.c: no files matched glob pattern "hard_float929.c.[0-9][0-9][0-9]r.expand" for " dg-require-effective-target 4 hard_float "
+ERROR: gcc.dg/pr30957-1.c: no files matched glob pattern "hard_float929.c.[0-9][0-9][0-9]r.expand" for " dg-require-effective-target 4 hard_float "
 FAIL: gcc.dg/pr31096-1.c (test for excess errors)
 UNRESOLVED: gcc.dg/pr31096-1.c scan-tree-dump-times optimized "\\\\(D\\\\) \\\\* 4" 24
 UNRESOLVED: gcc.dg/pr31096-1.c scan-tree-dump-times optimized "\\\\(D\\\\) \\\\* 4294967294" 12
@@ -178315,8 +178303,8 @@
 
                === gcc Summary ===
 
-# of expected passes           122886
-# of unexpected failures       64201
+# of expected passes           122898
+# of unexpected failures       64189
 # of unexpected successes      67
 # of expected failures         431
 # of unresolved testcases      26525
@@ -178327,10 +178315,21 @@
 
 
 Running target unix/
+FAIL: gfortran.dg/do_iterator.f90   -O  changing do-iterator 3 (test for errors, line 9)
+FAIL: gfortran.dg/do_iterator.f90   -O  changing do-iterator 3 (test for errors, line 10)
+FAIL: gfortran.dg/goacc/declare-2.f95   -O   (test for errors, line 33)
+FAIL: gfortran.dg/goacc/declare-2.f95   -O   (test for errors, line 34)
+FAIL: gfortran.dg/goacc/declare-2.f95   -O   (test for errors, line 36)
+FAIL: gfortran.dg/goacc/declare-2.f95   -O   (test for errors, line 46)
+FAIL: gfortran.dg/goacc/declare-2.f95   -O   (test for errors, line 47)
+FAIL: gfortran.dg/goacc/declare-2.f95   -O   (test for errors, line 54)
+FAIL: gfortran.dg/goacc/declare-2.f95   -O   (test for errors, line 62)
+FAIL: gfortran.dg/goacc/declare-2.f95   -O   (test for errors, line 69)
 
                === gfortran Summary for unix/ ===
 
-# of expected passes           45429
+# of expected passes           45419
+# of unexpected failures       10
 # of expected failures         77
 # of unsupported tests         190
 
@@ -217369,8 +217368,8 @@
 
                === gfortran Summary ===
 
-# of expected passes           45520
-# of unexpected failures       24449
+# of expected passes           45510
+# of unexpected failures       24459
 # of expected failures         121
 # of unresolved testcases      14564
 # of untested testcases                1752
@@ -224080,12 +224079,15 @@
 Running target unix/
 FAIL: 18_support/new_aligned.cc execution test
 FAIL: 23_containers/vector/capacity/resize/1.cc (test for excess errors)
+FAIL: 26_numerics/headers/cmath/dr550.cc (test for excess errors)
+UNRESOLVED: 26_numerics/headers/cmath/dr550.cc compilation failed to produce executable
 
                === libstdc++ Summary for unix/ ===
 
-# of expected passes           11382
-# of unexpected failures       2
+# of expected passes           11380
+# of unexpected failures       3
 # of expected failures         68
+# of unresolved testcases      1
 # of unsupported tests         616
 
 Running target unix//-msave-args
@@ -224103,9 +224105,10 @@
 
                === libstdc++ Summary ===
 
-# of expected passes           11382
-# of unexpected failures       2
+# of expected passes           11380
+# of unexpected failures       3
 # of expected failures         68
+# of unresolved testcases      1
 # of unsupported tests         616
 
 Compiler version: 7.4.0 (OpenIndiana 7.4.0-il-0) 
alp@buildzone:~/srcs/oi-userland/components/developer/gcc-7$ diff -u test/results-i386.master build/test/i86/results-32.snapshot  |less 
alp@buildzone:~/srcs/oi-userland/components/developer/gcc-7$ diff -u test/results-i386.master build/test/i86/results-32.snapshot   
--- test/results-i386.master    2019-06-20 08:46:44.126232751 +0000
+++ build/test/i86/results-32.snapshot  2019-08-10 06:01:14.569539372 +0000
@@ -87498,8 +87498,7 @@
 FAIL: gcc.dg/initpri1.c execution test
 FAIL: gcc.dg/initpri3.c execution test
 XPASS: gcc.dg/pr78768.c -Wformat-overflow (test for warnings, line 11)
-FAIL: gcc.dg/signbit-sa.c (test for excess errors)
-FAIL: gcc.dg/visibility-22.c execution test
+FAIL: gcc.dg/unroll-2.c  (test for warnings, line 28)
 XPASS: gcc.dg/guality/example.c   -O0  execution test
 XPASS: gcc.dg/guality/example.c   -O1  execution test
 XPASS: gcc.dg/guality/example.c   -O2  execution test
@@ -87584,7 +87583,6 @@
 FAIL: gcc.dg/guality/vla-1.c   -Os  line 17 sizeof (a) == 6
 FAIL: gcc.dg/guality/vla-1.c   -O2 -flto -flto-partition=none  line 17 sizeof (a) == 6
 FAIL: gcc.dg/guality/vla-1.c   -O2 -flto  line 17 sizeof (a) == 6
-FAIL: gcc.dg/torture/pr60092.c   -O0  execution test
 FAIL: gcc.target/i386/align-limit.c scan-assembler .p2align 6,,1
 FAIL: gcc.target/i386/avx512vl-pr79299-1.c (test for excess errors)
 FAIL: gcc.target/i386/avx512vl-pr79299-2.c (test for excess errors)
@@ -87601,18 +87599,9 @@
 FAIL: gcc.target/i386/indirect-thunk-7.c scan-assembler jmp[ \\t]*__x86_indirect_thunk_(r|e)ax
 FAIL: gcc.target/i386/indirect-thunk-attr-1.c scan-assembler jmp[ \\t]*__x86_indirect_thunk_(r|e)ax
 FAIL: gcc.target/i386/indirect-thunk-attr-2.c scan-assembler jmp[ \\t]*__x86_indirect_thunk_(r|e)ax
-FAIL: gcc.target/i386/indirect-thunk-attr-5.c scan-assembler call[ \\t]*__x86_indirect_thunk_(r|e)ax
-FAIL: gcc.target/i386/indirect-thunk-attr-6.c scan-assembler call[ \\t]*__x86_indirect_thunk_(r|e)ax
-FAIL: gcc.target/i386/indirect-thunk-attr-7.c scan-assembler jmp[ \\t]*__x86_indirect_thunk_(r|e)ax
 FAIL: gcc.target/i386/indirect-thunk-bnd-1.c scan-assembler bnd call[ \\t]*__x86_indirect_thunk_bnd_eax
 FAIL: gcc.target/i386/indirect-thunk-bnd-2.c scan-assembler bnd call[ \\t]*__x86_indirect_thunk_bnd_(r|e)ax
-FAIL: gcc.target/i386/indirect-thunk-extern-1.c scan-assembler jmp[ \\t]*__x86_indirect_thunk_(r|e)ax
-FAIL: gcc.target/i386/indirect-thunk-extern-2.c scan-assembler jmp[ \\t]*__x86_indirect_thunk_(r|e)ax
-FAIL: gcc.target/i386/indirect-thunk-extern-3.c scan-assembler call[ \\t]*__x86_indirect_thunk_(r|e)ax
-FAIL: gcc.target/i386/indirect-thunk-extern-4.c scan-assembler call[ \\t]*__x86_indirect_thunk_(r|e)ax
-FAIL: gcc.target/i386/indirect-thunk-extern-7.c scan-assembler jmp[ \\t]*__x86_indirect_thunk_(r|e)ax
 FAIL: gcc.target/i386/indirect-thunk-register-1.c scan-assembler jmp[ \\t]*__x86_indirect_thunk_(r|e)ax
-FAIL: gcc.target/i386/indirect-thunk-register-3.c scan-assembler jmp[ \\t]*__x86_indirect_thunk_(r|e)ax
 FAIL: gcc.target/i386/pad-1.c scan-assembler rep
 FAIL: gcc.target/i386/pad-2.c scan-assembler-times nop 8
 FAIL: gcc.target/i386/pad-5a.c scan-assembler-times nop 2
@@ -87639,7 +87628,6 @@
 FAIL: gcc.target/i386/ret-thunk-12.c scan-assembler call[ \\t]*__x86_indirect_thunk_(r|e)ax
 FAIL: gcc.target/i386/ret-thunk-12.c scan-assembler __x86_indirect_thunk_(r|e)ax:
 FAIL: gcc.target/i386/ret-thunk-13.c scan-assembler jmp[ \\t]*__x86_return_thunk
-FAIL: gcc.target/i386/ret-thunk-14.c scan-assembler call[ \\t]*__x86_indirect_thunk_(r|e)ax
 FAIL: gcc.target/i386/ret-thunk-15.c scan-assembler jmp[ \\t]*__x86_return_thunk
 FAIL: gcc.target/i386/ret-thunk-15.c scan-assembler call[ \\t]*__x86_indirect_thunk_(r|e)ax
 FAIL: gcc.target/i386/ret-thunk-22.c scan-assembler jmp[ \\t]*__x86_return_thunk_ecx
@@ -87663,8 +87651,8 @@
 
                === gcc Summary for unix/ ===
 
-# of expected passes           121279
-# of unexpected failures       138
+# of expected passes           121291
+# of unexpected failures       126
 # of unexpected successes      25
 # of expected failures         374
 # of unresolved testcases      2
@@ -137551,8 +137539,8 @@
 FAIL: gcc.dg/pr30949.c  (test for errors, line 9)
 FAIL: gcc.dg/pr30949.c (test for excess errors)
 FAIL: gcc.dg/pr30951.c (test for excess errors)
-ERROR: gcc.dg/pr30957-1.c: no files matched glob pattern "hard_float10262.c.[0-9][0-9][0-9]r.expand" for " dg-require-effective-target 4 hard_float "
-ERROR: gcc.dg/pr30957-1.c: no files matched glob pattern "hard_float10262.c.[0-9][0-9][0-9]r.expand" for " dg-require-effective-target 4 hard_float "
+ERROR: gcc.dg/pr30957-1.c: no files matched glob pattern "hard_float929.c.[0-9][0-9][0-9]r.expand" for " dg-require-effective-target 4 hard_float "
+ERROR: gcc.dg/pr30957-1.c: no files matched glob pattern "hard_float929.c.[0-9][0-9][0-9]r.expand" for " dg-require-effective-target 4 hard_float "
 FAIL: gcc.dg/pr31096-1.c (test for excess errors)
 UNRESOLVED: gcc.dg/pr31096-1.c scan-tree-dump-times optimized "\\\\(D\\\\) \\\\* 4" 24
 UNRESOLVED: gcc.dg/pr31096-1.c scan-tree-dump-times optimized "\\\\(D\\\\) \\\\* 4294967294" 12
@@ -178315,8 +178303,8 @@
 
                === gcc Summary ===
 
-# of expected passes           122886
-# of unexpected failures       64201
+# of expected passes           122898
+# of unexpected failures       64189
 # of unexpected successes      67
 # of expected failures         431
 # of unresolved testcases      26525
@@ -178327,10 +178315,21 @@
 
 
 Running target unix/
+FAIL: gfortran.dg/do_iterator.f90   -O  changing do-iterator 3 (test for errors, line 9)
+FAIL: gfortran.dg/do_iterator.f90   -O  changing do-iterator 3 (test for errors, line 10)
+FAIL: gfortran.dg/goacc/declare-2.f95   -O   (test for errors, line 33)
+FAIL: gfortran.dg/goacc/declare-2.f95   -O   (test for errors, line 34)
+FAIL: gfortran.dg/goacc/declare-2.f95   -O   (test for errors, line 36)
+FAIL: gfortran.dg/goacc/declare-2.f95   -O   (test for errors, line 46)
+FAIL: gfortran.dg/goacc/declare-2.f95   -O   (test for errors, line 47)
+FAIL: gfortran.dg/goacc/declare-2.f95   -O   (test for errors, line 54)
+FAIL: gfortran.dg/goacc/declare-2.f95   -O   (test for errors, line 62)
+FAIL: gfortran.dg/goacc/declare-2.f95   -O   (test for errors, line 69)
 
                === gfortran Summary for unix/ ===
 
-# of expected passes           45429
+# of expected passes           45419
+# of unexpected failures       10
 # of expected failures         77
 # of unsupported tests         190
 
@@ -217369,8 +217368,8 @@
 
                === gfortran Summary ===
 
-# of expected passes           45520
-# of unexpected failures       24449
+# of expected passes           45510
+# of unexpected failures       24459
 # of expected failures         121
 # of unresolved testcases      14564
 # of untested testcases                1752
@@ -224080,12 +224079,15 @@
 Running target unix/
 FAIL: 18_support/new_aligned.cc execution test
 FAIL: 23_containers/vector/capacity/resize/1.cc (test for excess errors)
+FAIL: 26_numerics/headers/cmath/dr550.cc (test for excess errors)
+UNRESOLVED: 26_numerics/headers/cmath/dr550.cc compilation failed to produce executable
 
                === libstdc++ Summary for unix/ ===
 
-# of expected passes           11382
-# of unexpected failures       2
+# of expected passes           11380
+# of unexpected failures       3
 # of expected failures         68
+# of unresolved testcases      1
 # of unsupported tests         616
 
 Running target unix//-msave-args
@@ -224103,9 +224105,10 @@
 
                === libstdc++ Summary ===
 
-# of expected passes           11382
-# of unexpected failures       2
+# of expected passes           11380
+# of unexpected failures       3
 # of expected failures         68
+# of unresolved testcases      1
 # of unsupported tests         616
 
 Compiler version: 7.4.0 (OpenIndiana 7.4.0-il-0) 
```

However, I'm not sure that the latest change has such influence, perhaps it's previous commits to gcc-7.

**Comment by alarcher** [comment]
@pyhalov The problem comes from one recent patch from illumos/gcc that throws an error when -msave-args is used in 32-bit, while previously it silently ignored it. Probably we need to pass -m64 to run the tests in 64-bit.

**Comment by pyhalov** [comment]
Well, at least update expected test outptut.

**Comment by alarcher** [comment]
@pyhalov I am trying to fix the tests on this version.

**Comment by alarcher** [comment]
@pyhalov The GCC testsuite is fine and illumos-gate builds are OK so I will merge this later today.

**Pull request merged**
