### PR TITLE
9957 mate-about-me can't change user password

### PR DESCRIPTION
**Pull request by pyhalov**

### CODE REVIEW

**Comment by pyhalov** [comment]
Corresponding Mate issue/PR: https://github.com/mate-desktop/mate-control-center/issues/384 https://github.com/mate-desktop/mate-control-center/pull/383

**Comment by alarcher** [comment]
@pyhalov I have built and installed: after entering my current password and clicking on the button password verification does not complete.

**Comment by pyhalov** [comment]
What if you run sudo ```truss -t write -f -p `pgrep mate-about-me` ``` while application is working and click "Authenticate" ? (don't forget to replace password if you paste output here :))

**Comment by pyhalov** [comment]
You should see something like 
```
793:   write(4, " E n t e r   e x i s t i".., 31)      = 31
1779/1:         write(4, "01\0\0\0\0\0\0\0", 8)                 = 8
1793:   write(4, "\n", 1)                               = 1
1779/1:         write(12, "REAL_PASSWORD\n", 8)                = 8
1779/1:         write(4, "01\0\0\0\0\0\0\0", 8)                 = 8
1779/1:         write(4, "01\0\0\0\0\0\0\0", 8)                 = 8
1779/1:         write(4, "01\0\0\0\0\0\0\0", 8)                 = 8
1793:   write(4, " N e w   P a s s w o r d".., 14)      = 14
````

**Comment by pyhalov** [comment]
We have additional issue to fix here - mate-about-me should know how to handle all pam_authtok_check error  messages https://github.com/mate-desktop/mate-control-center/pull/385

**Comment by pyhalov** [comment]
Updated mate-control-center PR: https://github.com/mate-desktop/mate-control-center/pull/386

**Comment by pyhalov** [comment]
@alarcher: Can you check this?

**Comment by pyhalov** [comment]
@alarcher Fixed two more bugs, does it help?

**Pull request merged**
