### PR TITLE
Update golang to 1.13.4

### PR DESCRIPTION
**Pull request by Toasterson**

### CODE REVIEW

**Comment by Mno-hime** [comment]
Better rebase or it brings a lot of weird stuff, see https://github.com/OpenIndiana/oi-userland/commit/4fd6b4b600e5ff0be9a54ea8e6446bc78df6c85b.

**Comment by Toasterson** [comment]
??? why is that not showing up in the files_changed window.  4fd6b4b was mandated by github because it found the whole branch to be conflicting. I think I broke github.

**Comment by Toasterson** [comment]
You are right github blew the merge Never press the resolve conflicts button ....

**Comment by Toasterson** [comment]
Fixed

**Review by Mno-hime — APPROVED** [review]

**Pull request merged**
