### PR TITLE
aria2: Add c-ares support.

### PR DESCRIPTION
**Pull request by mvwieringen**

### CODE REVIEW

**Comment by AndWac** [comment]
Are you still interested to get this merged?

**Comment by mvwieringen** [comment]
I think it makes more sense to first merge the support libs. e.g. c-ares. When that is merged this can also go in.

**Comment by AndWac** [comment]
Sorry, my comment was ment for #7126 where I have requested some changes.

**Comment by mvwieringen** [comment]
Ok great but those were addressed in a force push of the PR as far as I remember or is something still not ok ?

**Comment by AndWac** [comment]
Sorry, that was my fault. I started a review and forgot to press the "submit review" button.

**Comment by AndWac** [comment]
pkg5 also needs to be updated.

**Comment by mvwieringen** [comment]
Ok rebased and pushed.

**Review by AndWac — APPROVED** [review]

**Pull request merged**
