### PR TITLE
Update openconnect and vpnc-scripts

### PR DESCRIPTION
**Pull request by Mno-hime**
Should be merged after https://github.com/OpenIndiana/oi-userland/pull/5044 (there will be conflict in `openconnect`).

Anyone having Cisco VPN around to test this couple?

### CODE REVIEW

**Comment by jimklimov** [comment]
Tried to find the VPN server I used at that time, but seems it is no longer available so can't quite test the changes :(

**Comment by cgrzemba** [comment]
I use openconnect and Cisco VPN. How can I help? compile myself or are there the bins anywhere?
(also vpnc with fritzbox and other)

**Comment by Mno-hime** [comment]
@cgrzemba Here's the binary package you can install, it contains openconnect & vpnc-scripts: 
[openconnect+vpnc_scripts.p5p.gz](https://github.com/OpenIndiana/oi-userland/files/3971778/openconnect%2Bvpnc_scripts.p5p.gz)

Unpack it and the install like this:
```
pfexec pkg apply-hot-fix -v /tmp/openconnect+vpnc_scripts.p5p
```
Let me know if it worked for you. Thanks!

**Comment by cgrzemba** [comment]
Have the bits contained in package tested. openconnect with Cisco VPN and vpnc with fritzbox and PaloAlto
 All works for me in common manner.

**Comment by Mno-hime** [comment]
Thank you @cgrzemba!

**Pull request merged**
