### PR TITLE
ffmpeg: bump to 3.2.14

### PR DESCRIPTION
**Pull request by alarcher**

### CODE REVIEW

**Comment by pyhalov** [comment]
Why is it marked as "pending"? Does current vlc or audacity strictly require ffmpeg 2?

**Comment by alarcher** [comment]
Yes, vlc 2.x requires ffmpeg 2 although some distros hack around to support more recent versions.
I did not have time to follow up on that given the priority on gcc.
I have used vlc 3.x for some time before moving to the gcc-8 repository, so it would be possible to bump to latest.

**Comment by alarcher** [comment]
@pyhalov This ffmpeg version works with 3.0.4

**Comment by Mno-hime** [comment]
I don't see accelerated H.264 on Ivy Bridge laptop, see https://github.com/OpenIndiana/oi-userland/pull/4035#issuecomment-513556751.

**Comment by Mno-hime** [comment]
Added H.265 support, requires https://github.com/OpenIndiana/oi-userland/pull/5150 to be merged first.

**Pull request merged**
