### PR TITLE
perl/Mojo-Log-Clearable: rebuild for Perl 5.38

### PR DESCRIPTION
**Pull request by mtelka**

### CODE REVIEW

**Comment by AndWac** [comment]
Can you please create a PR with more than one of these simple changes?

**Comment by mtelka** [comment]
It is far easier for me to do it this way.  And, I also prefer to do not combine changes for different components into one single commit.

Thank you.

**Comment by AndWac** [comment]
You can have multiple commits in a single PR.

**Comment by mtelka** [comment]
Yes, but on merge they will be combined to single commit.

**Comment by mtelka** [comment]
Sorry, I mistakenly deleted the branch.

**Pull request closed without merging**
