### PR TITLE
vim: bump to 8.1.0412

### PR DESCRIPTION
**Pull request by kenmays**

### CODE REVIEW

**Comment by alarcher** [comment]
Patches need update apparently.

**Comment by Mno-hime** [comment]
Why do you remove the var_tabstops patch?

**Comment by kenmays** [comment]
Integrated in v8.1.0412.

**Comment by alarcher** [comment]
@kenmays Did you delete your branch?

**Comment by kenmays** [comment]
@alarcher - Pushed to #4460

**Pull request closed without merging**
