### PR TITLE
mc: Set default hotkey fg/bg colors to lightgray/black

### PR DESCRIPTION
**Pull request by Mno-hime**
This is unblocking https://github.com/OpenIndiana/oi-userland/pull/4745.

### CODE REVIEW

**Comment by pyhalov** [comment]
What is generating this \E315m?

**Comment by Mno-hime** [comment]
I don't know. How do I find out?

**Comment by pyhalov** [comment]
Do you have a link to a full conversation with ncurses devs (cited in https://github.com/OpenIndiana/oi-userland/pull/4745#issuecomment-497346383)?

**Comment by Mno-hime** [comment]
> Do you have a link to a full conversation with ncurses devs (cited in [#4745 (comment)](https://github.com/OpenIndiana/oi-userland/pull/4745#issuecomment-497346383))?

I've just forwarded you the conversation we had.

**Comment by pyhalov** [comment]
Do we need this?

**Comment by Mno-hime** [comment]
Nope, we fixed the actual bug.

**Pull request closed without merging**
