### PR TITLE
xmlsec: update to 1.3.6, rebuild for library/security/openssl-3

### PR DESCRIPTION
**Pull request by klausz65**
Please merge this as the first one, then: #19933 and #19931 afterwards as they depend in this order

### CODE REVIEW

**Comment by mtelka** [comment]
@klausz65 hint: to make sure that #19931 and #19933 are merged after this one just mark them as a Draft.

**Comment by AndWac** [comment]
Did you run gmake test? My results here differ.

**Comment by klausz65** [comment]
Okay, have forgotten - will amend shorty - sorry

**Comment by klausz65** [comment]
Okay, new results-all.master added

**Pull request merged**
