### PR TITLE
update to samba-4.11.2

### PR DESCRIPTION
**Pull request by chincheta0815**

### CODE REVIEW

**Comment by chincheta0815** [comment]
This pull request contains the latest samba version.
Unfortunately, tests are not yet included...

**Comment by chincheta0815** [comment]
@pyhalov Just saw that you pushed some release note for 10.2019.
Maybe this PR can make it into that.
Would be awesome.

**Comment by pyhalov** [comment]
This is not necessary to land prior to snapshot (can go immediately after it), as samba is not on ISO images.

**Comment by Mno-hime** [comment]
@chincheta0815 Hipster is a rolling-release distro, so, everyone has the bits once they are merged, no need to wait for the next snapshot release.

**Review by Mno-hime — APPROVED** [review]

**Comment by chincheta0815** [comment]
Thanks for approving.

**Pull request merged**
