### PR TITLE
gc: bump to 8.2.6

### PR DESCRIPTION
**Pull request by ivmai**

### CODE REVIEW

**Comment by mtelka** [comment]
The updated `pkg5` file is missing in this PR.

**Comment by ivmai** [comment]
Hmm, why do I need to update it?

**Comment by mtelka** [comment]
Because it contains metadata that needs to be up-to-date.  Basically, when you run all make targets needed to update the component (basically these: `sample-manifest`, `publish`, `test`, `REQUIRED_PACKAGES`) and you find some changed files (or the target fails) you should add them to changeset (or solve the failure).  Similarly as you did with `sample-manifest.p5m`.

**Comment by mtelka** [comment]
Also, I think `unexport SHELLOPTS` is no longer needed.  Could you please try to remove it?  If it is there it could hide some issues...

Thank you.

**Comment by ivmai** [comment]
> The updated `pkg5` file is missing in this PR.

Done

**Comment by mtelka** [comment]
Hm, strange.  How you achieved that `SUNWcs` and `shell/ksh93` are still in the `pkg5` file?  Is your `oi-userland` tree up-to-date?

**Comment by ivmai** [comment]
> Also, I think `unexport SHELLOPTS` is no longer needed. Could you please try to remove it? If it is there it could hide some issues...

Done

**Review by mtelka — APPROVED** [review]

**Pull request merged**
