### PR TITLE
Fix component consistency and rename clang-34

### PR DESCRIPTION
**Pull request by alarcher**
Not sure about the renaming process.

### CODE REVIEW

**Comment by pyhalov** [comment]
You can use history file to rename package, look, for example, at components/python/gnome-python/history. Not sure that we should deal with this ancient clang. I'd rather integrated 3.8 and deprecated 3.4

**Comment by alarcher** [comment]
I do not know if anyone relies on clang 3.4 but just in case maybe only deprecate 3.4 when we are sure 3.8 does the job?

**Comment by pyhalov** [comment]
Of course, so I'd do it in one PR :)

**Comment by xen0l** [comment]
note to myself: to further avoid such PRs, we should write some oi-userland best practices and start with naming components.

**Comment by alarcher** [comment]
OK. So I will update this when I can access my build machine again.

**Comment by xen0l** [comment]
Can this be merged prior to clang-38?

**Comment by alarcher** [comment]
This is independent but could be done.
I cannot spend too much time on that though and my build machine is being moved to another room right now.

**Comment by alarcher** [comment]
@pyhalov erf... I screwed up clang-38's name ... I named it clang-3.8 ....

**Comment by pyhalov** [comment]
Good to know, I'm not the only one... Time to fix it?

**Comment by alarcher** [comment]
@pyhalov Done.

**Pull request merged**
