### PR TITLE
bass-o-matic: incremental builds

### PR DESCRIPTION
**Pull request by xen0l**

### CODE REVIEW

**Comment by xen0l** [comment]
I am testing this right now on jenkins. I also modified Makefile, where I removed --component and --template-zone. As those were never implemented, I dropped them.

Please also not that this turns the incremental magic automatically on if BASS_O_MATIC_MODE is set to incremental. It tries to guess everything from environment variables. If the variable is not set, it will behave like it has until now. Let me know what you think.

**Comment by pyhalov** [comment]
Looks interesting. Have you checked that it works with encumbered components?

**Comment by jimklimov** [comment]
I am slowly moving to make the script to manage golden-template and disposable zones, and run commands in one, so maybe the option to use those for a build would come back in a while ;)

Otherwise, the code looks neat :)

**Comment by xen0l** [comment]
@pyhalov I haven't check if it works with encumbered, but it should as the changes are made to bass-o-matic itself and not Makefile.

**Comment by xen0l** [comment]
@jimklimov I am fine with adding it back once we have the functionality. Until then I would like to keep it minimal. At the moment, the code doesn't do anything.

**Comment by jimklimov** [comment]
Yes, right - good with me.

**Comment by pyhalov** [comment]
Cool. Thanks.

**Pull request merged**
