### PR TITLE
Adjust components/sysutils/nut recipes to deliver NUT v2.8.1 release (with dual python versions)

### PR DESCRIPTION
**Pull request by jimklimov**
Ret-conned prequel to #14630: this PR includes the commit for modernization of NUT to 2.8.1 with all the flexibility (including python 2.7 binding and UI client for whoever might need that). The original PR follows up with a commit to remove python 2.7 support and keep only the officially supported version(s) as dictated by `shared-macros.mk` of the day.

### CODE REVIEW

**Review by mtelka — CHANGES_REQUESTED** [review]
No.  Please don't.  Python 2.7 is really dead.  I'm sorry you spent a lot of time with Python 2.7 here, but I'm strongly -1 here.

**Comment by jimklimov** [comment]
Note for posterity: if someone *would* actually need the NUT recipe with python-2.x support for local builds, the necessary commit is parked in the source branch here.

* https://github.com/jimklimov/oi-userland/tree/nut-v2.8.1-oi-python-2x-3x - the "full original PR"
* https://github.com/jimklimov/oi-userland/tree/nut-v2.8.1-oi-py39 - added layers of clean-up to final state of the squashed PR, as separate commits

**Comment by AndWac** [comment]
There seem to be some problems with the PR and thus the build server choked:
system/management/nut                             2.7.4-2022.0.0.5           ---
system/management/nut-common                      2.7.4-2022.0.0.5           ---
system/management/nut/augeas                      2.7.4-2022.0.0.5           ---
system/management/nut/bins                        2.7.4-2022.0.0.5           ---
system/management/nut/cgi                         2.7.4-2022.0.0.5           ---
system/management/nut/clients                     2.8.1-2023.0.0.0           ---
system/management/nut/common                      2.8.1-2023.0.0.0           ---
system/management/nut/devtools                    2.7.4-2022.0.0.5           ---
system/management/nut/drivers                     2.7.4-2022.0.0.5           ---
system/management/nut/drivers/ipmi                2.8.1-2023.0.0.0           ---
system/management/nut/drivers/modbus              2.8.1-2023.0.0.0           ---
system/management/nut/drivers/neon                2.8.1-2023.0.0.0           ---
system/management/nut/drivers/powerman            2.8.1-2023.0.0.0           ---
system/management/nut/drivers/serial              2.8.1-2023.0.0.0           ---
system/management/nut/drivers/snmp                2.8.1-2023.0.0.0           ---
system/management/nut/drivers/software            2.8.1-2023.0.0.0           ---
system/management/nut/drivers/usb                 2.8.1-2023.0.0.0           ---
system/management/nut/libs                        2.7.4-2022.0.0.5           ---
system/management/nut/libs/pynut                  2.8.1-2023.0.0.0           ---
system/management/nut/nut-monitor-gui             2.8.1-2023.0.0.0           ---
system/management/nut/nut-monitor-gui-common      2.8.1-2023.0.0.0           ---
system/management/nut/nut-monitor-gui-py3qt5      2.8.1-2023.0.0.0           ---
system/management/nut/server                      2.8.1-2023.0.0.0           ---

There are lots of packages that seem to be abandoned without proper obsoletion.

**Comment by mtelka** [comment]
@AndWac, wrong PR :-), see https://github.com/OpenIndiana/oi-userland/pull/14630#issuecomment-1803888806

But, OTOH, good point, I forgot one package there...

**Comment by mtelka** [comment]
> But, OTOH, good point, I forgot one package there...

No.  I didn't forgot one, one is superfluous.

**Pull request closed without merging**
