### PR TITLE
update games/openttd to 1.6.1

### PR DESCRIPTION
**Pull request by jeffpc**

### CODE REVIEW

**Comment by xen0l** [comment]
This change will be merged. Thank you for your contribution!

**Comment by jimklimov** [comment]
Shouldn't @jeffpc 's (C) have been kept for the whole range (2014-2016 rather than just 2016)

**Comment by jeffpc** [comment]
I thought the preferred format for copyright lines was just the last year.  I don't really care that much and AFAIK I can change my own copyright whichever I like anyway ;)

**Comment by jimklimov** [comment]
Yeah, it's your right of course ;)

Just IMHO helps track how long one was active, and/or how long someone at all cared about a component etc. without parsing the SCM logs :)

**Comment by jeffpc** [comment]
On Wed, Jan 11, 2017 at 00:48:44 -0800, Jim Klimov wrote:
> Yeah, it's your right of course ;)
> 
> Just IMHO helps track how long one was active, and/or how long someone at
> all cared about a component etc. without parsing the SCM logs :)

Fair enough.  Next time I update it, I'll use a range.

Jeff.

**Pull request merged**
