### PR TITLE
twisted: update to 21.2.0 and drop -27

### PR DESCRIPTION
**Pull request by alarcher**

### CODE REVIEW

**Comment by AndWac** [comment]
gmake publish fails:
Lint engine setup...
Starting lint run...
ERROR pkglint.manifest002.5       package pkg:/library/python-2/python-twisted-27@10.1.0,5.11-2016.0.1.0 was renamed to an obsolete package pkg:/library/python/python-twisted-27@19.10.0,5.11-2020.0.1.1

**Comment by alarcher** [comment]
> gmake publish fails:
> Lint engine setup...
> Starting lint run...
> ERROR pkglint.manifest002.5 package pkg:/library/python-2/python-twisted-27@10.1.0,5.11-2016.0.1.0 was renamed to an obsolete package pkg:/library/python/python-twisted-27@19.10.0,5.11-2020.0.1.1

Weird I do not have this issue in my environment... :S

**Comment by AndWac** [comment]
I will check with my 2nd build env. But I need to update it first. Can we merge automat already?

**Comment by alarcher** [comment]
> I will check with my 2nd build env. But I need to update it first. Can we merge automat already?

Yes I fixed what you asked. Maybe you can merge kvm at the same time.

**Comment by AndWac** [comment]
My 2nd environment has the same problem. Maybe you have something in yours that is missing on my?

**Comment by balrog-nona** [comment]
I also got the same error message when running `gmake publish` and I got rid of it when I deleted the second part of the last line in `history` file:
`library/python-2/python-twisted-27@10.1.0,5.11-2016.0.1.0` instead of
`library/python-2/python-twisted-27@10.1.0,5.11-2016.0.1.0 library/python/python-twisted-27`
I don't know what the line was about but could it be some kind of renaming?
After that `gmake publish` ran fine with some `pkglint` warnings, though.

But when I tried to install the package, I got this:
```
pkg install: No matching version of library/python/python-twisted-37 can be installed:
  Reject:  pkg://userland/library/python/python-twisted-37@21.2.0-2020.0.1.0
  Reason:  No version for 'require' dependency on library/python/hyperlink-37 can be found
No matching version of library/python/python-twisted-39 can be installed:
  Reject:  pkg://userland/library/python/python-twisted-39@21.2.0-2020.0.1.0
  Reason:  No version for 'require' dependency on library/python/hyperlink-39 can be found
No matching version of library/python/python-twisted can be installed:
  Reject:  pkg://userland/library/python/python-twisted@21.2.0-2020.0.1.0
  Reason:  No version matching 'conditional' dependency library/python/python-twisted-35@21.2.0-2020.0.1.0 can be installed
    ----------------------------------------
    Reject:  pkg://userland/library/python/python-twisted-35@21.2.0-2020.0.1.0
    Reason:  No version matching 'require' dependency library/python/python-twisted@21.2.0-2020.0.1.0 can be installed
    ----------------------------------------
  Reason:  No version matching 'conditional' dependency library/python/python-twisted-37@21.2.0-2020.0.1.0 can be installed
No matching version of library/python/python-twisted-35 can be installed:
  Reject:  pkg://userland/library/python/python-twisted-35@21.2.0-2020.0.1.0
  Reason:  [already rejected; see above]
```
According to hyperlink's Makefile https://github.com/OpenIndiana/oi-userland/blob/8eb85b2000ed20586d95f4569a73b079b04769f3/components/python/hyperlink/Makefile#L47 it looks like we don't provide Python3.7 and 3.9.

**Comment by alarcher** [comment]
It seems I forgot to push it before twisted, it is in my python 3.9 branch.

**Comment by AndWac** [comment]
Can you split the deprecation of the python-2.7 version and the update and add of python 3.7 and 3.9 versions into two separate PRs?

**Comment by AndWac** [comment]
During the successful twisted-27 obsoletion I found the main culprit: the old history entry for the python-2.6 version referenced the python-2.7 version.

**Comment by Toasterson** [comment]
@alarcher There have been changes to twisted from another PR since your PR can you rebase and split the obosetion and the upgade?

**Comment by AndWac** [comment]
This has been superceded by #7187

**Pull request closed without merging**
