### PR TITLE
virtualbox: update to 6.1.14a

### PR DESCRIPTION
**Pull request by AndWac**

### CODE REVIEW

**Comment by bytes-and-bits** [comment]
I built and ran VirtualBox 6.1.14 on my OI install and was able to start OmniOS and Windows 7 VMs.  I did not do much with the OmniOS VM other than 'pkg update' and reboot, and that worked as expected.  On the Windows 7 VM I was able to access files via shared folders and run Firefox to play back some audio on from Youtube.  The audio playback stuttered quite a bit, though from tickets like https://www.virtualbox.org/ticket/17225 that seems to be a VirtualBox issue.

**Comment by AndWac** [comment]
That sounds great, thank you for testing!

**Comment by bleve97** [comment]
On 18/10/2020 8:07 pm, bytes-and-bits wrote:
> I built and ran VirtualBox 6.1.14 on my OI install and was able to start 
> OmniOS and Windows 7 VMs. I did not do much with the OmniOS VM other 
> than 'pkg update' and reboot, and that worked as expected. On the 
> Windows 7 VM I was able to access files via shared folders and run 
> Firefox to play back some audio on from Youtube. The audio playback 
> stuttered quite a bit, though from tickets like 
> https://www.virtualbox.org/ticket/17225 
> <https://www.virtualbox.org/ticket/17225> that seems to be a VirtualBox 
> issue.


Thank you!

Carl

**Comment by 3eka** [comment]
Hi all,

Just have installed 6.1.14a from IPS repository and it seems that works (at
least, similar to old 6.1.8 one).

Many thanks!

**Pull request merged**
