### PR TITLE
move mpfr header files to /usr/include and add MPN64_sparc options.

### PR DESCRIPTION
**Pull request by klausz65**
This is to follow the coding standards of Oracle Solaris 11.4, solaris-userland has switched re-locating mpfr.h to /usr/include about 4 years ago now. Dependent other software packages will be changed in separate PR(s).

### CODE REVIEW

**Review by Toasterson — COMMENTED** [review]
Can you check if the packages depending on this need to have their include paths updated? Otherwise LGTM

**Comment by klausz65** [comment]
> Can you check if the packages depending on this need to have their include paths updated? Otherwise LGTM
packages which need to be updated will follow in a seperate PR

**Comment by Toasterson** [comment]
Ah, ok. Then we need to prepare a quick testing run. Once you publish the seperate PR I can run a test on Vagrant

**Comment by Toasterson** [comment]
Found a quick bug on https://github.com/klausz65/oi-userland/blob/relocate-mpfr.h/components/library/mpfr/Makefile#L70

I needed add this patch so the component could build.
```diff
diff --git a/components/library/mpfr/Makefile b/components/library/mpfr/Makefile
index 1053ca1b5..72b81fb91 100644
--- a/components/library/mpfr/Makefile
+++ b/components/library/mpfr/Makefile
@@ -67,7 +67,6 @@ CONFIGURE_ENV += SED="$(GSED)"
 CONFIGURE_ENV += ABI="$(BITS)"
 CONFIGURE_ENV += "MPN_PATH=$(MPN_$(BITS))"
 
-CONFIGURE_OPTIONS += --includedir=/usr/include/mpfr
 CONFIGURE_OPTIONS += --localstatedir=/var
 CONFIGURE_OPTIONS += --enable-shared
 CONFIGURE_OPTIONS += --disable-static
```

patch for sample-manifest is
```diff
diff --git a/components/library/mpfr/manifests/sample-manifest.p5m b/components/library/mpfr/manifests/sample-manifest.p5m
index 12a34626a..bde190352 100644
--- a/components/library/mpfr/manifests/sample-manifest.p5m
+++ b/components/library/mpfr/manifests/sample-manifest.p5m
@@ -10,7 +10,7 @@
 #
 
 #
-# Copyright 2020 <contributor>
+# Copyright 2021 <contributor>
 #
 
 set name=pkg.fmri value=pkg:/$(COMPONENT_FMRI)@$(IPS_COMPONENT_VERSION),$(BUILD_VERSION)
```

**Pull request merged**
