### PR TITLE
libgit2: split runtime lib to own pkg; add libgit2-1.7

### PR DESCRIPTION
**Pull request by mtelka**
This is needed to fix cargo (yes, rust rebuild would fix that too, but ...) and to make the future libgit2 updates easier (so no package rebuilds are needed).

### CODE REVIEW

**Comment by mtelka** [comment]
BTW, the problem is this:
```
$ cargo
ld.so.1: cargo: fatal: libgit2.so.1.7: open failed: No such file or directory
Killed
$
```

**Comment by AndWac** [comment]
I am not happy with the idea to have a separate libgit package for cargo. When cargo needs a newer version we need to obsolete the package and create a new one.

**Comment by Toasterson** [comment]
I am wondering if we are using IPS wrong here. It should be possible to have two versions of libgit installed and remove the nonversioned symlink from the old package.

**Comment by AndWac** [comment]
I added a compatibility link into libgit2. With that we can rebuild rustc.

**Comment by mtelka** [comment]
> I am not happy with the idea to have a separate libgit package for cargo. When cargo needs a newer version we need to obsolete the package and create a new one.

This was not needed for cargo only, but also for geany plugins.  This is also good design to avoid rebuilds in future.

**Pull request closed without merging**
