### PR TITLE
Make perl headers Sun Studio friendly

### PR DESCRIPTION
**Pull request by mtelka**

### CODE REVIEW

**Comment by pyhalov** [comment]
Please, also bump COMPONENT_REVISION in components/perl/perl522/Makefile

**Comment by mtelka** [comment]
Done

**Comment by pyhalov** [comment]
Shouldn't patch also handle __SUNPRO_CC?

**Comment by mtelka** [comment]
No idea.  I did this to be able to build illumos-gate on recent hipster using Sun Studio.  I didn't notice that I need to do the same for __SUNPRO_CC so I didn't do it.  Maybe it is needed maybe not, I really do not know.  If it is needed we could do it later easily.

**Pull request merged**
