### PR TITLE
glib: update to 2.82.0

### PR DESCRIPTION
**Pull request by mtelka**

### CODE REVIEW

**Comment by AndWac** [comment]
A dependency on library/python/docutils-39 is missing:

Configuring config.h using configuration
Program rst2man rst2man.py found: NO

meson.build:2653:10: ERROR: Program 'rst2man rst2man.py' not found or not executable

**Comment by mtelka** [comment]
> A dependency on library/python/docutils-39 is missing:

Fixed.  Thank you.

**Comment by AndWac** [comment]
Almost fixed, pkg5 needs an update, too.

**Comment by mtelka** [comment]
> Almost fixed, pkg5 needs an update, too.

Right.  `pkg5` updated.

**Pull request merged**
