### PR TITLE
Golang 113 Fixing building on Jenkins

### PR DESCRIPTION
**Pull request by Toasterson**
Modified the GOCACHE GOROOT and GOPATH VARIABLES so that they use SOURCE_DIR during building and thus allow building inside jenkins.

Tested on my own jenkins server.

### CODE REVIEW

**Comment by Mno-hime** [comment]
Squash those commits, please. Otherwise LGTM.

**Comment by Toasterson** [comment]
@Mno-hime squashed as requested. Although why not the merge and squash button. Does it have limits?

**Review by Mno-hime — APPROVED** [review]
LGTM. Though I am not sure if `COMPONENT_REVISION` bump is required for this fix.

**Comment by Mno-hime** [comment]
> Although why not the merge and squash button. Does it have limits?

It should work but sometimes someone misses that those commits are just fixups and hits "Rebase and merge", which is the default.

**Comment by Toasterson** [comment]
@Mno-hime We couldn't publish yet. Or did we?

**Comment by Mno-hime** [comment]
@Toasterson I eventually managed to do that manually and Jenkins eventually made it available: http://pkg.openindiana.org/hipster/info/0/developer%2Fgolang-113%401.13%2C5.11-2019.0.0.0%3A20190916T172431Z.

**Comment by Toasterson** [comment]
@Mno-hime Ah didn't know. Bumped Component revision. Anything still blocking merge?

**Pull request merged**
