### PR TITLE
GNU TLS 2 disentanglement rebuild

### PR DESCRIPTION
**Pull request by Mno-hime**
Merge after https://github.com/OpenIndiana/oi-userland/pull/5295.

### CODE REVIEW

**Comment by alarcher** [comment]
Unfortunately this does not work so well for other build machines ;) We should really work on Adam's rebuild dependent PR, this is not very sustainable :) Is it enough to uninstall gnutls-2 and rebuild these components after gnutls-3 is updated?

**Comment by alarcher** [comment]
Also is this warning expected in gnutls-3?

```
***
*** In solaris hardware acceleration is disabled by default due to issues
*** with the assembler. Use --enable-hardware-acceleration to enable it.
*** 

```

**Comment by Mno-hime** [comment]
> Also is this warning expected in gnutls-3?
> 
> ```
> ***
> *** In solaris hardware acceleration is disabled by default due to issues
> *** with the assembler. Use --enable-hardware-acceleration to enable it.
> *** 
> ```

I think so. Looking at the old gnutls-3 it manifests the same warning - it was added upstream 5 years ago https://gitlab.com/gnutls/gnutls/commit/0b5c84761883565c303a5918ad2bc5cd26b91e7e - and we never enabled this explicitly. Perhaps it does not apply to us, but we don't know because it fails to build with `--enable-hardware-acceleration`:
```
  CC       aes-gcm-padlock.lo
/export/home/newman/ws/oi-userland/components/library/gnutls-3/gnutls-3.5.19/lib/accelerated/x86/aes-padlock.c: In function 'padlock_aes_cipher_setkey':
/export/home/newman/ws/oi-userland/components/library/gnutls-3/gnutls-3.5.19/lib/accelerated/x86/aes-padlock.c:92:4: warning: 'nettle_aes_set_encrypt_key' is deprecated [-Wdeprecated-declarations]
    aes_set_encrypt_key(&nc, keysize, userkey);
    ^~~~~~~~~~~~~~~~~~~
In file included from /export/home/newman/ws/oi-userland/components/library/gnutls-3/gnutls-3.5.19/lib/accelerated/x86/aes-padlock.c:35:0:
/usr/include/nettle/aes.h:158:1: note: declared here
 aes_set_encrypt_key(struct aes_ctx *ctx,
 ^
/export/home/newman/ws/oi-userland/components/library/gnutls-3/gnutls-3.5.19/lib/accelerated/x86/aes-padlock.c:94:4: warning: 'nettle_aes_set_decrypt_key' is deprecated [-Wdeprecated-declarations]
    aes_set_decrypt_key(&nc, keysize, userkey);
    ^~~~~~~~~~~~~~~~~~~
In file included from /export/home/newman/ws/oi-userland/components/library/gnutls-3/gnutls-3.5.19/lib/accelerated/x86/aes-padlock.c:35:0:
/usr/include/nettle/aes.h:163:1: note: declared here
 aes_set_decrypt_key(struct aes_ctx *ctx,
 ^
/export/home/newman/ws/oi-userland/components/library/gnutls-3/gnutls-3.5.19/lib/accelerated/x86/aes-padlock.c:96:28: error: 'struct aes_ctx' has no member named 'keys'; did you mean 'key_size'?
   memcpy(pce->ks.rd_key, nc.keys, sizeof(nc.keys));
                            ^
/export/home/newman/ws/oi-userland/components/library/gnutls-3/gnutls-3.5.19/lib/accelerated/x86/aes-padlock.c:96:44: error: 'struct aes_ctx' has no member named 'keys'; did you mean 'key_size'?
   memcpy(pce->ks.rd_key, nc.keys, sizeof(nc.keys));
                                            ^
/export/home/newman/ws/oi-userland/components/library/gnutls-3/gnutls-3.5.19/lib/accelerated/x86/aes-padlock.c:97:22: error: 'struct aes_ctx' has no member named 'rounds'
   pce->ks.rounds = nc.rounds;
                      ^
make[6]: *** [Makefile:1661: aes-padlock.lo] Error 1
```
Perhaps a nettle incompatibility? Should be fixed in GNU TLS 3.6 (https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=240171).

**Comment by Mno-hime** [comment]
> Unfortunately this does not work so well for other build machines ;) We should really work on Adam's rebuild dependent PR, this is not very sustainable :)

Looking at OpenSSL dependencies needed to be rebuild/fixed for OpenSSL 1.1.1, I tend to agree... I like the Adam's thing and it used to work for me back then.

> Is it enough to uninstall gnutls-2 and rebuild these components after gnutls-3 is updated?

Yes, that's what I did on the hipster build server. Removed gnutls (v2) component and those packages which required it, integrated gnutls-3 component, rebuild gnutls-3 dependants, and re-installed packages removed in the first stage (except for gnutls v2, which got dropped entirely).

**Comment by alarcher** [comment]
OK cool, after updating gnutls-3 the rebuild seems of gnutls dependent components on my machine :)

**Pull request merged**
