### PR TITLE
Mate 1.24 part 5

### PR DESCRIPTION
**Pull request by mvwieringen**
Ok last part with patches mate-power-manager and mate-system-monitor with the polkit stuff removed.

### CODE REVIEW

**Comment by mvwieringen** [comment]
@andwac here are the last 2 mate utils which now publish correctly and have polkit stuff removed just as was done partly before but it seems these tools got more deps on polkit in 1.24.

**Comment by AndWac** [comment]
Alas part4 failed in mate-control-center for no apparent reason. At least a manual "gmake build" in the jenkins workspace worked fine but
the next jenkins run failed again.

**Comment by AndWac** [comment]
I commented too early. The last jenkins run went fine but fooled me because it went red during its run and then finished successfully.

**Comment by mvwieringen** [comment]
Yeah I do see it as published.

**Pull request merged**
