### PR TITLE
gtkhtml: Move to library folder and add manual build dependency

### PR DESCRIPTION
**Pull request by AndWac**
gtkhtml needs gnome-icon-theme otherwise the build fails.

### CODE REVIEW

**Comment by alarcher** [comment]
@AndWac Have you forgotten to add the dependency change?

**Comment by AndWac** [comment]
No, it's on my branch. I don't know why it didn't make it into the PR.
My git status is clean and my Makefile has several changes made by me.
Maybe I did something wrong. What I basically did was:
git mv gtkhtml library/
Then I changed the Makefile
And then committed.
git status says all clean and the Makefile contains the changes here...

**Comment by AndWac** [comment]
I don't know why my Makefile changes didn't make it into this PR.
I will try again from a fresh point.

**Review by pyhalov — COMMENTED** [review]
Heh... You didn't mean this

**Pull request closed without merging**
