### PR TITLE
Geany Editor Plugins: version bump to 1.30

### PR DESCRIPTION
**Pull request by 3eka**

### CODE REVIEW

**Comment by pyhalov** [comment]
Got this error:
geanydoc/tests/unittests.c:3:19: fatal error: check.h: No such file or directory
 #include <check.h>
It seems 01-unittest-cflags.patch was required.

**Comment by 3eka** [comment]
Strange, it was not required when I have built it.
Will check

**Comment by pyhalov** [comment]
perhaps depends on having developer/check installed

**Comment by 3eka** [comment]
I do not have package developer/check installed on build zone...

And checked build log:
```
Making all in geanydoc
make[3]: Entering directory '/export/home/zeka/oi-userland/components/editor/geany-plugins/build/i86/geanydoc'
Making all in src
make[4]: Entering directory '/export/home/zeka/oi-userland/components/editor/geany-plugins/build/i86/geanydoc/src'
  CC       geanydoc_la-config.lo
  CC       geanydoc_la-geanydoc.lo
  CCLD     geanydoc.la
make[4]: Leaving directory '/export/home/zeka/oi-userland/components/editor/geany-plugins/build/i86/geanydoc/src'
Making all in tests
make[4]: Entering directory '/export/home/zeka/oi-userland/components/editor/geany-plugins/build/i86/geanydoc/tests'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/export/home/zeka/oi-userland/components/editor/geany-plugins/build/i86/geanydoc/tests'
make[4]: Entering directory '/export/home/zeka/oi-userland/components/editor/geany-plugins/build/i86/geanydoc'
make[4]: Nothing to be done for 'all-am'.
make[4]: Leaving directory '/export/home/zeka/oi-userland/components/editor/geany-plugins/build/i86/geanydoc'
make[3]: Leaving directory '/export/home/zeka/oi-userland/components/editor/geany-plugins/build/i86/geanydoc'
```
I  have both installed from local userland repository (after build, anyway, geany package was required to build geany/plugins):
```
zeka@builder ~/oi-userland/components/editor/geany-plugins$ pkg info geany geany/plugins
          Name: editor/geany
       Summary: A fast and lightweight IDE
      Category: System/Text Tools
         State: Installed
     Publisher: userland
       Version: 1.30.1
        Branch: 2017.0.0.0
Packaging Date: May  3, 2017 01:54:45 PM
          Size: 13.49 MB
          FMRI: pkg://userland/editor/geany@1.30.1-2017.0.0.0:20170503T135445Z
   Project URL: http://www.geany.org/Main/HomePage
    Source URL: http://download.geany.org/geany-1.30.1.tar.bz2

             Name: editor/geany/plugins
          Summary: Plugins for Geany editor
         Category: System/Text Tools
            State: Installed
        Publisher: userland
          Version: 1.30
           Branch: 2017.0.0.0
   Packaging Date: May  4, 2017 07:59:05 AM
Last Install Time: May  4, 2017 08:03:11 AM
             Size: 4.57 MB
             FMRI: pkg://userland/editor/geany/plugins@1.30-2017.0.0.0:20170504T075905Z
      Project URL: https://plugins.geany.org/
       Source URL: http://plugins.geany.org/geany-plugins/geany-plugins-1.30.tar.gz
```
Not sure hot reproduce this? To install developer/check package?

Regards.

**Comment by pyhalov** [comment]
yes

**Comment by 3eka** [comment]
OK,
installed and build has failed. Will re-add patch...
Thanks for input

**Comment by pyhalov** [comment]
Please, rename patches back and merge commits

**Comment by 3eka** [comment]
Why is patch order so important?
It compiles...

**Comment by pyhalov** [comment]
to avoid unnecessary questions when one will look on the history

**Comment by 3eka** [comment]
What would be proper way to do "rename patches back and merge commits"?

**Comment by pyhalov** [comment]
Something like
git mv file1 new_name
git mv file2 new_name
git commit
git rebase -i $(COMMIT_BEFORE_YOUR_WORK)
git show (see that everything is fine)
git push -f

**Comment by 3eka** [comment]
Hopefully, all is fine now...

**Comment by pyhalov** [comment]
Just merge 3 commits in one

**Comment by 3eka** [comment]
Thanks

**Pull request merged**
